### ISSUE TITLE
Multi-gpu training error

### ISSUE THREAD

**Issue by hahapt** [ultralytics/yolov5#10088]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to train with multi gpu with recommend way as follow:
`python -m torch.distributed.run --nproc_per_node 4 train.py --img 1280 --epochs 300 --batch 64 --data ./data/v1.yaml --cfg ./models/yolov5m.yaml --resume --weights ./runs/exp/weights/best.pt --device 0,1,2,3`
but here comes the error:
`Traceback (most recent call last):
  File "train.py", line 520, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 70, in train
    with torch_distributed_zero_first(rank):
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/paddleflow/storage/mnt/hpt/yolov5-4.0/utils/torch_utils.py", line 29, in torch_distributed_zero_first
    torch.distributed.barrier()
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    default_pg = _get_default_group()
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 74 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 76 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 77) of binary: /root_mmt/hpt/anaconda3/envs/yolo5_4/bin/python
Traceback (most recent call last):
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root_mmt/hpt/anaconda3/envs/yolo5_4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: `
Can you tell me where is the problem?

**Comment by glenn-jocher** [comment]
@hahapt can't tell exactly what might be wrong, but I'd strongly recommend training all DDP runs inside our Docker image to minimize environment risk. 

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>
