### ISSUE TITLE
'PReLU' object has no attribute 'total_params'

### ISSUE THREAD

**Issue by colchicinewf** [ultralytics/yolov5#10249]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

when i change  the class Conv's default act from
```
default_act = nn.SiLU()
```
to
```
default_act = nn.PReLU()
```
in the files models/common.py，and run
```
python models/yolo.py  --line-profile
```
,the FLOPs increase from 16.6 to 170.3，and it just print the first two layer's info just like
time (ms)     GFLOPs     params  module
      0.94       0.74       3521  models.common.Conv
      0.30       0.96      18561  models.common.Conv
then ,it appears

_Traceback (most recent call last):
  File "models/yolo.py", line 378, in <module>
    model(im, profile=True)
  File "./envs/pth3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "models/yolo.py", line 120, in _forward_once
    self._profile_one_layer(m, x, dt)
  File "models/yolo.py", line 132, in _profile_one_layer
    m(x.copy() if c else x)
  File "./envs/pth3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./yolov5-master2/models/common.py", line 168, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), 1))
  File "./envs/pth3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./yolov5-master2/models/common.py", line 57, in forward
    return self.act(self.bn(self.conv(x)))
  File "./envs/pth3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1151, in _call_impl
    hook_result = hook(self, input, result)
  File "./envs/pth3.8/lib/python3.8/site-packages/thop/vision/basic_hooks.py", line 15, in count_parameters
    m.total_params[0] = calculate_parameters(m.parameters())
  File "./envs/pth3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    **raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PReLU' object has no attribute 'total_param**s'_

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by colchicinewf** [comment]
@glenn-jocher I find that if I set 
[class Conv's ](https://github.com/ultralytics/yolov5/blob/bfa1f23045c7c4136a9b8ced9d6be8249ed72692/models/common.py#L54)
`self.act = nn.PReLU()`
rather than
`self.act = default_act`
it can get the right  FLOPs .

it seems that all network's acts are the same one if use `self.act = default_act` because `id(layers[0].act)`=`id(layers[1].act)`。
