### ISSUE TITLE
Yolov5 7.0 segmentation training 'anchors' error?

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#10289]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using date labelled data from CVAT for object detection, is there a different data preparation path or attribute set required?
Thank you.

```
Traceback (most recent call last):
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 658, in <module>
    main(opt)
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 554, in main
    train(opt.hyp, opt, device, callbacks)
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 115, in train
    model = SegmentationModel(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)
  File "/yv7test/lib/yolov5_v7/models/yolo.py", line 270, in __init__
Traceback (most recent call last):
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 658, in <module>
Traceback (most recent call last):
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 658, in <module>
    super().__init__(cfg, ch, nc, anchors)
  File "/yv7test/lib/yolov5_v7/models/yolo.py", line 185, in __init__
    main(opt)
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 554, in main
    main(opt)
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 554, in main
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/yv7test/lib/yolov5_v7/models/yolo.py", line 302, in parse_model
    train(opt.hyp, opt, device, callbacks)
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 115, in train
    train(opt.hyp, opt, device, callbacks)
  File "/yv7test/lib/yolov5_v7/segment/train.py", line 115, in train
    anchors, nc, gd, gw, act = d['anchors'], d['nc'], d['depth_multiple'], d['width_multiple'], d.get('activation')
```

**Comment by glenn-jocher** [comment]
@apiszcz segmentation training requires segmentation labels, same txt files but instead of `cls xywh` you use `cls xy1 xy2 xy3...`. Take a look at coco128-seg.yaml for an example:

```
python segment/train.py --data coco128-seg.yaml
```

**Comment by apiszcz** [comment]
So I assume these are the enclosing boundary for the shape of the object. Will review. This appears to be related.
https://github.com/ultralytics/yolov5/issues/9816

**Comment by glenn-jocher** [comment]
@apiszcz cVAT's YOLO V1.1 export does not support polygons and masks required for segmentation training. You will need to find a way to export the data in the required format. The segmentation class indeed produces polygon information and masks, which are not present in the COCO128 format. Good luck with your data preparation!
