### ISSUE TITLE
Wandb sweep fails after 1 run

### ISSUE THREAD

**Issue by lana211191** [ultralytics/yolov5#10316]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am trying to run a sweep with wandb however it fails after 1 run .

```
wandb: ERROR Error while calling W&B API: 0.01125 is not a permitted value of the categorical hyperparameter cls in the current sweep. (<Response [400]>)
wandb: Terminating and syncing runs. Press ctrl-c to kill.
Traceback (most recent call last):
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2048, in agent_heartbeat
    response = self.gql(
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\Scripts\wandb.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\cli\cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\cli\cli.py", line 1311, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\wandb_agent.py", line 641, in agent
    return run_agent(
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\wandb_agent.py", line 583, in run_agent
    agent.run()
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\wandb_agent.py", line 275, in run
    commands = self._api.agent_heartbeat(agent_id, {}, run_status)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\apis\internal.py", line 126, in agent_heartbeat
    return self.api.agent_heartbeat(*args, **kwargs)
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2059, in agent_heartbeat
    message = ast.literal_eval(e.args[0])["message"]
  File "C:\Users\mayname\Anaconda3\envs\TORCH110PY39\lib\ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\myname\Anaconda3\envs\TORCH110PY39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
        ^
SyntaxError: invalid syntax
```

my sweep.yaml is the following: 
```
program: utils/loggers/wandb/sweep.py
method: bayes
metric:
  name: metrics/mAP_0.5
  goal: maximize

parameters:
  # hyperparameters: set either min, max range or values list
  data:
    value: "data/dataset_real.yaml"
  batch_size:
    values: [8]
  epochs:
    values: [1]
  lr0:
    values: [0.001,0.01,0.1]
  lrf:
    values: [0.001,0.01]
  momentum:
    values: [0.934]    
  weight_decay:
    values: [0.0005]   
  warmup_epochs:
    values: [3.0]    
  warmup_momentum:
    values: [0.8]
  warmup_bias_lr:
    values: [0.1 ]
  box:
    values: [0.05]
  cls:
    values: [0.3]
  cls_pw:
    values: [1.0]
  obj:
    values: [0.7]
  obj_pw:
    values: [1.0]
  iou_t:
    values: [0.7]
  anchor_t:
    values: [4.0]
  fl_gamma:
    values: [0.0,0.5,1,2,3,4]
  hsv_h:
    values: [0.015]
  hsv_s:
    values: [0.7]
  hsv_v:
    values: [0.4]
  degrees:
    values: [0.0]
  translate:
    values: [0.1]
  scale:
    values: [0.9]
  shear:
    values: [0.0]
  perspective:
    values: [0.0]
  flipud:
    values: [0.0]
  fliplr:
    values: [0.5]
  mosaic:
    values: [1.0]
  mixup:
    values: [0.1]
  copy_paste:
    values: [0.1]


```

I managed to solve most of the errors however i don't understand what this error means.
I would appreciate if someone took a look.

Thank you :-)

**Comment by parambharat** [comment]
Hi @lana211191 :  I tried recreating your issues by running a sweep with your `sweep.yaml`. However, I used a different dataset since I don't have access to the `dataset_real.yaml` mentioned in your sweep config.  Nevertheless, I did not see the same error you are seeing related to the `cls` hyperparameter.

The successfully run sweep workspace can be seen [here](https://wandb.ai/parambharat/yolov5/sweeps/0ks6ipjl?workspace=user-parambharat)

I created the sweep with
```
wandb sweep -p yolov5 -e parambharat --name test_sweep ./utils/loggers/wandb/sweep.yaml
```

Next I ran the sweep agent with

```
wandb agent parambharat/yolov5/0ks6ipjl --count=5
```

The sweep config I used can be seen in the overview page [here](https://wandb.ai/parambharat/yolov5/sweeps/0ks6ipjl/overview?workspace=user-parambharat)


From the error above it looks like you initially created sweep with the `cls` hyperparameter as as `int` instead of a `float` and then changed it to `float` in the `sweep,yaml` before running the agent. If this is the case, all you need to do is recreate a new sweep by running the command `wandb sweep ./utils/loggers/wandb/sweep.yaml` and start a corresponding `wandb agent` for the sweep.

I hope this fixes the issue you are facing with the sweep.
