### ISSUE TITLE
An error is reported during classification detection(yolov5m-cls.pt).AttributeError: 'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by HiaHong** [ultralytics/yolov5#10331]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

```
import torch

# 模型
# PyTorch
model = torch.hub.load('D:/yolov5-master_v7.0', 'custom', 'D:/yolov5-master_v7.0/runs/train-cls/exp2/weights/best.pt', source='local')


# 图像
imgdizhi = 'D:/yolov5-master_v7.0/cash_fenlei/test/cash_you/ALN_cash_cash_21_9.jpg' # or file, Path, PIL, OpenCV, numpy, list

# 推理
results = model(imgdizhi)
print(results)

# 结果
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

### Bug

```
YOLOv5  2022-11-27 Python-3.7.13 torch-1.11.0 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
Model summary: 166 layers, 11671316 parameters, 0 gradients, 30.6 GFLOPs
WARNING  YOLOv5 ClassificationModel is not yet AutoShape compatible. You must pass torch tensors in BCHW to this model, i.e. shape(1,3,224,224).

Fusing layers...
Model summary: 166 layers, 11671316 parameters, 0 gradients, 30.6 GFLOPs
WARNING  YOLOv5 ClassificationModel is not yet AutoShape compatible. You must pass torch tensors in BCHW to this model, i.e. shape(1,3,224,224).

Traceback (most recent call last):
  File "d:/yolov5-master_v7.0/p.py", line 20, in <module>
    results = model(imgdizhi)
  File "D:\anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:/yolov5-master_v7.0\models\common.py", line 508, in forward    b, ch, h, w = im.shape  # batch, channel, height, width
**AttributeError: 'str' object has no attribute 'shape'**
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HiaHong see WARNING:

WARNING YOLOv5 ClassificationModel is not yet AutoShape compatible. You must pass torch tensors in BCHW to this model, i.e. shape(1,3,224,224).

**Comment by VITEK-THE-BEST** [comment]
> @HiaHong see WARNING:
> 
> WARNING YOLOv5 ClassificationModel is not yet AutoShape compatible. You must pass torch tensors in BCHW to this model, i.e. shape(1,3,224,224).

how can I do this
