### ISSUE TITLE
Yolov5-7.0-segment specific bug:RuntimeError: The expanded size of the tensor (15) must match the existing size (0) at non-singleton dimension 0.  Target sizes: [15, 5].  Tensor sizes: [0, 5]

### ISSUE THREAD

**Issue by fppccc** [ultralytics/yolov5#10354]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

This is a bug specific to Yolov5-7.0-segment.
I train yolov5x-seg on my own dataset,which can be successfully trained on yolov5-6.2 for object detection.

Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
  0%|          | 0/7 00:00
Traceback (most recent call last):
  File "segment/train.py", line 658, in <module>
    main(opt)
  File "segment/train.py", line 554, in main
    train(opt.hyp, opt, device, callbacks)
  File "segment/train.py", line 283, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/root/autodl-tmp/yolov5-7.0/utils/dataloaders.py", line 171, in __iter__
    yield next(self.iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/yolov5-7.0/utils/segment/dataloaders.py", line 201, in __getitem__
    labels_out[:, 1:] = torch.from_numpy(labels)
RuntimeError: The expanded size of the tensor (15) must match the existing size (0) at non-singleton dimension 0.  Target sizes: [15, 5].  Tensor sizes: [0, 5]

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UNeedCryDear** [comment]
The problem I encountered before is that the dataset format is wrong. For example, at least three points are required to form a complete mask, but if your labels are only two points,it will make this mistake.

**Comment by fppccc** [comment]
> 

Thank you very much for the reply.I have seen coco128-seg datasets.But I was wondering the specific format is 'C x1 y1 x2 y2 x3 y3....' or  'C x y w h x1 y1 x2 y2 x3 y3....'?  'xywh' means bbox for object detection.Because yolov5-seg model can predict bbox and segmentation meantime.I have to know this in order to convert my data from coco to yolo. 
I would be really grateful if you could help me to solve them out.

**Comment by fppccc** [comment]
> The problem I encountered before is that the dataset format is wrong. For example, at least three points are required to form a complete mask, but if your labels are only two points,it will make this mistake.

Thank you very much for the reply.I found my datasets format is incorrect because its format is for object detection.(c x1 y1 x2 y2)But I was wondering the specific format is 'C x1 y1 x2 y2 x3 y3....' or 'C x y w h x1 y1 x2 y2 x3 y3....'? 'xywh' means bbox for object detection.I have to know this in order to convert my data from coco to yolo.
I would be really grateful if you could help me to solve them out.

**Comment by UNeedCryDear** [comment]
C x1 y1 x2 y2 x3 y3 x4 y4.....
and all the pointd need to normalized to 0-1

**Comment by fppccc** [comment]
> C x1 y1 x2 y2 x3 y3 x4 y4..... and all the points need to normalized to 0-1

Thank you very much!!!

**Comment by glenn-jocher** [comment]
@fppccc you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your dataset conversion!
