### ISSUE TITLE
  raise ModuleAttributeError("'{}' object has no attribute '{}'".format( torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

### ISSUE THREAD

**Issue by 172624346** [ultralytics/yolov5#1055]
## ❔Question
Model Summary: 140 layers, 7.45958e+06 parameters, 7.45958e+06 gradients
Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 64, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "E:\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\pyProject\yolov5-3.0\yolov5-3.0\models\yolo.py", line 111, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "D:\pyProject\yolov5-3.0\yolov5-3.0\models\yolo.py", line 131, in forward_once
    x = m(x)  # run
  File "E:\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\pyProject\yolov5-3.0\yolov5-3.0\models\yolo.py", line 38, in forward
    x[i] = self.m[i](x[i])  # conv
  File "E:\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

## Additional context
Can anyone help me answer this question
I am very thankful

**Comment by NanoCode012** [comment]
Reclone repo. See #690
