### ISSUE TITLE
Is network necessary for training YOLOV5?

### ISSUE THREAD

**Issue by songyuc** [ultralytics/yolov5#1062]
## ❔Question
Is network necessary for training YOLOV5?

## Additional context
I tried training YOLOV5 on a computer without network and met an error as,
> fatal: unable to access 'https://github.com/ultralytics/yolov5.git/': Failed to connect to github.com port 443: 连接超时
Traceback (most recent call last):
  File "train.py", line 418, in <module>
    check_git_status()
  File "/home/yucheng/Program/Vessel Detection/Experiments/YOLOV5/yolov5/utils/general.py", line 70, in check_git_status
    s = subprocess.check_output('if [ -d .git ]; then git fetch && git status -uno; fi', shell=True).decode('utf-8')
  File "/home/yucheng/anaconda3/envs/conda-general/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/yucheng/anaconda3/envs/conda-general/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'if [ -d .git ]; then git fetch && git status -uno; fi' returned non-zero exit status 128.
(conda-general) yucheng@yucheng-Ubuntu:~/Program/Vessel Detection/Experiments/YOLOV5/yolov5$ python train.py --img 768 --batch 20 --epochs 3 --data ./data/pdata.yaml --cfg ./models/yolov5s.yaml --weights kas_exp57_best.pt
fatal: unable to access 'https://github.com/ultralytics/yolov5.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "train.py", line 418, in <module>
    check_git_status()
  File "/home/yucheng/Program/Vessel Detection/Experiments/YOLOV5/yolov5/utils/general.py", line 70, in check_git_status
    s = subprocess.check_output('if [ -d .git ]; then git fetch && git status -uno; fi', shell=True).decode('utf-8')
  File "/home/yucheng/anaconda3/envs/conda-general/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/yucheng/anaconda3/envs/conda-general/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'if [ -d .git ]; then git fetch && git status -uno; fi' returned non-zero exit status 128.

So how can I solve this?

Any answer or idea will be appreciated!

**Comment by AndreaBrg** [comment]
You could remove (or comment out) the lines that try to connect to the internet i.e. attempt_download() and check_git_status(). Doing so you wont be notified of newly pushed updates to the code but it should be able to run even without the network access.

That said you'll need all of the requirements already downloaded, like the dataset or the pretrained weights if you need them.
