### ISSUE TITLE
Autoshape not working correctly on TensorRT packed models

### ISSUE THREAD

**Issue by chichun2002** [ultralytics/yolov5#10742]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Export, PyTorch Hub

### Bug

When using the TensorRT packed model, the autoshape doesn't appear to be working correctly, using other models results in no issues but when using TensorRT`.engine` it requires the model to be exported with the exact img size, Using --dynamic or --half also results in the same issue.

output:

```
Loading yolov5s.engine for TensorRT inference...
[01/11/2023-18:00:34] [TRT] [I] Loaded engine size: 16 MiB
[01/11/2023-18:00:34] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14, now: CPU 0, GPU 14 (MiB)
[01/11/2023-18:00:34] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +31, now: CPU 0, GPU 45 (MiB)
[01/11/2023-18:00:34] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See CUDA_MODULE_LOADING in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
Adding AutoShape...
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    results = model('bus.jpg')
  File "C:\Users\chich\miniconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\chich\miniconda3\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\chich/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 705, in forward
    y = self.model(x, augment=augment)  # forward
  File "C:\Users\chich\miniconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\chich/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 537, in forward
    assert im.shape == s, f"input size {im.shape} {'>' if self.dynamic else 'not equal to'} max model size {s}"
AssertionError: input size torch.Size([1, 3, 640, 480]) not equal to max model size (1, 3, 640, 640)
```

when specifically applying the img size when exporting the model works, though for my use case I cannot guarantee the input will be of the specified img size.

### Environment

-YOLO V5 fdc35b119ad21c7f205596dbb238f780c87040ec Pytorch 1.13.1 Cuda compilation tools, release 11.7, V11.7.99 (3090Ti 24GB)
-OS: Windows 11
-Python 3.8 Anaconda Environment

### Minimal Reproducible Example

Export as any of the following:

`export.py --weights yolov5s.pt --half --include engine --device 0`
`export.py --weights yolov5s.pt --dynamic --include engine --device 0`
`export.py --weights yolov5s.pt  --include engine --device 0`

then run this python script

```
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s.engine')
results = model('bus.jpg')
results.print()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RossLeeThomas** [comment]
Have the same issue here as well. Also tried the same export methods.

**Comment by WalterbutnotWalter** [comment]
Have same issue. The V5 version is the new one.

**Comment by chichun2002** [comment]
Bump

**Comment by michael-mayo** [comment]
This is also an issue when trying to inference using tensorrt on linux

**Comment by dsoltysiuk** [comment]
+1

**Comment by glenn-jocher** [comment]
@dsoltysiuk thank you for your comment. We have taken note of your interest in this issue. The YOLOv5 team is actively working on enhancements for the library and we appreciate your feedback. Your continued support is important to us!

If you have any more questions or concerns, please don't hesitate to let us know how we can help.

Best regards!
