### ISSUE TITLE
Detect.py run on terminal raise ImportError from DetectMultiBackend to no name ASTText from asttokens

### ISSUE THREAD

**Issue by w12l3-c** [ultralytics/yolov5#10758]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I read through some issues and discussions of this question and I have tried all the methods on there but it doesn't work and there is some variance between their problems to mine. 

I try to run `python3 detect.py` or `python3 detect.py --source OPTION` in my terminal but it raises an ImportError telling me about a certain text cannot be imported in some library in my pip. However, I checked that my asttokens is the most recent version and I just clone this repo yesterday so it shouldn't be a version problem(?).  Are there any solutions to this?

The following error:
`% python3 detect.py --source OPTION
Traceback (most recent call last):
  File "/Users/me/yolov5/detect.py", line 45, in <module>
    from models.common import DetectMultiBackend
  File "/Users/me/yolov5/models/common.py", line 24, in <module>
    from IPython.display import display
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/__init__.py", line 51, in <module>
    from .core.application import Application
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/core/application.py", line 26, in <module>
    from IPython.core import release, crashhandler
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/core/ultratb.py", line 101, in <module>
    import stack_data
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stack_data/__init__.py", line 1, in <module>
    from .core import Source, FrameInfo, markers_from_ranges, Options, LINE_GAP, Line, Variable, RangeInLine, \
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stack_data/core.py", line 19, in <module>
    from stack_data.utils import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stack_data/utils.py", line 11, in <module>
    from asttokens import ASTText
ImportError: cannot import name 'ASTText' from 'asttokens' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/asttokens/__init__.py)`

**Comment by glenn-jocher** [comment]
@w12l3-c hi there! 🌟 It seems that the issue you're encountering is related to incompatible library versions. The error message indicates an `ImportError` stemming from the `asttokens` library. This often occurs when there are conflicts with different library versions.

To resolve this, I recommend checking and ensuring that all your dependencies, including `asttokens`, are up to date. You can do this by updating the `asttokens` library using `pip` by running `pip install --upgrade asttokens`. Additionally, you may want to verify if there are any conflicting dependencies that may be impacting the `asttokens` library.

If the issue persists, you might want to consider creating a clean virtual environment and reinstalling all the required dependencies to ensure a clean and compatible environment.

I hope this helps! Let me know how it goes.
