### ISSUE TITLE
classify/val.py not working for custom data

### ISSUE THREAD

**Issue by akashAD98** [ultralytics/yolov5#10920]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

i have trained model, now i want to see the validation score, but im getting this error

```
!python classify/val.py --weights /content/drive/MyDrive/yolov5/runs/train-cls/exp15/weights/best.pt --data 'NewData' --img 224  # validate
```

```
Traceback (most recent call last):
  File "classify/val.py", line 168, in <module>
    main(opt)
  File "classify/val.py", line 163, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "classify/val.py", line 90, in run
    dataloader = create_classification_dataloader(path=test_dir,
  File "/content/drive/MyDrive/yolov5/utils/dataloaders.py", line 1207, in create_classification_dataloader
    dataset = ClassificationDataset(root=path, imgsz=imgsz, augment=augment, cache=cache)
  File "/content/drive/MyDrive/yolov5/utils/dataloaders.py", line 1173, in __init__
    super().__init__(root=root)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: 'NewData/val'
```

<img width="352" alt="image" src="https://user-images.githubusercontent.com/62583018/217199806-4a5dc92b-27ef-4434-9919-b8e7956958a0.png">

### Environment

im using google collab

**Comment by usapeshka** [comment]
what was the issue?

**Comment by glenn-jocher** [comment]
@usapeshka hello there!

The error message you provided suggests that the `val.py` script could not find the validation data directory in the path you specified. Please make sure that the `--data` argument in your command points to the correct directory (in this case, to the root folder of your validation data). Also, please make sure that the subdirectory `val/` exists within your `NewData/` directory.

If you're still experiencing issues, please let me know and I'll try to assist you further. 

Best regards, 
Glenn Jocher

**Comment by usapeshka** [comment]
Got it, Thanks!

**Comment by glenn-jocher** [comment]
@usapeshka you're welcome! If you have any further issues or questions, please don't hesitate to ask. We're always here to help.
