### ISSUE TITLE
Invalid dimensions errors on exported models

### ISSUE THREAD

**Issue by tlong123** [ultralytics/yolov5#11129]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there, love this project! I'm having some trouble using the exported models - but can't tell how to solve this.

I have trained a model with the resultant model in the root of the repo called "v3seaDrone.pt" (with an image size of 1920). this works fine with my test image "3.jpg" when called either with the python detect.py script or through the torch.hub.load method. I have exported this model to onnx and torchscript with the command:

`python export.py --weights "v3seaDrone.pt" --img 1920 --include onnx torchscript`

and these appear to work fine when I run them with the detect script:

`python detect.py --weights "v3seaDrone.onnx" --imgsz 1920 --source "3.jpg"`

however when I try to do the same thing with the hub load method:

```    
    model = torch.hub.load(".", "custom",  path="v3seaDrone.onnx", source='local')
    results = model("3.jpg", size=1920)
    results.print()
```

I get the following error (I have installed onnx):

```    
Loading v3seaDrone.onnx for ONNX Runtime inference...
Adding AutoShape...
Traceback (most recent call last):
  File "F:\ml\yolov5\detect_and_notify.py", line 21, in <module>
    results = model(img, size=1920)
  File "C:\Users\Me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\ml\yolov5\.\models\common.py", line 704, in forward
    y = self.model(x, augment=augment)  # forward
  File "C:\Users\Me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\ml\yolov5\.\models\common.py", line 523, in forward
    y = self.session.run(self.output_names, {self.session.get_inputs()[0].name: im})
  File "C:\Users\Me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 1472 Expected: 1920
 Please fix either the inputs or the model.
```

and with the torchscript version I get:

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo.py", line 101, in forward
    _51 = (_31).forward((_30).forward(act, _50, ), _40, )
    _52 = (_33).forward(_46, _48, _50, (_32).forward(_51, ), )
           ~~~~~~~~~~~~ <--- HERE
    return (_52,)
class Detect(Module):
  File "code/__torch__/models/yolo.py", line 134, in forward
    _25 = torch.split_with_sizes(torch.sigmoid(_24), [2, 2, 7], 4)
    xy, wh, conf, = _25
    _26 = torch.add(torch.mul(xy, CONSTANTS.c0), CONSTANTS.c1)
          ~~~~~~~~~ <--- HERE
    xy0 = torch.mul(_26, torch.select(CONSTANTS.c2, 0, 0))
    _27 = torch.pow(torch.mul(wh, CONSTANTS.c0), 2)
RuntimeError: The size of tensor a (184) must match the size of tensor b (240) at non-singleton dimension 2
```

Any ideas about what I might be doing wrong or how to fix this?

**Comment by tlong123** [comment]
fixed this - I either needed to resize the images in a separate step or add the --dynamic flag to the export

**Comment by glenn-jocher** [comment]
@tlong123 glad to hear you found a solution! Resizing the images separately or adding the `--dynamic` flag to the export command are both valid approaches to address this issue. Good luck with your YOLOv5 project, and feel free to reach out if you need further assistance.
