### ISSUE TITLE
在运行分割代码的时候报错

### ISSUE THREAD

**Issue by sansanshizuibangde** [ultralytics/yolov5#11138]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

IndexError: Caught IndexError in DataLoader worker process 0.
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 6

### Environment

python 3.9.11 
torch  1.12.1
torch.version.cuda	 11.3
GPU	NVIDIA GeForce RTX 3060

### Minimal Reproducible Example

Traceback (most recent call last):
  File "/home/jiangyanshan/yolov5/segment/train.py", line 664, in <module>
    main(opt)
  File "/home/jiangyanshan/yolov5/segment/train.py", line 555, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/jiangyanshan/yolov5/segment/train.py", line 284, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/jiangyanshan/yolov5/utils/dataloaders.py", line 172, in __iter__
    yield next(self.iterator)
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jiangyanshan/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jiangyanshan/yolov5/utils/segment/dataloaders.py", line 115, in __getitem__
    img, labels, segments = self.load_mosaic(index)
  File "/home/jiangyanshan/yolov5/utils/segment/dataloaders.py", line 255, in load_mosaic
    img4, labels4, segments4 = random_perspective(img4,
  File "/home/jiangyanshan/yolov5/utils/segment/augmentations.py", line 102, in random_perspective
    new_segments = np.array(new_segments)[i]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 6

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sansanshizuibangde this error is likely due to a mismatch in array dimensions during data loading and is not uncommon during data augmentation. To troubleshoot, please ensure your custom segmentation dataset adheres to the expected format outlined in our Docs at https://docs.ultralytics.com/yolov5/. Furthermore, a potential fix can often be found by upgrading to the latest YOLOv5 release, as similar issues may have already been addressed. If the problem persists, please provide more details about your custom dataset and any non-default training settings you are using. Good luck, and thank you for your understanding!
