### ISSUE TITLE
Error training model on kaggle

### ISSUE THREAD

**Issue by lemon1022** [ultralytics/yolov5#11279]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I compressed and uploaded the project to kaggle for training, and the error is as follows:

`Traceback (most recent call last):
  File "/kaggle/input/yolov5/train.py", line 67, in <module>
    GIT_INFO = check_git_info()
  File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/kaggle/input/yolov5/utils/general.py", line 362, in check_git_info
    commit = repo.head.commit.hexsha  # i.e. '3134699c73af83aac2a481435550b968d5792c0d'
  File "/opt/conda/lib/python3.7/site-packages/git/refs/symbolic.py", line 226, in _get_commit
    obj = self._get_object()
  File "/opt/conda/lib/python3.7/site-packages/git/refs/symbolic.py", line 219, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/opt/conda/lib/python3.7/site-packages/git/objects/base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/opt/conda/lib/python3.7/site-packages/git/db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/opt/conda/lib/python3.7/site-packages/git/cmd.py", line 1383, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/opt/conda/lib/python3.7/site-packages/git/cmd.py", line 1370, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/opt/conda/lib/python3.7/site-packages/git/cmd.py", line 1329, in _parse_object_header
    raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
ValueError: SHA could not be resolved, git returned: b''`

how to solve this problem？

**Comment by Oink98** [comment]
Same problem, how to fix it?
When I commented this line of code, the model trained for only one epoch and stopped.
It gave the following error:
`Traceback (most recent call last):
  File "train.py", line 655, in <module>
    main(opt)
  File "train.py", line 544, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 382, in train
    'git': GIT_INFO,  # {remote, branch, commit} if a git repo
NameError: name 'GIT_INFO' is not defined`

**Comment by llavkush** [comment]
same problem on azure machine learning notebook
  ```
GIT_INFO = check_git_info()
  File "/anaconda/envs/azureml_py38/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/grt-dl-compute2/code/Users/lavkush.gupta/rgrt_train/yolov5/utils/general.py", line 362, in check_git_info
    commit = repo.head.commit.hexsha  # i.e. '3134699c73af83aac2a481435550b968d5792c0d'
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/git/refs/symbolic.py", line 226, in _get_commit
    obj = self._get_object()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/git/refs/symbolic.py", line 219, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/git/objects/base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/git/db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/git/cmd.py", line 1338, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/git/cmd.py", line 1325, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/git/cmd.py", line 1284, in _parse_object_header
    raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
ValueError: SHA could not be resolved, git returned: b''
```

**Comment by llavkush** [comment]
doing a 'git fetch' inside yolov5 folder seems to solve this error

**Comment by glenn-jocher** [comment]
@llavkush it looks like the error is related to GIT_INFO, which is a part of the code that retrieves information about the Git repository if there is any (e.g., remote, branch, and commit info). One of the main reasons for this error could be corrupt Git data. 

Try running the command 'git fetch' in the YOLOv5 directory, and it could help solve the problem. If the problem persists, please check if you have Git installed on your machine, and it's accessible in the current environment. Sometimes it is possible that Git might not be appropriately installed, which could result in such errors. If that is the case, please install it and make sure that it's properly setup to run within your environment.

Let me know if it helps or you need further assistance.
