### ISSUE TITLE
Torch RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by vanshreddy** [ultralytics/yolov5#11414]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions. Any leads is much appreciated

### Question

Hey have this error from torch. I load the yolov5 with ` model = torch.hub.load(
        "ultralytics/yolov5", "custom", path=f"/app/weights/{model_file}"
    )` . I am running the code in a container

```
YOLOv5 🚀 2023-4-22 Python-3.8.0 torch-1.11.0a0+gitbc2c6ed CUDA:0 (NVIDIA Tegra X1, 3964MiB)

Traceback (most recent call last):
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 49, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 344, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 60, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/src/petra/petra_camera_publisher/publisher_main.py", line 63, in <module>
    yolov5_model = load_yolov5_model_on_gpu()
  File "/app/src/petra/petra_camera_publisher/yolov5_utils/helper.py", line 70, in load_yolov5_model_on_gpu
    model = torch.hub.load(
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
```
###

**Comment by glenn-jocher** [comment]
@vanshreddy it seems like PyTorch is having trouble reading the zip archive containing the model weights. As suggested in the error message, you can try to `force_reload=True` (e.g. `torch.hub.load("ultralytics/yolov5", "custom", path="path/to/weights", force_reload=True)`) to help reload your cache.

Alternatively, you could try to download the weights manually and then load the model from the local path (e.g. `torch.hub.load("ultralytics/yolov5", "custom", path="path/to/local/weights.pt")`). If you have already downloaded the weights, make sure to double-check that the archived zip file is not corrupted. 

If these steps do not help, please let me know and provide more information on your environment setup, the dataset used, and the distribution of images and classes.

**Comment by vanshreddy** [comment]
So i have tried  `force_reload` but it gives me the same error. I will try loading the model manually let you know if that works.

**Comment by glenn-jocher** [comment]
@vanshreddy okay, feel free to let me know if loading the model manually works or not. If not, please provide more information on your environment setup, the dataset used, and the distribution of images and classes, so I can help you better.

**Comment by ake020675** [comment]
loading the model manually works for me.

**Comment by glenn-jocher** [comment]
@ake020675 thank you for letting us know, we're glad to hear that loading the model manually worked for you. If you have any further issues or questions, feel free to ask.
