### ISSUE TITLE
Training in Windows environment

### ISSUE THREAD

**Issue by Jeon-wodn** [ultralytics/yolov5#11620]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone. 
I am learning with the FLIR dataset in the Windows conda environment. However, every time the training ends, an error like the following picture appears. How should I solve it?

![image](https://github.com/ultralytics/yolov5/assets/106516273/a9a5e143-8a45-4efb-8f3e-1d7d92a88a20)

**Comment by glenn-jocher** [comment]
@Hogushake hi there!

Thanks for reaching out. It looks like an error occurred during training. It's difficult to diagnose the issue with just the image, but it might be caused by different reasons. You can first try to make sure that you have all the requirements installed with the correct versions. Also, make sure you have enough memory for the dataset to be loaded successfully. 

If the issue persists, could you please provide the error message as text in your next reply? This would give us more information about the error and help us to provide you with a more accurate solution.

Thanks!

**Comment by Jeon-wodn** [comment]
Appreciate for your quick response.
first of all, The dataset structure is as follows.

```
yolov5
 ├── data
         ├── thermal
                 ├── train_flir_images
                         ├── images
                         ├── labels
                 ├── val_flir_images
                         ├── images
                         ├── labels
                 ├── test_flir_images
                         ├── images
                         ├── labels
        ├── rgb
                 ├── train_flir_images
                         ├── images
                         ├── labels
                 ├── val_flir_images
                         ├── images
                         ├── labels
                 ├── test_flir_images
                         ├── images
                         ├── labels
 ├── FLIR.yaml
```

The train command proceeded as follows.
`python train.py --img 640 --batch 30 --epochs 20 --data ./data/FLIR.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt --name yolov5s_results`

The error code is
```
20 epochs completed in 0.851 hours.
Optimizer stripped from runs\train\yolov5s_results5\weights\last.pt, 14.5MB
Optimizer stripped from runs\train\yolov5s_results5\weights\best.pt, 14.5MB

Validating runs\train\yolov5s_results5\weights\best.pt...
Fusing layers...
YOLOv5s summary: 157 layers, 7039792 parameters, 0 gradients, 15.8 GFLOPs
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   5%|▍         | 1/21 [00:00<Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tnvj4\github_source\yolov5\utils\plots.py", line 302, in plot_images
    cls = names[cls] if names else cls
KeyError: 2

Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tnvj4\github_source\yolov5\utils\plots.py", line 302, in plot_images
    cls = names[cls] if names else cls
KeyError: 4

                 Class     Images  Instances          P          R      mAP50   mAP50-95:  10%|▉         | 2/21 [00:01<Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tnvj4\github_source\yolov5\utils\plots.py", line 302, in plot_images
    cls = names[cls] if names else cls
KeyError: 4

Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tnvj4\github_source\yolov5\utils\plots.py", line 302, in plot_images
    cls = names[cls] if names else cls
KeyError: 2

                 Class     Images  Instances          P          R      mAP50   mAP50-95:  14%|█▍        | 3/21 [00:02<Exception in thread Thread-13:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tnvj4\github_source\yolov5\utils\plots.py", line 302, in plot_images
    cls = names[cls] if names else cls
KeyError: 4

Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tnvj4\github_source\yolov5\utils\plots.py", line 302, in plot_images
    cls = names[cls] if names else cls
KeyError: 2

                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 21/21 [00:14
C:\Users\tnvj4\github_source\yolov5\utils\metrics.py:83: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  names = [v for k, v in names.items() if k in unique_classes]  # list: only classes that have data
                   all       1212      13958      0.651      0.498      0.536      0.308
Traceback (most recent call last):
  File "train.py", line 630, in <module>
    main(opt)
  File "train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 422, in train
    compute_loss=compute_loss)  # val best model with plots
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\tnvj4\github_source\yolov5\val.py", line 290, in run
    LOGGER.info(pf % (names[c], seen, nt[c], p[i], r[i], ap50[i], ap[i]))
KeyError: 0

```

**Comment by glenn-jocher** [comment]
@Hogushake hello! 

Based on the error message, it looks like you have a KeyError when you're plotting images in `plot.py`. This could be caused by issues with your dataset. You can check the dataset and make sure that all images are properly labeled and that the labels match the number of classes you have specified in your `.yaml` file. 

Regarding your other errors, it's hard to diagnose the issue with just the image you provided. However, you can try upgrading PyTorch as this issue might be related to a PyTorch version. Additionally, double-check that you have all the required dependencies installed with their correct versions to avoid any compatibility issues. 

Hope this helps!

**Comment by Jeon-wodn** [comment]
It seems to be a problem with the dataset annotation data. No error occurred when using the flir dataset uploaded to roboflow. It seems that it did not work properly in the yolo format conversion process. thank you!

**Comment by glenn-jocher** [comment]
@Hogushake hi there! 

It's good to hear that the issue resolved when using the FLIR dataset uploaded to Roboflow. It could be that there were some issues with the original dataset's annotations that caused problems with the YOLO format conversion process. It's always a good idea to double-check the annotations and make sure they're correctly formatted. 

If you have any further issues or questions in the future, please don't hesitate to reach out. Thanks for using YOLOv5!
