### ISSUE TITLE
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Artifact batch size exceeded the limit of 100'

### ISSUE THREAD

**Issue by pathikg** [ultralytics/yolov5#11717]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations

### Bug

I was training a yolov8n on my custom dataset with integrated `azure-mlfow` for tracking. 
![image](https://github.com/ultralytics/yolov5/assets/55437218/9af7e871-c0a7-4b6c-9b52-b33cd704975e)
![image](https://github.com/ultralytics/yolov5/assets/55437218/d74291a9-b7e1-4040-a8da-19b3eba1165d)

Training and tracking worked fine for `epochs` mentioned in the argument but at the end of training, I received the following error 
**Traceback:** 

```
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "ultralytics-exp.py", line 8, in <module>
    model.train(data="data.yaml", epochs=1)  # train the model
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 401, in _do_train
    self.run_callbacks('on_train_end')
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 165, in run_callbacks
    callback(self)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/utils/callbacks/mlflow.py", line 61, in on_train_end
    run.pyfunc.log_model(artifact_path=experiment_name,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 1578, in log_model
    return Model.log(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/models/model.py", line 487, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 810, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1048, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_store/artifact/artifact_repo.py", line 88, in log_artifacts
    self.artifacts.upload_dir(local_dir, dest_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 90, in upload_dir
    empty_artifact_res = self._create_empty_artifacts(paths=remote_paths, run_id=self._run_id)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 146, in _create_empty_artifacts
    response = self._client.run_artifacts.batch_create_empty_artifacts(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_restclient/run_artifact/operations/_run_artifacts_operations.py", line 1122, in batch_create_empty_artifacts
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Artifact batch size exceeded the limit of 100'
```

### Environment

YOLO - Ultralytics YOLOv8.0.117 🚀 Python-3.8.5 torch-2.0.1+cu117 CUDA:0 (Tesla T4, 15110MiB)
OS - Ubuntu 20.04.6 LTS (Azure ML GPU instance)

### Minimal Reproducible Example

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
model.train(data="data.yaml", epochs=3)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
```

### Additional

AzureML GPU: Standard_NC4as_T4_v3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pathikg** [comment]
mistakenly opened the issue in yolov5
 I've created one in ultralytics at [#3223](https://github.com/ultralytics/ultralytics/issues/3223)

**Comment by glenn-jocher** [comment]
@pathikg hi there,

Thank you for reaching out to us. I see that you opened an issue on the Ultralytics repository as well (#3223) regarding an error you encountered while training your custom dataset with integrated `azure-mlflow`. I apologize for any confusion caused.

Our team will address your issue on the Ultralytics repository, and we will make sure to provide you with a solution or further assistance as soon as possible.

Thank you for bringing this to our attention, and we appreciate your patience.

Best regards,
Glenn Jocher, Ultralytics Team
