### ISSUE TITLE
How to successfully use a model in .pb format in `detect.py`?

### ISSUE THREAD

**Issue by Jack0097tw** [ultralytics/yolov5#11795]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question. I successfully converted the model from .pt to .pb format using the following code:
`python export.py --weights ./runs/train/exp37/weights/best.pt --include pb --imgsz 960`, and I obtained the message: TensorFlow GraphDef: export success  1.2s, saved as runs\train\exp37\weights\best.pb (27.1 MB).

However, when I try to use the model in detect.py, I encounter an error. How can I resolve this issue? Here's the code I used for calling the model in detect.py: 
`python detect.py --weights runs\train\exp37\weights\best.pb`. 
Thank you in advance!

**Error message**
(yolov5_tf2.4) C:\Users\Pycharm project\yolo tf1\yolov5>python detect.py --weights runs\train\exp37\weights\best.pb
detect: weights=['runs\\train\\exp37\\weights\\best.pb'], source=data\images, data=dataset.yaml, imgsz=[960, 960], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False,
save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=Fal
se, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
git: 'project\yolo' is not a git command. See 'git --help'.
YOLOv5  2023-3-23 Python-3.7.6 torch-1.8.1+cpu CPU

Loading runs\train\exp37\weights\best.pb for TensorFlow GraphDef inference...
2023-07-01 10:40:39.999646: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following
CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 128, in run
    pred = model(im, augment=augment, visualize=visualize)
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Pycharm project\yolo tf1\yolov5\models\common.py", line 563, in forward
    y = self.frozen_func(x=self.tf.constant(im))
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1474, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 244, in _call_impl
    args, kwargs, cancellation_manager)
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1492, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1541, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\tensorflow\python\eager\polymorphic_function\monomorphic_function.py", line 383, in call
    ctx=ctx)
  File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'model/tf_conv/sequential/conv2d/BiasAdd' defined at (most recent call last):
    File "detect.py", line 261, in <module>
      main(opt)
    File "detect.py", line 256, in main
      run(**vars(opt))
    File "C:\Users\anaconda3\envs\yolov5_tf2.4\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
      return func(*args, **kwargs)
    File "detect.py", line 98, in run
      model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
    File "C:\Users\Pycharm project\yolo tf1\yolov5\models\common.py", line 447, in __init__
      frozen_func = wrap_frozen_graph(gd, inputs='x:0', outputs=gd_outputs(gd))
    File "C:\Users\Pycharm project\yolo tf1\yolov5\models\common.py", line 435, in wrap_frozen_graph
      return x.prune(tf.nest.map_structure(ge, inputs), tf.nest.map_structure(ge, outputs))
Node: 'model/tf_conv/sequential/conv2d/BiasAdd'
Fused conv implementation does not support grouped convolutions for now.
         [[{{node model/tf_conv/sequential/conv2d/BiasAdd}}]] [Op:__inference_pruned_2099]

**Comment by glenn-jocher** [comment]
@1012Miller it appears that you are encountering an error when trying to use a model in .pb format with `detect.py`. The error message suggests that the issue is related to fused convolutions not supporting grouped convolutions at the moment. 

To resolve this issue, you can try the following steps:

1. Update TensorFlow: The error message suggests that you may need to rebuild TensorFlow with the appropriate compiler flags to enable the required CPU instructions. Make sure you have the latest version of TensorFlow installed and try rebuilding it with the necessary flags.

2. Check the model conversion: Double-check the conversion process from `.pt` to `.pb` format. Ensure that the conversion was successful and that the resulting `.pb` file is not corrupted.

3. Modify the model architecture: If the above steps don't resolve the issue, you may need to modify the model architecture to remove or adjust the grouped convolutions. This could involve editing the model definition or modifying the conversion script to handle grouped convolutions differently.

If these steps don't resolve the issue, please provide more details about the model architecture, the specific conversion script used, and any modifications made during the conversion process. Additionally, you can try reaching out to the YOLOv5 community or the developers for further assistance.
