### ISSUE TITLE
problem with Jetson TX1 ultralytics

### ISSUE THREAD

**Issue by SJavad** [ultralytics/yolov5#12058]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation, Detection, Integrations

### Bug

I want to run yolov5 model on my Jetson TX1 and when I enter `python3 val.py` for testing it gets me this error:
```
Traceback (most recent call last):
  File "val.py", line 39, in <module>
    from models.common import DetectMultiBackend
  File "/home/ubuntu/Downloads/yolov5/models/common.py", line 29, in <module>
    import ultralytics
  File "/usr/local/lib/python3.6/dist-packages/ultralytics-8.0.161-py3.6.egg/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "/usr/local/lib/python3.6/dist-packages/ultralytics-8.0.161-py3.6.egg/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "/usr/local/lib/python3.6/dist-packages/ultralytics-8.0.161-py3.6.egg/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/usr/local/lib/python3.6/dist-packages/ultralytics-8.0.161-py3.6.egg/ultralytics/models/rtdetr/model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "/usr/local/lib/python3.6/dist-packages/ultralytics-8.0.161-py3.6.egg/ultralytics/engine/model.py", line 10, in <module>
    from ultralytics.hub.utils import HUB_WEB_ROOT
  File "/usr/local/lib/python3.6/dist-packages/ultralytics-8.0.161-py3.6.egg/ultralytics/hub/__init__.py", line 6, in <module>
    from ultralytics.hub.auth import Auth
  File "/usr/local/lib/python3.6/dist-packages/ultralytics-8.0.161-py3.6.egg/ultralytics/hub/auth.py", line 76
    if header := self.get_auth_header():
               ^
SyntaxError: invalid syntax
```
how can I solve this problem?

### Environment

OS: Ubuntu 18.04
Python: 3.6.9
Platform: Jetson TX1
CUDA: 10.2
Cudnn: 8.2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SJavad** [comment]
any command I want to run it get me this error:
this is my packages that I installed on jetson:
```
Package                       Version
----------------------------- --------------------
apt-clone                     0.2.1
apturl                        0.5.2
asn1crypto                    0.24.0
beautifulsoup4                4.6.0
blinker                       1.4
Brlapi                        0.6.6
certifi                       2018.1.18
chardet                       3.0.4
charset-normalizer            2.0.12
click                         6.7
cmake                         3.22.0
colorama                      0.3.7
commonmark                    0.9.1
cryptography                  2.1.4
cupshelpers                   1.0
cycler                        0.10.0
Cython                        3.0.0
dataclasses                   0.8
decorator                     4.1.2
defer                         1.0.6
distro                        1.8.0
distro-info                   0.18ubuntu0.18.04.1
feedparser                    5.2.1
flatbuffers                   23.5.26
gitdb                         4.0.9
GitPython                     3.1.18
graphsurgeon                  0.4.5
html5lib                      0.999999999
httplib2                      0.9.2
idna                          2.6
importlib-resources           5.4.0
Jetson.GPIO                   2.0.17
jetson-stats                  4.2.3
joblib                        1.1.1
keyring                       10.6.0
keyrings.alt                  3.0
kiwisolver                    1.3.1
language-selector             0.1
launchpadlib                  1.10.6
lazr.restfulclient            0.13.5
lazr.uri                      1.0.3
louis                         3.5.0
lxml                          4.2.1
macaroonbakery                1.1.3
Mako                          1.0.7
MarkupSafe                    1.0
matplotlib                    3.3.4
numpy                         1.19.5
nvidia-pyindex                1.0.9
oauth                         1.0.1
oauthlib                      2.0.6
onboard                       1.4.1
onnx                          1.11.0
onnxruntime                   1.10.0
opencv-python                 4.8.0.76
PAM                           0.4.2
pandas                        1.1.5
Pillow                        6.2.2
pip                           21.3.1
protobuf                      3.19.6
psutil                        5.9.5
py-cpuinfo                    9.0.0
pycairo                       1.16.2
pycrypto                      2.6.1
pycups                        1.9.73
Pygments                      2.14.0
PyGObject                     3.26.1
PyICU                         1.9.8
PyJWT                         1.5.3
pymacaroons                   0.13.0
PyNaCl                        1.1.2
pyparsing                     2.2.0
pyRFC3339                     1.0
python-apt                    1.6.6
python-dateutil               2.8.2
python-debian                 0.1.32
pytz                          2018.3
pyxattr                       0.6.0
pyxdg                         0.25
PyYAML                        6.0.1
requests                      2.27.1
requests-unixsocket           0.1.5
rich                          12.6.0
scikit-learn                  0.24.0
scipy                         1.5.4
seaborn                       0.11.2
SecretStorage                 2.3.1
setuptools                    39.0.1
simplejson                    3.13.2
six                           1.11.0
smbus2                        0.4.2
smmap                         5.0.0
ssh-import-id                 5.7
system-service                0.3
systemd-python                234
tensorrt                      8.2.1.9
thop                          0.1.1.post2209072238
threadpoolctl                 3.1.0
torch                         1.9.0
torchvision                   0.10.0
tqdm                          4.64.1
typing_extensions             4.1.1
ubuntu-advantage-tools        8001
ubuntu-drivers-common         0.0.0
uff                           0.6.9
ultralytics                   8.0.161
unity-scope-calculator        0.1
unity-scope-chromiumbookmarks 0.1
unity-scope-colourlovers      0.1
unity-scope-devhelp           0.1
unity-scope-firefoxbookmarks  0.1
unity-scope-manpages          0.1
unity-scope-openclipart       0.1
unity-scope-texdoc            0.1
unity-scope-tomboy            0.1
unity-scope-virtualbox        0.1
unity-scope-yelp              0.1
unity-scope-zotero            0.1
urllib3                       1.22
urwid                         2.0.1
wadllib                       1.3.2
webencodings                  0.5
wheel                         0.30.0
xkit                          0.0.0
youtube_dl                    2018.3.14
zipp                          3.6.0
zope.interface                4.3.2
```

**Comment by glenn-jocher** [comment]
@SJavad the error you're encountering is due to the usage of the Walrus operator (:=) which is not supported in Python 3.6. The Ultralytics library requires a minimum Python version of 3.8.

To resolve this issue, you can upgrade your Python version to 3.8 or higher. After upgrading, you should be able to run the `val.py` script without any errors.

Please note that the YOLOv5 repository and the Ultralytics library are developed and maintained by an entire community of contributors. If you encounter any further issues or have any other questions, we are here to assist you.

**Comment by SJavad** [comment]
> @SJavad the error you're encountering is due to the usage of the Walrus operator (:=) which is not supported in Python 3.6. The Ultralytics library requires a minimum Python version of 3.8.
> 
> To resolve this issue, you can upgrade your Python version to 3.8 or higher. After upgrading, you should be able to run the `val.py` script without any errors.
> 
> Please note that the YOLOv5 repository and the Ultralytics library are developed and maintained by an entire community of contributors. If you encounter any further issues or have any other questions, we are here to assist you.

I previously use yolov5 on jetson tx1 
but now, I get this error...
I cannot update my python version because jetson tx1 do not support any python version greater than 3.6.
all my packages like tensorrt and ... installed on python3.6

**Comment by SJavad** [comment]
note that, I don't install ultrlytics on that jetson.
but yolov5 works fine

**Comment by glenn-jocher** [comment]
@SJavad thank you for bringing this issue to our attention. The error you are encountering with the Jetson TX1 and YOLOv5 seems to be related to the Ultralytics library, which is a dependency of YOLOv5.

The error message suggests that the Walrus operator (:=) is being used in the Ultralytics library, which is not supported in Python 3.6. The Ultralytics library requires a minimum Python version of 3.8.

Since you are unable to upgrade your Python version on the Jetson TX1, which supports a maximum of Python 3.6, it may not be possible to use the Ultralytics library with the current setup. However, you mentioned that YOLOv5 works fine without installing the Ultralytics library.

If you have any other questions or need further assistance, please let us know. We are here to help.
