### ISSUE TITLE
Real-time object detection app with GUI (tkinker) using yolov5

### ISSUE THREAD

**Issue by SzymonGroch** [ultralytics/yolov5#12247]
My current issue is continuation to #12110 
For reference here's the replay I'm refering to:

> @SzymonGroch hi,
> 
> To display the webcam feed while performing real-time object detection, you can modify the code in `detect.py` as follows:
> 
> 1. Import the necessary libraries:
> ```
> import cv2
> from PIL import Image
> ```
> 
> 2. Replace the line that reads the image with code to read the webcam feed:
> ```
> # Replace this line
> img = Image.open(img_path)
> 
> # with this line to read from webcam
> cap = cv2.VideoCapture(0)
> ret, frame = cap.read()
> img = Image.fromarray(frame)
> ```
> 
> 3. Modify the detection loop to continuously read frames from the webcam:
> ```
> while True:
>     # replace this line to read from webcam
>     ret, frame = cap.read()
>     img = Image.fromarray(frame)
> 
>     # Rest of the code for object detection and display
>     ...
> ```
> 
> By making these changes, the script will continuously process frames from the webcam feed and display the output with bounding boxes.
> 
> Please note that the code provided is a basic example and may need further modifications to integrate it into your specific application.
> 
> I hope this helps! If you have any further questions, feel free to ask.
> 
> Best regards,
> Glenn Jocher, author and maintainer of the Ultralytics YOLOv5 repo at https://github.com/ultralytics/yolov5 under AGPL-3.0 licenses.

_Originally posted by @glenn-jocher in https://github.com/ultralytics/yolov5/issues/12110#issuecomment-1713485938_
            
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Sorry for late replay. I was trying to implement yolov5 in C# with little success by the time I created that issue. Now I'm trying to deploy in python app and look up your reply.

Regarding your code:
I'm clueless as to what am I supposed to change since I can't find line you advised me to change
for example:

```
#Replace this line
img = Image.open(img_path)
```
My current goal is to display webcam feed (same as choosing webcam as source in detect.py ) in tkinter window.
My current attempt is (main.py file):

```
import tkinter as tk
from tkinter import ttk
import cv2
import torch
from PIL import Image, ImageTk
import time
import os


custom_model_path = os.path.join("models", "znaki21.pt")
if not os.path.exists(custom_model_path):
    print("Custom model file not found in the 'models' folder.")
    exit(1)


model = torch.load("znaki21.pt")
model.eval()

def initialize_webcam():
    global cap, selected_webcam
    if cap is not None:
        cap.release()  # Release the previously opened webcam

    # Get the selected webcam index from the dropdown
    selected_webcam = webcam_var.get()

    # Initialize the selected webcam
    cap = cv2.VideoCapture(selected_webcam)
selected_webcam = 0;

try:
    cap = cv2.VideoCapture(0)  # Adjust the camera index as needed
    if not cap.isOpened():
        raise Exception("Webcam capture object could not be opened.")
except Exception as e:
    print(f"Error: {e}")


root = tk.Tk()
root.title("Real-time Object Detection")


label = ttk.Label(root)
label.pack()


fps_label = ttk.Label(root, text="FPS: ")
fps_label.pack()


webcam_label = ttk.Label(root, text="Select Webcam:")
webcam_label.pack()


available_webcams = [f"Webcam {i}" for i in range(10)]  # You can adjust the range as needed


webcam_var = tk.StringVar()
webcam_var.set(selected_webcam)  # Set the default webcam


webcam_dropdown = ttk.Combobox(root, textvariable=webcam_var, values=available_webcams)
webcam_dropdown.pack()


initialize_button = ttk.Button(root, text="Initialize Webcam", command=initialize_webcam)
initialize_button.pack()


detected_objects_listbox = tk.Listbox(root, height=20, width=30)
detected_objects_listbox.pack()

frame_count = 0
start_time = time.time()

def update_frame():
    global frame_count, start_time
    ret, frame = cap.read()

    
    results = model(frame)

   
    detections = results.pred[0]

    
    annotated_frame = detections.render()[0]

    
    frame_count += 1
    if frame_count % 10 == 0:
        elapsed_time = time.time() - start_time
        fps = frame_count / elapsed_time
        fps_label.config(text=f"FPS: {fps:.2f}")

    
    frame_rgb = cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB)
    frame_tk = ImageTk.PhotoImage(Image.fromarray(frame_rgb))

    label.imgtk = frame_tk
    label.configure(image=frame_tk)

    
    detected_objects_listbox.delete(0, tk.END)  # Clear the existing items
    for obj in detections.names:
        detected_objects_listbox.insert(tk.END, obj)

    label.after(10, update_frame)  # Update every 10 milliseconds


update_frame()


root.mainloop()


if cap is not None:
    cap.release()
cv2.destroyAllWindows()
```
Initially I was working without yolov5 repo because I thought I could just open the model file but now I'm just to be sure.
I've tried other solutions but all of them fail at loading model phase.

current error:

```
Traceback (most recent call last):
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 17, in <module>
    model.eval()
AttributeError: 'dict' object has no attribute 'eval'
```
If I remove model.eval() it shows:
```
Traceback (most recent call last): File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 111, in <module> update_frame() File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 81, in update_frame results = model(frame) TypeError: 'dict' object is not callable
```
When I tried without yolov5 repo it had problem with "model.yolo" on line:
```
custom_model_path = os.path.join("models", "znaki21.pt")
```
Sorry If I'm spamming but I wasn't sure if **stale** issues are checked and I'm really want help. If I should reopen previous issue #12110 then let me know.

**Comment by glenn-jocher** [comment]
@SzymonGroch hi there!

I apologize for the confusion caused by my previous response. It seems that I provided inaccurate instructions for your specific use case. 

Looking at your code, it appears that you are encountering an error related to the model object. Specifically, the error message suggests that the model object is a dictionary and does not have the `eval` attribute. This indicates that the model is not in the expected format.

To resolve this issue, you will need to load the YOLOv5 model using the `torchvision.models.load_model` function. Here's an example of how you can modify your code:

```python
import torch
import torchvision

# Load the YOLOv5 model
model = torchvision.models.load_model("znaki21.pt", map_location=torch.device("cpu"))

```

Additionally, you can remove or comment out the line `model.eval()` as it is not necessary in this case.

I hope this helps! If you have any further questions or issues, feel free to ask.

Best regards,
Glenn Jocher, author and maintainer of the Ultralytics YOLOv5 repo under AGPL-3.0 licenses.

**Comment by SzymonGroch** [comment]
@glenn-jocher 
Thx for fast reply. In that post I was a little criptic about my goal so I'm to blame too a little.

I tried using your solution but got following error:
```
Traceback (most recent call last):
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 20, in <module>
    model = torchvision.models.load_model("znaki21.pt", map_location=torch.device("cpu"))
AttributeError: module 'torchvision.models' has no attribute 'load_model'
```
I research a bit and found that I can apparently use this instead
```
model = torch.load("znaki21.pt", map_location=torch.device("cpu"))
```
Even though I tried it before but a that time it had problem with argument part: `map_location=torch.device("cpu"))` (maybe it got fixed with adding` torchvision` ?)
but get this error instead
```
Traceback (most recent call last):
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 120, in <module>
    update_frame()
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 90, in update_frame
    results = model(frame)
TypeError: 'dict' object is not callable`
```
For the record my custom model **znaki21.pt** can be run using detect.py without problems. Unless I need my model to be in different format...

**Comment by glenn-jocher** [comment]
@SzymonGroch thanks for the update and providing more information about the issue you encountered.

Regarding the error you received when using `torchvision.models.load_model`, you are correct that the `load_model` function does not exist in `torchvision.models`. My apologies for the confusion caused by my previous response. 

To load the model, you can use `torch.load` as you mentioned. However, the error you encountered is likely due to the fact that the loaded model is a dictionary object and not a callable object. This means that you need to access the YOLOv5 model from the dictionary before you can use it for inference.

Based on the code structure of your original implementation, you can modify it as follows to access the YOLOv5 model:

```python
# Load the YOLOv5 model
model_dict = torch.load("znaki21.pt", map_location=torch.device("cpu"))
model = model_dict["model"].float().eval()
```

With these modifications, you should now be able to access the YOLOv5 model and use it for inference.

Please let me know if you have any further questions or if there's anything else I can assist you with.

**Comment by SzymonGroch** [comment]
@glenn-jocher 
I think it managed to read my model but there's know an error I can't begin to understand:
```
Traceback (most recent call last):
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 121, in <module>
    update_frame()
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 91, in update_frame
    results = model(frame)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\common.py", line 56, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)


Process finished with exit code 1
```
just to be sure I tried loading **yolov5s.pt** model but same error is displayed. Is there something wrong with 
**update_frame()** function ?

**Comment by glenn-jocher** [comment]
@SzymonGroch it looks like the error you're encountering is related to the `forward` function in the YOLOv5 model. Specifically, there is an issue with the `F.conv2d` call within the function. 

The error message indicates that the `F.conv2d` function received arguments of invalid types. It expects arguments of type `Tensor`, but it received a `numpy.ndarray`, `Parameter`, and `NoneType`.

To further investigate and resolve the issue, it would be helpful to have a closer look at the implementation of the `forward` function in your custom model. Can you please provide the relevant code snippet from the `yolo.py` file?

Regarding your question about the `update_frame()` function, it is difficult to determine whether there is an issue with it without seeing its implementation. However, based on the traceback, the problem seems to be related to the YOLOv5 model and not the `update_frame()` function itself.

**Comment by SzymonGroch** [comment]
@glenn-jocher Here you go

```
    def forward(self, x):
        z = []  # inference output
        for i in range(self.nl):
            x[i] = self.m[i](x[i])  # conv
            bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            if not self.training:  # inference
                if self.dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
                    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)

                if isinstance(self, Segment):  # (boxes + masks)
                    xy, wh, conf, mask = x[i].split((2, 2, self.nc + 1, self.no - self.nc - 5), 4)
                    xy = (xy.sigmoid() * 2 + self.grid[i]) * self.stride[i]  # xy
                    wh = (wh.sigmoid() * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, conf.sigmoid(), mask), 4)
                else:  # Detect (boxes only)
                    xy, wh, conf = x[i].sigmoid().split((2, 2, self.nc + 1), 4)
                    xy = (xy * 2 + self.grid[i]) * self.stride[i]  # xy
                    wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, conf), 4)
                z.append(y.view(bs, self.na * nx * ny, self.no))

        return x if self.training else (torch.cat(z, 1),) if self.export else (torch.cat(z, 1), x)
```

**Comment by glenn-jocher** [comment]
@SzymonGroch based on the code snippet you provided, it seems that the error is occurring in the forward function of the YOLOv5 model. Specifically, there is an issue with the `F.conv2d` call that expects arguments of type `Tensor`, but received a `numpy.ndarray`, `Parameter`, and `NoneType` instead.

To resolve this issue, you can try converting the `numpy.ndarray` to a `Tensor` before passing it to the `F.conv2d` function. You can use `torch.from_numpy` to perform this conversion. Here's an example of how you can modify the code:

```python
import torch

# ...

def forward(self, x):
    z = []  # inference output
    for i in range(self.nl):
        x[i] = self.m[i](torch.from_numpy(x[i]))  # convert to Tensor
        bs, _, ny, nx = x[i].shape
        x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
        
        # rest of the code remains the same
        # ...
```

By converting the `numpy.ndarray` to a `Tensor` using `torch.from_numpy`, you should be able to resolve the issue related to the `F.conv2d` call.

Let me know if this helps or if you have any further questions.

**Comment by SzymonGroch** [comment]
@glenn-jocher 
Seems I might have given you wrong forward function...
after editing function I gave you I get this error:
```
Traceback (most recent call last):
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 121, in <module>
    update_frame()
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 91, in update_frame
    results = model(frame)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\common.py", line 56, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)


Process finished with exit code 1
```

here are other two **forward** functions
(in class Segment(Detect) )
```
    def forward(self, x):
        p = self.proto(x[0])
        x = self.detect(self, x)
        return (x, p) if self.training else (x[0], p) if self.export else (x[0], p, x[1])
```
in this one last line is mentioned (line 209, in class BaseModel(nn.Module) )
```
    def forward(self, x, profile=False, visualize=False):
        return self._forward_once(x, profile, visualize)  # single-scale inference, train
```
Sorry for that

I'm also giving you **forward_once** since error mentions it:
```
def _forward_once(self, x, profile=False, visualize=False):
        y, dt = [], []  # outputs
        for m in self.model:
            if m.f != -1:  # if not from previous layer
                x = y[m.f] if isinstance(m.f, int) else [x if j == -1 else y[j] for j in m.f]  # from earlier layers
            if profile:
                self._profile_one_layer(m, x, dt)
            x = m(x)  # run
            y.append(x if m.i in self.save else None)  # save output
            if visualize:
                feature_visualization(x, m.type, m.i, save_dir=visualize)
        return x
```

**Comment by glenn-jocher** [comment]
@SzymonGroch hello,

Based on the error message you provided, it seems that there is an issue with the `forward` function and the `_forward_once` function in the YOLOv5 model.

It appears that the `forward` function in the `Segment` class is calling the `detect` method with the incorrect syntax. The correct syntax for calling a method in Python is `self.detect(x)` instead of `self.detect(self, x)`. Please update the `forward` function in the `Segment` class with the following code:

```python
def forward(self, x):
    p = self.proto(x[0])
    x = self.detect(x)  # update this line
    return (x, p) if self.training else (x[0], p) if self.export else (x[0], p, x[1])
```

Regarding the `_forward_once` function, there is no apparent issue with the code you provided. However, please make sure that the arguments passed to the `F.conv2d` function in the `forward_once` function are of type `Tensor` and not `numpy.ndarray`, `Parameter`, or `NoneType`. If any of the arguments are of the incorrect type, you can convert them to `Tensor` using `torch.from_numpy` or other appropriate functions.

I hope this helps. Let me know if you have any further questions.

**Comment by SzymonGroch** [comment]
@glenn-jocher hi,
Still issues...

```
Traceback (most recent call last):
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 121, in <module>
    update_frame()
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\main.py", line 91, in update_frame
    results = model(frame)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\yolo.py", line 210, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\yolo.py", line 122, in _forward_once
    x = m(x)  # run
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\models\common.py", line 56, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\szymo\Documents\Programowanie\python\pythonProject\Znaki_yolo\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)


Process finished with exit code 1

```

**Comment by glenn-jocher** [comment]
@SzymonGroch it seems that the previous changes did not resolve the issue. The error persists, and it seems to be related to the `F.conv2d` call within the YOLOv5 model.

To further diagnose and resolve the issue, I recommend seeking assistance from the YOLOv5 community. You can consider posting your question on the YOLOv5 GitHub Discussions page to garner insights and potential solutions from a wider audience of developers familiar with YOLOv5 and its inner workings. Additionally, the YOLOv5 GitHub Discussions page serves as a valuable resource for troubleshooting and collaborating on YOLOv5-related inquiries.

I hope you find the assistance you need to address this issue effectively. If you have any other questions or concerns, feel free to ask.
