### ISSUE TITLE
'Detect' object has no attribute 'grid'

### ISSUE THREAD

**Issue by tgbaoo** [ultralytics/yolov5#12305]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have run this code from this repo:
https://github.com/tryolabs/soccer-video-analytics/tree/main

python3 run.py --model ../../test-detection/best.pt --video ../../test-detection/puttduy02.mp4
cpu

And this is the app log:
And I also got this error below:

```
Using cache found in /home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2023-11-1 Python-3.10.12 torch-1.12.1+cu102 CPU

Fusing layers...
YOLOv5x summary: 444 layers, 86705005 parameters, 0 gradients
Adding AutoShape...
cpu
../../test-detection/best.pt
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /home/tgbaoo/.cache/torch/hub/master.zip
YOLOv5 🚀 2023-11-1 Python-3.10.12 torch-1.12.1+cu102 CPU

YOLOv5s summary (fused): 193 layers, 9112310 parameters, 0 gradients, 23.8 GFLOPs
Adding AutoShape...
Traceback (most recent call last):
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 73, in _create
    return model.to(device)
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 664, in _apply
    m.grid = list(map(fn, m.grid))
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Detect' object has no attribute 'grid'
The above exception was the direct cause of the following exception:



Traceback (most recent call last):
  File "/mnt/d/Code/hole-in-one-classification/soccer-tracking/soccer-video-analytics/run.py", line 49, in <module>
    ball_detector = YoloV5(model_path=args.model)
  File "/mnt/d/Code/hole-in-one-classification/soccer-tracking/soccer-video-analytics/inference/yolov5.py", line 28, in __init__
    self.model = torch.hub.load("ultralytics/yolov5", "custom", path=model_path, force_reload=True)
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: 'Detect' object has no attribute 'grid'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tgbaoo hi there,

Thank you for bringing this issue to our attention. The error message you encountered, `'Detect' object has no attribute 'grid'`, seems to be related to the YOLOv5 implementation you are using. 

From the provided logs, it appears that you are using the YOLOv5 model provided by the Ultralytics YOLOv5 repository. However, this specific issue seems to be occurring in the `yolov5.py` file of the Soccer Video Analytics repository.

To resolve this issue, I recommend cross-referencing the implementations between the two repositories and ensuring compatibility. It's possible that the implementation in the Soccer Video Analytics repository is not up to date with the latest changes in the Ultralytics YOLOv5 repository.

If you believe this issue resides within the Ultralytics YOLOv5 repository itself, please provide a minimal reproducible example along with any additional relevant information, and we will be happy to address it accordingly.

I hope this helps, and please let me know if you have any further questions or concerns.

Best regards.

**Comment by tgbaoo** [comment]
Like I have train on the yolov5su.pt (ultralytics format) but I notice that the repo soccer they implement with the weight of original yolov5.pt here is the code caused the error:
So, is there anyway that i can sync the torch.hub.load the yolov5su(ultralytics format)?
yolov5.py:
```
from typing import List

import numpy as np
import pandas as pd
import torch

from inference.base_detector import BaseDetector


class YoloV5(BaseDetector):
    def __init__(
        self,
        model_path: str = None,
    ):
        """
        Initialize detector

        Parameters
        ----------
        model_path : str, optional
            Path to model, by default None. If it's None, it will download the model with COCO weights
        """
        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        print(self.device)

        if model_path:
            print(model_path)
            self.model = torch.hub.load("ultralytics/yolov5", "custom", path=model_path, force_reload=True)
        else:
            self.model = torch.hub.load(
                "ultralytics/yolov5", "yolov5x", pretrained=True
            )

    def predict(self, input_image: List[np.ndarray]) -> pd.DataFrame:
        """
        Predicts the bounding boxes of the objects in the image

        Parameters
        ----------
        input_image : List[np.ndarray]
            List of input images

        Returns
        -------
        pd.DataFrame
            DataFrame containing the bounding boxes
        """

        result = self.model(input_image, size=640)

        return result.pandas().xyxy[0]
```

and this:
hubconf.py:

```
import torch


def _create(name, pretrained=True, channels=3, classes=80, autoshape=True, verbose=True, device=None):
    """Creates or loads a YOLOv5 model

    Arguments:
        name (str): model name 'yolov5s' or path 'path/to/best.pt'
        pretrained (bool): load pretrained weights into the model
        channels (int): number of input channels
        classes (int): number of model classes
        autoshape (bool): apply YOLOv5 .autoshape() wrapper to model
        verbose (bool): print all information to screen
        device (str, torch.device, None): device to use for model parameters

    Returns:
        YOLOv5 model
    """
    from pathlib import Path

    from models.common import AutoShape, DetectMultiBackend
    from models.experimental import attempt_load
    from models.yolo import ClassificationModel, DetectionModel, SegmentationModel
    from utils.downloads import attempt_download
    from utils.general import LOGGER, ROOT, check_requirements, intersect_dicts, logging
    from utils.torch_utils import select_device

    if not verbose:
        LOGGER.setLevel(logging.WARNING)
    check_requirements(ROOT / 'requirements.txt', exclude=('opencv-python', 'tensorboard', 'thop'))
    name = Path(name)
    path = name.with_suffix('.pt') if name.suffix == '' and not name.is_dir() else name  # checkpoint path
    try:
        device = select_device(device)
        if pretrained and channels == 3 and classes == 80:
            try:
                model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
                if autoshape:
                    if model.pt and isinstance(model.model, ClassificationModel):
                        LOGGER.warning('WARNING ⚠️ YOLOv5 ClassificationModel is not yet AutoShape compatible. '
                                       'You must pass torch tensors in BCHW to this model, i.e. shape(1,3,224,224).')
                    elif model.pt and isinstance(model.model, SegmentationModel):
                        LOGGER.warning('WARNING ⚠️ YOLOv5 SegmentationModel is not yet AutoShape compatible. '
                                       'You will not be able to run inference with this model.')
                    else:
                        model = AutoShape(model)  # for file/URI/PIL/cv2/np inputs and NMS
            except Exception:
                model = attempt_load(path, device=device, fuse=False)  # arbitrary model
        else:
            cfg = list((Path(__file__).parent / 'models').rglob(f'{path.stem}.yaml'))[0]  # model.yaml path
            model = DetectionModel(cfg, channels, classes)  # create model
            if pretrained:
                ckpt = torch.load(attempt_download(path), map_location=device)  # load
                csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
                csd = intersect_dicts(csd, model.state_dict(), exclude=['anchors'])  # intersect
                model.load_state_dict(csd, strict=False)  # load
                if len(ckpt['model'].names) == classes:
                    model.names = ckpt['model'].names  # set class names attribute
        if not verbose:
            LOGGER.setLevel(logging.INFO)  # reset to default
        return model.to(device)

    except Exception as e:
        help_url = 'https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading'
        s = f'{e}. Cache may be out of date, try `force_reload=True` or see {help_url} for help.'
        raise Exception(s) from e


def custom(path='path/to/model.pt', autoshape=True, _verbose=True, device=None):
    # YOLOv5 custom or local model
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)

```

**Comment by glenn-jocher** [comment]
@tgbaoo hi there,

Thank you for reaching out. 

Based on the code you provided, it looks like the 'Soccer' repository is using the original YOLOv5 implementation, while you are using the YOLOv5s model from the Ultralytics YOLOv5 repository.

To sync the torch.hub.load the yolov5s.pt (Ultralytics format) with the Soccer repository, you will need to make the following changes:

1. In the 'yolov5.py' file of the Soccer repository, replace the following line:
```
self.model = torch.hub.load("ultralytics/yolov5", "yolov5x", pretrained=True)
```
with:
```
self.model = torch.hub.load("ultralytics/yolov5", "yolov5s", pretrained=True)
```

2. In the 'hubconf.py' file of the Ultralytics YOLOv5 repository, add the following function:
```python
def yolov5s(pretrained=True, channels=3, classes=80, autoshape=True, verbose=True, device=None):
    return _create('yolov5s', pretrained, channels, classes, autoshape, verbose, device)
```
This function will allow you to load the YOLOv5s model using the `torch.hub.load` function.

After making these changes, you should be able to load the YOLOv5s model from the Ultralytics repository in the 'Soccer' repository.

I hope this helps! If you have any further questions, please let me know.

**Comment by tgbaoo** [comment]
Yes, like I have trained and have custom weight from the yolov5su.pt - after trained is best.pt, then I guess on the code logic It should be execute the code: 

```
if model_path:
      print(model_path)
      self.model = torch.hub.load("ultralytics/yolov5", "custom", path=model_path, force_reload=True)
```

I have passed the best.pt(yolov5su) to this repo so I sure that It not init the yolov5x bút the custom case that lead to this error

**Comment by glenn-jocher** [comment]
@tgbaoo hi,

Thank you for providing the additional information. Based on the code logic you shared, it seems that you are correctly attempting to load the custom YOLOv5 model using the `torch.hub.load` function.

However, the error message you encountered indicates that the `'Detect' object has no attribute 'grid'`, which suggests that there may be an issue with the implementation of the YOLOv5 model in the Soccer repository.

To further troubleshoot this issue, I recommend examining the `yolov5.py` file in the Soccer repository and ensuring that the implementation is compatible with the custom YOLOv5 model. It's possible that there may be a mismatch between the custom model's attributes and the code implementation.

If you believe that the issue lies within the implementation of the YOLOv5 model in the Soccer repository, you may need to modify the code accordingly to align with the custom model's attributes.

Please let me know if you have any further questions or concerns.

**Comment by tgbaoo** [comment]
@glenn-jocher 
I have do some investigate debug then I have found this:
https://github.com/ultralytics/yolov5/issues/11542
I think you guys have to do something with this because I have seen someone report about this issue
common.py:
```
class AutoShape(nn.Module):
    # YOLOv5 input-robust model wrapper for passing cv2/np/PIL/torch inputs. Includes preprocessing, inference and NMS
    conf = 0.25  # NMS confidence threshold
    iou = 0.45  # NMS IoU threshold
    agnostic = False  # NMS class-agnostic
    multi_label = False  # NMS multiple labels per box
    classes = None  # (optional list) filter by class, i.e. = [0, 15, 16] for COCO persons, cats and dogs
    max_det = 1000  # maximum number of detections per image
    amp = False  # Automatic Mixed Precision (AMP) inference

    def __init__(self, model, verbose=True):
        super().__init__()
        if verbose:
            LOGGER.info('Adding AutoShape... ')
        copy_attr(self, model, include=('yaml', 'nc', 'hyp', 'names', 'stride', 'abc'), exclude=())  # copy attributes
        self.dmb = isinstance(model, DetectMultiBackend)  # DetectMultiBackend() instance
        self.pt = not self.dmb or model.pt  # PyTorch model
        self.model = model.eval()
        if self.pt:
            m = self.model.model.model[-1] if self.dmb else self.model.model[-1]  # Detect()
            m.inplace = False  # Detect.inplace=False for safe multithread inference
            m.export = True  # do not output loss values

    def _apply(self, fn):
        # Apply to(), cpu(), cuda(), half() to model tensors that are not parameters or registered buffers
        self = super()._apply(fn)
        if self.pt:
            m = self.model.model.model[-1] if self.dmb else self.model.model[-1]  # Detect()
            m.stride = fn(m.stride)
            m.grid = list(map(fn, m.grid))
            if isinstance(m.anchor_grid, list):
                m.anchor_grid = list(map(fn, m.anchor_grid))
        return self

    @smart_inference_mode()
    def forward(self, ims, size=640, augment=False, profile=False):
        # Inference from various sources. For size(height=640, width=1280), RGB images example inputs are:
        #   file:        ims = 'data/images/zidane.jpg'  # str or PosixPath
        #   URI:             = 'https://ultralytics.com/images/zidane.jpg'
        #   OpenCV:          = cv2.imread('image.jpg')[:,:,::-1]  # HWC BGR to RGB x(640,1280,3)
        #   PIL:             = Image.open('image.jpg') or ImageGrab.grab()  # HWC x(640,1280,3)
        #   numpy:           = np.zeros((640,1280,3))  # HWC
        #   torch:           = torch.zeros(16,3,320,640)  # BCHW (scaled to size=640, 0-1 values)
        #   multiple:        = [Image.open('image1.jpg'), Image.open('image2.jpg'), ...]  # list of images

        dt = (Profile(), Profile(), Profile())
        with dt[0]:
            if isinstance(size, int):  # expand
                size = (size, size)
            p = next(self.model.parameters()) if self.pt else torch.empty(1, device=self.model.device)  # param
            autocast = self.amp and (p.device.type != 'cpu')  # Automatic Mixed Precision (AMP) inference
            if isinstance(ims, torch.Tensor):  # torch
                with amp.autocast(autocast):
                    return self.model(ims.to(p.device).type_as(p), augment=augment)  # inference

            # Pre-process
            n, ims = (len(ims), list(ims)) if isinstance(ims, (list, tuple)) else (1, [ims])  # number, list of images
            shape0, shape1, files = [], [], []  # image and inference shapes, filenames
            for i, im in enumerate(ims):
                f = f'image{i}'  # filename
                if isinstance(im, (str, Path)):  # filename or uri
                    im, f = Image.open(requests.get(im, stream=True).raw if str(im).startswith('http') else im), im
                    im = np.asarray(exif_transpose(im))
                elif isinstance(im, Image.Image):  # PIL Image
                    im, f = np.asarray(exif_transpose(im)), getattr(im, 'filename', f) or f
                files.append(Path(f).with_suffix('.jpg').name)
                if im.shape[0] < 5:  # image in CHW
                    im = im.transpose((1, 2, 0))  # reverse dataloader .transpose(2, 0, 1)
                im = im[..., :3] if im.ndim == 3 else cv2.cvtColor(im, cv2.COLOR_GRAY2BGR)  # enforce 3ch input
                s = im.shape[:2]  # HWC
                shape0.append(s)  # image shape
                g = max(size) / max(s)  # gain
                shape1.append([int(y * g) for y in s])
                ims[i] = im if im.data.contiguous else np.ascontiguousarray(im)  # update
            shape1 = [make_divisible(x, self.stride) for x in np.array(shape1).max(0)]  # inf shape
            x = [letterbox(im, shape1, auto=False)[0] for im in ims]  # pad
            x = np.ascontiguousarray(np.array(x).transpose((0, 3, 1, 2)))  # stack and BHWC to BCHW
            x = torch.from_numpy(x).to(p.device).type_as(p) / 255  # uint8 to fp16/32

        with amp.autocast(autocast):
            # Inference
            with dt[1]:
                y = self.model(x, augment=augment)  # forward

            # Post-process
            with dt[2]:
                y = non_max_suppression(y if self.dmb else y[0],
                                        self.conf,
                                        self.iou,
                                        self.classes,
                                        self.agnostic,
                                        self.multi_label,
                                        max_det=self.max_det)  # NMS
                for i in range(n):
                    scale_boxes(shape1, y[i][:, :4], shape0[i])

            return Detections(ims, y, files, dt, self.names, x.shape)
```

then I found this line:

```
    def _apply(self, fn):
        # Apply to(), cpu(), cuda(), half() to model tensors that are not parameters or registered buffers
        self = super()._apply(fn)
        if self.pt:
            m = self.model.model.model[-1] if self.dmb else self.model.model[-1]  # Detect()
            print("Object: ", m)
            print("Object Attr: ", dir(m))
            m.stride = fn(m.stride)
            m.grid = list(map(fn, m.grid))
            if isinstance(m.anchor_grid, list):
                m.anchor_grid = list(map(fn, m.anchor_grid))
        return self
```

I have add the print log then I got this logger on the terminal:
```
python3 run.py --model ../../test-detection/best.pt --video ../../test-detection/puttduy02.mp4
cuda:0
Using cache found in /home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2023-11-2 Python-3.10.12 torch-1.12.1+cu102 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)

Fusing layers...
YOLOv5x summary: 444 layers, 86705005 parameters, 0 gradients
Adding AutoShape...
Object:  Detect(
  (m): ModuleList(
    (0): Conv2d(320, 255, kernel_size=(1, 1), stride=(1, 1))
    (1): Conv2d(640, 255, kernel_size=(1, 1), stride=(1, 1))
    (2): Conv2d(1280, 255, kernel_size=(1, 1), stride=(1, 1))
  )
)
Object attr:  ['T_destination', '__annotations__', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__slotnames__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_buffers', '_call_impl', '_forward_hooks', '_forward_pre_hooks', '_get_backward_hooks', '_get_name', '_is_full_backward_hook', '_load_from_state_dict', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_make_grid', '_maybe_warn_non_full_backward_hook', '_modules', '_named_members', '_non_persistent_buffers_set', '_parameters', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_replicate_for_data_parallel', '_save_to_state_dict', '_slow_forward', '_state_dict_hooks', '_version', 'add_module', 'anchor_grid', 'anchors', 'apply', 'bfloat16', 'buffers', 'children', 'cpu', 'cuda', 'double', 'dump_patches', 'dynamic', 'eval', 'export', 'export', 'extra_repr', 'f', 'float', 'forward', 'get_buffer', 'get_extra_state', 'get_parameter', 'get_submodule', 'grid', 'half', 'i', 'inplace', 'ipu', 'load_state_dict', 'm', 'modules', 'na', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'nc', 'nl', 'no', 'np', 'parameters', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_full_backward_hook', 'register_load_state_dict_post_hook', 'register_module', 'register_parameter', 'requires_grad_', 'set_extra_state', 'share_memory', 'state_dict', 'stride', 'stride', 'to', 'to_empty', 'train', 'training', 'type', 'type', 'xpu', 'zero_grad']
cuda:0
../../test-detection/best.pt
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /home/tgbaoo/.cache/torch/hub/master.zip
YOLOv5 🚀 2023-11-2 Python-3.10.12 torch-1.12.1+cu102 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)

YOLOv5s summary (fused): 193 layers, 9112310 parameters, 0 gradients, 23.8 GFLOPs
Adding AutoShape...
Object:  Detect(
  (cv2): ModuleList(
    (0): Sequential(
      (0): Conv(
        (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
    )
    (1): Sequential(
      (0): Conv(
        (conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
    )
    (2): Sequential(
      (0): Conv(
        (conv): Conv2d(512, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (cv3): ModuleList(
    (0): Sequential(
      (0): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(128, 2, kernel_size=(1, 1), stride=(1, 1))
    )
    (1): Sequential(
      (0): Conv(
        (conv): Conv2d(256, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(128, 2, kernel_size=(1, 1), stride=(1, 1))
    )
    (2): Sequential(
      (0): Conv(
        (conv): Conv2d(512, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(128, 2, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (dfl): DFL(
    (conv): Conv2d(16, 1, kernel_size=(1, 1), stride=(1, 1), bias=False)
  )
)
Object attr:  ['T_destination', '__annotations__', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__slotnames__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_backward_pre_hooks', '_buffers', '_call_impl', '_forward_hooks', '_forward_hooks_always_called', '_forward_hooks_with_kwargs', '_forward_pre_hooks', '_forward_pre_hooks_with_kwargs', '_get_backward_hooks', '_get_name', '_is_full_backward_hook', '_load_from_state_dict', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_maybe_warn_non_full_backward_hook', '_modules', '_named_members', '_non_persistent_buffers_set', '_parameters', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_replicate_for_data_parallel', '_save_to_state_dict', '_slow_forward', '_state_dict_hooks', '_state_dict_pre_hooks', '_version', 'add_module', 'anchors', 'anchors', 'apply', 'bfloat16', 'bias_init', 'buffers', 'children', 'cpu', 'cuda', 'cv2', 'cv3', 'dfl', 'double', 'dump_patches', 'dynamic', 'eval', 'export', 'export', 'extra_repr', 'f', 'float', 'forward', 'get_buffer', 'get_extra_state', 'get_parameter', 'get_submodule', 'half', 'i', 'inplace', 'ipu', 'load_state_dict', 'modules', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'nc', 'nl', 'no', 'parameters', 'reg_max', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_full_backward_hook', 'register_load_state_dict_post_hook', 'register_module', 'register_parameter', 'requires_grad_', 'set_extra_state', 'shape', 'shape', 'share_memory', 'state_dict', 'stride', 'strides', 'strides', 'to', 'to_empty', 'train', 'training', 'type', 'type', 'xpu', 'zero_grad']
Traceback (most recent call last):
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 73, in _create
    return model.to(device)
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 666, in _apply
    m.anchor_grid = list(map(fn, m.anchor_grid))
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Detect' object has no attribute 'grid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/Code/hole-in-one-classification/soccer-tracking/soccer-video-analytics/run.py", line 49, in <module>
    ball_detector = YoloV5(model_path=args.model)
  File "/mnt/d/Code/hole-in-one-classification/soccer-tracking/soccer-video-analytics/inference/yolov5.py", line 28, in __init__
    self.model = torch.hub.load(
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/tgbaoo/.cache/pypoetry/virtualenvs/soccer_video_analytics-dX1aYCv1-py3.10/lib/python3.10/site-packages/torch/hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/home/tgbaoo/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: 'Detect' object has no attribute 'grid'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
```

But the logger show Detector do have the grid attribute:
![image](https://github.com/ultralytics/yolov5/assets/86455738/3e85e81d-2173-4f1e-b9b8-05c4894b4c28)


Hope this help you identify what cause this error

**Comment by tgbaoo** [comment]
@glenn-jocher 
I have trained yolov5s (not u) but result still the same when I use cli for sahi detect

sahi predict --model_path ./best.pt --model_type yolov5 --source ./putt02.mp4 --view_video                         ─╯

YOLOv5s summary (fused): 193 layers, 9112310 parameters, 0 gradients, 23.8 GFLOPs
Traceback (most recent call last):
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/sahi/models/yolov5.py", line 29, in load_model
    model = yolov5.load(self.model_path, device=self.device)
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/yolov5/helpers.py", line 64, in load_model
    return model.to(device)
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/yolov5/models/common.py", line 659, in _apply
    m.grid = list(map(fn, m.grid))
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Detect' object has no attribute 'grid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/gia_bao/code/golf/golf_detection/bin/sahi", line 8, in <module>
    sys.exit(app())
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/sahi/cli.py", line 31, in app
    fire.Fire(sahi_app)
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/sahi/predict.py", line 518, in predict
    detection_model.load_model()
  File "/mnt/d/gia_bao/code/golf/golf_detection/lib/python3.10/site-packages/sahi/models/yolov5.py", line 32, in load_model
    raise TypeError("model_path is not a valid yolov5 model path: ", e)
TypeError: ('model_path is not a valid yolov5 model path: ', AttributeError("'Detect' object has no attribute 'grid'"))

**Comment by glenn-jocher** [comment]
@tgbaoo thank you for sharing your findings. The issue appears to be related to the 'Detect' object not having the 'grid' attribute, as depicted in the provided code and logs.

Based on the error messages, it seems that the YOLOv5 model being used by the 'sahi' tool is encountering an AttributeError related to the 'grid' attribute of the 'Detect' object.

To address this issue, I recommend ensuring that the YOLOv5 model and its associated implementation in the 'sahi' tool are configured appropriately and are compatible with each other. It's possible that the model or its attributes are not being loaded or utilized correctly within the 'sahi' tool.

If you have trained the YOLOv5s model and are still encountering this issue, I recommend reviewing the implementation within the 'sahi' tool to validate the compatibility of the model and the tool.

I hope this information helps in identifying the root cause of the error. If you have any further insights or need additional assistance, please feel free to share them.

Thank you for your diligence in investigating this issue.
