### ISSUE TITLE
WARNING: Ignore distutils configs in setup.cfg due to encoding errors.

### ISSUE THREAD

**Issue by nanjin1** [ultralytics/yolov5#12322]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

WARNING: Ignore distutils configs in setup.cfg due to encoding errors.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nanjin1** [comment]
There is the detail of my problem,I think if it is a env compatible?
python train.py --img 640 --epochs 3 --data coco128.yaml --weights yolov5s.pt pip install numpy
Traceback (most recent call last):
  File "D:\360downloads\yolov5-master\yolov5-master\train.py", line 48, in <module>
    import val as validate  # for end-of-epoch mAP
  File "D:\360downloads\yolov5-master\yolov5-master\val.py", line 39, in <module>
    from models.common import DetectMultiBackend
  File "D:\360downloads\yolov5-master\yolov5-master\models\common.py", line 18, in <module>
    import cv2
  File "D:\Anaconda3\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "D:\Anaconda3\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "D:\Anaconda3\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "D:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Anaconda3\lib\site-packages\cv2\typing\__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable

**Comment by glenn-jocher** [comment]
@nanjin1 this error usually occurs when there is a compatibility issue between different packages. It seems like there might be a conflict between the versions of OpenCV and NumPy that you have installed.

To resolve this issue, make sure you have the compatible versions of both OpenCV and NumPy installed. You can try upgrading or downgrading either package to find a compatible combination.

Another possible solution is to create a new virtual environment and install the required packages from scratch, ensuring compatibility between them.

If you're still experiencing issues, please provide more information about your environment, such as the versions of OpenCV and NumPy that you have installed, as well as any other relevant details. This will help us further investigate the problem.

Remember, if you encounter any problems or have any questions, feel free to ask. We are here to help!
