### ISSUE TITLE
Exception in plot_images and class numbers

### ISSUE THREAD

**Issue by AnnacKK** [ultralytics/yolov5#12320]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

I trained YOLOV5 on custon dataset with 14 classes:
```
10 epochs completed in 0.058 hours.
Optimizer stripped from runs\train\exp2\weights\last.pt, 14.5MB
Optimizer stripped from runs\train\exp2\weights\best.pt, 14.5MB

Validating runs\train\exp2\weights\best.pt...
Fusing layers... 
Model summary: 157 layers, 7047883 parameters, 0 gradients, 15.9 GFLOPs
```

but when the training is over this error appears:
```
Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/9 [00:00<?, ?it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  11%|#1        | 1/9 [00:00<00:05,  1.44it/s]Exception in thread Thread-13 (plot_images):
Traceback (most recent call last):
  File "C:\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\utils\plots.py", line 172, in plot_images
    cls = names[cls] if names else cls
          ~~~~~^^^^^
KeyError: 2

                 Class     Images  Instances          P          R      mAP50   mAP50-95:  22%|##2       | 2/9 [00:01<00:05,  1.27it/s]Exception in thread Thread-15 (plot_images):
Traceback (most recent call last):
  File "C:\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\utils\plots.py", line 172, in plot_images
    cls = names[cls] if names else cls
          ~~~~~^^^^^
KeyError: 2

                 Class     Images  Instances          P          R      mAP50   mAP50-95:  33%|###3      | 3/9 [00:02<00:04,  1.22it/s]Exception in thread Thread-17 (plot_images):
Traceback (most recent call last):
  File "C:\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\utils\plots.py", line 172, in plot_images
    cls = names[cls] if names else cls
          ~~~~~^^^^^
KeyError: 2

                 Class     Images  Instances          P          R      mAP50   mAP50-95:  44%|####4     | 4/9 [00:03<00:04,  1.21it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  56%|#####5    | 5/9 [00:03<00:03,  1.28it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  67%|######6   | 6/9 [00:04<00:02,  1.33it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  78%|#######7  | 7/9 [00:05<00:01,  1.37it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  89%|########8 | 8/9 [00:06<00:00,  1.39it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|##########| 9/9 [00:06<00:00,  1.50it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|##########| 9/9 [00:06<00:00,  1.37it/s]
                   all        281        281      0.106      0.684      0.206      0.123
               a_major        281         20      0.068       0.85      0.248     0.0973
               a_minor        281         20      0.108        0.7      0.172     0.0837
Traceback (most recent call last):
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\train.py", line 647, in <module>
    main(opt)
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\train.py", line 536, in main
Exception in thread Thread-19 (plot_mc_curve):
Traceback (most recent call last):
  File "C:\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    train(opt.hyp, opt, device, callbacks)
Exception in thread Thread-20 (plot_mc_curve):
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\train.py", line 419, in train
Traceback (most recent call last):
    self.run()
  File "C:\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    results, _, _ = validate.run(
  File "C:\anaconda3\Lib\threading.py", line 975, in run
Exception in thread Thread-21 (plot_mc_curve):
                    ^^^^^^^^^^^^^
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
  File "C:\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\anaconda3\Lib\threading.py", line 975, in run
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\utils\metrics.py", line 347, in plot_mc_curve
    self.run()
    return func(*args, **kwargs)
  File "C:\anaconda3\Lib\threading.py", line 975, in run
    ax.plot(px, y, linewidth=1, label=f'{names[i]}')  # plot(confidence, metric)
    self._target(*self._args, **self._kwargs)
                                         ~~~~~^^^
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\utils\metrics.py", line 347, in plot_mc_curve
    self._target(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\utils\metrics.py", line 347, in plot_mc_curve
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\val.py", line 290, in run
KeyError: 13
    ax.plot(px, y, linewidth=1, label=f'{names[i]}')  # plot(confidence, metric)
    ax.plot(px, y, linewidth=1, label=f'{names[i]}')  # plot(confidence, metric)
                                         ~~~~~^^^
                                         ~~~~~^^^
KeyError: 13
KeyError: 13
    LOGGER.info(pf % (names[c], seen, nt[c], p[i], r[i], ap50[i], ap[i]))
                      ~~~~~^^^
KeyError: 2
Exception in thread Thread-18 (plot_pr_curve):
Traceback (most recent call last):
  File "C:\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\***\Machine_Learning\Object_Detection\yolov5\utils\metrics.py", line 325, in plot_pr_curve
    ax.plot(px, y, linewidth=1, label=f'{names[i]} {ap[i, 0]:.3f}')  # plot(recall, precision)
                                         ~~~~~^^^
KeyError: 13
```
It seems like the model was trained only on 2 classes, instead of 14.
YAML file looks like this and located in data folder inside yolov5 folder:
![yaml](https://github.com/ultralytics/yolov5/assets/79131944/94337594-0020-4d3f-9ae7-054860326516)

### Environment

- Yolov5 torch 2.1.0+cu118
- OS: Windows 10
- Python: Python 3.11.6

### Minimal Reproducible Example

`!cd yolov5 && python train.py --img 640 --batch 16 --epochs 10 --data custom.yaml --weights yolov5s.pt --workers 2`

### Additional

Yolo located in C:\Users\***\Machine_Learning\Object_Detection\yolov5
Dataset folder located in:C:\Users\***\Machine_Learning\Object_Detection
Images located in C:\Users\***\Machine_Learning\Object_Detection\data\images
Labels located in C:\Users\***\Machine_Learning\Object_Detection\data\labels

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AnnacKK hi there,

Thank you for reaching out. It seems that you are encountering an error during training when using YOLOv5 on a custom dataset with 14 classes. The error message suggests a `KeyError: 2` within the `plot_images` function. This error occurs when the class ID specified in the YAML file does not match the class ID in the dataset.

To resolve this issue, please ensure that the class IDs specified in the `custom.yaml` file match the class IDs in your dataset. You can check the YAML file and make the necessary corrections. 

If the issue persists, please provide more details such as the contents of your `custom.yaml` file and a sample of your dataset. This will help us investigate further and provide you with a more accurate solution.

Please let me know if you have any more questions. The YOLO community and the Ultralytics team are always here to help.

Best regards,
Glenn Jocher

**Comment by AnnacKK** [comment]
Hi! Thanks, it was my mistake in id.

**Comment by glenn-jocher** [comment]
@AnnacKK hello, 

No worries, it happens to everyone! Just make sure to double-check the class IDs in your `custom.yaml` file and ensure they match the class IDs in your dataset. Once that's done, you should be good to go. If you encounter any further issues, feel free to ask for assistance.

Best regards *Your Name*
