### ISSUE TITLE
custom dataset path

### ISSUE THREAD

**Issue by geekdreamer04** [ultralytics/yolov5#12336]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have my data in a different path instead of 
 ├── yolov5
 └── datasets
     └── coco

I placed my dataset in /workspace/datasets/coco instead of home/ubuntu/datasets/. I cant move my dataset to home/ubuntu/ because my system doesn't have enough space. How do i change the location? I am unable to trace it properly and i get this error.

TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/

Dataset not found ⚠️, missing paths ['/workspace/datasets/coco/val2017.txt']
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels.zip to /workspace/datasets/coco2017labels.zip...
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/yolov5/train.py", line 647, in <module>
    main(opt)
  File "/home/ubuntu/yolov5/train.py", line 536, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/ubuntu/yolov5/train.py", line 117, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/ubuntu/yolov5/utils/general.py", line 541, in check_dataset
    r = exec(s, {'yaml': data})  # return None
  File "<string>", line 9, in <module>
  File "/home/ubuntu/yolov5/utils/general.py", line 648, in download
    download_one(u, dir)
  File "/home/ubuntu/yolov5/utils/general.py", line 619, in download_one
    torch.hub.download_url_to_file(url, f, progress=threads == 1)  # torch download
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/ubuntu/anaconda3/envs/pytorch_p310/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

### Additional

Please help me

**Comment by glenn-jocher** [comment]
@geekdreamer04 to change the location of your dataset, you can specify the path to your dataset using the `--data` argument when running the training script. 

For example, if your dataset is located at `/workspace/datasets/coco`, you can modify your training command to include the `--data` argument as follows:

```bash
python train.py --data /workspace/datasets/coco/your_dataset.yaml
```

Make sure to replace `your_dataset.yaml` with the actual name of your dataset configuration file.

Regarding the error message you received, it seems to be related to a temporary failure in name resolution, which could be due to network connectivity issues. Please ensure that you have a stable internet connection and try running the training script again.

If the issue persists, feel free to provide more details or error logs, and we'll be happy to assist you further.
