### ISSUE TITLE
Regarding running yolov5l model on multiple Gpu on teslav100 

### ISSUE THREAD

**Issue by KAKAROT12419** [ultralytics/yolov5#12357]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to run yolov5l model on multiple Gpu's
i am using command
python  -m torch.distributed.run --nproc_per_node=2     /home/akshatt/Akash/yolov5/yolov5/train.py --data /home/akshatt/Akash/yolov5/dataset/dataset.yaml  --weights  /home/akshatt/Akash/yolov5/yolov5/[yolov5x.pt](http://yolov5x.pt/)  --img 1024 --epochs 150 --batch 64 --device 4,5"
It is the format given on train.py file,for running on multiple gpu but it is throwing error
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "RuntimeError: Address already in use",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py\", line 719, in main\n    run(args)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py\", line 710, in run\n    elastic_launch(\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py\", line 252, in launch_agent\n    result = agent.run()\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 709, in run\n    result = self._invoke_run(role)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 837, in _invoke_run\n    self._initialize_workers(self._worker_group)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 678, in _initialize_workers\n    self._rendezvous(worker_group)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 538, in _rendezvous\n    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()\n  File \"/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py\", line 55, in next_rendezvous\n    self._store = TCPStore(  # type: ignore[call-arg]\nRuntimeError: Address already in use\n",
      "timestamp": "1699512397"
    }
  }
}
Traceback (most recent call last):
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
    result = agent.run()
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 837, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: Address already in use

//please anyone help

**Comment by glenn-jocher** [comment]
@KAKAROT12419 the error message "RuntimeError: Address already in use" indicates that there's already an instance of the training process running on the specified ports. To resolve this, try terminating any existing processes using those ports. Also, it's recommended to check if torch.distributed.run is set up properly and ensures each process is using unique ports for communication. Feel free to reach out again if the issue persists.

**Comment by KAKAROT12419** [comment]
thankyou   @glenn-jocher  sir i killed the process and ran again but again it throws error now different one.Kindly help me with it.

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
train: weights=/home/akshatt/Akash/yolov5/yolov5/[yolov5x.pt](http://yolov5x.pt/), cfg=, data=/home/akshatt/Akash/yolov5/dataset/dataset.yaml, hyp=yolov5/data/hyps/hyp.scratch-low.yaml, epochs=150, batch_size=64, imgsz=1024, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=6,7, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=yolov5/runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: ⚠️ YOLOv5 is out of date by 8 commits. Use 'git pull' or 'git clone https://github.com/ultralytics/yolov5' to update.
YOLOv5 🚀 v7.0-232-g1c60c53 Python-3.9.18 torch-1.10.0+cu111 CUDA:6 (Tesla V100-SXM2-32GB, 32510MiB)
                                                             CUDA:7 (Tesla V100-SXM2-32GB, 32510MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5 🚀 runs in Comet
TensorBoard: Start with 'tensorboard --logdir yolov5/runs/train', view at http://localhost:6006/
Traceback (most recent call last):
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 651, in <module>
    main(opt)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 540, in main
Traceback (most recent call last):
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 651, in <module>
    train(opt.hyp, opt, device, callbacks)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 120, in train
    with torch_distributed_zero_first(LOCAL_RANK):
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/contextlib.py", line 119, in __enter__
    main(opt)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 540, in main
    return next(self.gen)
  File "/home/akshatt/Akash/yolov5/yolov5/utils/torch_utils.py", line 92, in torch_distributed_zero_first
    train(opt.hyp, opt, device, callbacks)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 121, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/contextlib.py", line 126, in __exit__
    dist.barrier(device_ids=[local_rank])
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    next(self.gen)
  File "/home/akshatt/Akash/yolov5/yolov5/utils/torch_utils.py", line 95, in torch_distributed_zero_first
    dist.barrier(device_ids=[0])
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError    : work = default_pg.barrier(opts=opts)NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.

RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26606) of binary: /home/akshatt/anaconda3/envs/yolov5update/bin/python
Traceback (most recent call last):
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/akshatt/Akash/yolov5/yolov5/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-10_05:05:43
  host      : NVIDIA2020
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 26607)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-10_05:05:43
  host      : NVIDIA2020
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26606)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by glenn-jocher** [comment]
@KAKAROT12419 The "Unhandled CUDA error" often points to an issue with the environment and resources. The first step is to ensure that CUDA and CuDNN are correctly installed and compatible with your PyTorch version. Also, check if the NCCL library is installed and up to date.

Additionally, the YOLOv5 GitHub action message "YOLOv5 is out of date by 8 commits" suggests that you are using an older version of YOLOv5. Consider updating your YOLOv5 repository to the latest version using `git pull` or by cloning the repository again.

Lastly, inspect the specific CUDA error message to identify the root cause of the problem, and consider checking your hardware resources as well.

Let me know if there's anything else I can help you with!

**Comment by KAKAROT12419** [comment]
Sir ,I am trying to find the error but the  cuda version installed is 9.1,torch is 1.1.0 and torchvision is 0.11.0  and nccl version shows 2.10.3  so i need to downgrade nccl version?

**Comment by KAKAROT12419** [comment]
Sir, when ran for single gpu then the code was working fine and gave some results so i think  cudA  and cudnn version are ,by the way i have cuda version 11.0 toolkit version 9.1 and nccl version 2.10.3 ,libnccl 2.12.10,torch version 1.10.0,torch vision 0.11.sir can you tell me show i have to upgrade nccl version?

**Comment by glenn-jocher** [comment]
@KAKAROT12419 It seems like the NCCL version (2.10.3) you are using might be causing compatibility issues with your current setup. For an optimal experience, it's recommended to use the NCCL version that matches the CUDA and PyTorch versions. 

For your CUDA version 11.0 and PyTorch version 1.10.0, I recommend using NCCL version 2.9.x or 2.10.x to ensure full compatibility.

To upgrade the NCCL version, you can visit the NVIDIA website or use package managers like Conda or pip to install the specific NCCL version that matches your CUDA and PyTorch versions.

Once you have upgraded NCCL, ensure that you update the environment variables and paths accordingly to reflect the changes.

Let me know if you need further assistance with the upgrade process!

**Comment by KAKAROT12419** [comment]
Sir actually i think i need to downgrade the nccl version because cuda version is 9.1as my local cuda toolkit  version is 9.1 and the gpu drivers are not updated by admin  so we cannot upgrade our cuda toolkit version.Nccl is installed seperately or it comes with pytorch version? I have search a lot and tried a lot of commands but none of them are working  do i need to change the versions of pytorch and torch vison, and  If i do so then i need to change versions of all the dependencies mentioned in yolov5 requirements.txt

**Comment by glenn-jocher** [comment]
@KAKAROT12419 understood, given your constraints, it's clear that downgrading your NCCL version to match your CUDA 9.1 toolkit version would be the appropriate step.

NCCL is typically not installed with PyTorch and needs to be installed separately, thus you can manage it independent of your PyTorch installation.

When adjusting versions to align with CUDA 9.1, it's advisable to ensure that all dependencies, including PyTorch, TorchVision, and other related packages, are also compatible with the same CUDA version to maintain a consistent and stable environment.

Updating versions can be a delicate process, but adjusting to the right versions should help ensure compatibility with your current environment.

Feel free to ask if you need further assistance during this process!
