### ISSUE TITLE
训练模型的时候报错如下不知道怎么解决

### ISSUE THREAD

**Issue by ZhouYFei7788** [ultralytics/yolov5#12374]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

C:\Users\yeife\anaconda3\envs\yolov5\python.exe C:\Users\yeife\Desktop\yolov5\yolov5-7.0\train.py 
train: weights=yolov5s.pt, cfg=, data=data\bvn.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=100, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2022-11-22 Python-3.8.18 torch-1.8.2+cu111 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
Traceback (most recent call last):
  File "C:\Users\yeife\Desktop\yolov5\yolov5-7.0\train.py", line 633, in <module>
    main(opt)
  File "C:\Users\yeife\Desktop\yolov5\yolov5-7.0\train.py", line 527, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\yeife\Desktop\yolov5\yolov5-7.0\train.py", line 95, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "C:\Users\yeife\Desktop\yolov5\yolov5-7.0\utils\loggers\__init__.py", line 121, in __init__
    self.clearml = ClearmlLogger(self.opt, self.hyp)
  File "C:\Users\yeife\Desktop\yolov5\yolov5-7.0\utils\loggers\clearml\clearml_utils.py", line 87, in __init__
    self.task = Task.init(
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\task.py", line 565, in init
    task = cls._create_dev_task(
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\task.py", line 3595, in _create_dev_task
    task = cls(
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\task.py", line 206, in __init__
    super(Task, self).__init__(**kwargs)
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\backend_interface\task\task.py", line 161, in __init__
    super(Task, self).__init__(id=task_id, session=session, log=log)
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\backend_interface\base.py", line 149, in __init__
    super(IdObjectBase, self).__init__(session, log, **kwargs)
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\backend_interface\base.py", line 41, in __init__
    self._session = session or self._get_default_session()
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\backend_interface\base.py", line 119, in _get_default_session
    InterfaceBase._default_session = Session(
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\backend_api\session\session.py", line 158, in __init__
    self._connect()
  File "C:\Users\yeife\anaconda3\envs\yolov5\lib\site-packages\clearml\backend_api\session\session.py", line 218, in _connect
    raise MissingConfigError()
clearml.backend_api.session.defs.MissingConfigError: It seems ClearML is not configured on this machine!
To get started with ClearML, setup your own 'clearml-server' or create a free account at https://app.clear.ml
Setup instructions can be found here: https://clear.ml/docs
他似乎是在提醒我ClearML的配置存在问题但我找不到问题所在

**Comment by glenn-jocher** [comment]
@ZhouYFei7788 hi there,

It looks like the error is related to the ClearML configuration in your environment. ClearML is not properly configured, and as a result, the training script is encountering this issue. You might need to set up ClearML or check the configuration to resolve this problem.

If you need further assistance with ClearML setup, you can refer to the setup instructions here: https://clear.ml/docs.

Feel free to reach out if you have any more questions or need additional help. Good luck with your YOLOv5 training!

**Comment by weird-angel** [comment]
请问，如何解决？
me, too. 
I should how to deal it?

**Comment by glenn-jocher** [comment]
Hi there! 😊

If you're running into an issue that's similar to one already discussed, could you provide a bit more detail on what problem you're facing? Knowing the exact error message or behavior you're encountering could help in offering a more specific solution. Feel free to give a brief description or share a snippet of the error you're seeing!

Looking forward to helping you out!
