### ISSUE TITLE
Hello author, I would like to use multiple machines and multiple cards for training in a Windows environment. What do I need to do?

### ISSUE THREAD

**Issue by yxl23** [ultralytics/yolov5#12546]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello author, I would like to use multiple machines and multiple cards for training in a Windows environment. What do I need to do

**Comment by glenn-jocher** [comment]
@yxl23 hi there! To train on multiple machines and cards in a Windows environment, you can use the `torch.distributed.launch` module. There's detailed guidance in the Ultralytics Docs here: https://docs.ultralytics.com/yolov5/train-multi-node. Happy training!

**Comment by yxl23** [comment]
Hello, author. It seems that the website you provided cannot be accessed and shows 404
![Uploading 9e4f55e3d9d13e17188b9a78b563a12.png…]()

**Comment by yxl23** [comment]
![9e4f55e3d9d13e17188b9a78b563a12](https://github.com/ultralytics/yolov5/assets/115678682/3b35313f-249b-4d11-8169-61107417d4a5)
![9e4f55e3d9d13e17188b9a78b563a12](https://github.com/ultralytics/yolov5/assets/115678682/7b44a59c-52eb-4533-b37c-40e3b7624ea5)

**Comment by yxl23** [comment]
And how to solve this error
![Uploading b573682364ca6cf40f96f9d79e93994.png…]()

**Comment by yxl23** [comment]
![Uploading b573682364ca6cf40f96f9d79e93994.png…]()

**Comment by yxl23** [comment]
![Uploading b573682364ca6cf40f96f9d79e93994.png…]()

**Comment by yxl23** [comment]
Traceback (most recent call last):
  File "train.py", line 635, in <module>
    main(opt)
  File "train.py", line 525, in main
    dist.init_process_group(backend="gloo" if dist.is_nccl_available() else "gloo")
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\distributed_c10d.py", line 583, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\distributed_c10d.py", line 684, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: Socket Timeout
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13836) of binary: C:\Users\ADMIN\.conda\envs\cu113py38torch110\python.exe
Traceback (most recent call last):
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\run.py", line 723, in <module>
    main()
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\run.py", line 719, in main
    run(args)
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\run.py", line 710, in run
    elastic_launch(
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\ADMIN\.conda\envs\cu113py38torch110\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by glenn-jocher** [comment]
@yxl23 it looks like you're encountering a socket timeout error when initializing the process group for distributed training. This issue can sometimes occur due to network connectivity or firewall settings. 

I recommend checking your network configuration and firewall settings to ensure that there are no restrictions causing the timeout. Additionally, you may want to verify that the machines and cards you are using for training are able to communicate with each other over the network.

If the issue persists, consider reaching out to the YOLO community or the Ultralytics team for further assistance. Good luck!
