### ISSUE TITLE
quick start, new rpi5:  Failed to open tcp://127.0.0.1:8888

### ISSUE THREAD

**Issue by stuartcrobinson** [ultralytics/yolov5#12583]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

re https://docs.ultralytics.com/guides/raspberry-pi/#quick-start-with-yolov5

brand new raspberry pi 5. followed the steps in that guide and got this:

```
(.venv) stuart@mypi:~ $ cd ~/yolov5
python3 detect.py --source=tcp://127.0.0.1:8888
detect: weights=yolov5s.pt, source=tcp://127.0.0.1:8888, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-267-gc42aba5 Python-3.11.2 torch-2.1.2 CPU

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt to yolov5s.pt...
100%|██████████████████████████████████████| 14.1M/14.1M [00:00<00:00, 16.9MB/s]

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Traceback (most recent call last):
  File "/home/stuart/yolov5/detect.py", line 295, in <module>
    main(opt)
  File "/home/stuart/yolov5/detect.py", line 290, in main
    run(**vars(opt))
  File "/home/stuart/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stuart/yolov5/detect.py", line 109, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stuart/yolov5/utils/dataloaders.py", line 397, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: tcp://127.0.0.1:8888... Failed to open tcp://127.0.0.1:8888
(.venv) stuart@mypi:~/yolov5 $ 

```

libcamera-vid terminal window:
```
(.venv) stuart@mypi:~ $ libcamera-vid -n -t 0 --width 1280 --height 960 --framerate 1 --inline --listen -o tcp://127.0.0.1:8888
[0:26:05.314994219] [15946]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
[0:26:05.331492702] [15949]  INFO RPI pisp.cpp:653 libpisp version v1.0.2 fa44a258644a 22-11-2023 (21:59:22)
[0:26:05.352347996] [15949]  INFO RPI pisp.cpp:1112 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/imx708@1a to CFE device /dev/media1 and ISP device /dev/media0 using PiSP variant BCM2712_C0
[0:26:31.866467254] [15946]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format Y16 
[0:26:31.866513495] [15946]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format RGB6
[0:26:31.866527273] [15946]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format BGR6
[0:26:31.866542310] [15946]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format PC1M
Mode selection for 1280:960:12:P(1)
    SRGGB10_CSI2P,1536x864/120.135 - Score: 1422.67
    SRGGB10_CSI2P,2304x1296/56.0255 - Score: 1506.67
    SRGGB10_CSI2P,4608x2592/14.3536 - Score: 2406.67
Stream configuration adjusted
[0:26:31.866852053] [15946]  INFO Camera camera.cpp:1183 configuring streams: (0) 1280x960-YUV420 (1) 1536x864-BGGR16_PISP_COMP1
[0:26:31.866927646] [15949]  INFO RPI pisp.cpp:1396 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/imx708@1a - Selected sensor format: 1536x864-SBGGR10_1X10 - Selected CFE format: 1536x864-PC1B
[NULL @ 0x555661638720] Unable to find a suitable output format for 'tcp://127.0.0.1:8888'
ERROR: *** libav: cannot allocate output context ***
(.venv) stuart@mypi:~ $ 
```

i installed the OS today using Raspberry Pi Imager v1.8.4 and selected bookworm 64-bit released 2023-12-5

libcamera-hello seems to work. displays video feed for a few seconds.

system info:

```
(.venv) stuart@mypi:~/yolov5 $ uname -a
Linux mypi 6.1.0-rpi7-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux
(.venv) stuart@mypi:~/yolov5 $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Environment

- YOLOv5 v7.0-267-gc42aba5 
- OS Debian GNU/Linux 12 (bookworm)
- Python 3.11.2
- Raspberry Pi 5

### Minimal Reproducible Example

follow these steps to run yolov5 on a fresh rpi5 https://docs.ultralytics.com/guides/raspberry-pi/#quick-start-with-yolov5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by stuartcrobinson** [comment]
fwiw i get the same thing for yolov8, following the guide:

```
stuart@mypi:~ $ source .venv/bin/activate
(.venv) stuart@mypi:~ $ python
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics import YOLO

>>> 
>>> model = YOLO('yolov8n.pt')
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100%|██████████████████████████████████████| 6.23M/6.23M [00:00<00:00, 12.4MB/s]
>>> 
>>> 
>>> results = model('tcp://127.0.0.1:8888', stream=True)
>>> 
>>> 
>>> while True:
...     for result in results:
...         boxes = result.boxes
...         probs = result.probs
... 

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/stuart/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/stuart/.venv/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 241, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "/home/stuart/.venv/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 216, in setup_source
    self.dataset = load_inference_source(source=source,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stuart/.venv/lib/python3.11/site-packages/ultralytics/data/build.py", line 166, in load_inference_source
    dataset = LoadStreams(source, imgsz=imgsz, vid_stride=vid_stride, buffer=buffer)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stuart/.venv/lib/python3.11/site-packages/ultralytics/data/loaders.py", line 92, in __init__
    raise ConnectionError(f'{st}Failed to open {s}')
ConnectionError: 1/1: tcp://127.0.0.1:8888... Failed to open tcp://127.0.0.1:8888
>>> 
```

```
stuart@mypi:~ $ source .venv/bin/activate
(.venv) stuart@mypi:~ $ libcamera-vid -n -t 0 --width 1280 --height 960 --framerate 1 --inline --listen -o tcp://127.0.0.1:8888
[0:00:53.163341819] [1947]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
[0:00:53.177607551] [1950]  INFO RPI pisp.cpp:653 libpisp version v1.0.2 fa44a258644a 22-11-2023 (21:59:22)
[0:00:53.196786487] [1950]  INFO RPI pisp.cpp:1112 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/imx708@1a to CFE device /dev/media0 and ISP device /dev/media2 using PiSP variant BCM2712_C0
[0:02:04.510510919] [1947]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format Y16 
[0:02:04.510557562] [1947]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format RGB6
[0:02:04.510569875] [1947]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format BGR6
[0:02:04.510584114] [1947]  WARN V4L2 v4l2_pixelformat.cpp:338 Unsupported V4L2 pixel format PC1M
Mode selection for 1280:960:12:P(1)
    SRGGB10_CSI2P,1536x864/120.135 - Score: 1422.67
    SRGGB10_CSI2P,2304x1296/56.0255 - Score: 1506.67
    SRGGB10_CSI2P,4608x2592/14.3536 - Score: 2406.67
Stream configuration adjusted
[0:02:04.510956221] [1947]  INFO Camera camera.cpp:1183 configuring streams: (0) 1280x960-YUV420 (1) 1536x864-BGGR16_PISP_COMP1
[0:02:04.511068005] [1950]  INFO RPI pisp.cpp:1396 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/imx708@1a - Selected sensor format: 1536x864-SBGGR10_1X10 - Selected CFE format: 1536x864-PC1B
[NULL @ 0x5556266e4720] Unable to find a suitable output format for 'tcp://127.0.0.1:8888'
ERROR: *** libav: cannot allocate output context ***
(.venv) stuart@mypi:~ $ 
```

also the guide worked fine for me on a rpi4 using the same camera

**Comment by default-student** [comment]
isnt that because tcp just isnt supported?

**Comment by glenn-jocher** [comment]
@default-student hello! It looks like you're encountering an issue with the TCP stream setup on your Raspberry Pi 5. The error message from `libcamera-vid` suggests that the output format for the TCP stream is not being recognized or supported.

The message `Unable to find a suitable output format for 'tcp://127.0.0.1:8888'` indicates that the streaming command might not be correctly setting up the video stream for YOLOv5 or YOLOv8 to consume.

Please ensure that you have followed all the steps correctly and that the `libcamera-vid` command is executed with the right parameters. Also, make sure that no other process is using the TCP port 8888 and that your firewall settings allow TCP connections on this port.

If the problem persists, you might want to try using a different method to provide the video stream to the model, such as using a file or a camera directly connected to the Raspberry Pi.

For further assistance, please refer to the Ultralytics Docs and consider opening an issue on the GitHub repository with the details of the error you're facing. The community and maintainers can help troubleshoot the problem more effectively there. Thank you for your contribution and for using YOLOv5! 🚀
