### ISSUE TITLE
A question about bbox normalization

### ISSUE THREAD

**Issue by doLei-2001** [ultralytics/yolov5#13051]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

    In the data enhancement part of yolov5, I have my own idea, but I found this problem when implementing it.

    I directly resized the mosaic spliced ​​img4 to 640*640, and performed the corresponding scaling transformation on labels4. The code is as follows:
```python
    def resize640_and_adjust_labels(self, img4, labels4):
        """
        将图像调整为640x640, 并相应地调整标签中的边界框bbox。

        参数：
        img4: 输入图像(numpy数组)。
        labels4: 边界框标签（格式：[class, x_min, y_min, x_max, y_max]）。

        返回：
        resized_img: 调整大小后的图像。
        updated_labels: 相对于调整大小后图像的更新边界框标签。
        """
        # 目标大小
        target_size = 640
        original_height, original_width = img4.shape[:2]

        # 计算缩放比例
        scale_x = target_size / original_width
        scale_y = target_size / original_height

        # 调整图像大小
        resized_img = cv2.resize(img4, (target_size, target_size), interpolation=cv2.INTER_LINEAR)

        # 更新边界框标签
        updated_labels = []
        for label in labels4:
            class_id, x1, y1, x2, y2 = label

            # 缩放边界框坐标
            new_x1 = x1 * scale_x
            new_y1 = y1 * scale_y
            new_x2 = x2 * scale_x
            new_y2 = y2 * scale_y

            # 归一化到 [0, 1]
            new_x1 /= target_size
            new_y1 /= target_size
            new_x2 /= target_size
            new_y2 /= target_size

            # 限制坐标范围在 (0, 1] 内
            new_x1 = max(1e-5, min(new_x1, 1))
            new_y1 = max(1e-5, min(new_y1, 1))
            new_x2 = max(1e-5, min(new_x2, 1))
            new_y2 = max(1e-5, min(new_y2, 1))

            updated_labels.append([class_id, new_x1, new_y1, new_x2, new_y2])

        return resized_img, np.array(updated_labels)
    
```

    However, yolov5 reported an error when running as follows. I followed the error message and normalized labels4 to (0,1], but it still reported an error.

```shell
raceback (most recent call last):
  File "train.py", line 848, in <module>
    main(opt)
  File "train.py", line 623, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 356, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/public/dol/code/python/yolov5/utils/dataloaders.py", line 239, in __iter__
    yield next(self.iterator)
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/public/dol/code/python/yolov5/utils/dataloaders.py", line 812, in __getitem__
    img, labels = self.albumentations(img, labels)
  File "/home/public/dol/code/python/yolov5/utils/augmentations.py", line 52, in __call__
    new = self.transform(image=im, bboxes=labels[:, 1:], class_labels=labels[:, 0])  # transformed
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/albumentations/core/composition.py", line 253, in __call__
    p.preprocess(data)
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/albumentations/core/utils.py", line 90, in preprocess
    data[data_name] = self.check_and_convert(data[data_name], rows, cols, direction="to")
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/albumentations/core/utils.py", line 104, in check_and_convert
    return self.convert_to_albumentations(data, rows, cols)
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/albumentations/core/bbox_utils.py", line 151, in convert_to_albumentations
    return convert_bboxes_to_albumentations(data, self.params.format, rows, cols, check_validity=True)
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/albumentations/core/bbox_utils.py", line 433, in convert_bboxes_to_albumentations
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/albumentations/core/bbox_utils.py", line 433, in <listcomp>
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]
  File "/home/public/dol/miniconda3/envs/yolov5/lib/python3.8/site-packages/albumentations/core/bbox_utils.py", line 352, in convert_bbox_to_albumentations
    raise ValueError(msg)
ValueError: In YOLO format all coordinates must be float and in range (0, 1]
```

I would like to ask, how can I modify this code so that it can run without an error?

**Comment by glenn-jocher** [comment]
Hello! Thanks for providing detailed information about the issue you're encountering. It seems like the error arises because the bounding box coordinates are not correctly normalized to the range (0, 1] after resizing and scaling transformations.

From your code snippet, it appears that you are normalizing the bounding box coordinates by dividing by `target_size` after scaling them. However, the error suggests that some values might still be out of the expected range. This could potentially be due to floating-point precision issues or initial values slightly outside the expected range before scaling.

To address this, you might want to ensure that the bounding box coordinates are strictly within the (0, 1] range before they are passed to the augmentation pipeline. Here's a modified version of your label updating loop that includes an additional check and correction for bounding box coordinates:

```python
updated_labels = []
for label in labels4:
    class_id, x1, y1, x2, y2 = label

    # Scale bounding box coordinates
    new_x1 = x1 * scale_x
    new_y1 = y1 * scale_y
    new_x2 = x2 * scale_x
    new_y2 = y2 * scale_y

    # Normalize to [0, 1]
    new_x1 /= target_size
    new_y1 /= target_size
    new_x2 /= target_size
    new_y2 /= target_size

    # Ensure coordinates are within (0, 1]
    new_x1 = max(1e-5, min(new_x1, 1))
    new_y1 = max(1e-5, min(new_y1, 1))
    new_x2 = max(1e-5, min(new_x2, 1))
    new_y2 = max(1e-5, min(new_y2, 1))

    updated_labels.append([class_id, new_x1, new_y1, new_x2, new_y2])
```

Please make sure that the initial bounding box coordinates (x1, y1, x2, y2) are within the valid range before transformation. If the issue persists, you might want to add debug prints to check the values of coordinates at each step.

Let me know if this helps or if you have any more questions!
