### ISSUE TITLE
yolov5 Tensortt errors ?

### ISSUE THREAD

**Issue by Janeqs-cx** [ultralytics/yolov5#13057]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was trying to run tensort with my trained best.engine version. I checked best.engine file and it's working fine with tensort but when tried to run with script by yolov5 it's give these errors : 

PS C:\Users\Janek\Desktop\Val-sz> & c:/Users/Janek/Desktop/Val-sz/cheats-env/Scripts/python.exe c:/Users/Janek/Desktop/Val-sz/scripts/dxcam_main.py
YOLOv5  2022-11-22 Python-3.10.5 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6144MiB)

Loading C:\Users\Janek\Desktop\Val-sz\scripts\best.engine for TensorRT inference...
[05/31/2024-21:01:11] [TRT] [I] [MemUsageChange] Init CUDA: CPU +297, GPU +0, now: CPU 11292, GPU 1015 (MiB)
[05/31/2024-21:01:11] [TRT] [I] Loaded engine size: 10 MiB
[05/31/2024-21:01:11] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[05/31/2024-21:01:11] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\tensorrt\__init__.py:331: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  bool: np.bool,
Traceback (most recent call last):
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\hubconf.py", line 49, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\models\common.py", line 406, in __init__
    dtype = trt.nptype(model.get_binding_dtype(i))
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\tensorrt\__init__.py", line 331, in nptype
    bool: np.bool,
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically 
wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\hubconf.py", line 60, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Janek\Desktop\Val-sz\scripts\dxcam_main.py", line 104, in <module>
    model = torch.hub.load(r'C:\Users\Janek\Desktop\Val-sz\yolov5' , 'custom', path= r'C:\Users\Janek\Desktop\Val-sz\scripts\best.engine',source='local').cpu()
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\torch\hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\torch\hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: unpickling stack underflow. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.

Can someone explain and help me fix it?

**Comment by Janeqs-cx** [comment]
already did this 💀

**Comment by glenn-jocher** [comment]
It seems like you've already tried some troubleshooting steps. Could you please specify which steps you've taken so far? This will help us provide more targeted assistance. Thank you!

**Comment by Janeqs-cx** [comment]
I reinstalled whole Tensort Pytorch And cuda cudnn i tried also making a new model but it also failed and now i really dont know why it's not working i also tried yolov5 older versions like v6.2

**Comment by glenn-jocher** [comment]
Thank you for detailing the steps you've taken. It sounds like you've already tried a comprehensive set of troubleshooting actions. Let's try a couple more things:

1. **Check NumPy Version**: The error related to `np.bool` suggests there might be a compatibility issue with the NumPy version. Ensure you are using a version compatible with your TensorRT and PyTorch setup.

2. **Revisit TensorRT Engine**: Since you mentioned creating a new model didn't help, double-check the TensorRT engine creation process. Ensure that the `.engine` file is correctly generated and compatible with the version of TensorRT you are using.

3. **Environment Verification**: Sometimes, environment path issues could cause unexpected behavior. Verify that your Python environment is correctly set up and that there are no conflicting packages.

If these steps don't resolve the issue, could you provide the exact command or script you are using to run the inference? This might help pinpoint where things are going wrong.

**Comment by Janeqs-cx** [comment]
Reinstalled numpy + Checked TensortRT Engine to check i corrupted and also reinstalled whole python venv

**Comment by Janeqs-cx** [comment]
Hi @glenn-jocher  i just changed some version of dependecies and now throwwing these errors : 

YOLOv5  v7.0-318-gc0380fd8 Python-3.9.13 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6144MiB)

Loading C:\Users\Janek\Desktop\Val-sz\best.engine for TensorRT inference...
[06/04/2024-14:46:21] [TRT] [I] [MemUsageChange] Init CUDA: CPU +286, GPU +0, now: CPU 11276, GPU 1008 (MiB)
[06/04/2024-14:46:21] [TRT] [I] Loaded engine size: 34 MiB
[06/04/2024-14:46:21] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[06/04/2024-14:46:21] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
Adding AutoShape... 
(544, 307, 816, 460)
Traceback (most recent call last):
  File "c:\Users\Janek\Desktop\Val-sz\scripts\main.py", line 150, in <module>
    df= model(screenshot, size=640).pandas().xyxy[0]
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\models\common.py", line 872, in forward
    y = self.model(x, augment=augment)  # forward
  File "C:\Users\Janek\Desktop\Val-sz\cheats-env\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Janek\Desktop\Val-sz\yolov5\models\common.py", line 688, in forward
    assert im.shape == s, f"input size {im.shape} {'>' if self.dynamic else 'not equal to'} max model size {s}"
AssertionError: input size torch.Size([1, 3, 384, 640]) not equal to max model size (1, 3, 736, 736)

**Comment by glenn-jocher** [comment]
Hi @Janeqs-cx,

It looks like the input image size does not match the expected size by the model. The model is expecting an input size of (1, 3, 736, 736), but it received an input size of (1, 3, 384, 640).

Please ensure that the input images are resized or padded to match the model's expected input dimensions of 736x736 before passing them to the model. This adjustment should resolve the assertion error you're encountering.

Let us know if you need further assistance!

**Comment by Avaneesh-S** [comment]
Hey @Janeqs-cx, regarding your original error. I have also faced the similar issue. installing numpy==1.23 before exporting to tensorrt format resolved the issue for me (I have tested it on colab)
