### ISSUE TITLE
error in cmd

### ISSUE THREAD

**Issue by mojtabat96** [ultralytics/yolov5#13172]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

hello when I run this code i get these problems!
python detect.py --weights yolov5m.pt --source 0
---------
C:\Users\mojta\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py:749: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() if nvml_count < 0 else nvml_count
detect: weights=['yolov5m.pt'], source=0, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
fatal: cannot change to 'C:\Users\mojta\OneDrive\Desktop\New': No such file or directory
YOLOv5  2024-7-4 Python-3.11.1 torch-2.3.1+cu121 CPU

Traceback (most recent call last):
  File "C:\Users\mojta\OneDrive\Desktop\New folder\yolov5\detect.py", line 313, in <module>
    main(opt)
  File "C:\Users\mojta\OneDrive\Desktop\New folder\yolov5\detect.py", line 308, in main
    run(**vars(opt))
  File "C:\Users\mojta\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mojta\OneDrive\Desktop\New folder\yolov5\detect.py", line 116, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mojta\OneDrive\Desktop\New folder\yolov5\models\common.py", line 467, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mojta\OneDrive\Desktop\New folder\yolov5\models\experimental.py", line 98, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location="cpu")  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mojta\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mojta\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mojtabat96 hello,

Thank you for reaching out and providing details about the issue you're encountering. It looks like there are a couple of potential problems here. Let's address them step-by-step:

1. **CUDA Driver Warning**:
   The warning indicates that your NVIDIA driver is outdated. Please update your GPU driver to the latest version from [NVIDIA's website](http://www.nvidia.com/Download/index.aspx). This should resolve the CUDA initialization warning.

2. **File Path Issue**:
   The error `fatal: cannot change to 'C:\Users\mojta\OneDrive\Desktop\New': No such file or directory` suggests that the directory path specified does not exist. Ensure that the path to your YOLOv5 directory is correct and accessible.

3. **RuntimeError: PytorchStreamReader failed reading zip archive**:
   This error typically occurs when there's an issue with the model weights file (`yolov5m.pt`). The file might be corrupted or not downloaded correctly. Try re-downloading the weights file:
   ```bash
   python -m torch.hub download ultralytics/yolov5 yolov5m.pt
   ```

To help us further investigate, please provide a minimal reproducible example of your code. This will enable us to replicate the issue on our end. You can find guidance on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, ensure you are using the latest versions of `torch` and the YOLOv5 repository. You can update them using the following commands:
```bash
pip install --upgrade torch
git pull https://github.com/ultralytics/yolov5
```

If the issue persists after trying these steps, please share the updated error messages and any additional details.

Thank you for your cooperation, and we look forward to assisting you further!
