### ISSUE TITLE
Error running in windows 11 with python 3.12 virtual env

### ISSUE THREAD

**Issue by balakreshnan** [ultralytics/yolov5#13335]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

File "c:\Code\gradioapps\mfgappsv1\.venv\Lib\site-packages\torch\hub.py", line 599, in _load_local
    model = entry(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 215, in yolov5s
    return _create("yolov5s", pretrained, channels, classes, autoshape, _verbose, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 103, in _create
    raise Exception(s) from e
Exception: 'model'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.

### Environment

python 3.12
latest on all libraries

### Minimal Reproducible Example

import torch

# Model
model = torch.hub.load("ultralytics/yolov5", "yolov5s", channels=3, force_reload=True)

# Image
im = "https://ultralytics.com/images/zidane.jpg"

# Inference
results = model(im)

results.pandas().xyxy[0]
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

### Additional

PS C:\Code\gradioapps\mfgappsv1> python .\yolotest.py
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\babal/.cache\torch\hub\master.zip
YOLOv5  2024-9-27 Python-3.12.6 torch-2.4.1+cpu CPU

Traceback (most recent call last):
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 70, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 489, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 99, in attempt_load
    ckpt = (ckpt.get("ema") or ckpt["model"]).to(device).float()  # FP32 model
                               ~~~~^^^^^^^^^
KeyError: 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 85, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 99, in attempt_load
    ckpt = (ckpt.get("ema") or ckpt["model"]).to(device).float()  # FP32 model
                               ~~~~^^^^^^^^^
KeyError: 'model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Code\gradioapps\mfgappsv1\yolotest.py", line 4, in <module>
    model = torch.hub.load("ultralytics/yolov5", "yolov5s", channels=3, force_reload=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Code\gradioapps\mfgappsv1\.venv\Lib\site-packages\torch\hub.py", line 570, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Code\gradioapps\mfgappsv1\.venv\Lib\site-packages\torch\hub.py", line 599, in _load_local
    model = entry(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 215, in yolov5s
    return _create("yolov5s", pretrained, channels, classes, autoshape, _verbose, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\babal/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 103, in _create
    raise Exception(s) from e
Exception: 'model'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @balakreshnan, thank you for reporting this issue with YOLOv5 on Windows 11 using Python 3.12 🐍!

This is an automated response to help guide you through potential solutions. An Ultralytics engineer will also review your issue soon.

It seems like you're encountering an error related to loading the model. Please ensure that the cache is cleared and try using `force_reload=True` in your code, as suggested in the error message. Also, verify that you're using compatible versions of Python and PyTorch, as specified below:

## Requirements

Ensure you have [**Python>=3.8.0**](https://www.python.org/) and all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) are installed, including [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/). To get started, run:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

## Environments

YOLOv5 can run in these environments with dependencies pre-installed:
- **Notebooks**: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** VM: [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **AWS AMI**: [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: [Docker Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml"><img src="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml/badge.svg" alt="YOLOv5 CI"></a>

Our Continuous Integration (CI) tests verify the functionality of YOLOv5 [training](https://github.com/ultralytics/yolov5/blob/master/train.py), [validation](https://github.com/ultralytics/yolov5/blob/master/val.py), [inference](https://github.com/ultralytics/yolov5/blob/master/detect.py), [export](https://github.com/ultralytics/yolov5/blob/master/export.py), and [benchmarks](https://github.com/ultralytics/yolov5/blob/master/benchmarks.py).

If your issue persists, please provide any additional information or updates here. Feel free to explore our ⭐️ [Tutorials](https://docs.ultralytics.com/yolov5/) for more guidance.

## Introducing YOLOv8 🚀

Check out our latest model, [YOLOv8](https://github.com/ultralytics/ultralytics), for enhanced performance in object detection, image segmentation, and classification tasks. Explore [YOLOv8 Docs](https://docs.ultralytics.com/) to get started:
```bash
pip install ultralytics
```

Thank you for your patience, and we look forward to helping you resolve this issue! 😊

**Comment by balakreshnan** [comment]
i do have it.
________________________________

**Comment by glenn-jocher** [comment]
@balakreshnan if you've already tried clearing the cache and using `force_reload=True`, please ensure all dependencies are up to date. If the issue persists, consider testing with a different Python version, as Python 3.12 might have compatibility issues. Let us know if you need further assistance!

**Comment by balakreshnan** [comment]
yolov8 worked so pls close v5 doesn't work.
________________________________

**Comment by glenn-jocher** [comment]
Thank you for the update. If YOLOv8 works for you, feel free to continue using it. We'll close this issue. If you have further questions, let us know.
