### ISSUE TITLE
7.0版本首次运行报错AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by MonHer** [ultralytics/yolov5#13342]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

报错日志：
```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\38yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\anaconda3\envs\38yolov5\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Code\Python\YoloPoker\yolo\utils\plots.py", line 305, in plot_images
    annotator.box_label(box, label, color=color)
  File "E:\Code\Python\YoloPoker\yolo\utils\plots.py", line 91, in box_label
    w, h = self.font.getsize(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getsize' 训练完成报错这个 
```
#导致原因
这个错误是由于 FreeTypeFont 对象没有 getsize() 方法引起的，这通常是因为 Pillow 版本的问题。自 Pillow 10.0.0 版本起，getsize() 方法被弃用，改为了 textsize() 或 getbbox()
解决办法：
# 解决方法：
有两种方式可以解决这个问题：

## 1. 降级 Pillow 版本
YOLOv5 和其他旧代码可能依赖于较早版本的 Pillow，因此降级 Pillow 到适合的版本（比如 9.x.x 版本）可以解决这个问题。使用以下命令降级 Pillow：

```
pip install pillow==9.5.0
```
这样可以确保旧的 getsize() 方法在 FreeTypeFont 中可用。
## 2. 修改代码适应新的 Pillow 版本
如果你希望使用较新的 Pillow 版本，可以通过修改 plots.py 文件中的代码，使用新的 getbbox() 方法替换 getsize()。修改代码如下
```
w, h = self.font.getsize(label)  # text width, height
```
update 为：
```
w, h = self.font.getbbox(label)[2:]  # text width, height
```
getbbox() 返回一个 4 元素的元组 (left, top, right, bottom)，其中 right-left 就是宽度，bottom-top 就是高度

### Environment

- yolov5  python 3.8   cuda 12.4

### Minimal Reproducible Example

![image](https://github.com/user-attachments/assets/48904a79-835b-43a8-876d-1102af68a32f)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @MonHer, thank you for reaching out and for your interest in YOLOv5 🚀!

It seems you're encountering an issue related to the `FreeTypeFont` object's `getsize` method. This is commonly due to changes in Pillow versions where `getsize` has been deprecated. You've already identified potential solutions, which is fantastic! 🎉

To assist us in resolving this bug more effectively, could you provide a **minimum reproducible example (MRE)**? This will help our team understand the issue better.

In the meantime, ensure your environment is set up as per the requirements:

## Requirements

- [**Python>=3.8.0**](https://www.python.org/) and all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed, including [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/). To set up:
  ```bash
  git clone https://github.com/ultralytics/yolov5  # clone
  cd yolov5
  pip install -r requirements.txt  # install
  ```

## Environments

You can run YOLOv5 in various environments, including:

- **Notebooks** with free GPU: 
  <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> 
  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> 
  <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** and **Amazon** deep learning environments
- **Docker**: <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

An Ultralytics engineer will review your issue further. Thank you for your patience and contribution! 😊

🔍 For a more detailed exploration, check our ⭐️ [Tutorials](https://docs.ultralytics.com/yolov5/).

**Comment by pderrenger** [comment]
@MonHer thank you for identifying this issue. To resolve it, you can either downgrade Pillow to version 9.5.0 using `pip install pillow==9.5.0` or update the code in `plots.py` to use `getbbox()` instead of `getsize()`. If you choose to submit a PR with the code update, it would be greatly appreciated by the community.
