### ISSUE TITLE
Error: You must call wandb.init() before wandb.log()

### ISSUE THREAD

**Issue by yasindagasan** [ultralytics/yolov5#1356]
hyperparameter tuning gave an error about wandb logging. I think the wandb has not been initialised for parameter tuning but it was attempted to be used for logging images. Here are the details:

## To Reproduce

Input: 

```
python train.py 
--data data/9_folders.yaml 
--cfg models/yolov5x.yaml 
--weights '' 
--batch-size 10 
--rect 
--epochs 2 
--img-size 1280 
--evolve
```

Output:
```
Traceback (most recent call last):
  File "train.py", line 555, in <module>
    results = train(hyp.copy(), opt, device)
  File "train.py", line 326, in train
    log_imgs=opt.log_imgs)
  File "/home/dagasan/Documents/yolov5_source/test.py", line 214, in test
    wandb.log({"outputs": wandb_images})
  File "/home/dagasany/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/lib/preinit.py", line 37, in preinit_wrapper
    raise wandb.Error("You must call wandb.init() before {}()".format(name))
wandb.errors.error.Error: You must call wandb.init() before wandb.log()
Internal process exited

```

## Issue:

 this part seemed to cause the issue

![image](https://user-images.githubusercontent.com/20746470/98883018-b18d4880-24e1-11eb-8423-8d05e053f384.png)

## My workaround

changes in test.py

![image](https://user-images.githubusercontent.com/20746470/98883057-d1247100-24e1-11eb-8fb2-2f4467ca1776.png)

![image](https://user-images.githubusercontent.com/20746470/98883869-01b8da80-24e3-11eb-97ed-6ec8ddf5d204.png)

changes in train.py

![image](https://user-images.githubusercontent.com/20746470/98883969-3b89e100-24e3-11eb-8ea2-7db3ba92b818.png)

## Environment
 - OS: Ubuntu 20.04
 - GPU: 2080 Ti

**Comment by Uoops** [comment]
The wandb does not support evolve mode. You can update the project, I think they have fixed it.

**Comment by Uoops** [comment]
The wandb does not support -- evolve mode. 
I had the same problem. If it is your first time to use wandb, I think you can try train mode first, then you will not have this issue in the evolve mode.

**Comment by Uoops** [comment]
Or just run wandb login on the command line

**Comment by yasindagasan** [comment]
> The wandb does not support -- evolve mode.
> I had the same problem. If it is your first time to use wandb, I think you can try train mode first, then you will not have this issue in the evolve mode.

@Uoops I was actually logged on wandb. I could see my trainings on wandb until I tried to use the evolve mode. So it was not my first time to use wandb and it was all set up. I did not want to specifiially use wandb with evolve but it just gave an error

**Comment by glenn-jocher** [comment]
@yasindagasan @AyushExel thanks for raising this bug report! 

`wandb` is a new integration so there may be a few issues still with it. I recently started an evolution myself, but ran `pip uninstall wandb` first just to keep things simple, and can confirm that evolution operates correctly and without issue with that workflow. But we definitely also want evolution to behave nicely with an installed wandb package, logged in or not. I'll look into this.

**Comment by AyushExel** [comment]
@glenn-jocher I think I know what's happening here but my branch is currently polluted with this PR #1350 .
A simple fix would be to pass `wandb` argument when using evolve mode. Currently it doesn't initialize `wandb` in evovlve mode but `opt.log_imgs` is set to 10 as `wandb` get imported successfully. So, test.py tries to log images but `wandb` is not initialized

**Comment by glenn-jocher** [comment]
@AyushExel hmm ok, thanks I'll check it out. 

How does `wandb off` and `wandb on` relate to `os.environ.set('WANDB_DISABLED')`?

**Comment by yasindagasan** [comment]
> @yasindagasan @AyushExel thanks for raising this bug report!
> 
> `wandb` is a new integration so there may be a few issues still with it. I recently started an evolution myself, but ran `pip uninstall wandb` first just to keep things simple, and can confirm that evolution operates correctly and without issue with that workflow. But we definitely also want evolution to behave nicely with an installed wandb package, logged in or not. I'll look into this.

@glenn-jocher thanks very much!

**Comment by AyushExel** [comment]
> @AyushExel hmm ok, thanks I'll check it out.
> 
> How does `wandb off` and `wandb on` relate to `os.environ.set('WANDB_DISABLED')`?

@glenn-jocher  Wandb off is meant to turn off cloud syncing. It's a dry run mode where your metrics won't be logged to cloud. They can be later synced to the cloud by calling `wandb sync run_dir`.
`os.environ.set('WANDB_DISABLED')` is meant to not use wandb at all!

**Comment by glenn-jocher** [comment]
@AyushExel hmm ok. Is there an equivalent command to setting this variable, like `wandb disable`, `wandb enable`?

**Comment by AyushExel** [comment]
@glenn-jocher No, currently there's no command like that. You might want to checkout this thread for similar discussion.
[wandb silent](https://github.com/wandb/client/issues/764)

**Comment by glenn-jocher** [comment]
@AyushExel ok thanks, added my 2 cents over there. I think PR #1373 should fix this. It still import wandb in test.py, but since there's no logging other than images there, passing in zero images for logging should suffice.

**Comment by glenn-jocher** [comment]
@yasindagasan this should be fixed now in #1373. Please `git pull` to receive this update and let us know if you run into any other problems!

**Comment by yasindagasan** [comment]
@glenn-jocher works all good. thanks!

**Comment by glenn-jocher** [comment]
@yasindagasan great, I'm glad it works now!

**Comment by ma-batita** [comment]
Hello, I know it has been while since the last comment but I am running on a strange behavior with wandb.
I have the same warning massage "You must call wandb.init() before wandb.log()" but at the end of my training!
I am running my code on vertex Al (using a docker file) and I dont get any error or warning from wandb but at the end of the training (after the run summary of wandb) I got this : 

```
wandb: Synced test_CB_wandb: https://wandb.ai/bodyguard/huggingface/runs/m19hgjkq
2022-10-07 16:58:31.503 CEST

workerpool0-0
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
2022-10-07 16:58:31.503 CEST

workerpool0-0
wandb: Find logs at: ./wandb/run-20221007_145819-m19hgjkq/logs
2022-10-07 16:58:31.719 CEST

workerpool0-0
wandb: ERROR You must call wandb.init() before wandb.log()
2022-10-07 16:58:31.721 CEST

workerpool0-0
Traceback (most recent call last):
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-10-07 16:58:31.721 CEST

workerpool0-0
 "__main__", mod_spec)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
2022-10-07 16:58:31.721 CEST

workerpool0-0
 exec(code, run_globals)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 100, in <module>
2022-10-07 16:58:31.721 CEST

workerpool0-0
 main()
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 96, in main
2022-10-07 16:58:31.721 CEST

workerpool0-0
 experiment.run(args)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/app/my_trainer/experiment.py", line 154, in run
2022-10-07 16:58:31.721 CEST

workerpool0-0
 metrics = trainer.evaluate(eval_dataset=val_dataset)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2807, in evaluate
2022-10-07 16:58:31.721 CEST

workerpool0-0
 self.log(output.metrics)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2401, in log
2022-10-07 16:58:31.721 CEST

workerpool0-0
 self.control = self.callback_handler.on_log(self.args, self.state, self.control, logs)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 390, in on_log
2022-10-07 16:58:31.721 CEST

workerpool0-0
 return self.call_event("on_log", args, state, control, logs=logs)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 407, in call_event
2022-10-07 16:58:31.721 CEST

workerpool0-0
 **kwargs,
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 731, in on_log
2022-10-07 16:58:31.721 CEST

workerpool0-0
 self._wandb.log({**logs, "train/global_step": state.global_step})
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
2022-10-07 16:58:31.721 CEST

workerpool0-0
 raise wandb.Error(f"You must call wandb.init() before {name}()")
2022-10-07 16:58:31.721 CEST

workerpool0-0
wandb.errors.Error: You must call wandb.init() before wandb.log()
2022-10-07 16:58:31.722 CEST

workerpool0-0
ERROR:root:Traceback (most recent call last):
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-10-07 16:58:31.722 CEST

workerpool0-0
 "__main__", mod_spec)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
2022-10-07 16:58:31.722 CEST

workerpool0-0
 exec(code, run_globals)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 100, in <module>
2022-10-07 16:58:31.722 CEST

workerpool0-0
 main()
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 96, in main
2022-10-07 16:58:31.722 CEST

workerpool0-0
 experiment.run(args)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/app/my_trainer/experiment.py", line 154, in run
2022-10-07 16:58:31.722 CEST

workerpool0-0
 metrics = trainer.evaluate(eval_dataset=val_dataset)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2807, in evaluate
2022-10-07 16:58:31.722 CEST

workerpool0-0
 self.log(output.metrics)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2401, in log
2022-10-07 16:58:31.722 CEST

workerpool0-0
 self.control = self.callback_handler.on_log(self.args, self.state, self.control, logs)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 390, in on_log
2022-10-07 16:58:31.722 CEST

workerpool0-0
 return self.call_event("on_log", args, state, control, logs=logs)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 407, in call_event
2022-10-07 16:58:31.722 CEST

workerpool0-0
 **kwargs,
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 731, in on_log
2022-10-07 16:58:31.722 CEST

workerpool0-0
 self._wandb.log({**logs, "train/global_step": state.global_step})
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
2022-10-07 16:58:31.722 CEST

workerpool0-0
 raise wandb.Error(f"You must call wandb.init() before {name}()")
2022-10-07 16:58:31.722 CEST

workerpool0-0
wandb.errors.Error: You must call wandb.init() before wandb.log()
2022-10-07 16:58:31.722 CEST

workerpool0-0
NoneType: None
```
