### ISSUE TITLE
How to test with multi-GPU?

### ISSUE THREAD

**Issue by oyange** [ultralytics/yolov5#1503]
## ❔Question
When I test my model with multi-GPU using Dataparallel,  an error happens that input and weight should be on the same device.

## Additional context
![image](https://user-images.githubusercontent.com/23448269/100195124-d649dd00-2f31-11eb-8283-b9ba43249ccf.png)
### All error information:
`Traceback (most recent call last):
  File "detect_czy.py", line 158, in <module>
    test(opt)
  File "detect_czy.py", line 115, in test
    inf_out, _ = model(img, augment=augment)  # inference and training outputs
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/proj/yolov5_mark/models/yolo.py", line 116, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/workspace/proj/yolov5_mark/models/yolo.py", line 137, in forward_once
    x = m(x)  # run
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/proj/yolov5_mark/models/common.py", line 95, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/proj/yolov5_mark/models/common.py", line 37, in fuseforward
    return self.act(self.conv(x))
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)`

**Comment by glenn-jocher** [comment]
@oyange test.py generally operates in single-GPU mode with FP16 inference. When we developed this code, we could select FP16 inference or multi-GPU, but not both, so we went with FP16, which would benefit all users equally.
https://github.com/ultralytics/yolov5/blob/2026d4c5eb4e3e48b5295106db85c844000d95d1/test.py#L58-L61

If you'd like to try to implement multi-GPU testing as a feature addition please submit a PR if you succeed!

**Comment by yustaub** [comment]
Hello @oyange , can you finish multi-gpu testing now?
