### ISSUE TITLE
Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.

### ISSUE THREAD

**Issue by xyl3902596** [ultralytics/yolov5#1505]
I want to convert yolov5 pth model to tensorrt model. So I first convert it to ONNX, and then I would use my onnx2trt tools to convert the onnx model to tensorrt model. But my onnx2trt tool only support opset version 10. So I must use opset v10 to convert my model to ONNX. And I also want to get the decode map of yolo. so I set self.training is False. But when  I use opset v10, I got the error of unsupport of some operations, while it works well when I use opset v11. The code is bellow.
```
class Detect(nn.Module):
    stride = None  # strides computed during build
    export = False  # onnx export
    def __init__(self, nc=80, anchors=(), ch=()):  # detection layer
        super(Detect, self).__init__()
        self.nc = nc  # number of classes
        self.no = nc + 5  # number of outputs per anchor
        self.nl = len(anchors)  # number of detection layers
        self.na = len(anchors[0]) // 2  # number of anchors
        self.grid = [torch.zeros(1)] * self.nl  # init grid
        a = torch.tensor(anchors).float().view(self.nl, -1, 2)
        self.register_buffer('anchors', a)  # shape(nl,na,2)
        self.register_buffer('anchor_grid', a.clone().view(self.nl, 1, -1, 1, 1, 2))  # shape(nl,1,na,1,1,2)
        self.m = nn.ModuleList(nn.Conv2d(x, self.no * self.na, 1) for x in ch)  # output conv

    def forward(self, x):

        # x = x.copy()  # for profiling
        z = []  # inference output

        self.training |= self.export
        if ONNX_EXPORT:
           self.training=False
        for i in range(self.nl):
            x[i] = self.m[i](x[i])  # conv
            bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            if not self.training:  # inference
                if self.grid[i].shape[2:4] != x[i].shape[2:4]:
                    self.grid[i] = self._make_grid(nx, ny).to(x[i].device)

                y = x[i].sigmoid()
                y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
                y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
                z.append(y.view(bs, -1, self.no))
        return x if self.training else (torch.cat(z, 1), x)
```
And this is the error when I use opset 10
```
Traceback (most recent call last):
  File "models/export.py", line 68, in <module>
    torch.onnx.export(model, img, f, verbose=False, opset_version=10, input_names=['images'],
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 203, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/utils.py", line 526, in _export
    graph, params_dict, torch_out = _model_to_graph(model, args, verbose, input_names,
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/utils.py", line 382, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 1228, in index_put
    sym_help._onnx_opset_unsupported('index_put', 9, 11)
  File "/opt/miniconda3/envs/yolov3/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 185, in _onnx_opset_unsupported
    raise RuntimeError('Unsupported: ONNX export of {} in '
RuntimeError: Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.
```
However,if the output doesn't incluse decode part, version 10 works well. So there must be something unsurported in decode part with vesion 10. Cound you please help me find it?

**Comment by glenn-jocher** [comment]
@xyl3902596 See Tutorials section of README for TensorRT deployment.
https://docs.ultralytics.com/yolov5

**Comment by xyl3902596** [comment]
> @xyl3902596 See Tutorials section of README for TensorRT deployment.
> https://docs.ultralytics.com/yolov5

Thank you for your reply. I found the problem occurs at :
y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
opset 10 doesn't support y[...,0:2]= *********
if I write as follows, it works well in opset10
xy=  (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
wh= (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh

**Comment by yushuinanrong** [comment]
@xyl3902596 
How did you change line 59?
```
z.append(y.view(bs, -1, self.no))
```

**Comment by xyl3902596** [comment]
> @xyl3902596
> How did you change line 59?
> 
> ```
> z.append(y.view(bs, -1, self.no))
> ```

what's your meaning? You can ask me in Chinese directly
