### ISSUE TITLE
Inference yolov5 models on torch1.4.0?

### ISSUE THREAD

**Issue by sourabhyadav** [ultralytics/yolov5#1629]
## ❔Question
I am trying inference a pre-trained yolov5 model on the following setup:  
```  
Ubuntu 16.04  
torch==1.4.0  
torchvision==0.5.0  
```  
However, I am facing below error:
```
Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.05, device='', img_size=640, iou_thres=0.5, output='/home/jyadavso/sourabh/people_counter_lookdown/Object-Detection-Metrics/sourabh_data/comparision/customer/yolov5/tmp_pt1.4', save_txt=True, source='/data/sourabh/people_counter_lookdown/test_data/customer_focused/images/', update=False, view_img=False, weights=['runs/exp3/weights/best.pt'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)
           device1 _CudaDeviceProperties(name='Quadro P2000', total_memory=5050MB)

Traceback (most recent call last):
  File "detect.py", line 191, in <module>
    detect()
  File "detect.py", line 36, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fda4d8fe193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7fda507f7afb in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7fda507f8d14 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c5106 (0x7fdaa9d10106 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x295f24 (0x7fdaa98e0f24 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
```  

The closed issues like #581 requested to update the torch to 1.6.0. However, it is not possible for our deployment constraint.  
 
Is it possible to inference yolov5 models using torch1.4.0 and torchvision 0.5.0?

**Comment by glenn-jocher** [comment]
@sourabhyadav requirements should be quite clear.

**Comment by TAOSHss** [comment]
@glenn-jocher  Why does Yolov5x have more params than Yolov3 but less model memory than Yolov3

**Comment by glenn-jocher** [comment]
@TAOSHss I'm not sure I follow. You can compare YOLOv3/5 specs at https://github.com/ultralytics/yolov3 and https://github.com/ultralytics/yolov5

**Comment by TAOSHss** [comment]
The yolov3 that I use has a 62M parameter, and the yolov3.pt that I saved uses 264M of memory. But the yolov5x I used was 85M in the parameter you gave, and the saved Yolov5x.pt occupied 175M memory


---Original---

**Comment by glenn-jocher** [comment]
@TAOSHss all updated models are saved in FP16. Older YOLOv3 models were saved in FP32. You can see updated YOLOv3 model sizes in https://github.com/ultralytics/yolov3/releases

<img width="1030" alt="Screen Shot 2020-12-14 at 9 19 52 AM" src="https://user-images.githubusercontent.com/26833433/102113160-8aca7680-3ded-11eb-98bb-539258086fde.png">
