### ISSUE TITLE
 non_max_suppression() got an unexpected keyword argument 'fast'

### ISSUE THREAD

**Issue by azuryl** [ultralytics/yolov5#172]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
 non_max_suppression() got an unexpected keyword argument 'fast'

## To Reproduce (REQUIRED)

Input:
 python detect.py --source ./inference/images/ --weights yolov5s.pt --conf 0.4

Output:
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/images/', view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11175MB)
           device1 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)
           device2 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)
           device3 _CudaDeviceProperties(name='GeForce GTX 1080 Ti', total_memory=11178MB)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0    848      0 --:--:-- --:--:-- --:--:--   846
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.4M    0 14.4M    0     0  6314k      0 --:--:--  0:00:02 --:--:-- 10.6M
Downloading https://drive.google.com/uc?export=download&id=1R5T6rIyy3lLwgFXNms8whc-387H0tMQO as yolov5s.pt... Done (5.1s)
/home/azuryl/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
image 1/2 inference/images/bus.jpg: Traceback (most recent call last):
  File "detect.py", line 158, in <module>
    detect()
  File "detect.py", line 68, in detect
    fast=True, classes=opt.classes, agnostic=opt.agnostic_nms)
TypeError: non_max_suppression() got an unexpected keyword argument 'fast'


## Expected behavior
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', half=False, img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/images/', view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla P100-PCIE-16GB', total_memory=16280MB)

Downloading https://drive.google.com/uc?export=download&id=1R5T6rIyy3lLwgFXNms8whc-387H0tMQO as yolov5s.pt... Done (2.6s)

image 1/2 inference/images/bus.jpg: 640x512 3 persons, 1 buss, Done. (0.009s)
image 2/2 inference/images/zidane.jpg: 384x640 2 persons, 2 ties, Done. (0.009s)
Results saved to /content/yolov5/inference/output


## Environment
If applicable, add screenshots to help explain your problem.

 - OS: [e.g. Ubuntu 18.04]
 - GPU [e.g. 1080 Ti]

**Comment by glenn-jocher** [comment]
@azuryl thanks for the bug report. You are not using the current repo, as the messages recommended. Suggest you follow the guidance above.

**Comment by azuryl** [comment]
@glenn-jocher thank you reply  I am use the  current repo
git clone https://github.com/ultralytics/yolov5 # clone repo
python3 -c "from yolov5.utils.google_utils import gdrive_download; gdrive_download('1n_oKgR81BJtqk75b00eAjdv03qVCQn2f','coco128.zip')" # download dataset
cd yolov5
pip install -U -r requirements.txt
