### ISSUE TITLE
Turning yolov5 detect.py to exe by pyinstaller

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/yolov5#1737]
I use pyinstaller in python3.8, the exe can work by using powershell, but not work by cmd and another computer, error information as follow:

Traceback (most recent call last):
File "detect.py", line 10, in
File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.dict)
File "utils_all.py", line 41, in
File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.dict)
File "scipy\cluster_init_.py", line 25, in
File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.dict)
File "scipy\cluster\vq.py", line 71, in
File "c:\users\cwy\anaconda3\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.dict)
File "scipy\spatial_init_.py", line 98, in
ImportError: DLL load failed while importing qhull: 找不到指定的模块。
[8372] Failed to execute script detect

And there is my pip list:
Package Version

absl-py 0.11.0
altgraph 0.17
cachetools 4.1.1
certifi 2020.6.20
chardet 3.0.4
click 7.1.2
cycler 0.10.0
Cython 0.29.21
future 0.18.2
google-auth 1.23.0
google-auth-oauthlib 0.4.2
grpcio 1.33.2
idna 2.10
kiwisolver 1.3.1
Markdown 3.3.3
matplotlib 3.3.3
numpy 1.18.4
oauthlib 3.1.0
opencv-python 4.4.0.46
pefile 2019.4.18
Pillow 8.0.1
pip 20.2.4
protobuf 3.14.0
pyasn1 0.4.8
pyasn1-modules 0.2.8
pycairo 1.20.0
pyinstaller 4.1
pyinstaller-hooks-contrib 2020.10
pyparsing 2.4.7
pypiwin32 223
python-dateutil 2.8.1
pywin32 300
pywin32-ctypes 0.2.0
PyYAML 5.3.1
requests 2.25.0
requests-oauthlib 1.3.0
rsa 4.6
scipy 1.5.4
setuptools 50.3.1.post20201107
six 1.15.0
spark-parser 1.8.9
tensorboard 2.4.0
tensorboard-plugin-wit 1.7.0
torch 1.6.0+cu101
torchvision 0.7.0+cu101
tornado 6.1
tqdm 4.52.0
uncompyle6 3.7.4
urllib3 1.26.2
Werkzeug 1.0.1
wheel 0.35.1
wincertstore 0.2
xdis 5.0.6

Anyone know how to slove it?

**Comment by yao-zheng-yi** [comment]
I have solved the problem.But now in computers without CUDA, the exe can't work normally, and can only used with cpu, can't GPU.
The error as follow:
Traceback (most recent call last):
  File "detect.py", line 233, in <module>
  File "detect.py", line 38, in detect
  File "utils_all.py", line 2492, in select_device
AssertionError: CUDA unavailable, invalid device 1 requested

How can I use GPU to detect in computer without CUDA?  Or the exe can only use CPU in computers without CUDA?

**Comment by glenn-jocher** [comment]
@yao-zheng-yi I have no experience with windows installers, but in python we check to see if cuda is available before defining the backend device:
https://github.com/ultralytics/yolov5/blob/394d1c89f33f29b2039c54f4a81e561a0b140b3a/utils/torch_utils.py#L46-L53

**Comment by mrlightman5** [comment]
@yao-zheng-yi hello,can you tell me how you solve it ?i have the same problems when using the pyinstaller

**Comment by onyx27182** [comment]
@yao-zheng-yi  but how did you fix your original problem (DLL failure loading qhull).     @mrlightman5  Did you find a fix to the problem also?
