### ISSUE TITLE
When training coco128 dataset, setting single GPU: "device = 2" will automatically go to CUDA:0 Run on！

### ISSUE THREAD

**Issue by firstelfin** [ultralytics/yolov5#1760]
## 🐛 Bug
```shell
# Train YOLOv5x on COCO128 for 3 epochs with "device:2"
$ python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5x.pt --device "2"
```

**RuntimeError**: CUDA out of memory. Tried to allocate 126.00 MiB (GPU 0; 10.76 GiB total capacity; 9.69 GiB already allocated; 11.56 MiB free; 9.74 GiB reserved in total by PyTorch)

**GPU of current environment**
![image](https://user-images.githubusercontent.com/36871890/102949132-83e4e780-4502-11eb-8cc7-2bbf7a27f831.png)

Output:
```
$ python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5x.pt --device "2"
Using torch 1.7.1 CUDA:0 (GeForce RTX 2080 Ti, 11019MB)

Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='', data='./data/coco128.yaml', device='2', epochs=3, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=-1, log_artifacts=False, log_imgs=16, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', rect=False, resume=False, save_dir='runs/train/exp22', single_cls=False, sync_bn=False, total_batch_size=16, weights='yolov5x.pt', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}

   ……
Model Summary: 607 layers, 88965245 parameters, 88965245 gradients, 221.7 GFLOPS

Transferred 802/802 items from yolov5x.pt
Optimizer groups: 134 .bias, 142 conv.weight, 131 other
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:00<?, ?it/s]
Plotting labels... 
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:01<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:01<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:02<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:02<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:02<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:02<?, ?it/s]
Scanning '../coco128/labels/train2017.cache' for images and labels... 128 found, 0 missing, 2 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████| 128/128 [00:02<?, ?it/s]

Analyzing anchors... anchors/target = 4.26, Best Possible Recall (BPR) = 0.9946
Image sizes 640 train, 640 test
Using 8 dataloader workers
Logging results to runs/train/exp22
Starting training for 3 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
  0%|                                                                                                                                                                                         | 0/8 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 512, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 289, in train
    pred = model(imgs)  # forward
  File "/home/elfin/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/elfin/utils/yolov5-master/models/yolo.py", line 122, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/elfin/utils/yolov5-master/models/yolo.py", line 138, in forward_once
    x = m(x)  # run
  File "/home/elfin/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/elfin/utils/yolov5-master/models/common.py", line 119, in forward
    return torch.cat(x, self.d)
RuntimeError: CUDA out of memory. Tried to allocate 126.00 MiB (GPU 0; 10.76 GiB total capacity; 9.69 GiB already allocated; 11.56 MiB free; 9.74 GiB reserved in total by PyTorch)
```

## Expected behavior
You want to call GPU:2 Training model

## Environment

 - OS: [Ubuntu]
 - GPU [3*2080 Ti]
 - python：Anaconda virtual environment

## Additional context
I want to specify the last GPU training model, but using "device" to specify it doesn't work, and using "os.environ[“CUDA_VISIBLE_DEVICES”]" to specify it still doesn't work. See the code "Torch"_ utils.py ”After the "os.environ[“CUDA_VISIBLE_DEVICES”]" is found, it is returned “cuda:0 ”In this case, the support for multiple GPUs seems to result in the failure of single GPU specification. Use in source code“ torch.cuda.device_ Count() "will cause an error when specifying the single GPU, and modify “select_device”, in the“train.py“ When you call "train", you will still report wrong.

**Comment by glenn-jocher** [comment]
@firstelfin arguments are without quotations:
`python train.py --device 2`

**Comment by glenn-jocher** [comment]
@firstelfin also you should git pull to make sure you are running the latest code, a --device bug fix PR was merged recently.

**Comment by firstelfin** [comment]
@glenn-jocher OK, thank you. I'll try again

**Comment by firstelfin** [comment]
@glenn-jocher This error is still reported when using the latest code. When multiple GPUs are specified, you must also use the GPU:0 "Go
```shell
$ python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5x.pt --device 2,1
Using torch 1.7.1 CUDA:0 (GeForce RTX 2080 Ti, 11019MB)
                  CUDA:1 (GeForce RTX 2080 Ti, 11019MB)
```

**Comment by glenn-jocher** [comment]
@firstelfin 

> @glenn-jocher This error is still reported when using the latest code. When multiple GPUs are specified, you must also use the GPU:0 "Go
> 
> ```shell
> $ python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5x.pt --device 2,1
> Using torch 1.7.1 CUDA:0 (GeForce RTX 2080 Ti, 11019MB)
>                   CUDA:1 (GeForce RTX 2080 Ti, 11019MB)
> ```

In this example everything appears well. If you are worried about the CUDA:# indices, these are with respect to your visible devices, not absolute devices. So in your command CUDA:0 and CUDA:1 are local indices to your visible devices 2,1.

**Comment by firstelfin** [comment]
@glenn-jocher Thank you for your reply

**Comment by glenn-jocher** [comment]
@firstelfin I was thinking we could improve this by reporting the same devices specified by the --device argument, i.e. if a user runs `python train.py --device 2,3` then the screen printout would read as below. This would naturally make more sense and cause less confusion.
```
Using torch 1.7.1 CUDA:2 (GeForce RTX 2080 Ti, 11019MB)
                  CUDA:3 (GeForce RTX 2080 Ti, 11019MB)
```

This would not work with the `CUDA_VISIBLE_DEVICES` environment variable, but this use case is not common I believe since we have the --device argument.

TODO: report same CUDA device IDs as --device argument.

**Comment by firstelfin** [comment]
@glenn-jocher Thank you for your reply. I guess many people will ignore the difference of GPU ID. After improvement, it will be more in line with most people's writing habits.

**Comment by glenn-jocher** [comment]
@firstelfin issue should be resolved now in PR https://github.com/ultralytics/yolov5/pull/1776. 

Let us know if you spot any other areas for improvement!
