### ISSUE TITLE
a quesstion when training brainwash dataset

### ISSUE THREAD

**Issue by guchengxi1994** [ultralytics/yolov5#1814]
## ❔Question
i converted brainwash annotations to yolo annotations(txt), but when i tried to train a model, there was a problem. how can i solve this problem?

## Additional context
`WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val82.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val83.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val84.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val85.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val86.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val87.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val88.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val89.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val9.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val90.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val91.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val92.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val93.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val94.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val95.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val96.jpg: duplicate labels
Scanning '/home/ps/face/labels/val2017' for images and labels... 490 found, 0 missing, 0 empty, 490 corrupted:  99%|???????????WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val97.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val98.jpg: duplicate labels
WARNING: Ignoring corrupted image and/or label /home/ps/face/images/val2017/val99.jpg: duplicate labels
Scanning '/home/ps/face/labels/val2017' for images and labels... 493 found, 0 missing, 0 empty, 493 corrupted: 100%|???????????
New cache created: /home/ps/face/labels/val2017.cache
Scanning '/home/ps/face/labels/val2017.cache' for images and labels... 493 found, 0 missing, 0 empty, 493 corrupted: 100%|?????Traceback (most recent call last):
  File "train.py", line 503, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 197, in train
    testloader = create_dataloader(test_path, imgsz_test, total_batch_size, gs, opt,  # testloader
  File "/home/ps/v5/utils/datasets.py", line 61, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/ps/v5/utils/datasets.py", line 384, in __init__
    labels, shapes = zip(*cache.values())
ValueError: not enough values to unpack (expected 2, got 0)
Scanning '/home/ps/face/labels/val2017.cache' for images and labels... 493 found, 0 missing, 0 empty, 493 corrupted: 100%|`

**Comment by guchengxi1994** [comment]
sorry, my bad
