### ISSUE TITLE
pytorch1.7 is not completely support.'inplace'! 'inplace'! 'inplace'!

### ISSUE THREAD

**Issue by cww97** [ultralytics/yolov5#1832]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

```
your requirements.txt said pytorch>=1.7, on cpu this is fine, but when I ran it on GPU, yeah, boom
I fixed it from [here](https://github.com/ultralytics/yolov5/issues/1265#issuecomment-723497340),
yes, downgrade pytorch into 1.6.
```

## To Reproduce (REQUIRED)

Input:
```
$ python detect.py --source ./inference/images/ --weights yolov5s.pt --conf 0.4
```

Output:
```
Traceback (most recent call last):
  File "detect.py", line 188, in <module>
    detect()
  File "detect.py", line 69, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/opt/chenweiwen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/chenweiwen/sec-model-code/yolov5/models/yolo.py", line 112, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/opt/chenweiwen/sec-model-code/yolov5/models/yolo.py", line 132, in forward_once
    x = m(x)  # run
  File "/opt/chenweiwen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/chenweiwen/sec-model-code/yolov5/models/common.py", line 88, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/opt/chenweiwen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/chenweiwen/sec-model-code/yolov5/models/common.py", line 32, in fuseforward
    return self.act(self.conv(x))
  File "/opt/chenweiwen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/chenweiwen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 438, in forward
    return F.hardswish(input, self.inplace)
  File "/opt/chenweiwen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'
```

## Environment

 - OS: [centOS 7]
 - GPU [Tesla M60]

**Comment by glenn-jocher** [comment]
@cww97 our Colab notebook runs 1.7.0 on GPU perfectly well. Everything is working correctly on all OSs if you meet the requirements.

<img width="1262" alt="Screen Shot 2021-01-04 at 9 25 50 PM" src="https://user-images.githubusercontent.com/26833433/103609828-916f7980-4ed3-11eb-8173-6fdfe9840606.png">

**Comment by wwdok** [comment]
You don't have to downgrade torch version, just refer to [this](https://github.com/pytorch/pytorch/issues/46971#issuecomment-722775106), it works for me !
