### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by ryan994** [ultralytics/yolov5#1859]
Hello, when I try to run v4.0, I meet a issue, maybe a bug? 

## 🐛 Bug
BrokenPipeError: [Errno 32] Broken pipe

## To Reproduce
I did not change anything, the commond I run is : 
python train.py --batch 20 --epochs 300 --data ./data/coco128.yaml --weights ./weights/yolov5s.pt --name test123

Output:

Traceback (most recent call last):
  File "train.py", line 519, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 202, in train
    rank=-1, world_size=opt.world_size, workers=opt.workers, pad=0.5)[0]
  File "D:\yolov5_v4.0\utils\datasets.py", line 83, in create_dataloader
    collate_fn=LoadImagesAndLabels.collate_fn4 if quad else LoadImagesAndLabels.collate_fn)
  File "D:\yolov5_v4.0\utils\datasets.py", line 96, in __init__
    self.iterator = super().__iter__()
  File "D:\Anaconda3\envs\pytorch17\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\Anaconda3\envs\pytorch17\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\pytorch17\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\Anaconda3\envs\pytorch17\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\pytorch17\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\pytorch17\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\pytorch17\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\pytorch17\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

## Environment

 - OS: win10
 - GPU Using torch 1.7.1+cu101 CUDA:0 (GeForce GTX 1070, 8192.0MB)
 - Memory: 16
 
## Additional context

I google this issue, it seems about thread, when I change number of workers to 6 or below, it worked successfully. Is my computer issue or a bug? Anyone has idea? Thanks!!!

**Comment by glenn-jocher** [comment]
@ryan994 yes this may be associated with multiple dataloader workers. I don't think there's any relation to the recent release. If you can reproduce this in a Colab notebook please advise, otherwise your solution should work locally.

**Comment by ryan994** [comment]
@glenn-jocher I run v3.0 before, It works prefectly with 8 workers, however, it does not work in v4.0 at same env.

**Comment by glenn-jocher** [comment]
@ryan994 if you can supply a reproducible example in a common environment (one of the 4 above), we can take a look.

**Comment by glenn-jocher** [comment]
@ryan994 also just an FYI we are training several models at the moment with v4.0 release with default worker counts with no known issues other than https://github.com/ultralytics/yolov5/pull/1852, which is unrelated.

**Comment by ryan994** [comment]
@glenn-jocher ok, I will try to run it on other pc, and check if my pc's problem.

**Comment by glenn-jocher** [comment]
@ryan994 ok! docker image is a good solution also for local environment issues:
https://hub.docker.com/r/ultralytics/yolov5
https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/
