### ISSUE TITLE
KeyError: "weights/yolov5s.pt is not compatible with ./models/yolov5s.yaml. Specify --weights '' or specify a --cfg compatible with weights/yolov5s.pt."

### ISSUE THREAD

**Issue by Al-Razi-KR** [ultralytics/yolov5#186]
Input:
```
python train.py --img 640 --batch 16 --epochs 5 --data ./data/Dataset.yaml --cfg ./models/yolov5s.yaml --weights weights/yolov5s.pt
```

Output:
```
Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
{'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='./models/yolov5s.yaml', data='./data/Dataset.yaml', device='', epochs=5, evolve=False, img_size=[640], multi_scale=False, name='', noautoanchor=False, nosave=False, notest=False, rect=False, resume=False, single_cls=False, weights='weights/yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce MX250', total_memory=2048MB)

Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/

              from  n    params  module                                  arguments                     
  0             -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1             -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2             -1  1     20672  models.common.Bottleneck                [64, 64]                      
  3             -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4             -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
  5             -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6             -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
  7             -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8             -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9             -1  1   1905152  models.common.BottleneckCSP             [512, 512, 2]                 
 10             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
 11             -1  1     15390  torch.nn.modules.conv.Conv2d            [512, 30, 1, 1]               
 12             -2  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 13        [-1, 6]  1         0  models.common.Concat                    [1]                           
 14             -1  1    197120  models.common.Conv                      [768, 256, 1, 1]              
 15             -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
 16             -1  1      7710  torch.nn.modules.conv.Conv2d            [256, 30, 1, 1]               
 17             -2  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 18        [-1, 4]  1         0  models.common.Concat                    [1]                           
 19             -1  1     49408  models.common.Conv                      [384, 128, 1, 1]              
 20             -1  1     78720  models.common.BottleneckCSP             [128, 128, 1, False]          
 21             -1  1      3870  torch.nn.modules.conv.Conv2d            [128, 30, 1, 1]               
 22   [-1, 16, 11]  1         0  models.yolo.Detect                      [5, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]]]
Model Summary: 165 layers, 6.8719e+06 parameters, 6.8719e+06 gradients

Optimizer groups: 54 .bias, 60 conv.weight, 51 other
2020-06-24 04:06:44.944075: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-24 04:06:44.944309: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\FYP-2020-S1\anaconda3\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "train.py", line 115, in train
    ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items()
  File "train.py", line 116, in <dictcomp>
    if model.state_dict()[k].shape == v.shape}  # to FP32, filter
KeyError: 'model.2.cv2.weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 403, in <module>
    train(hyp)
  File "train.py", line 121, in train
    raise KeyError(s) from e
KeyError: "weights/yolov5s.pt is not compatible with ./models/yolov5s.yaml. Specify --weights '' or specify a --cfg compatible with weights/yolov5s.pt."
```

## Environment

 - OS: [Windows]
 - GPU [GeForce MX250]

![image](https://user-images.githubusercontent.com/61910469/85457605-cf115280-b5d2-11ea-94ae-c29569a1104c.png)

**Comment by glenn-jocher** [comment]
@Al-Razi-KR code and models have both been updated recently. Delete models and update repo.

**Comment by Al-Razi-KR** [comment]
Thanks, that error got fixed
