### ISSUE TITLE
RuntimeError: DataLoader worker

### ISSUE THREAD

**Issue by dcboy** [ultralytics/yolov5#1908]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
```
Traceback (most recent call last):
  File "train.py", line 519, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 292, in train
    pred = model(imgs)  # forward
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/yolo.py", line 119, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/dcboy/work/project/yolov5/models/yolo.py", line 135, in forward_once
    x = m(x)  # run
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/common.py", line 86, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/common.py", line 52, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/common.py", line 36, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 394, in forward
    return F.silu(input, inplace=self.inplace)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1741, in silu
    return torch._C._nn.silu(input)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 10497) is killed by signal: Killed.
```

## To Reproduce (REQUIRED)

Input:
```
python train.py --name 6970399920439 --img 640 --batch 16 --epochs 300 --data ../6970399920439/dataset.yaml --cfg ../6970399920439/model.yaml --weight yolov5l.pt
```

Output:
```
Traceback (most recent call last):
  File "train.py", line 519, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 292, in train
    pred = model(imgs)  # forward
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/yolo.py", line 119, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/dcboy/work/project/yolov5/models/yolo.py", line 135, in forward_once
    x = m(x)  # run
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/common.py", line 86, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/common.py", line 52, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/work/project/yolov5/models/common.py", line 36, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 394, in forward
    return F.silu(input, inplace=self.inplace)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1741, in silu
    return torch._C._nn.silu(input)
  File "/home/dcboy/.local/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 10497) is killed by signal: Killed.
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [TX2]

**Comment by glenn-jocher** [comment]
@dcboy this can occur if your system resources are overwhelmed. You should simply restart your machine and retry, and possibly reduce --workers when training.

**Comment by dcboy** [comment]
> @dcboy this can occur if your system resources are overwhelmed. You should simply restart your machine and retry, and possibly reduce --workers when training.

i have set workers as 1 , but also have issues

**Comment by dcboy** [comment]
`
Analyzing anchors... anchors/target = 5.68, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 6 dataloader workers
Logging results to runs/train/69211685092565
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
  0%|                                                                                                                                                                                                                                                    | 0/73 [00:35<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 519, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 292, in train
    pred = model(imgs)  # forward
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/my/Work/project/yolov5/models/yolo.py", line 119, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/my/Work/project/yolov5/models/yolo.py", line 135, in forward_once
    x = m(x)  # run
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/my/Work/project/yolov5/models/common.py", line 86, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/my/Work/project/yolov5/models/common.py", line 52, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/my/Work/project/yolov5/models/common.py", line 36, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/my/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
  File "/home/my/.local/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 30853) is killed by signal: Killed.
`

=======
pytorch == 1.7.1
Linux desktop 4.9.201-tegra #1 SMP PREEMPT Fri Jan 15 14:54:23 PST 2021 aarch64 aarch64 aarch64 GNU/Linux
CUDA 10.2
jetson TX2

**Comment by glenn-jocher** [comment]
@dcboy killed workers can be a symptom of hardware strains (i.e. out of memory, too many threads, etc.)

**Comment by youngfreeFJS** [comment]
set `--workers 0` is working for me (macbook pro m1)

> > @dcboy this can occur if your system resources are overwhelmed. You should simply restart your machine and retry, and possibly reduce --workers when training.
> 
> i have set workers as 1 , but also have issues
