### ISSUE TITLE
3090ti CUDA11.1 torch1.7.1 training error

### ISSUE THREAD

**Issue by faded-TJU** [ultralytics/yolov5#2028]
## ❔Question
Hello, I changed the environment of 3090cuda11.1 torch 1.7.1, the following error occurred during the training, no solution found, would you like to see，THX!!!：
I can run the detect.py, but there was an error when I ran train.py.

## Additional context
This is the command I entered：
python train.py --img 640 --batch 16 --epochs 5 --data coco128.yaml --weights yolov5s.pt

autoanchor: Analyzing anchors... anchors/target = 4.26, Best Possible Recall (BPR) = 0.9946
Image sizes 640 train, 640 test
Using 8 dataloader workers
Logging results to runs/train/exp7
Starting training for 5 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
  0%|                                                                                                                                                                                      | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 522, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 264, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/wh/project/yolov5/utils/datasets.py", line 103, in __iter__
    yield next(self.iterator)
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wh/.conda/envs/wanghan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wh/project/yolov5/utils/datasets.py", line 499, in __getitem__
    img, labels = load_mosaic(self, index)
  File "/home/wh/project/yolov5/utils/datasets.py", line 648, in load_mosaic
    img, _, (h, w) = load_image(self, index)
  File "/home/wh/project/yolov5/utils/datasets.py", line 609, in load_image
    assert img is not None, 'Image Not Found ' + path
AssertionError: Image Not Found ..\coco128\images\train2017\000000000009.jpg

**Comment by faded-TJU** [comment]
I like this project very much,and at present also is studying.I hoped that you can be convenient to look at this question, thx!!!

![image](https://user-images.githubusercontent.com/69620592/105633547-2abafb80-5e94-11eb-8f72-2135182877ec.png)
But it's in the COCO128 folder

**Comment by glenn-jocher** [comment]
@faded-TJU 11.1 is very new, and not part of the standard pytorch installation offerings (https://pytorch.org/get-started/locally/). For stability I would install no further than 11.0. You might also use our docker container for a working local environment: https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

I don't understand your second question. You can train COCO128 in just two clicks in our Colab notebook, I would recommend you start there:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Comment by faded-TJU** [comment]
Okay, thank you. I'll try.
