### ISSUE TITLE
TypeError: int() can't convert non-string with explicit base

### ISSUE THREAD

**Issue by laenix** [ultralytics/yolov5#2066]
## TypeError: int() can't convert non-string with explicit base

Input:
```
python train.py --img 640 --batch 16 --epochs 5 --data ./data/dataset/dataset.yaml --cfg ./models/yolov5s.yaml --weights ''
```
Output:
```
Traceback (most recent call last):
  File "D:\software\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\software\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\yolov5\utils\plots.py", line 124, in plot_images
    colors = color_list()  # list of colors
  File "D:\yolov5\utils\plots.py", line 34, in color_list
    return [hex2rgb(h) for h in plt.rcParams['axes.prop_cycle'].by_key()['color']]
  File "D:\yolov5\utils\plots.py", line 34, in <listcomp>
    return [hex2rgb(h) for h in plt.rcParams['axes.prop_cycle'].by_key()['color']]
  File "D:\yolov5\utils\plots.py", line 32, in hex2rgb
    return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))
  File "D:\yolov5\utils\plots.py", line 32, in <genexpr>
    return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))
TypeError: int() can't convert non-string with explicit base
```
## Environment

 - OS: [Windows 10]
 - GPU [1660 super]

## Additional context
```
def color_list():
    # Return first 10 plt colors as (r,g,b) https://stackoverflow.com/questions/51350872/python-from-color-name-to-rgb
    def hex2rgb(h):
        return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))

    return [hex2rgb(h) for h in plt.rcParams['axes.prop_cycle'].by_key()['color']]
```

**Comment by laenix** [comment]
![Uploading image.png…]()

**Comment by glenn-jocher** [comment]
@laenix thanks for the bug report. What version of matplotlib are you using?

```python
import matplotlib

print(matplotlib.__version__)
```

**Comment by glenn-jocher** [comment]
@laenix could you try the following two blocks of code and see if they work for you?

Block 1
```python
import matplotlib

def color_list():
    # Return first 10 plt colors as (r,g,b) https://stackoverflow.com/questions/51350872/python-from-color-name-to-rgb
    def hex2rgb(h):
        return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))

    return [hex2rgb(h) for h in plt.rcParams['axes.prop_cycle'].by_key()['color']]

print(color_list())
```

Block 2
```python
import matplotlib

def color_list():
    # Return first 10 plt colors as (r,g,b) https://stackoverflow.com/questions/51350872/python-from-color-name-to-rgb
    def hex2rgb(h):
        return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))

    return [hex2rgb(h) for h in matplotlib.colors.TABLEAU_COLORS.values()]

print(color_list())
```
