### ISSUE TITLE
https connection

### ISSUE THREAD

**Issue by Happyna88** [ultralytics/yolov5#2117]
## ❔Question

When i run test.py: python test.py --weights weights/yolov5s.pt --data data/coco.yaml --img 640 --conf 0.001 --iou 0.65 , i have put yolov5s.pt in the weights folder, but when i run test, it still have error:
Traceback (most recent call last):
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9fc82309d0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/yolov5/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9fc82309d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 307, in <module>
    test(opt.data,
  File "test.py", line 55, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/chenglina/code/yolov5-4.0/models/experimental.py", line 117, in attempt_load
    attempt_download(w)
  File "/home/chenglina/code/yolov5-4.0/utils/google_utils.py", line 25, in attempt_download
    response = requests.get('https://api.github.com/repos/ultralytics/yolov5/releases/latest').json()  # github api
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/chenglina/anaconda3/envs/pytorch17/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/yolov5/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9fc82309d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

Why is that? Hope your help.

**Comment by glenn-jocher** [comment]
@Happyna88 this checks github for code updates. You should update your code (git pull) as this error is resolved I believe.

**Comment by wudashuo** [comment]
被墙了啊，手动git pull一下

**Comment by fanghua2021** [comment]
> @ Happyna88这会检查github是否有代码更新。我相信您应该更新您的代码（git pull），因为此错误已得到解决。
