### ISSUE TITLE
Unable to Convert to ONNX MOdel

### ISSUE THREAD

**Issue by vdaita** [ultralytics/yolov5#224]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo - Is using current repository.
 - **Common dataset**: coco.yaml or coco128.yaml Dataset: https://github.com/archie9211/Mask-Detection-Dataset, with .yaml files described in notebook.
 - **Common environment**: **Colab**, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment -- 
 
Based on the following repository: https://github.com/offsouza/yolov5_face_mask_detection

If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

Following error when using the following command to convert .pt to ONNX.
`!python3 onnx_export.py --weights=results.pt --img-size=416 --batch-size=1
`

```
/content/yolov5
Namespace(batch_size=1, img_size=[416], weights='results.pt')
Fusing layers...
Model Summary: 140 layers, 7.24922e+06 parameters, 6.61683e+06 gradients
Traceback (most recent call last):
  File "onnx_export.py", line 34, in <module>
    _ = model(img)  # dry run
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/yolov5/models/yolo.py", line 90, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/content/yolov5/models/yolo.py", line 110, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/yolov5/models/common.py", line 87, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/yolov5/models/common.py", line 25, in fuseforward
    return self.act(self.conv(x))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 12, 3, 3], but got 3-dimensional input of size [1, 6, 208] instead
```

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Expected behavior

I expected an onnx model that I could then convert to Tensorflow, before integrating that into an Android app. (Hopefully MLKit has built-in NMS)

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

Google Colab GPU instance

**Comment by zhanghang1989** [comment]
@vdaita have you transferred the model to tensorflow format successfully?

**Comment by vdaita** [comment]
@zhanghang1989 Not to TF formal, there is another Issue for that I believe.
