### ISSUE TITLE
Training on custom dataset fails with RuntimeError: NCCL Error 2: unhandled system error

### ISSUE THREAD

**Issue by ganesh3** [ultralytics/yolov5#2253]
## ❔Question
Hi,

Training on custom dataset failed with the below error while running on AWS EC2 p8 instance with ubuntu.

```
train.py  --batch-size 64 --data coco.yaml --weights yolov5s.pt --device 0,1,2,3,4,5,6,7

The yaml file above was replaced with the correct filename. Please ignore the above.
```
ERROR DETAILS. Can this be resolved?
```
Traceback (most recent call last):
  File "train.py", line 526, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 292, in train
    pred = model(imgs)  # forward
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 160, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 88, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 22, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 56, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: NCCL Error 2: unhandled system error
```

Same error encountered with distributed training.

```
python -m torch.distributed.launch --master_port=56789 --nproc_per_node 4 train.py --batch-size 64 --data coco.yaml --weights yolov5s.pt
```

ERROR DETAILS:

```
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 505, in <module>
  File "train.py", line 505, in <module>
  File "train.py", line 505, in <module>
  File "train.py", line 505, in <module>
            dist.init_process_group(backend='nccl', init_method='env://')  # distributed backenddist.init_process_group(backend='nccl', init_method='env://')  # distributed backenddist.init_process_group(backend='nccl', init_method='env://')  # distributed backend


      File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
dist.init_process_group(backend='nccl', init_method='env://')  # distributed backend
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
        barrier()barrier()

barrier()  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier

    barrier()  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier

  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
            work = _default_pg.barrier()work = _default_pg.barrier()work = _default_pg.barrier()


work = _default_pg.barrier()RuntimeErrorRuntimeErrorRuntimeError
: : : NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8RuntimeErrorNCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

:
NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/yolo5/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/yolo5/bin/python3', '-u', 'train.py', '--local_rank=3', '--batch-size', '64', '--data', 'claims.yaml', '--weights', 'yolov5s.pt']' returned non-zero exit status 1
```
Running the python command with NCCL_DEBUG=INFO python.... gives below details:

```
ip-172-31-25-38:18863:18863 [0] NCCL INFO Bootstrap : Using [0]ens5:172.31.25.38<0>
ip-172-31-25-38:18863:18863 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v3 symbol.
ip-172-31-25-38:18863:18863 [0] NCCL INFO NET/IB : No device found.
ip-172-31-25-38:18863:18863 [0] NCCL INFO NET/Socket : Using [0]ens5:172.31.25.38<0>
ip-172-31-25-38:18863:18863 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2

ip-172-31-25-38:18863:19129 [1] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch
ip-172-31-25-38:18863:19129 [1] NCCL INFO graph/xml.cc:662 -> 2
ip-172-31-25-38:18863:19129 [1] NCCL INFO graph/topo.cc:523 -> 2
ip-172-31-25-38:18863:19129 [1] NCCL INFO init.cc:581 -> 2
ip-172-31-25-38:18863:19129 [1] NCCL INFO init.cc:840 -> 2
ip-172-31-25-38:18863:19129 [1] NCCL INFO group.cc:73 -> 2 [Async thread]

ip-172-31-25-38:18863:19128 [0] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch
ip-172-31-25-38:18863:19128 [0] NCCL INFO graph/xml.cc:662 -> 2
ip-172-31-25-38:18863:19128 [0] NCCL INFO graph/topo.cc:523 -> 2
ip-172-31-25-38:18863:19128 [0] NCCL INFO init.cc:581 -> 2
ip-172-31-25-38:18863:19128 [0] NCCL INFO init.cc:840 -> 2
ip-172-31-25-38:18863:19128 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
ip-172-31-25-38:18863:18863 [0] NCCL INFO init.cc:906 -> 2
  0%|          | 0/9 [01:40<?, ?it/s]
```
The driver version listed is as below:
```
cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  440.33.01  Wed Nov 13 00:00:22 UTC 2019
GCC version:  gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```
RUnning the below command validates that 440 version is available.

```
 dpkg -l | grep nvidia-driver
ii  nvidia-driver-440                         450.102.04-0ubuntu0.18.04.1         amd64        Transitional package for nvidia-driver-450
ii  nvidia-driver-450                         450.102.04-0ubuntu0.18.04.1         amd64        NVIDIA driver metapackage

```

**Comment by glenn-jocher** [comment]
@ganesh3 there is no delay before training starts. You likely have CUDA and environment related issues. Suggest you try docker if training locally. Full text below.

It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by ganesh3** [comment]
Resolved the issue by following this link on stackoverflow - https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch 

and this link on distributed training on pytorch - https://tutorials.pytorch.kr/beginner/aws_distributed_training_tutorial.html and this link - https://discuss.pytorch.org/t/problem-in-dataprallel-for-more-than-2-gpus/103373/6
