### ISSUE TITLE
detect.py  report an error

### ISSUE THREAD

**Issue by HalvesChen** [ultralytics/yolov5#2262]
## Additional context
Traceback (most recent call last):
  File "D:/yolov5/yolov5-master/yolov5-master/detect.py", line 167, in <module>
    check_requirements()
  File "D:\yolov5\yolov5-master\yolov5-master\utils\general.py", line 92, in check_requirements
    pkg_resources.require(requirements)  # DistributionNotFound or VersionConflict exception if requirements not met
  File "D:\anaconda\envs\yolov5\lib\site-packages\pkg_resources\__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\anaconda\envs\yolov5\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycocotools>=2.0' distribution was not found and is required by the application

Process finished with exit code 1

**Comment by glenn-jocher** [comment]
The 'pycocotools>=2.0' distribution was not found and is required by the application
