### ISSUE TITLE
set NUMEXPR_MAX_THREADS  -> TypeError: int() can't convert non-string with explicit base

### ISSUE THREAD

**Issue by Liuxuweilxw** [ultralytics/yolov5#2351]
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
errors ocurr after adding os.environ['NUMEXPR_MAX_THREADS'] = '16' in utils/general.py or train.py

Exception in thread Thread-9:
Traceback (most recent call last):
  File "D:\Anaconda\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Code\YOLOv5\yolov5-master\mynet\utils\plots.py", line 123, in plot_images
    colors = color_list()  # list of colors
  File "D:\Code\YOLOv5\yolov5-master\mynet\utils\plots.py", line 33, in color_list
    return [hex2rgb(h) for h in plt.rcParams['axes.prop_cycle'].by_key()['color']]
  File "D:\Code\YOLOv5\yolov5-master\mynet\utils\plots.py", line 33, in <listcomp>
    return [hex2rgb(h) for h in plt.rcParams['axes.prop_cycle'].by_key()['color']]
  File "D:\Code\YOLOv5\yolov5-master\mynet\utils\plots.py", line 31, in hex2rgb
    return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))
  File "D:\Code\YOLOv5\yolov5-master\mynet\utils\plots.py", line 31, in <genexpr>
    return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))
TypeError: int() can't convert non-string with explicit base

**Comment by glenn-jocher** [comment]
@Liuxuweilxw you can try to set this value at the command line:
```bash
NUMEXPR_MAX_THREADS=16 && python train.py ...
```
