### ISSUE TITLE
Error after model training

### ISSUE THREAD

**Issue by atomrun39** [ultralytics/yolov5#2433]
## ❔Question
After training my model, what is the reason for the following error?

```
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     98/99     0.83G   0.03993   0.07117  0.000314    0.1114        87       640: 100%|██████████| 800/800 [09:39<00:00,  1.38it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 49/49 [00:21<00:00,  2.31it/s]
                 all         387    1.49e+03       0.734        0.67       0.663       0.293

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     99/99     0.83G      0.04   0.06952 0.0003226    0.1098        39       640: 100%|██████████| 800/800 [09:38<00:00,  1.38it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 49/49 [00:21<00:00,  2.30it/s]
                 all         387    1.49e+03       0.685       0.689        0.67       0.302
                  01         387    1.38e+03       0.578       0.582       0.553       0.208
                  02         387         115       0.792       0.797       0.787       0.396
Traceback (most recent call last):
  File "/home/jiaoda/PycharmProjects/yolov5/train.py", line 530, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "/home/jiaoda/PycharmProjects/yolov5/train.py", line 405, in train
    strip_optimizer(f)
  File "/home/jiaoda/PycharmProjects/yolov5/utils/general.py", line 492, in strip_optimizer
    x['model'].half()  # to FP16
AttributeError: 'tuple' object has no attribute 'half'

Process finished with exit code 1
```

**Comment by glenn-jocher** [comment]
@atomrun39 your code or your models are out of date, please git clone the latest repo, or git pull to update your existing repo, and train again.
