### ISSUE TITLE
error while using torchscript version model: yolov5s.torchscript.pt

### ISSUE THREAD

**Issue by Wilson-inclaims** [ultralytics/yolov5#2513]
Using torchscript version model for yolov5s.pt
After running the export.py, I found the 'yolov5s.torchscript.pt' in 'weights/' folder.
```
(pytorch_latest_p37) ubuntu@ip-172-31-15-63:~/yolo-test/yolov5$ export PYTHONPATH="$PWD" && python models/export.py --weights ./weights/yolov5s.pt --img 640 --batch 1
Namespace(batch_size=1, device='cpu', dynamic=False, grid=False, img_size=[640, 640], weights='./weights/yolov5s.pt')
YOLOv5 🚀 v4.0-138-ged2c742 torch 1.8.0+cu111 CPU

Fusing layers...
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS

Starting TorchScript export with torch 1.8.0+cu111...
/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/jit/_trace.py:940: 
TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. 
Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). 
If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
  _force_outplace,
TorchScript export success, saved as ./weights/yolov5s.torchscript.pt

Starting ONNX export with onnx 1.5.0...
ONNX export failure: Your model ir_version is higher than the checker's.
CoreML export failure: No module named 'coremltools'

Export complete (4.43s). Visualize with https://github.com/lutzroeder/netron.
```

Then I had changed default weights in detect.py 

>  parser.add_argument('--weights', nargs='+', type=str, default='weights/yolov5s.torchscript.pt', help='model.pt path(s)')

## 🐛 Bug
When I run the detect.py, there are issue like the bellow.

```
(pytorch_latest_p37) ubuntu@ip-172-31-15-63:~/yolo-test/yolov5$ python detect.py  --source data/videos/sample_video.mp4
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='data/videos/sample_video.mp4', update=False, view_img=False, weights='weights/yolov5s.torchscript.pt')
YOLOv5 🚀 v4.0-138-ged2c742 torch 1.8.0+cu111 CPU

/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/serialization.py:589: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
Traceback (most recent call last):
  File "detect.py", line 175, in <module>
    detect()
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/ubuntu/yolo-test/yolov5/models/experimental.py", line 119, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/jit/_script.py", line 561, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/jit/_script.py", line 291, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'RecursiveScriptModule' object has no attribute 'get'
```

Is there any way to solve this?

## Environment
This is running on EC2(ubuntu 16.04)
python:    3.7.10
torch version:   1.8.0+cu111
torchvision version:    0.9.0+cu111

**Comment by UNeedCryDear** [comment]
yolov5s.torchscript.pt is for torchlib. If you want to use it in detect.py,please use yolov5s.pt which for pytorch.
