### ISSUE TITLE
Error with drawing rectangle

### ISSUE THREAD

**Issue by ElrondL** [ultralytics/yolov5#2770]
Hi I am using yolov5 on Windows 10, Python 3.9.2 and PyCharm 2021.1 in the Conda Environment, when I run the script for 'Detailed Example' most things are fine but there is an error with the result.save() command

Saved zidane.jpg,Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2021.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/.../PycharmProjects/cnnGantry/main.py", line 37, in <module>
    results.save()  # or .show()
  File "C:\Users\....cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 348, in save
    self.display(save=True, save_dir=save_dir)  # save results
  File "C:\Users\.../.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 325, in display
    plot_one_box(box, img, label=label, color=colors[int(cls) % 10])
  File "C:\Users\.../.cache\torch\hub\ultralytics_yolov5_master\utils\plots.py", line 62, in plot_one_box
    cv2.rectangle(img, c1, c2, color, thickness=tl, lineType=cv2.LINE_AA)
TypeError: argument for rectangle() given by name ('thickness') and position (4)

This is an error with drawing the rectangular boxes in the image to be displayed?

**Comment by ElrondL** [comment]
Tired switching to results.show() and the same error happened

**Comment by ElrondL** [comment]
Solved by replacing cv2.read(img2)... line with

img2 = Image.open('bus.jpg')

**Comment by glenn-jocher** [comment]
@ElrondL thanks for the bug report. We were not able to reproduce your error. Here is a screenshot of copying and pasting the detailed example into a new colab notebook.
<img width="1251" alt="Screenshot 2021-04-12 at 18 12 14" src="https://user-images.githubusercontent.com/26833433/114426847-c23e0980-9bba-11eb-8b66-f00e10b3484c.png">
