### ISSUE TITLE
 Sizes of tensors must match 

### ISSUE THREAD

**Issue by Zumbalamambo** [ultralytics/yolov5#2824]
Multi Threaded Inference is not working with Yolo5.  It throws the following error,

```
  File "/home/zumbala/anaconda3/envs/environment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zumbala/yolov5/models/yolo.py", line 113, in forward
    yi = self.forward_once(xi)[0]  # forward
  File "/home/zumbala/yolov5/models/yolo.py", line 139, in forward_once
    x = m(x)  # run
  File "/home/zumbala/anaconda3/envs/environment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zumbala/yolov5/models/yolo.py", line 54, in forward
    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
RuntimeError: The size of tensor a (68) must match the size of tensor b (56) at non-singleton dimension 3
Exception in thread Thread-112:
Traceback (most recent call last):
  File "/home/zumbala/anaconda3/envs/environment/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/zumbala/anaconda3/envs/environment/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
```

I saw the similar bug in other issue and I used the latest version of this repo. Still the problem persists. How can I fix it?

**Comment by Zumbalamambo** [comment]
Here is the complete log,


```
  File "/home/zumbala/yolov5/models/common.py", line 171, in forward
RuntimeError: Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0)
RuntimeError: Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0)  File "/home/zumbala/yolov5/models/common.py", line 171, in forward

  File "/home/zumbala/yolov5/models/yolo.py", line 113, in forward
        yi = self.forward_once(xi)[0]  # forward    
  File "/home/zumbala/yolov5/models/yolo.py", line 139, in forward_once
x = m(x)  # runreturn self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
RuntimeError:     return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))

    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0)
RuntimeError: RuntimeError  File "/home/zumbala/anaconda3/envs/environment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0): Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0)

    x = m(x)  # run
  File "/home/zumbala/anaconda3/envs/environment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
    result = self.forward(*input, **kwargs)  File "/home/zumbala/yolov5/models/common.py", line 171, in forward

  File "/home/zumbala/yolov5/models/common.py", line 171, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
RuntimeError: Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0)    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))

RuntimeError: Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0)
```

**Comment by glenn-jocher** [comment]
@Zumbalamambo yes this is a known issue in the Detect() layer, though it only affects users trying to run mutliple models on multiple threads simultaneously. A possible fix is here:
https://github.com/ultralytics/yolov5/pull/2120/commits/03fae98d86394fe02804d7e9bc20013311bf5837
