### ISSUE TITLE
Errors when Training with Dataset Artifacts

### ISSUE THREAD

**Issue by michelle-aubin** [ultralytics/yolov5#3057]
## 🐛 Bug
I uploaded my dataset to wandb using log_dataset.py then started training with the _wandb.yaml file that was produced which looks like this:
```
names:
- anomaly
nc: 1
train: wandb-artifact://FOD\train
val: wandb-artifact://FOD\val
```
When training I ran into this error:
```
wandb.errors.CommError: Project michelle-aubin/FOD does not contain artifact: "FOD\train:latest"
```
I figured this had something to do with the backwards slashes in the .yaml file so I changed them to forward slashes and this solved the error.

 Now for the next error, I tried training again and at the end of the first epoch the training crashes with the following error:
```
ValueError: File with name "media\cls.classes.json" already exists at "C:\Users\michelle\AppData\Local\Temp\tmp1tbwugn5\media\cls.classes.json"
```
See below for more detailed output. I tried deleting the artifacts on wandb and my local references to them, then reuploaded the dataset and still ran into the same error.

## To Reproduce (REQUIRED)

Upload a dataset to wandb using log_dataset.py then start training with the produced _wandb.yaml file (I followed [these instructions](https://wandb.ai/cayush/yolov5-dsviz-demo/reports/Object-Detection-with-YOLO-and-Weights-Biases--Vmlldzo0NTgzMjk#using-upload-dataset-script))

Output:
```
Starting training for 30 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
      0/29     3.53G   0.07489   0.03545         0    0.1103        14       480: 100%|█| 818/818 [01:19<00:00, 10.28it
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|█| 103/103 [00:13<00
                 all         818        2928       0.644       0.689       0.688       0.371
Images sizes do not match. This will causes images to be display incorrectly in the UI.
Traceback (most recent call last):
  File "train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 388, in train
    wandb_logger.end_epoch(best_result=best_fitness == fi)
  File "C:\Users\michelle\Documents\metrized-work\object-detection\yolov5\utils\wandb_logging\wandb_utils.py", line 292, in end_epoch
    self.result_artifact.add(train_results, 'result')
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 490, in add
    val = obj.to_json(self)
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\data_types.py", line 1123, in to_json
    table2 = self._ensure_table_in_artifact(self._table2, artifact, 2)
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\data_types.py", line 1100, in _ensure_table_in_artifact
    entry = artifact.add(table, table_name)
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 490, in add
    val = obj.to_json(self)
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\data_types.py", line 544, in to_json
    mapped_row.append(_json_helper(v, artifact))
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\data_types.py", line 135, in _json_helper
    return val.to_json(artifact)
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\sdk\data_types.py", line 1796, in to_json
    classes_entry = artifact.add(self._classes, class_name)
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 510, in add
    with self.new_file(name) as f:
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\michelle\anaconda3\envs\yolov5_env\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 350, in new_file
    raise ValueError(
ValueError: File with name "media\cls.classes.json" already exists at "C:\Users\michelle\AppData\Local\Temp\tmp1tbwugn5\media\cls.classes.json"
```

## Environment

 - OS: Windows 10
 - GPU: RTX 3060 Ti

**Comment by AyushExel** [comment]
@michelle-aubin I'm looking into this. I'll try to reproduce this and get back to you

**Comment by AyushExel** [comment]
@michelle-aubin okay I was able to reproduce this. The path issue can be fixed easily and I'll make a PR for it. 
The 2nd issue seems related to artifacts API which is a windows specific issue. The same commands work in colab and Linux environments. So, you might want to use colab for trying this out and I'll do further investigation into it and update you

**Comment by whitepers** [comment]
solve it?

**Comment by AyushExel** [comment]
@whitepers  are you facing a similar problem?

**Comment by RahulReddy20** [comment]
I am facing a similar problem

wandb: Currently logged in as: rahul20 (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.9
wandb: Syncing run log dataset
wandb:  View project at https://wandb.ai/rahul20/meter_serial_number
wandb:  View run at https://wandb.ai/rahul20/meter_serial_number/runs/ag9qvsgi
wandb: Run data is saved locally in D:\yolov5-master\wandb\run-20220104_202907-ag9qvsgi
wandb: Run `wandb offline` to turn off syncing.

Scanning 'bigdataset_yolo\train.cache' images and labels... 1320 found, 0 missing, 0 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████████████████| 1320/1320 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                       | 0/1 [00:00<?, ?it/s]wandb: Adding directory to artifact (.\bigdataset_yolo\train)... Done. 11.2s
wandb: Adding directory to artifact (.\bigdataset_yolo\train)... Done. 1.0s
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.22s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1320/1320 [00:35<00:00, 37.41it/s]
Traceback (most recent call last):
  File "D:\yolov5-master\utils\loggers\wandb\log_dataset.py", line 27, in <module>
    create_dataset_artifact(opt)
  File "D:\yolov5-master\utils\loggers\wandb\log_dataset.py", line 11, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "D:\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 190, in __init__
    self.data_dict = self.check_and_upload_dataset(opt)
  File "D:\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 203, in check_and_upload_dataset
    config_path = self.log_dataset_artifact(opt.data,
  File "D:\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 345, in log_dataset_artifact
    self.train_artifact = self.create_dataset_table(LoadImagesAndLabels(
  File "D:\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 428, in create_dataset_table
    artifact.add(table, name)
  File "C:\Users\rr010\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 500, in add
    val = obj.to_json(self)
  File "C:\Users\rr010\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 610, in to_json
    mapped_row.append(_json_helper(v, artifact))
  File "C:\Users\rr010\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 105, in _json_helper
    return val.to_json(artifact)
  File "C:\Users\rr010\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 2303, in to_json
    classes_entry = artifact.add(self._classes, class_name)
  File "C:\Users\rr010\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 520, in add
    with self.new_file(name) as f:
  File "C:\Users\rr010\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\rr010\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 359, in new_file
    raise ValueError(
ValueError: File with name "media\classes\280a60a8c7bb6e1c1c8f5f726273ccca_cls.classes.json" already exists at "C:\Users\rr010\AppData\Local\Temp\tmpf3n8h8vj\media\classes\280a60a8c7bb6e1c1c8f5f726273ccca_cls.classes.json"

wandb: Waiting for W&B process to finish, PID 7000... (failed 1). Press ctrl-c to abort syncing.
wandb:
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced log dataset: https://wandb.ai/rahul20/meter_serial_number/runs/ag9qvsgi
wandb: Find logs at: .\wandb\run-20220104_202907-ag9qvsgi\logs\debug.log
wandb:

**Comment by AyushExel** [comment]
@GangstarGang007 Hey, this is something that we're working on fixing. This is a windows specific issue. I'll keep you updated once it is fixed

**Comment by RahulReddy20** [comment]
Ok. Thank you

**Comment by Basuki74** [comment]
I'm facing a similar problem

wandb: Currently logged in as: dwiki74 (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.9
wandb: Syncing run log dataset
wandb:  View project at https://wandb.ai/dwiki74/YOLOPARO
wandb:  View run at https://wandb.ai/dwiki74/YOLOPARO/runs/nbpd3t08
wandb: Run data is saved locally in D:\File download\yolov5-master\wandb\run-20220113_213455-nbpd3t08
wandb: Run `wandb offline` to turn off syncing.

Scanning 'custom_dataset\train' images and labels...241 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 241/241 [00:16<
New cache created: custom_dataset\train.cache
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]wandb: Adding directory to artifact (.\custom_dataset\train)... Done. 4.0s
wandb: Adding directory to artifact (.\custom_dataset\train)... Done. 0.3s
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.32s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 241/241 [00:20<00:00, 11.84it/s]
Traceback (most recent call last):
  File "D:\File download\yolov5-master\utils\loggers\wandb\log_dataset.py", line 27, in <module>
    create_dataset_artifact(opt)
  File "D:\File download\yolov5-master\utils\loggers\wandb\log_dataset.py", line 11, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "D:\File download\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 190, in __init__
    self.data_dict = self.check_and_upload_dataset(opt)
  File "D:\File download\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 203, in check_and_upload_dataset
    config_path = self.log_dataset_artifact(opt.data,
  File "D:\File download\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 345, in log_dataset_artifact
    self.train_artifact = self.create_dataset_table(LoadImagesAndLabels(
  File "D:\File download\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 428, in create_dataset_table
    artifact.add(table, name)
  File "C:\Users\Dwiki\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 500, in add
    val = obj.to_json(self)
  File "C:\Users\Dwiki\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 610, in to_json
    mapped_row.append(_json_helper(v, artifact))
  File "C:\Users\Dwiki\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\data_types.py", line 105, in _json_helper
    return val.to_json(artifact)
  File "C:\Users\Dwiki\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 2303, in to_json
    classes_entry = artifact.add(self._classes, class_name)
  File "C:\Users\Dwiki\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 520, in add
    with self.new_file(name) as f:
  File "C:\Users\Dwiki\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\Dwiki\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 359, in new_file
    raise ValueError(
ValueError: File with name "media\classes\038aa5d7141b654fcbc60515250b6ce4_cls.classes.json" already exists at "C:\Users\Dwiki\AppData\Local\Temp\tmpzr7wgib4\media\classes\038aa5d7141b654fcbc60515250b6ce4_cls.classes.json"

wandb: Waiting for W&B process to finish, PID 14588... (failed 1). Press ctrl-c to abort syncing.
wandb:
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced log dataset: https://wandb.ai/dwiki74/YOLOPARO/runs/nbpd3t08
wandb: Find logs at: .\wandb\run-20220113_213455-nbpd3t08\logs\debug.log
wandb:
