### ISSUE TITLE
Chinese label error, what is the solution

### ISSUE THREAD

**Issue by iss-hui** [ultralytics/yolov5#3141]
Traceback (most recent call last):
  File "train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 64, in train
    data_dict = yaml.safe_load(f)  # data dict
  File "/data/home/scv0479/.conda/envs/iss/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/data/home/scv0479/.conda/envs/iss/lib/python3.7/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/data/home/scv0479/.conda/envs/iss/lib/python3.7/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/data/home/scv0479/.conda/envs/iss/lib/python3.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/data/home/scv0479/.conda/envs/iss/lib/python3.7/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/data/home/scv0479/.conda/envs/iss/lib/python3.7/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/data/home/scv0479/.conda/envs/iss/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 70: invalid start byte

**Comment by glenn-jocher** [comment]
@iss-hui hi, sorry to hear you are encountering errors with Chinese characters. Please use the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem if you can. If we can't reproduce the error ourselves then we can't help you. Thank you!

**Comment by iss-hui** [comment]
Error report after modifying data 'data.yaml' file. Change the document from Chinese to English and there will be no problem

**Comment by glenn-jocher** [comment]
@iss-hui can you share your problem yaml file here?

**Comment by iss-hui** [comment]
train: ../DATA/train/images
val: ../DATA/valid/images

nc: 6
names: ['冰糖葫芦','抹布','手套','竹签','耳机','包装袋']

**Comment by wudashuo** [comment]
Why don't you use English instead? I suppose you want a Chinese-labeled detection video?
Even if the yolov5 project supports Chinese, OpenCV doesn't. So when plotting(putText) on images or video, you cannot use Chinese either.
You can read the images and put text yourself by PIL after you get the detection result by `--save-txt`
