### ISSUE TITLE
Getting Error: No module named 'numpy' while running yolo.py

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3228]
When I am trying to run the yolo.py on linux based environment I get the following error

```
Traceback (most recent call last):
  File "models/yolo.py", line 12, in <module>
    from models.common import *
  File "/home/pi/Desktop/yolov5/models/common.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

@glenn-jocher can you help me know how I can resolve this error in order to successfully run the yolo.py file on my environment

**Comment by yannclaes** [comment]
Could you provide the list of installed packages in your environment?

**Comment by jaskiratsingh2000** [comment]
yes, here you go @yannclaes 

```
libwebpdemux2:armhf
libwebpmux3:armhf
libwebrtc-audio-processing1:armhf
libwildmidi2:armhf
libwnck-common
libwnck22:armhf
libwoff1:armhf
libwrap0:armhf
libx11-6:armhf
libx11-data
libx11-dev:armhf
libx11-xcb1:armhf
libx264-155:armhf
libx264-dev:armhf
libx265-165:armhf
libxapian30:armhf
libxau-dev:armhf
libxau6:armhf
libxaw7:armhf
libxcb-dri2-0:armhf
libxcb-dri3-0:armhf
libxcb-glx0:armhf
libxcb-icccm4:armhf
libxcb-image0:armhf
libxcb-keysyms1:armhf
libxcb-present0:armhf
libxcb-randr0:armhf
libxcb-render-util0:armhf
libxcb-render0:armhf
libxcb-render0-dev:armhf
libxcb-shape0:armhf
libxcb-shm0:armhf
libxcb-shm0-dev:armhf
libxcb-sync1:armhf
libxcb-util0:armhf
libxcb-xfixes0:armhf
libxcb-xinerama0:armhf
libxcb-xkb1:armhf
libxcb-xv0:armhf
libxcb1:armhf
libxcb1-dev:armhf
libxcomposite-dev:armhf
libxcomposite1:armhf
libxcursor-dev:armhf
libxcursor1:armhf
libxdamage-dev:armhf
libxdamage1:armhf
libxdmcp-dev:armhf
libxdmcp6:armhf
libxdot4
libxerces-c3.2:armhf
libxext-dev:armhf
libxext6:armhf
libxfce4util-bin
libxfce4util-common
libxfce4util7:armhf
libxfconf-0-2
libxfixes-dev:armhf
libxfixes3:armhf
libxfont2:armhf
libxft-dev:armhf
libxft2:armhf
libxi-dev:armhf
libxi6:armhf
libxine2-bin
libxine2-dev
libxinerama-dev:armhf
libxinerama1:armhf
libxkbcommon-dev:armhf
libxkbcommon-x11-0:armhf
libxkbcommon0:armhf
libxkbfile1:armhf
libxklavier16:armhf
libxml-commons-resolver1.1-java
libxml2:armhf
libxml2-dev:armhf
libxml2-utils
libxmu6:armhf
libxmuu1:armhf
libxpm4:armhf
libxrandr-dev:armhf
libxrandr2:armhf
libxrender-dev:armhf
libxrender1:armhf
libxres1:armhf
libxshmfence1:armhf
libxslt1.1:armhf
libxss-dev:armhf
libxss1:armhf
libxt-dev:armhf
libxt6:armhf
libxtables12:armhf
libxtst-dev:armhf
libxtst6:armhf
libxv1:armhf
libxvidcore-dev:armhf
libxvidcore4:armhf
libxxf86dga1:armhf
libxxf86vm1:armhf
libyaml-0-2:armhf
libzbar0:armhf
libzmq5:armhf
libzstd1:armhf
libzvbi-common
libzvbi0:armhf
lightdm
lightdm-gtk-greeter
linux-base
linux-libc-dev:armhf
locales
login
logrotate
lsb-base
lsb-release
lsof
lua5.1
luajit
lxappearance
lxappearance-obconf
lxde
lxde-common
lxde-core
lxde-icon-theme
lxhotkey-core
lxhotkey-gtk
lxinput
lxmenu-data
lxpanel
lxpanel-data
lxplug-bluetooth
lxplug-cputemp
lxplug-ejecter
lxplug-network
lxplug-ptbatt
lxplug-volume
lxpolkit
lxrandr
lxsession
lxsession-data
lxsession-edit
lxsession-logout
lxtask
lxterminal
m4
make
man-db
manpages
manpages-dev
mariadb-common
mawk
menu-xdg
mesa-va-drivers:armhf
mesa-vdpau-drivers:armhf
mime-support
minecraft-pi
mount
mousepad
mu-editor
multiarch-support
mypy
mysql-common
nano
ncdu
ncurses-base
ncurses-bin
ncurses-term
net-tools
netbase
netcat-openbsd
netcat-traditional
nfs-common
node-abbrev
node-ajv
node-ansi
node-ansi-align
node-ansi-regex
node-ansi-styles
node-ansistyles
node-aproba
node-archy
node-are-we-there-yet
node-asn1
node-assert-plus
node-asynckit
node-aws-sign2
node-aws4
node-balanced-match
node-bcrypt-pbkdf
node-bluebird
node-boxen
node-brace-expansion
node-builtin-modules
node-builtins
node-cacache
node-call-limit
node-camelcase
node-caseless
node-chalk
node-chownr
node-cli-boxes
node-cliui
node-clone
node-co
node-color-convert
node-color-name
node-combined-stream
node-concat-map
node-concat-stream
node-config-chain
node-console-control-strings
node-copy-concurrently
node-core-util-is
node-cross-spawn
node-cyclist
node-dashdash
node-decamelize
node-decompress-response
node-deep-extend
node-defaults
node-delayed-stream
node-delegates
node-detect-indent
node-detect-newline
node-duplexer3
node-duplexify
node-ecc-jsbn
node-editor
node-encoding
node-end-of-stream
node-errno
node-escape-string-regexp
node-execa
node-extend
node-extsprintf
node-find-up
node-flush-write-stream
node-forever-agent
node-form-data
node-from2
node-fs-vacuum
node-fs-write-stream-atomic
node-fs.realpath
node-gauge
node-get-caller-file
node-get-stream
node-getpass
node-glob
node-got
node-graceful-fs
node-gyp
node-har-schema
node-har-validator
node-has-flag
node-has-symbol-support-x
node-has-to-string-tag-x
node-has-unicode
node-hosted-git-info
node-http-signature
node-iconv-lite
node-iferr
node-import-lazy
node-imurmurhash
node-inflight
node-inherits
node-ini
node-invert-kv
node-is-builtin-module
node-is-npm
node-is-object
node-is-plain-obj
node-is-retry-allowed
node-is-stream
node-is-typedarray
node-isarray
node-isexe
node-isstream
node-isurl
node-jsbn
node-json-parse-better-errors
node-json-schema
node-json-stable-stringify
node-json-stringify-safe
node-jsonify
node-jsonparse
node-jsonstream
node-jsprim
node-latest-version
node-lazy-property
node-lcid
node-libnpx
node-locate-path
node-lockfile
node-lowercase-keys
node-lru-cache
node-mem
node-mime-types
node-mimic-fn
node-mimic-response
node-minimatch
node-minimist
node-mississippi
node-mkdirp
node-move-concurrently
node-mute-stream
node-node-uuid
node-nopt
node-normalize-package-data
node-npm-package-arg
node-npm-run-path
node-npmlog
node-oauth-sign
node-object-assign
node-once
node-opener
node-os-locale
node-osenv
node-p-cancelable
node-p-finally
node-p-limit
node-p-locate
node-p-timeout
node-package-json
node-parallel-transform
node-path-exists
node-path-is-absolute
node-path-is-inside
node-performance-now
node-prepend-http
node-process-nextick-args
node-promise-inflight
node-promzard
node-proto-list
node-prr
node-pump
node-pumpify
node-punycode
node-qs
node-qw
node-rc
node-read
node-read-package-json
node-readable-stream
node-registry-auth-token
node-registry-url
node-request
node-require-directory
node-require-main-filename
node-resolve-from
node-retry
node-rimraf
node-run-queue
node-safe-buffer
node-semver
node-semver-diff
node-set-blocking
node-sha
node-shebang-command
node-shebang-regex
node-signal-exit
node-slash
node-slide
node-sorted-object
node-spdx-correct
node-spdx-expression-parse
node-spdx-license-ids
node-sshpk
node-ssri
node-stream-each
node-stream-iterate
node-stream-shift
node-string-decoder
node-string-width
node-strip-ansi
node-strip-eof
node-strip-json-comments
node-supports-color
node-tar
node-term-size
node-text-table
node-through
node-through2
node-timed-out
node-tough-cookie
node-tunnel-agent
node-tweetnacl
node-typedarray
node-uid-number
node-unique-filename
node-unpipe
node-url-parse-lax
node-url-to-options
node-util-deprecate
node-uuid
node-validate-npm-package-license
node-validate-npm-package-name
node-verror
node-wcwidth.js
node-which
node-which-module
node-wide-align
node-widest-line
node-wrap-ansi
node-wrappy
node-write-file-atomic
node-xdg-basedir
node-xtend
node-y18n
node-yallist
node-yargs
node-yargs-parser
nodejs
nodejs-doc
nodered
npm
ntfs-3g
nuscratch
obconf
ocl-icd-libopencl1:armhf
odbcinst
odbcinst1debian2:armhf
omxplayer
openbox
openbox-lxde-session
openjdk-11-jdk:armhf
openjdk-11-jdk-headless:armhf
openjdk-11-jre:armhf
openjdk-11-jre-headless:armhf
openjfx
openjfx-source
openmpi-bin
openmpi-common
openresolv
openssh-client
openssh-server
openssh-sftp-server
openssl
packagekit
pango1.0-tools
parted
passwd
patch
paxctld
pciutils
pcmanfm
perl
perl-base
perl-modules-5.28
pi-bluetooth
pi-greeter
pi-language-support
pi-package
pi-package-data
pi-package-session
piclone
pigpio
pigpio-tools
pigpiod
pigz
pimixer
pinentry-curses
pipanel
pishutdown
piwiz
pixflat-icons
pkg-config
plymouth
plymouth-label
plymouth-themes
po-debconf
point-rpi
policykit-1
poppler-data
pprompt
procps
proj-bin
proj-data
protobuf-compiler
psmisc
publicsuffix
pyflakes
pyflakes3
pylint3
pypy
pypy-lib:armhf
python
python-all
python-all-dev
python-apt-common
python-asn1crypto
python-atomicwrites
python-attr
python-automationhat
python-backports.functools-lru-cache
python-blinker
python-blinkt
python-buttonshim
python-cairo:armhf
python-cap1xxx
python-certifi
python-cffi-backend
python-chardet
python-click
python-cloudpickle
python-colorama
python-colorzero
python-configparser
python-cookies
python-crypto
python-cryptography
python-cycler
python-dateutil
python-dbus
python-decorator
python-dev
python-drumhat
python-entrypoints
python-enum34
python-envirophat
python-explorerhat
python-flask
python-fourletterphat
python-funcsigs
python-future
python-games
python-gdal
python-gi
python-git
python-gitdb
python-gobject-2
python-gpiozero
python-gtk2
python-idna
python-ipaddress
python-itsdangerous
python-jinja2
python-joblib
python-jwt
python-keyring
python-keyrings.alt
python-kiwisolver
python-lz4
python-markupsafe
python-matplotlib
python-matplotlib-data
python-matplotlib2-data
python-microdotphat
python-minecraftpi
python-minimal
python-mock
python-more-itertools
python-mote
python-motephat
python-networkx
python-nose
python-numpy
python-oauthlib
python-olefile
python-opencv
python-openssl
python-pantilthat
python-pathlib2
python-pbr
python-phatbeat
python-pianohat
python-picamera
python-picraft
python-piglow
python-pigpio
python-pil:armhf
python-pip
python-pip-whl
python-pkg-resources
python-pluggy
python-psutil
python-py
python-pyflakes
python-pygame
python-pygraphviz
python-pyinotify
python-pyparsing
python-pytest
python-pywt
python-qt4
python-rainbowhat
python-requests
python-requests-oauthlib
python-responses
python-rpi.gpio
python-rtimulib
python-scandir
python-scipy
python-scrollphat
python-scrollphathd
python-secretstorage
python-sense-emu
python-sense-emu-doc
python-sense-hat
python-serial
python-setuptools
python-simplejson
python-sip
python-six
python-skimage
python-skimage-lib
python-sklearn
python-sklearn-lib
python-skywriter
python-smbus:armhf
python-smmap
python-sn3218
python-spidev
python-subprocess32
python-talloc:armhf
python-tk
python-touchphat
python-twython
python-tz
python-unicornhathd
python-urllib3
python-werkzeug
python-wheel
python-xdg
python-yaml
python2
python2-dev
python2-minimal
python2.7
python2.7-dev
python2.7-minimal
python3
python3-appdirs
python3-apt
python3-asn1crypto
python3-astroid
python3-asttokens
python3-automationhat
python3-blinker
python3-blinkt
python3-bs4
python3-buttonshim
python3-cairo:armhf
python3-cap1xxx
python3-certifi
python3-cffi-backend
python3-chardet
python3-click
python3-colorama
python3-colorzero
python3-cookies
python3-crypto
python3-cryptography
python3-cycler
python3-dateutil
python3-dbus
python3-debconf
python3-decorator
python3-dev
python3-distutils
python3-docutils
python3-drumhat
python3-entrypoints
python3-envirophat
python3-explorerhat
python3-flask
python3-fourletterphat
python3-gi
python3-gi-cairo
python3-gpiozero
python3-guizero
python3-html5lib
python3-idna
python3-ipykernel
python3-ipython
python3-ipython-genutils
python3-isort
python3-itsdangerous
python3-jedi
python3-jinja2
python3-jupyter-client
python3-jupyter-core
python3-jwt
python3-keyring
python3-keyrings.alt
python3-kiwisolver
python3-lazy-object-proxy
python3-lib2to3
python3-linecache2
python3-logilab-common
python3-lxml:armhf
python3-markupsafe
python3-matplotlib
python3-mccabe
python3-microdotphat
python3-minecraftpi
python3-minimal
python3-mote
python3-motephat
python3-mypy
python3-mypy-extensions
python3-nudatus
python3-numpy
python3-oauthlib
python3-olefile
python3-openssl
python3-pantilthat
python3-parso
python3-pbr
python3-pexpect
python3-pgzero
python3-phatbeat
python3-pianohat
python3-picamera
python3-pickleshare
python3-picraft
python3-piglow
python3-pigpio
python3-pil:armhf
python3-pil.imagetk:armhf
python3-pip
python3-pkg-resources
python3-prompt-toolkit
python3-psutil
python3-ptyprocess
python3-pycodestyle
python3-pyflakes
python3-pygame
python3-pygments
python3-pyinotify
python3-pyparsing
python3-pyqt5
python3-pyqt5.qsci
python3-pyqt5.qtchart:armhf
python3-pyqt5.qtserialport
python3-pyqt5.qtsvg
python3-qtconsole
python3-rainbowhat
python3-requests
python3-requests-oauthlib
python3-responses
python3-roman
python3-rpi.gpio
python3-rtimulib
python3-scrollphat
python3-scrollphathd
python3-secretstorage
python3-semver
python3-send2trash
python3-sense-emu
python3-sense-hat
python3-serial
python3-setuptools
python3-simplegeneric
python3-simplejson
python3-sip
python3-six
python3-skywriter
python3-smbus:armhf
python3-sn3218
python3-soupsieve
python3-spidev
python3-testresources
python3-tk:armhf
python3-tornado
python3-touchphat
python3-traceback2
python3-traitlets
python3-twython
python3-typed-ast
python3-uflash
python3-unicornhathd
python3-unittest2
python3-urllib3
python3-venv
python3-wcwidth
python3-webencodings
python3-werkzeug
python3-wheel
python3-wrapt
python3-xdg
python3-zmq
python3.7
python3.7-dev
python3.7-minimal
python3.7-venv
qdbus
qjackctl
qpdfview
qpdfview-djvu-plugin
qpdfview-ps-plugin
qpdfview-translations
qt-at-spi:armhf
qt5-default:armhf
qt5-gtk-platformtheme:armhf
qt5-qmake:armhf
qt5-qmake-bin
qt5-style-plugins:armhf
qt5ct
qtbase5-dev:armhf
qtbase5-dev-tools
qtchooser
qtcore4-l10n
qttranslations5-l10n
rake
raspberrypi-artwork
raspberrypi-bootloader
raspberrypi-kernel
raspberrypi-net-mods
raspberrypi-sys-mods
raspberrypi-ui-mods
raspbian-archive-keyring
raspi-config
raspi-copies-and-fills
raspi-gpio
rc-gui
read-edid
readline-common
realvnc-vnc-server
realvnc-vnc-viewer
rfkill
rng-tools
rp-prefapps
rpcbind
rpd-plym-splash
rpd-wallpaper
rpi-chromium-mods
rpi-eeprom
rpi-eeprom-images
rpi-update
rsync
rsyslog
ruby
ruby-activesupport
ruby-afm
ruby-ascii85
ruby-atomic
ruby-coderay
ruby-concurrent
ruby-did-you-mean
ruby-ffi
ruby-hamster
ruby-hashery
ruby-i18n
ruby-kramdown
ruby-memoist
ruby-minitest
ruby-multi-json
ruby-net-telnet
ruby-oj:armhf
ruby-pdf-core
ruby-pdf-reader
ruby-power-assert
ruby-prawn
ruby-prawn-table
ruby-rc4
ruby-rouge
ruby-rugged:armhf
ruby-stringex
ruby-test-unit
ruby-thread-safe
ruby-ttfunk
ruby-tzinfo
ruby-wavefile
ruby-xmlrpc
ruby2.5
rubygems-integration
samba-libs:armhf
sc3-plugins-server
scratch
scratch2
scratch3
scrot
sed
sense-emu-tools
sense-hat
sensible-utils
sgml-base
shared-mime-info
smartsim
sonic-pi
sonic-pi-samples
sonic-pi-server
sound-theme-freedesktop
squeak-vm
ssh
ssh-import-id
strace
sudo
supercollider-server
systemd
systemd-sysv
sysvinit-utils
tar
tasksel
tasksel-data
tcl
tcl-dev:armhf
tcl8.6
tcl8.6-dev:armhf
thonny
timgm6mb-soundfont
tk
tk-dev:armhf
tk8.6
tk8.6-blt2.5
tk8.6-dev:armhf
traceroute
tree
triggerhappy
ttf-bitstream-vera
tzdata
ucf
udev
udisks2
unzip
usb-modeswitch
usb-modeswitch-data
usb.ids
usbutils
util-linux
uuid
uuid-dev:armhf
uvcdynctrl
uvcdynctrl-data
v4l-utils
va-driver-all:armhf
vdpau-driver-all:armhf
vim
vim-common
vim-runtime
vim-tiny
vl805fw
vlc
vlc-bin
vlc-data
vlc-l10n
vlc-plugin-base:armhf
vlc-plugin-notify:armhf
vlc-plugin-qt:armhf
vlc-plugin-samba:armhf
vlc-plugin-skins2:armhf
vlc-plugin-video-output:armhf
vlc-plugin-video-splitter:armhf
vlc-plugin-visualization:armhf
wamerican
wayland-protocols
wbritish
wget
whiptail
wireless-regdb
wireless-tools
wolframscript
wpasupplicant
x11-common
x11-utils
x11-xkb-utils
x11-xserver-utils
x11proto-composite-dev
x11proto-core-dev
x11proto-damage-dev
x11proto-dev
x11proto-fixes-dev
x11proto-input-dev
x11proto-randr-dev
x11proto-record-dev
x11proto-scrnsaver-dev
x11proto-xext-dev
x11proto-xinerama-dev
x264
xarchiver
xauth
xcompmgr
xdg-user-dirs
xdg-utils
xfconf
xfonts-100dpi
xfonts-encodings
xfonts-utils
xinit
xinput
xkb-data
xml-core
xorg-sgml-doctools
xsel
xserver-common
xserver-xorg
xserver-xorg-core
xserver-xorg-input-all
xserver-xorg-input-libinput
xserver-xorg-video-fbdev
xserver-xorg-video-fbturbo
xtrans-dev
xxd
xz-utils
yasm
zenity
zenity-common
zip
zlib1g:armhf
zlib1g-dev:armhf
```

**Comment by jaskiratsingh2000** [comment]
@yannclaes Can you let me know exactly what and how to install the specific thing if required.

**Comment by yannclaes** [comment]
I'm not certain of how the repo you cloned relates to your packages, but I would create a virtual environment (conda or virtualenv) and then run these three lines in your virtual environment:

```
$ git clone https://github.com/ultralytics/yolov5  # clone repo
$ cd yolov5
$ pip install -r requirements.txt  # install
```

**Comment by jaskiratsingh2000** [comment]
@yannclaes I am actually running this on Raspberry Pi and I had ran the same commands as you mentioned but I am getting error as mentioned.
Can you help me resolve this in another way?

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher Can you help here please?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 your error message appears self-explanatory, you don't have numpy installed.

**Comment by maciej-autobon** [comment]
@jaskiratsingh2000 have you tried the above suggestion: https://github.com/ultralytics/yolov5/issues/3228#issuecomment-843286186
?
If you're getting an error, please paste it here.
