### ISSUE TITLE
Error running custom model on android

### ISSUE THREAD

**Issue by p-caixeta** [ultralytics/yolov5#3539]
## ❔Question

I trained a custom yolov5s model (following https://github.com/ultralytics/yolov5) and converted the weights to tflite-fp16 using https://github.com/zldrobit/yolov5/blob/tf-android/models/tf.py :

`PYTHONPATH=. python models/tf.py --weights runs/train/exp/weights/best.pt --cfg models/yolov5s.yaml --img 640`

When I imported this project to Android Studio (4.2.1 for windows 10 x64) and tested it with the example model (downloaded with https://github.com/zldrobit/yolov5/weights/download_weights.sh) and converted to tflite-fp16, it ran just fine (phone model: Samsung A12 - https://www.samsung.com/us/mobile/phones/galaxy-a/galaxy-a12-unlocked-sm-a125uzkdxaa/)

But when I changed the model, labelmap and labels.txt in the assets folder to my own, and the image size accordingly, I got this error:

`E/tensorflow: CameraActivity: Exception!
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at org.tensorflow.lite.examples.detection.tflite.YoloV5Classifier.create(YoloV5Classifier.java:78)
        at org.tensorflow.lite.examples.detection.tflite.DetectorFactory.getDetector(DetectorFactory.java:49)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:97)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:273)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8173)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

Obs: I tested the original weights (best.pt) from my training in my computer, also worked; as well as the converted tflite model.

## Additional context
Android Gradle Plugin Version: 3.5.0
Gradle Version: 5.4.1
Java SDK: 1.8.0_291
Compile SDK version: 28

**Comment by zldrobit** [comment]
Did you change`output_width` according to the new/old inputSize ratio?
You could verify the fp16 tflite model by running `python` inference on a PC:
```
python3 detect.py --weights weights/best-fp16.tflite --img SIZE
```
and change `SIZE` according to your model input resolution.

**Comment by p-caixeta** [comment]
> Did you change`output_width` according to the new/old inputSize ratio?

Do you mean the `--input_size` flag on tf.py? If so, yes, I set it to 640 (the same picture size my yolov5 model was trained on)

Quick side question: the `--input_size` and `--img` flags when calling tf.py are the same thing?

**Comment by zldrobit** [comment]
I checked there is no `--input_size` in `tf.py`.
If you are using 640x640 input resolution, the `output_width` numbers have to be doubled.
The original numbers are comliant to 320x320 resolution.
Plz also check the anchor sizes as described in [Step Four](https://github.com/zldrobit/yolov5#4-put-tflite-models-in-assets-folder-of-android-project-and-change) in `README.md`.
