### ISSUE TITLE
test.py is not able to fetch the requirements

### ISSUE THREAD

**Issue by jaskiratsingh2000** [ultralytics/yolov5#3623]
## To Reproduce (REQUIRED)

Input:
```
python3 test.py --data coco128.yaml --weight yolov5s.pt

```

Output:
```
Namespace(augment=False, batch_size=32, conf_thres=0.001, data='./data/coco128.yaml', device='', exist_ok=False, half=False, imgsz=640, iou_thres=0.6, name='exp', project='runs/test', save_conf=False, save_hybrid=False, save_json=False, save_txt=False, single_cls=False, task='val', verbose=False, weights=['yolov5s.pt'])
requirements: opencv-python>=4.1.2 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install opencv-python>=4.1.2' skipped (offline)
requirements: torch>=1.7.0 not found and is required by YOLOv5, attempting auto-update...
ERROR: Could not find a version that satisfies the requirement torch>=1.7.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.7.0
requirements: Command 'pip install 'torch>=1.7.0'' returned non-zero exit status 1.
requirements: torchvision>=0.8.1 not found and is required by YOLOv5, attempting auto-update...
ERROR: Could not find a version that satisfies the requirement torchvision>=0.8.1 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)
ERROR: No matching distribution found for torchvision>=0.8.1
requirements: Command 'pip install 'torchvision>=0.8.1'' returned non-zero exit status 1.
YOLOv5 🚀 v5.0-190-g4c5d9bf torch 1.7.0a0+e85d494 CPU

Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt to yolov5s.pt...
100%|███████████████████████| 14.1M/14.1M [00:01<00:00, 11.5MB/s]

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients

WARNING: Dataset not found, nonexistent paths: ['/home/ubuntu/Desktop/coco128/images/train2017']
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip ...
100%|███████████████████████| 21.1M/21.1M [00:03<00:00, 6.56MB/s]
Dataset autodownload success

val: Scanning '../coco128/labels/train2017' images and labels...1
val: New cache created: ../coco128/labels/train2017.cache
               Class     Images     Labels          P          R 
Traceback (most recent call last):
  File "test.py", line 326, in <module>
    test(**vars(opt))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 106, in test
    for batch_i, (img, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/ubuntu/Desktop/yolov5/utils/datasets.py", line 111, in __iter__
    yield next(self.iterator)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/Desktop/yolov5/utils/datasets.py", line 568, in __getitem__
    labels_out[:, 1:] = torch.from_numpy(labels)
RuntimeError: PyTorch was compiled without NumPy support

```

## Expected behavior
I expected to receive the accuracy metrics by running this command which didn't happen

## Environment

 - OS: [Ubuntu 20.04] on Raspberry Pi 4

## Additional Information

This is to let you know that I have already installed all the requirements needed for running the Yolov5. The other command reworking totally fine and able to fetch the requirements whereas running this command resulting in errors.

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 your command runs correctly. We are unable to reproduce your error, therefore there is no action for us to take on this issue.

<img width="1524" alt="Screen Shot 2021-06-15 at 2 55 50 PM" src="https://user-images.githubusercontent.com/26833433/122056402-d7692b80-cde9-11eb-97f8-8c9e19f7a50f.png">

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 also we have no Raspberry Pi hardware ourselves, but we have an open competition for export to R Pi here:

## <div align="center">Compete and Win</div>

We are super excited about our first-ever Ultralytics YOLOv5 🚀 EXPORT Competition with **$10,000** in cash prizes!  

<div align="center">
<a href="https://github.com/ultralytics/yolov5/discussions/3213">
    <img src="https://github.com/ultralytics/yolov5/releases/download/v1.0/banner-export-competition.png"/>
</a>
</div>

**Comment by jaskiratsingh2000** [comment]
@glenn-jocher can you please test this on Raspberry Pi if you have any handy? That would really be of great help. 

Another thing - where does it shows accuracy for different YAML files? If I change the parameters in yolov5 will these metric gets affected?

**Comment by glenn-jocher** [comment]
@jaskiratsingh2000 we have no R Pi hardware.

Yes, test.py outputs are naturally a function of the arguments you pass it.
