### ISSUE TITLE
training error：AttributeError: _cache

### ISSUE THREAD

**Issue by LiangYong1216** [ultralytics/yolov5#3776]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
when i training my own datasets, The program is loading the data set consistently about 99%,And it doesn't go on.Throw memory error. could you help me?   thank you!!

## To Reproduce (REQUIRED)

Input:  train
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "F:\Model_of_others\YOLOV5-V5.0\yolov5-master\utils\datasets.py", line 18, in <module>
    import torch
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\__init__.py", line 447, in <module>
    from .tensor import Tensor
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\tensor.py", line 13, in <module>
    from torch.overrides import (
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 939, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
MemoryError
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "F:\Model_of_others\YOLOV5-V5.0\yolov5-master\utils\datasets.py", line 18, in <module>
    import torch
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\__init__.py", line 561, in <module>
    from .functional import *
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\nn\modules\__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\nn\modules\linear.py", line 6, in <module>
    from .. import functional as F
  File "C:\Users\86180\.conda\envs\YOLOV5-V5.0\lib\site-packages\torch\nn\functional.py", line 9, in <module>
    from torch._torch_docs import reproducibility_notes, tf32_notes
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 939, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
MemoryError
train: Scanning 'data\coco\labels\train2017' images and labels...7612 found, 0 missing, 0 empty, 0 corrupted:  99%|█████████▉| 7592/7636 [00:20<00:00, 3464.49it/s]
```

## Expected behavior
start training !

## Environment

 - OS: [e.g. windows10]
 - GPU [e.g. 1660superTi]

**Comment by glenn-jocher** [comment]
@LiangYong1216 MemoryError seems to indicate your system is out of memory.
