### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED 

### ISSUE THREAD

**Issue by amananand97** [ultralytics/yolov5#3808]
## 🐛 Bug
Not able to execute train.py on AWS SageMaker.

Input:
```
python3 train.py --img 640 --batch 64 --epochs 100 --data '../data.yaml' --cfg ./models/yolov5x.yaml --weights '' --name yolov5x_results  --cache
```

Output:
```
Traceback (most recent call last):
  File "train.py", line 519, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 300, in train
    scaler.scale(loss).backward()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([8, 64, 80, 80], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(64, 64, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_HALF
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f6e34271950
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 64, 80, 80, 
    strideA = 409600, 6400, 80, 1, 
output: TensorDescriptor 0x7f6e3423cf40
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 64, 80, 80, 
    strideA = 409600, 6400, 80, 1, 
weight: FilterDescriptor 0x7f6e3424cc40
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 64, 3, 3, 
Pointer addresses: 
    input: 0x7dd2180000
    output: 0x7ee4220000
    weight: 0x7d1ed4a000
Additional pointer addresses: 
    grad_output: 0x7ee4220000
    grad_weight: 0x7d1ed4a000
Backward filter algorithm: 5

```

## Expected behavior
It should complete the training and provide model weights.

## Environment
<img width="2937" alt="Screenshot 2021-06-28 at 3 09 16 pm" src="https://user-images.githubusercontent.com/35375157/123650985-04263580-d823-11eb-8d13-95750e965b98.png">
<img width="945" alt="Screenshot 2021-06-28 at 3 10 29 pm" src="https://user-images.githubusercontent.com/35375157/123650997-06888f80-d823-11eb-96b7-0d4b080336ba.png">

 - OS : Ubuntu
 - GPU : Tesla K80 on AWS SageMaker
 - Yolov5 : Version 4.0 ( As SageMaker only provide Kernel for python3.7)

**Comment by glenn-jocher** [comment]
@amananand97 it looks like both your torch and YOLOv5 versions are out of date. Naturally you should update both to the latest.

**Comment by amananand97** [comment]
@glenn-jocher I am using the older version of YOLOv5 because SageMaker does not support the current version, it only supports (Python 3.7). SageMaker already have an optimised pytorch kernel on Jupiter Notebooks.

Is it possible to fix the above error ?

**Comment by glenn-jocher** [comment]
@amananand97 current version of YOLOv5 requires python >= 3.6.0.

We do not debug out of date code.
