### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [32, 12, 3, 3], expected input[4, 4, 208, 208] to have 12 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by wantaoliu** [ultralytics/yolov5#3853]
## ❔Question
My image has only a single band.using `yolov5s.yaml`,I make the shape of image from(416,416) to (416,416,1)
 `bands, im_width, im_height, im_proj, im_geotrans, img, dataset = read_img(path)`
`img = img[:, :,np.newaxis]`
but I met the problem,how to solute the problem,Thanks.
## Additional context
Traceback (most recent call last):
  File "E:/Project/YOLO/yolov5-4.0/train.py", line 296, in train
    pred = model(imgs)  # forward
  File "D:\SoftWare\AnacondaNew\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Project\YOLO\yolov5-4.0\models\yolo.py", line 119, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\Project\YOLO\yolov5-4.0\models\yolo.py", line 135, in forward_once
    x = m(x)  # run
  File "D:\SoftWare\AnacondaNew\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Project\YOLO\yolov5-4.0\models\common.py", line 111, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "D:\SoftWare\AnacondaNew\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Project\YOLO\yolov5-4.0\models\common.py", line 36, in forward
    return self.act(self.bn(self.conv(x)))
  File "D:\SoftWare\AnacondaNew\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\SoftWare\AnacondaNew\envs\yolo\lib\site-packages\torch\nn\modules\conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "D:\SoftWare\AnacondaNew\envs\yolo\lib\site-packages\torch\nn\modules\conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 12, 3, 3], expected input[4, 4, 208, 208] to have 12 channels, but got 4 channels instead
python-BaseException

**Comment by glenn-jocher** [comment]
@wantaoliu YOLOv5 expects 3-ch images. Greyscale images are automatically loaded as 3-ch images by the YOLOv5 dataloaders.
