### ISSUE TITLE
Jetson Nano experiment problem

### ISSUE THREAD

**Issue by krambriw** [ultralytics/yolov5#3878]
## ❔Question
I have a small problem getting torch and torchvision to like each other when experimenting with YOLO V5 and wonder if you could have a look what I'm eventually doing wrong? Grateful for any help!
Best regards, Walter

## Additional context
HaveJetson Nano, seems I have Jetpack 4.4 installed

```
wk@jn227:~$ dpkg-query --show nvidia-l4t-core
nvidia-l4t-core 32.4.4-20201016124427

```
Installed succesfully:
- torch-1.9.0-cp36-cp36m-linux_aarch64.whl
- torchvision 0.10.0

```
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
>>> torchvision.__version__
'0.10.0'
>>> import torch
>>> torch.__version__
'1.9.0'
>>> torch.cuda.is_available()
True
>>>

```

But when trying to run yolov5 demo.py I get error message they are not compatible!! But they should be if I understand correctly. One thing noted makes me worried, it seems to think I have a Tegra X1 but I just have a Jetson Nano :(

YOLOv5 🚀 2021-7-4 torch 1.9.0 CUDA:0 (NVIDIA Tegra X1, 3964.12109375MB)

```
wk@jn227:~/yolov5$ python3 demo.py
Using cache found in /home/wk/.cache/torch/hub/ultralytics_yolov5_master
Fusing layers...
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /media/nvidia/NVME/pytorch/pytorch-v1.9.0/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Adding AutoShape...
YOLOv5 🚀 2021-7-4 torch 1.9.0 CUDA:0 (NVIDIA Tegra X1, 3964.12109375MB)

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    results = model(img)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/wk/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 281, in forward
    y = non_max_suppression(y, self.conf, iou_thres=self.iou, classes=self.classes, max_det=self.max_det)  # NMS
  File "/home/wk/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py", line 547, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py", line 34, in nms
    _assert_has_ops()
  File "/usr/local/lib/python3.6/dist-packages/torchvision/extension.py", line 63, in _assert_has_ops
    "Couldn't load custom C++ ops. This can happen if your PyTorch and "
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
wk@jn227:~/yolov5$


```

**Comment by knghyunwoo** [comment]
Got same problem...
Have you solved it?

**Comment by krambriw** [comment]
No, currently sticked to YOLOV4

**Comment by glenn-jocher** [comment]
@krambriw sorry, we don't have official Jetson tutorials yet, but I'd note that the YOLOv5 GPU definition is correct, Jetson Nanos are equipped with Tegra X1 GPUs.

**Comment by glenn-jocher** [comment]
@krambriw for torch torchvision compatibility matrix see https://pypi.org/project/torchvision/
