### ISSUE TITLE
a problem about torch.hub.load

### ISSUE THREAD

**Issue by goldentimecoolk** [ultralytics/yolov5#3910]
hello, I just succeed installing the environment with `requirement.txt`. But when I tried the command `model = torch.hub.load('ultralytics/yolov5', 'yolov5s')`, it was always showing **Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\Administrator/.cache\torch\hub\master.zip**. Several minutes later, it shows info as 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\site-packages\torch\hub.py", line 362, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\site-packages\torch\hub.py", line 169, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\site-packages\torch\hub.py", line 419, in download_url_to_file
    u = urlopen(req)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\urllib\request.py", line 1358, in do_open
    r = h.getresponse()
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```

Then, I tried to download the package of `"https://github.com/ultralytics/yolov5/archive/master.zip"` to `C:\Users\Administrator/.cache\torch\hub`, it didn't work either. 

Please help me, thank you.

---

sometims, it shows info like 
```
>>> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\Administrator/.cache\torch\hub\master.zip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\site-packages\torch\hub.py", line 362, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\site-packages\torch\hub.py", line 171, in _get_cache_or_reload
    with zipfile.ZipFile(cached_file) as cached_zipfile:
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by goldentimecoolk** [comment]
problem has been solved!
The key is to permit `python.exe` to communicate through windows defender firewall.
Details could refer to [here](https://www.cnblogs.com/si-dian/p/12196931.html) (in Chinese)
