### ISSUE TITLE
AssertionError: Image Not Found

### ISSUE THREAD

**Issue by Hurri-cane** [ultralytics/yolov5#4010]
Hi，When I use YOLOv5 to train my own data set, I get the following error：

## To Reproduce (REQUIRED)
intput::
```
python /home/sha/PycharmProjects/Object_Detection/yolov5-v4.0/yolov5-4.0_car_part/train.py

```

output:
```
Using torch 1.8.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2070 SUPER, 7979.1875MB)
                        CUDA:1 (NVIDIA GeForce RTX 2070 SUPER, 7982.3125MB)


Namespace(weights='weights/yolov5s.pt', cfg='', data='data/car_part.yaml', hyp='data/hyp.scratch.yaml', epochs=300, batch_size=128, img_size=[320, 320], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=False, image_weights=False, device='0,1', multi_scale=False, single_cls=False, adam=False, sync_bn=False, local_rank=-1, log_imgs=16, log_artifacts=False, workers=10, project='runs/train', name='exp', exist_ok=False, quad=False, world_size=1, global_rank=-1, save_dir='runs/train/exp2', total_batch_size=128)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}
Overriding model.yaml nc=80 with nc=4

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     24273  models.yolo.Detect                      [4, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7071633 parameters, 7071633 gradients, 16.4 GFLOPS

Transferred 356/362 items from weights/yolov5s.pt
Scaled weight_decay = 0.001
Optimizer groups: 62 .bias, 62 conv.weight, 59 other
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels' for images and labels... 1480 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 1480/1480 [00:01<00:00, 1262.13it/s]
New cache created: /media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 1480 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 1480/1480 [00:00<?, ?it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<00:00, 1901.25it/s]
New cache created: /media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]
Plotting labels... 
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:00<?, ?it/s]

Analyzing anchors... anchors/target = 5.34, Best Possible Recall (BPR) = 0.9998
Image sizes 320 train, 320 test
Using 10 dataloader workers
Logging results to runs/train/exp2
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     0/299      2.7G    0.1242    0.0279   0.04514    0.1973       503       320: 100%|██████████| 12/12 [00:07<00:00,  1.56it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:01<00:00,  1.04it/s]
                 all         165         583           0           0     0.00046    6.21e-05

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     1/299     3.21G    0.1134   0.03386   0.04058    0.1879       501       320: 100%|██████████| 12/12 [00:02<00:00,  4.35it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  3.13it/s]
                 all         165         583           0           0     0.00355    0.000557

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     2/299     3.21G    0.1034   0.03729   0.03715    0.1778       473       320: 100%|██████████| 12/12 [00:02<00:00,  4.31it/s]
Scanning '/media/sha/Disk_1/Data_Set/data_KIITI_car_part/labels.cache' for images and labels... 165 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 165/165 [00:19<?, ?it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]
                 all         165         583        0.25     0.00111      0.0334     0.00591


................



     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    49/299     3.21G   0.04203   0.02288  0.002801   0.06771       895       320:  58%|█████▊    | 7/12 [00:01<00:01,  4.23it/s]libpng error: IDAT: CRC error
    49/299     3.21G   0.04316   0.02271  0.002976   0.06885       513       320: 100%|██████████| 12/12 [00:02<00:00,  4.36it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  3.49it/s]
                 all         165         583       0.566       0.936       0.887       0.487

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    50/299     3.21G   0.04138   0.02211  0.002773   0.06627       515       320: 100%|██████████| 12/12 [00:02<00:00,  4.32it/s]
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 2/2 [00:00<00:00,  3.59it/s]
                 all         165         583       0.703       0.934       0.906       0.493

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
    51/299     3.21G   0.03285   0.02216  0.002664   0.05768       834       320:   8%|▊         | 1/12 [00:00<00:02,  4.27it/s]
Traceback (most recent call last):
  File "/home/sha/PycharmProjects/Object_Detection/yolov5-v4.0/yolov5-4.0_car_part/train.py", line 519, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "/home/sha/PycharmProjects/Object_Detection/yolov5-v4.0/yolov5-4.0_car_part/train.py", line 267, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/home/sha/PycharmProjects/Object_Detection/yolov5-v4.0/yolov5-4.0_car_part/utils/datasets.py", line 103, in __iter__
    yield next(self.iterator)
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sha/Documents/Program/Anaconda/envs/torch1.8/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sha/PycharmProjects/Object_Detection/yolov5-v4.0/yolov5-4.0_car_part/utils/datasets.py", line 499, in __getitem__
    img, labels = load_mosaic(self, index)
  File "/home/sha/PycharmProjects/Object_Detection/yolov5-v4.0/yolov5-4.0_car_part/utils/datasets.py", line 655, in load_mosaic
    img, _, (h, w) = load_image(self, index)
  File "/home/sha/PycharmProjects/Object_Detection/yolov5-v4.0/yolov5-4.0_car_part/utils/datasets.py", line 616, in load_image
    assert img is not None, 'Image Not Found ' + path
AssertionError: Image Not Found /media/sha/Disk_1/Data_Set/data_KIITI_car_part/images/001012_0.png


Process finished with exit code 1
```

## Environment
Python 3.9.6
torch                         1.8.0+cu111
torchaudio                    0.8.0
torchvision                   0.9.0+cu111

## Analysis
I try to change the environment and replace the YOLOv5-5.0 version with a lower version 4.0. The same problem will occur.
I have analyzed this problem myself. The problem is that the path of the picture is not found, but I have checked that there is indeed a corresponding picture under the path. Otherwise, the program will not report an error after training multiple epochs

I hope to get your help, thank you！

**Comment by glenn-jocher** [comment]
@ShakalakaPHD the error is self explanatory, cv2 can't find an image correctly in datasets.py L616, so your image is not available. This is up to you, there's no bug in our code.

**Comment by Hurri-cane** [comment]
> @ShakalakaPHD the error is self explanatory, cv2 can't find an image correctly in datasets.py L616, so your image is not available. This is up to you, there's no bug in our code.
Thank you for your reply @glenn-jocher . I also noticed that cv2 failed to assign the read image to the img variable. I grabbed the breakpoint of this error through debug,
```
def load_image(self, index):
    # loads 1 image from dataset, returns img, original hw, resized hw
    img = self.imgs[index]
    if img is None:  # not cached
        path = self.img_files[index]
        img = cv2.imread(path)  # BGR
        if img is None:
            print("error")
        assert img is not None, 'Image Not Found ' + path
        h0, w0 = img.shape[:2]  # orig hw
        r = self.img_size / max(h0, w0)  # resize image to img_size
        if r != 1:  # always resize down, only resize up if training with augmentation
            interp = cv2.INTER_AREA if r < 1 and not self.augment else cv2.INTER_LINEAR
            img = cv2.resize(img, (int(w0 * r), int(h0 * r)), interpolation=interp)
        return img, (h0, w0), img.shape[:2]  # img, hw_original, hw_resized
    else:
        return self.imgs[index], self.img_hw0[index], self.img_hw[index]  # img, hw_original, hw_resized
```
I try to use those command
```
>>> img1 = cv2.imread(path)
>>> img = cv2.imread(path)
>>> print(type(img))
<class 'NoneType'>
>>> print(type(img1))
<class 'numpy.ndarray'>
```

Obviously, with the same assignment command, img1 gets the correct data, but img does not get it. This is what bothers me, because if there is an error in OpenCV, then img1 should not get the value, and train.py can't finish running. 50 epochs

**Comment by glenn-jocher** [comment]
@ShakalakaPHD there seems to be some problem with your system. cv2.imread will work for any number of sequential operations on the same image, i.e.:

```python
import cv2

print(cv2.imread('data/images/zidane.jpg').shape)
(720, 1280, 3)
print(cv2.imread('data/images/zidane.jpg').shape)
(720, 1280, 3)
```

**Comment by Hurri-cane** [comment]
@glenn-jocher 
Yes, in order to avoid system problems, I uninstalled and reinstalled anaconda, but the problem was still not resolved. As you said, cv2.imread will work for any number of sequential operations on the same image, but unfortunately I encountered a problem in this place. Although it did not completely solve my problem, anyway, thank you very much for your reply

**Comment by Hurri-cane** [comment]
@glenn-jocher  
HI，sir, I have an idea, is it possible that the img is locked by other parts of yolov5? So I can't assign it correctly

**Comment by glenn-jocher** [comment]
@ShakalakaPHD there is no problem at all in the code with reading images. We train thousands of models every month on various datasets with zero issues.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
