### ISSUE TITLE
How do I perform rectangular training?

### ISSUE THREAD

**Issue by zcswdt** [ultralytics/yolov5#4181]

**Comment by glenn-jocher** [comment]
@zcswdt 
```
python train.py --rect
```

See train.py argparser for details.

**Comment by zcswdt** [comment]
> python train.py --rect

My training command is as follows, but it will report an error：
`python -m torch.distributed.launch --nproc_per_node 2 train.py --batch 8 --data data.yaml --weights yolov5l.pt --rect  --device 0,1`

Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
  0%|                                                                                                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 660, in <module>
    main(opt)
  File "train.py", line 558, in main
    train(opt.hyp, opt, device)
  File "train.py", line 312, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/data/github/X-yolov5/yolov5-master/utils/datasets.py", line 137, in __iter__
    yield next(self.iterator)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/data/github/X-yolov5/yolov5-master/utils/datasets.py", line 592, in collate_fn
    return torch.stack(img, 0), torch.cat(label, 0), path, shapes
RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 640] at entry 0 and [3, 640, 544] at entry 1

Traceback (most recent call last):
  File "train.py", line 660, in <module>
    main(opt)
  File "train.py", line 558, in main
    train(opt.hyp, opt, device)
  File "train.py", line 312, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/data/github/X-yolov5/yolov5-master/utils/datasets.py", line 137, in __iter__
    yield next(self.iterator)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/data/github/X-yolov5/yolov5-master/utils/datasets.py", line 592, in collate_fn
    return torch.stack(img, 0), torch.cat(label, 0), path, shapes
RuntimeError: stack expects each tensor to be equal size, but got [3, 416, 640] at entry 0 and [3, 640, 608] at entry 1

Exception ignored in: <function tqdm.__del__ at 0x7f58b8f4c710>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1065, in __del__
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1248, in close
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 564, in _decr_instances
  File "/opt/conda/lib/python3.7/site-packages/tqdm/_monitor.py", line 51, in exit
  File "/opt/conda/lib/python3.7/threading.py", line 522, in set
  File "/opt/conda/lib/python3.7/threading.py", line 365, in notify_all
  File "/opt/conda/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=1', '--batch', '8', '--data', 'data.yaml', '--weights', 'yolov5l.pt', '--rect', '--device', '0,1']' returned non-zero exit status 1.

**Comment by glenn-jocher** [comment]
@zcswdt it works well for me, I'm not able to reproduce any issue with --rect:

<img width="1585" alt="Screenshot 2021-07-28 at 13 01 19" src="https://user-images.githubusercontent.com/26833433/127311850-0b68638f-0024-4376-bf63-3ba4ebf49df2.png">


👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by zcswdt** [comment]
> * e as little c

I don’t know why I report an error. I don’t report an error during normal training. If rectangle training is added, an error will be reported. Can rectangle training increase the accuracy?

**Comment by glenn-jocher** [comment]
@zcswdt if you have a reproducible error please submit a new bug report with code to reproduce.

**Comment by jaideep11061982** [comment]
@glenn-jocher  what image size will it take with rectangle  ,the actual ones?
Image sizes 640 train, 640 val
```
 --image-weights \
                 --rect \
```
How do i validate if Rect is taking desired sizes.?

**Comment by jaideep11061982** [comment]
```
  img, (h0, w0), (h, w) = load_image(self, index)

            # Letterbox
            shape = self.batch_shapes[self.batch[index]] if self.rect else self.img_size  # final letterboxed shape
            img, ratio, pad = letterbox(img, shape, auto=False, scaleup=self.augment)
```
I doubt  if it is taking into account rect image size, load image will resize as per img size we give in parameter.My Image is rectangle

**Comment by davidsvaughn** [comment]
I'm a little late to the party, but I believe the original error reported here may have been caused by doing rectangular training in DDP (multi-GPU) mode.  Has this ever been successfully tested?  I'm having a similar issue.  Don't have time right now to do formal bug report with reproducible code etc., but I may be able to later... just wanted to make a note of this...

Actually, this bug has already been reported here: 
[Does --rect conflict with DDP training? (#8698)](https://github.com/ultralytics/yolov5/issues/8698)

And yet again here: 
[multi gpus not woking when i use --rect (#757)](https://github.com/ultralytics/yolov5/issues/757)

**Comment by glenn-jocher** [comment]
@davidsvaughn thank you for bringing this to our attention. You are correct that there have been reports of issues with rectangular training in YOLOv5 when using DDP (multi-GPU) mode. 

This issue has been previously reported and is being tracked in the following GitHub issues:
- [Does --rect conflict with DDP training? (#8698)](https://github.com/ultralytics/yolov5/issues/8698)
- [multi gpus not working when i use --rect (#757)](https://github.com/ultralytics/yolov5/issues/757)

We are aware of this issue and it is currently under investigation. Thank you for your understanding, and we appreciate your patience as we work to resolve this issue.
