### ISSUE TITLE
The size of tensor a (18) must match the size of tensor b (24) at non-singleton dimension 0

### ISSUE THREAD

**Issue by maltamas** [ultralytics/yolov5#4315]
Traceback (most recent call last):
  File "train.py", line 540, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 312, in train
    scaler.step(optimizer)  # optimizer.step
  File "/home/abhishekg/Tensorflow2.2_venv/lib/python3.6/site-packages/torch/cuda/amp/grad_scaler.py", line 339, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/abhishekg/Tensorflow2.2_venv/lib/python3.6/site-packages/torch/cuda/amp/grad_scaler.py", line 286, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/abhishekg/Tensorflow2.2_venv/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/abhishekg/Tensorflow2.2_venv/lib/python3.6/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/abhishekg/Tensorflow2.2_venv/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/abhishekg/Tensorflow2.2_venv/lib/python3.6/site-packages/torch/optim/sgd.py", line 117, in step
    nesterov)
  File "/home/abhishekg/Tensorflow2.2_venv/lib/python3.6/site-packages/torch/optim/_functional.py", line 169, in sgd
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (18) must match the size of tensor b (24) at non-singleton dimension 0

![labels](https://user-images.githubusercontent.com/39873267/128327048-8574849b-5a08-4c58-a6a5-4e56a7cb83b3.jpg)
![labels_correlogram](https://user-images.githubusercontent.com/39873267/128327056-38815fc1-8b0e-4361-a7da-b8f9567e71b2.jpg)

I'm trying to train model on a custom dataset.

**Comment by glenn-jocher** [comment]
@maltamas see **Train Custom Data** tutorial to get started:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
