### ISSUE TITLE
Cannot load new models from torch hub

### ISSUE THREAD

**Issue by mfoglio** [ultralytics/yolov5#4459]
Code:
```
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5m6')
```
Error:
```
Using cache found in /home/ubuntu/.cache/torch/hub/ultralytics_yolov5_master
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/hub.py", line 339, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/hub.py", line 367, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/hub.py", line 187, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable yolov5m6 in hubconf
```
The following works fine:
```
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5m')
```

**Comment by mfoglio** [comment]
This fixed the issue:
```
rm -r ~/.cache/torch
```
