### ISSUE TITLE
Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by CachCheng** [ultralytics/yolov5#4463]
Traceback (most recent call last):
  File "train.py", line 602, in <module>
    main(opt)
  File "train.py", line 500, in main
    train(opt.hyp, opt, device)
  File "train.py", line 317, in train
    pred = model(imgs)  # forward
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/cash/dl/yolov5/models/yolo.py", line 124, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "/data/cash/dl/yolov5/models/yolo.py", line 155, in forward_once
    x = m(x)  # run
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/cash/dl/yolov5/models/common.py", line 136, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/cash/dl/yolov5/models/common.py", line 44, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

**Comment by fazer125** [comment]
I've had the same error.
The error disappeared when I lowered the batch size.
Try it!

**Comment by CachCheng** [comment]
> I've had the same error.
> The error disappeared when I lowered the batch size.
> Try it!

but when I enlarge the image size, this error still exist, such as 1280

**Comment by fazer125** [comment]
> but when I enlarge the image size, this error still exist, such as 1280

I think it's lack of VRAM.

**Comment by star-pluto** [comment]
You were right, man

> I've had the same error.
> The error disappeared when I lowered the batch size.
> Try it!

You were right, man
thanks a lot .
