### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#4516]
## 🐛 Bug

Error in title is thrown when trying to run train.py

## To Reproduce 

Getting the latest image and running it:
```
sudo docker pull ultralytics/yolov5:latest
sudo docker run --ipc-host --gpus all -it ultralytics/yolov5:latest
nvidia-smi
```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    On   | 00000000:09:00.0  On |                  N/A |
|  0%   43C    P8    20W / 420W |     83MiB / 24260MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

Then running train.py with 'python train.py'

```
Traceback (most recent call last):
  File "train.py", line 602, in <module>
    main(opt)
  File "train.py", line 500, in main
    train(opt.hyp, opt, device)
  File "train.py", line 114, in train
    csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 692, in float
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 692, in <lambda>
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

## Expected behavior

Training starting as expected

## Environment

GPU: RTX 3090
OS: Ubuntu 20.04
OS kernel: 5.11.0-27-generic
Nvidia driver: 460 (Proprietary)
CUDA version: 11.2

**Comment by ghost** [comment]
Fixed it by following this:
https://pytorch.org/get-started/locally/
