### ISSUE TITLE
Detection using torchscript.pt model

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [ultralytics/yolov5#4698]
**Is detect.py capable of detecting objects using torchscript.pt model?**

After converting the best.pt model using 

`python export.py --weights runs/train/exp6/weights/best.pt --img 320 --batch 1`

I have run 

`python detect.py --source ../data/custom/images/im_0_4528.png --weights runs/train/exp6/weights/best.torchscript.pt --img 320`

and I get the following results:

```
/usr/local/lib/python3.7/site-packages/torch/serialization.py:604: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
Traceback (most recent call last):
  File "detect.py", line 287, in <module>
    main(opt)
  File "detect.py", line 282, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 75, in run
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/yolov5/models/experimental.py", line 96, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "/usr/local/lib/python3.7/site-packages/torch/jit/_script.py", line 667, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/_script.py", line 384, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'RecursiveScriptModule' object has no attribute 'get'
```

The code has been launched in a Docker container with python 3.7 and all the denoted requirements installed

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar no, detect.py does not accept torchscript models.

**Comment by JNaranjo-Alcazar** [comment]
Okey! Thank you so much for this clarification
