### ISSUE TITLE
issue while sending the custom data to wandb

### ISSUE THREAD

**Issue by alijundi** [ultralytics/yolov5#4699]
I get the below

```
andb: Adding directory to artifact (.\custom_dataset\train)... Done. 0.0s
wandb: Adding directory to artifact (.\custom_dataset\train)... Done. 0.0s
100%|███████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.56it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.91it/s]
Traceback (most recent call last):
  File "C:\Work/Python/yolov5-master\utils\datasets.py", line 398, in __init__
    assert self.img_files, f'{prefix}No images found'
AssertionError: No images found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\log_dataset.py", line 23, in <module>
    create_dataset_artifact(opt)
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\log_dataset.py", line 9, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 183, in __init__
    self.data_dict = self.check_and_upload_dataset(opt)
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 196, in check_and_upload_dataset
    config_path = self.log_dataset_artifact(opt.data,
  File "C:\Work\Python\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 334, in log_dataset_artifact
    self.val_artifact = self.create_dataset_table(LoadImagesAndLabels(
  File "C:\Work/Python/yolov5-master\utils\datasets.py", line 400, in __init__
    raise Exception(f'{prefix}Error loading data from {path}: {e}\nSee {HELP_URL}')
Exception: Error loading data from custom_dataset\val: No images found
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

wandb: Waiting for W&B process to finish, PID 11948
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
```
Any idea why guys?

**Comment by glenn-jocher** [comment]
@alijundi can you please provide a reproducible example and a wandb run url for this problem?

@AyushExel can you take a look at this please? Thanks!

**Comment by AyushExel** [comment]
@alijundi looks like there's something wrong with the dataset. Can you share the link to it so I can test on the same dataset ?
