### ISSUE TITLE
name 'keras_model' is not defined when convert yolov5 weights to tflite model

### ISSUE THREAD

**Issue by diogogonnelli** [ultralytics/yolov5#4733]
**I'm trying to convert weigths from yolov5 to tflite, but the process show this error:**

TFLite export failure: name 'keras_model' is not defined
Traceback (most recent call last):
  File "C:\Users\SpotML\Desktop\Cmder\yolov5\models\tf.py", line 521, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
NameError: name 'keras_model' is not defined

**I tried to use tensorflow .2.4.1 and 2.6.0 with keras 2.4.1 and 2.6.0**

does anyone get this error?

**see below the entire message:**

λ python models\tf.py --weight yolov5s.pt --cfg models\yolov5s.yaml
2021-09-09 18:22:05.211214: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
Namespace(cfg='models\\yolov5s.yaml', weights='yolov5s.pt', img_size=[320, 320], batch_size=1, dynamic_batch_size=False, source='../data/coco128.yaml', ncalib=100, tfl_int8=False, tf_nms=False, agnostic_nms=False, tf_raw_resize=False, topk_per_class=100, topk_all=100, iou_thres=0.5, score_thres=0.4)

Starting TensorFlow saved_model export with TensorFlow 2.5.1...
2021-09-09 18:22:07.709639: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2021-09-09 18:22:07.732937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2021-09-09 18:22:07.733447: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-09-09 18:22:07.733561: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2021-09-09 18:22:07.733663: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
2021-09-09 18:22:07.733762: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
2021-09-09 18:22:07.733870: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2021-09-09 18:22:07.733958: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2021-09-09 18:22:07.734043: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
2021-09-09 18:22:07.734153: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-09-09 18:22:07.734326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-09-09 18:22:07.734697: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-09 18:22:07.735512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2021-09-09 18:22:07.736111: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-09-09 18:22:08.070317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-09 18:22:08.070505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-09-09 18:22:08.070633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-09-09 18:22:08.070862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5464 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-09-09 18:22:08.384519: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-09-09 18:22:08.827224: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2021-09-09 18:22:08.829499: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
TensorFlow saved_model export failure: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]
Traceback (most recent call last):
  File "C:\Users\SpotML\Desktop\Cmder\yolov5\models\tf.py", line 472, in <module>
    y = tf_model.predict(img)
  File "C:\Users\SpotML\Desktop\Cmder\yolov5\models\tf.py", line 355, in predict
    x = m(x)  # run
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\SpotML\Desktop\Cmder\yolov5\models\tf.py", line 122, in call
    return self.conv(tf.concat([inputs[:, ::2, ::2, :],
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\SpotML\Desktop\Cmder\yolov5\models\tf.py", line 110, in call
    return self.act(self.bn(self.conv(inputs)))
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1142, in convolution_internal
    return op(
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 931, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\SpotML\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\framework\ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

Starting TensorFlow GraphDef export with TensorFlow 2.5.1...
TensorFlow GraphDef export failure: name 'keras_model' is not defined
Traceback (most recent call last):
  File "C:\Users\SpotML\Desktop\Cmder\yolov5\models\tf.py", line 491, in <module>
    tf.TensorSpec(keras_model.inputs[0].shape, keras_model.inputs[0].dtype))
NameError: name 'keras_model' is not defined

Starting TFLite export with TensorFlow 2.5.1...

TFLite export failure: name 'keras_model' is not defined
Traceback (most recent call last):
  File "C:\Users\SpotML\Desktop\Cmder\yolov5\models\tf.py", line 521, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
NameError: name 'keras_model' is not defined

**Comment by glenn-jocher** [comment]
@diogogonnelli 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. Your error is not reproducible:

<img width="1517" alt="Screenshot 2021-09-10 at 12 25 01" src="https://user-images.githubusercontent.com/26833433/132839854-4bf7c575-33b1-42ef-a915-6406a3e80ad3.png">


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
