### ISSUE TITLE
Errno 110 Connection Time out error

### ISSUE THREAD

**Issue by BenMaslen** [ultralytics/yolov5#4766]
# ❔Question
I am trying to to run yolov5 on the road sign data set as done in https://blog.paperspace.com/train-yolov5-custom-data/, however I am getting the error below which has previously been described https://github.com/ultralytics/yolov5/issues/2117, yet despite cloning the most up to date version I am still getting this issue. Wondering if anyone has any tips, is this a bug or am I doing something wrong?

## Additional context
The code I am using to run the model is:
python3 train.py --img 640 --cfg yolov5s.yaml --hyp hyp.scratch.yaml --batch 32 --epochs 100 --data road_sign_data.yaml --weights yolov5s.pt --workers 24 --name yolo_road_det

### Where my yaml file is:
train: ../Road_Sign_Dataset/images/train/ 
val:  ../Road_Sign_Dataset/images/val/
test: ../Road_Sign_Dataset/images/test/

nc: 4

names: ["trafficlight","stop", "speedlimit","crosswalk"]

## Error message

Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1269, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1315, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1264, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 978, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1429, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 950, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/yq06/bm6004/yolo_ex/yolov5/utils/downloads.py", line 29, in safe_download
    torch.hub.download_url_to_file(url, str(file))
  File "/scratch/yq06/bm6004/yolo_ex/test_venv/lib64/python3.6/site-packages/torch/hub.py", line 419, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/yq06/bm6004/yolo_ex/yolov5/utils/downloads.py", line 32, in safe_download
    file.unlink(missing_ok=True)  # remove partial downloads
TypeError: unlink() got an unexpected keyword argument 'missing_ok'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 611, in <module>
    main(opt)
  File "train.py", line 509, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 112, in train
    weights = attempt_download(weights)  # download if not found locally
  File "/scratch/yq06/bm6004/yolo_ex/yolov5/utils/downloads.py", line 74, in attempt_download
    error_msg=f'{file} missing, try downloading from https://github.com/{repo}/releases/')
  File "/scratch/yq06/bm6004/yolo_ex/yolov5/utils/downloads.py", line 37, in safe_download
    file.unlink(missing_ok=True)  # remove partial downloads
TypeError: unlink() got an unexpected keyword argument 'missing_ok'

**Comment by glenn-jocher** [comment]
@BenMaslen from stackoverflow:
https://stackoverflow.com/questions/68668895/when-i-run-the-code-it-says-typeerror-unlink-got-an-unexpected-keyword-argum
The `missing_ok` parameter was added to Path.unlink only on python 3.8. You should upgrade python to newer version if you want to use this parameter.

The other part of your problem is just your internet connection. You don't seem able to download pretrained weights. Solution is to just try again or use a machine with a better connection.

**Comment by BenMaslen** [comment]
Hi @glenn-jocher, I am using the most up to date python and have tried multiple times from different servers and no luck unfortunately.

**Comment by glenn-jocher** [comment]
@BenMaslen can you supply a Colab notebook that reproduces the issue? We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
