### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '.E:\\proj\\ms_prj\\source\\yolov5-5.0\\VOCdevkit\\images\\val'

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#4898]
## ❔Question
Traceback (most recent call last):
  File "E:\proj\ms_prj\source\yolov5-5.0\train.py", line 545, in <module>
    train(hyp, opt, device, tb_writer)
  File "E:\proj\ms_prj\source\yolov5-5.0\train.py", line 97, in train
    check_dataset(data_dict)  # check
  File "E:\proj\ms_prj\source\yolov5-5.0\utils\general.py", line 160, in check_dataset
    val = [Path(x).resolve() for x in (val if isinstance(val, list) else [val])]  # val path
  File "E:\proj\ms_prj\source\yolov5-5.0\utils\general.py", line 160, in <listcomp>
    val = [Path(x).resolve() for x in (val if isinstance(val, list) else [val])]  # val path
  File "C:\Users\LuRundong\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\LuRundong\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '.E:\\proj\\ms_prj\\source\\yolov5-5.0\\VOCdevkit\\images\\val'
## Additional context
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Why there is a '.' be added before disk 'E:‘?
The file path exists, but I do not know where caused the superfluous dot symbol.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by ghost** [comment]
I write something wrong in the yaml file.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: E:\proj\ms_prj\source\yolov5-5.0\VOCdevkit\images\train
val: .E:\proj\ms_prj\source\yolov5-5.0\VOCdevkit\images\val
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
The extra dot was added
