### ISSUE TITLE
usb camera ass source

### ISSUE THREAD

**Issue by mikel-brostrom** [ultralytics/yolov5#4943]
## ❔Question

Hi! I want to use a USB camera. I can stream it by:

`ffplay /dev/video4`

I tried to feed this to Yolov5 by:

`python3 detect.py --source /dev/video4`

## Additional context

The error I get is 

```
Traceback (most recent call last):
  File "detect.py", line 293, in <module>
    main(opt)
  File "detect.py", line 288, in main
    run(**vars(opt))
  File "/xxx/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 118, in run
    dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt)
  File "/xxx/yolov5/utils/datasets.py", line 167, in __init__
    raise Exception(f'ERROR: {p} does not exist')
Exception: ERROR: /dev/video4 does not exist
```

Thank you for your time!

**Comment by mikel-brostrom** [comment]
I figured this out. List the video devices picked up by the kernel. By, for example:

`ls -ltrh /dev/video*`

find out which among them you want to feed to the tracker by inspecting each source:

`ffplay  /dev/video1`
`ffplay  /dev/video2`
`...`

Then what is important is to keep in mind the number associated to the source. So, if the source you want to feed is
`/dev/video3` you should run:

`python3 detect.py --source 3`
