### ISSUE TITLE
SKU-110K HUB: `OSError: broken data stream when reading image file`

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#5105]
Discovered by @kalenmike 

To reproduce:
```bash
from utils.datasets import *; dataset_stats('SKU-110K.yaml', autodownload=True, hub=True)
```

Result
```bash
from utils.datasets import *; dataset_stats('SKU-110K.yaml', autodownload=True, hub=True)
Backend MacOSX is interactive backend. Turning interactive mode on.
WARNING: Dataset not found, nonexistent paths: ['/Users/glennjocher/PycharmProjects/datasets/SKU-110K/val.txt']
Unzipping ../datasets/SKU110K_fixed.tar.gz...
Converting ../datasets/SKU-110K/annotations_train.csv: 100%|██████████| 8219/8219 [02:51<00:00, 47.80it/s]
Converting ../datasets/SKU-110K/annotations_val.csv: 100%|██████████| 588/588 [00:02<00:00, 242.84it/s]
Converting ../datasets/SKU-110K/annotations_test.csv: 100%|██████████| 2936/2936 [00:21<00:00, 134.23it/s]
Dataset autodownload success, saved to ../datasets
Scanning '../datasets/SKU-110K/train' images and labels...8216 found, 0 missing, 0 empty, 4 corrupted: 100%|██████████| 8219/8219 [00:25<00:00, 317.05it/s]
Statistics: 100%|██████████| 8215/8215 [00:00<00:00, 385153.39it/s]
HUB Ops:  65%|██████▌   | 5348/8215 [02:29<01:20, 35.81it/s]
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6121dbc7ada1>", line 1, in <module>
    from utils.datasets import *; dataset_stats('SKU-110K.yaml', autodownload=True, hub=True)
  File "/Users/glennjocher/PycharmProjects/yolov5/utils/datasets.py", line 979, in dataset_stats
    for _ in tqdm(ThreadPool(NUM_THREADS).imap(hub_ops, dataset.img_files), total=dataset.n, desc='HUB Ops'):
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/glennjocher/PycharmProjects/yolov5/utils/datasets.py", line 950, in hub_ops
    im = im.resize((int(im.width * r), int(im.height * r)))
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/PIL/Image.py", line 1982, in resize
    self.load()
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file
```

**Comment by glenn-jocher** [comment]
Caused by a corrupt image.
<img width="1590" alt="Screen Shot 2021-10-08 at 3 44 29 PM" src="https://user-images.githubusercontent.com/26833433/136632049-7d9ce380-8c47-4a3c-81b8-7982fe80ee71.png">
