### ISSUE TITLE
Windows. Training with multi GPU

### ISSUE THREAD

**Issue by Yoon5** [ultralytics/yolov5#5126]
When I try to training with using multi GPU based on a tutorial that was shared. I got the above error. I work on windows 10, python 3.8. 
(yolo5) C:\yolov5-master>python -m torch.distributed.run --nproc_per_node 2 train.py --data D:\yolo5/data.yaml --cfg D:\yolo5/models/custom_yolov5s.yaml --weights '' --name  yolo5s  --img-size 512 --batch 64 --epochs 8000 --device 0,1
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:__main__:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
train: weights='', cfg=D:\yolo5/models/custom_yolov5s.yaml, data=D:\yolo5/data.yaml, hyp=data\hyps\hyp.scratch.yaml, epochs=8000, batch_size=64, imgsz=512, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=0,1, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs\train, name=yolo5s, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=0, save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\yolov5-master\train.py", line 620, in <module>
    main(opt)
  File "C:\Users\pc\Desktop\yolov5-master\train.py", line 505, in main
    device = select_device(opt.device, batch_size=opt.batch_size)
  File "C:\Users\pc\Desktop\yolov5-master\utils\torch_utils.py", line 67, in select_device
    assert torch.cuda.is_available(), f'CUDA unavailable, invalid device {device} requested'  # check availability
AssertionError: CUDA unavailable, invalid device 0,1 requested
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\yolov5-master\train.py", line 620, in <module>
    main(opt)
  File "C:\Users\pc\Desktop\yolov5-master\train.py", line 505, in main
    device = select_device(opt.device, batch_size=opt.batch_size)
  File "C:\Users\pc\Desktop\yolov5-master\utils\torch_utils.py", line 67, in select_device
    assert torch.cuda.is_available(), f'CUDA unavailable, invalid device {device} requested'  # check availability
AssertionError: CUDA unavailable, invalid device 0,1 requested
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3612) of binary: C:\Users\pc\anaconda3\envs\yolo5\python.exe
C:\Users\pc\anaconda3\envs\yolo5\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py:367: UserWarning:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 3612 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\site-packages\torch\distributed\run.py", line 702, in <module>
    main()
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\site-packages\torch\distributed\run.py", line 698, in main
    run(args)
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\site-packages\torch\distributed\run.py", line 689, in run
    elastic_launch(
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\site-packages\torch\distributed\launcher\api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\pc\anaconda3\envs\yolo5\lib\site-packages\torch\distributed\launcher\api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
            train.py FAILED
=======================================
Root Cause:
[0]:
  time: 2021-10-11_17:15:48
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 3612)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"

**Comment by glenn-jocher** [comment]
@Yoon5 I'm not sure if PyTorch supports DDP on Windows, but you should definitely use the Docker image for all DDP trainings.
