### ISSUE TITLE
OSError Too many open files: `/tmp/tmphv67gzd0wandb-media` when doing --evolve

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#5306]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following,
otherwise it is non-actionable, and we can not help you:

- **Current repo**: master
- **Common dataset**: custom dataset
- **Common environment**: Using Docker ultralytics/yolov5

## 🐛 Bug

Currently getting this error
```
  File "/opt/conda/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmphv67gzd0wandb-media'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/weakref.py", line 642, in _exitfunc
  File "/opt/conda/lib/python3.8/weakref.py", line 566, in __call__
  File "/opt/conda/lib/python3.8/tempfile.py", line 817, in _cleanup
  File "/opt/conda/lib/python3.8/tempfile.py", line 813, in _rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 714, in rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmphv67gzd0wandb-media'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/weakref.py", line 642, in _exitfunc
  File "/opt/conda/lib/python3.8/weakref.py", line 566, in __call__
  File "/opt/conda/lib/python3.8/tempfile.py", line 817, in _cleanup
  File "/opt/conda/lib/python3.8/tempfile.py", line 813, in _rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 714, in rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmphv67gzd0wandb-media'

```

## To Reproduce (REQUIRED)
Run `train.py` with `--evolve` parameter

Getting this error in about 20th round out of 300th.

## Environment

- OS: Ubuntu
- GPU 1080Ti

**Comment by AyushExel** [comment]
@sarmientoj24 thanks for filing the bug report. I'll reproduce this and get back to you.

**Comment by AyushExel** [comment]
@sarmientoj24 I couldn't reproduce this. I'm running an evolve, 2 full evolutions of 300 epochs have been completed successfully without any errors. This error can be caused by low disk space which results in program being unable to create temp files.
Please check that and let me know if you're still facing this issue

**Comment by glenn-jocher** [comment]
@AyushExel linked to known W&B bug here https://github.com/wandb/client/issues/2825. I found this via a quick Google search.

**Comment by AyushExel** [comment]
@glenn-jocher yes this was picked up for a fix. Should have been fixed in the latest release

**Comment by glenn-jocher** [comment]
@AyushExel got it, thanks! Can you check if the fix is live and if so update both open issues to reflect that? Part of what I try to do is go back everywhere a bug was mentioned and inform users that it's been fixed. Otherwise there's no visibility into the fix for users. Thanks!

**Comment by AyushExel** [comment]
@glenn-jocher Yes, I'll verify and close this

**Comment by glenn-jocher** [comment]
@AyushExel is this issue resolved now?

**Comment by AyushExel** [comment]
Hey, yes this ticket's resolved

**Comment by glenn-jocher** [comment]
@AyushExel great thanks! TODO removed :)
