### ISSUE TITLE
python export.py --weights runs/train/exp6/weights/best.pt --include tfjs

### ISSUE THREAD

**Issue by gamefake588** [ultralytics/yolov5#5434]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

KeyError: 'The name "\'Identity" refers to an Operation not in the graph.'

**Comment by gamefake588** [comment]
TensorFlow.js: starting export with tensorflowjs 3.11.0...
2021-11-01 22:04:46.901506: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\code-tool\Anaconda\bin\envs\yolov5\Scripts\tensorflowjs_converter.exe\__main__.py", line 7, in <module>
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflowjs\converters\converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflowjs\converters\converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflowjs\converters\converter.py", line 803, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflowjs\converters\converter.py", line 574, in _dispatch_converter
    tf_saved_model_conversion_v2.convert_tf_frozen_model(
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 522, in convert_tf_frozen_model
    optimize_graph(graph, signature,
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 146, in optimize_graph
    graph.add_to_collection('train_op', graph.get_operation_by_name(name))
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflow\python\framework\ops.py", line 3854, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflow\python\framework\ops.py", line 3726, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "F:\code-tool\Anaconda\bin\envs\yolov5\lib\site-packages\tensorflow\python\framework\ops.py", line 3785, in _as_graph_element_locked
    raise KeyError("The name %s refers to an Operation not in the "
KeyError: 'The name "\'Identity" refers to an Operation not in the graph.'

TensorFlow.js: export failure: [Errno 2] No such file or directory: 'runs\\train\\exp6\\weights\\best_web_model/model.json'

**Comment by glenn-jocher** [comment]
@gamefake588 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your error is not reproducible in our Colab notebook using the following commands:

```python
!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt
!python export.py --weights runs/train/exp/weights/best.pt --include tfjs
```

<img width="1056" alt="Screenshot 2021-11-01 at 20 52 15" src="https://user-images.githubusercontent.com/26833433/139732760-8471a070-931b-4cbb-959e-b70b525f95fd.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
