### ISSUE TITLE
modifying backbone structure

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#5753]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to use different backbones with YOLOV5. I have defined VGG16 in `common.py` as below and modified model.yaml file to use the VGG16. I tried to run it but the get the following error. 

```
## VGG16 layer
class vggLayer(nn.Module):
    def __init__(self, c1, c2, n=1, s=2): #chin, chout, block_nums, stride
        super(vggLayer,self).__init__()
        blocks=[nn.Conv2d(c1, c2, kernel_size=3, stride=1, padding=1, bias=True),nn.ReLU(inplace=True)]
        for _ in range(n-1):
            blocks+=[nn.Conv2d(c2, c2, kernel_size=3, stride=1, padding=1, bias=True),nn.ReLU(inplace=True)]
        blocks.append(nn.MaxPool2d(kernel_size=2, stride=s, padding=0, dilation=1))
        self.layers = nn.Sequential(*blocks)
    def forward(self, x):
        return self.layers(x)
```

model.yaml file
```
backbone:
  # [from, number, module, args] 
   [
   [-1, 1, vggLayer, [64, 2]],   # 0 P1/2
   [-1, 1, vggLayer, [128, 2]],  # 1 P2/4 
   [-1, 2, vggLayer, [256, 2]],  # 2 P3/8 
   [-1, 2, vggLayer, [512, 2]],  # 3 P4/16
   [-1, 2, vggLayer, [512, 2]],  # 4 P5/32
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 5], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 3], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
```

### Additional
error message:
```
                 from  n    params  module                                  arguments                     
  0                -1  1      1154  models.common.vggLayer                  [64, 2]                       
  1                -1  1      2306  models.common.vggLayer                  [128, 2]                      
  2                -1  2      9220  models.common.vggLayer                  [256, 2]                      
  3                -1  2     18436  models.common.vggLayer                  [512, 2]                      
  4                -1  2     18436  models.common.vggLayer                  [512, 2]                      
  5                -1  1      2560  models.common.Conv                      [3, 512, 1, 1]                
  6                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
  7           [-1, 5]  1         0  models.common.Concat                    [1]                           
  8                -1  3   2757632  models.common.C3                        [1024, 512, 3, False]         
  9                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 10                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 11           [-1, 3]  1         0  models.common.Concat                    [1]                           
 12                -1  3    625920  models.common.C3                        [259, 256, 3, False]          
 13                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
Traceback (most recent call last):
  File "train.py", line 625, in <module>
    main(opt)
  File "train.py", line 522, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 123, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/content/yolov5/models/yolo.py", line 102, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/content/yolov5/models/yolo.py", line 271, in parse_model
    c2 = sum(ch[x] for x in f)
  File "/content/yolov5/models/yolo.py", line 271, in <genexpr>
    c2 = sum(ch[x] for x in f)
IndexError: list index out of range
CPU times: user 92.5 ms, sys: 34.8 ms, total: 127 ms
Wall time: 7.71 s
```
_No response_

**Comment by myasser63** [comment]
@glenn-jocher Could you help me to understand how to determine what layers should be concatinated in the head section

**Comment by myasser63** [comment]
@glenn-jocher can you please provide any help

**Comment by glenn-jocher** [comment]
@myasser63 I'm sorry we don't have availability for customization support.

**Comment by myasser63** [comment]
@glenn-jocher Thank you I have managed to solve it and make it work.

**Comment by XhHello** [comment]
> Thank you I have managed to solve it and make it work.

Do you load yolov5.pt for training after replacing the backbone network

**Comment by myasser63** [comment]
I am not sure about this part too, and I didn't know what to use so i used `--weights ''` but the model performance is so poor. May be @glenn-jocher  could give some advice.

**Comment by XhHello** [comment]
> I am not sure about this part too, and I didn't know what to use so i used `--weights ''` but the model performance is so poor. May be @glenn-jocher could give some advice.

I'm also obsessed with this. I don't know how to train after modifying the model

**Comment by myasser63** [comment]
What did you use for backbone?

**Comment by XhHello** [comment]
> What did you use for backbone?
such as shuff

**Comment by glenn-jocher** [comment]
@myasser63 you can start training from any yaml and attempt to pair it with any pretrained weights. All pretrained layers with matching names and shapes will be transferred, and you will see a report stating how many layers were transferred, i.e. `transferred 270/554 layers`.

```python
python train.py --cfg new.yaml --weights ''  # train from scratch
python train.py --cfg new.yaml --weights yolov5s.pt  # attempt to transfer pretrained weights
```

**Comment by myasser63** [comment]
Thanks @glenn-jocher for your explanation

**Comment by ArgoHA** [comment]
> @glenn-jocher Thank you I have managed to solve it and make it work.

Could you share your solution?

I have deleted one layer in backbone and I get the same error

**Comment by FisherDom** [comment]
> @glenn-jocher Thank you I have managed to solve it and make it work.

hello!
could u show your solution? thanks a lot

**Comment by rickyfazaa** [comment]
> @glenn-jocher Thank you I have managed to solve it and make it work.

Hai, @myasser63! could you show your solution please?

**Comment by glenn-jocher** [comment]
Hello @rickyfazaa! I'm glad to hear that you have managed to solve the issue. Would you be able to share the solution that worked for you, so that others who may face the same issue can benefit from your experience? Thank you!
