### ISSUE TITLE
Problem of wandb in train.py

### ISSUE THREAD

**Issue by sergorl** [ultralytics/yolov5#5772]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Command for training:

`python train.py --img 640 --batch 16 --epochs 100 --data "D:\repositories\yolov5Test\train\shapes.yaml" --weights yolov5n.pt`

gave me

```
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: (30 second timeout) 3
wandb: You chose 'Don't visualize my results'
train: weights=yolov5n.pt, cfg=, data=D:\repositories\yolov5Test\train\shapes.yaml, hyp=data\hyps\hyp.scratch.yaml, epochs=100, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=0, save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2021-11-22 torch 1.8.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2080 Super, 8192MiB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=9

                 from  n    params  module                                  arguments
  0                -1  1      1760  models.common.Conv                      [3, 16, 6, 2, 2]
  1                -1  1      4672  models.common.Conv                      [16, 32, 3, 2]
  2                -1  1      4800  models.common.C3                        [32, 32, 1]
  3                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  4                -1  2     29184  models.common.C3                        [64, 64, 2]
  5                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  6                -1  3    156928  models.common.C3                        [128, 128, 3]
  7                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  8                -1  1    296448  models.common.C3                        [256, 256, 1]
  9                -1  1    164608  models.common.SPPF                      [256, 256, 5]
 10                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 14                -1  1      8320  models.common.Conv                      [128, 64, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     22912  models.common.C3                        [128, 64, 1, False]
 18                -1  1     36992  models.common.Conv                      [64, 64, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1     74496  models.common.C3                        [128, 128, 1, False]
 21                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 24      [17, 20, 23]  1     18942  models.yolo.Detect                      [9, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [64, 128, 256]]
Model Summary: 270 layers, 1776094 parameters, 1776094 gradients, 4.2 GFLOPs

Transferred 343/349 items from yolov5n.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight, 60 weight (no decay), 60 bias
train: Scanning 'D:\dataset\flowchart\raw\dataset\labels.cache' images and labels... 7478 found, 1 missing, 3 empty, 0 corrupted: 100%|███████████████████████████████████████████████| 7479/7479 [00:00<?, ?it/s]
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: (30 second timeout) 3
wandb: You chose 'Don't visualize my results'
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: (30 second timeout) 3
wandb: You chose 'Don't visualize my results'
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: (30 second timeout) Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\s00557672\.cache\torch\hub\ultralytics_yolov5_master\train.py", line 46, in <module>
    from utils.loggers import Loggers
  File "C:\Users\s00557672\.cache\torch\hub\ultralytics_yolov5_master\utils\loggers\__init__.py", line 27, in <module>
    wandb_login_success = wandb.login(timeout=30)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\wandb_login.py", line 65, in login
    configured = _login(**kwargs)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\wandb_login.py", line 274, in _login
    wlogin.prompt_api_key()
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\wandb_login.py", line 202, in prompt_api_key
    key, status = self._prompt_api_key()
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\wandb_login.py", line 182, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\apikey.py", line 93, in prompt_api_key
    result = prompt_choices(
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\util.py", line 1090, in prompt_choices
    choice = _prompt_choice(input_timeout=input_timeout, jupyter=jupyter)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\util.py", line 1077, in _prompt_choice
    choice = input_fn(text, jupyter=jupyter)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\timed_input.py", line 119, in timed_input
    return _timed_input(prompt=prompt, timeout=timeout)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\timed_input.py", line 62, in _windows_timed_input
    time.sleep(interval)
KeyboardInterrupt
```

So it seems `wandb `doesn't recognize I chose option (3) without visualization. How can I fix it and finally start the training?

### Environment

- YOLO: YOLOv5  2021-11-22 torch 1.8.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2080 Super, 8192MiB)
- OS: Windows 10
- Python: 3.8.3

### Minimal Reproducible Example

`python train.py --img 640 --batch 16 --epochs 100 --data "D:\repositories\yolov5Test\train\shapes.yaml" --weights yolov5n.pt`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AyushExel can you take a look at this? Thanks!

**Comment by AyushExel** [comment]
@sergorl I'll try to reproduce this and get back today. 
Alternatively you can also login via terminal just run `wandb login`

**Comment by sergorl** [comment]
@AyushExel , I fixed it by creating account and applying API key. But I don't like it. What if user doesn't want to use `wandb`?! Is it possible to do not use `wandb`?

**Comment by AyushExel** [comment]
@sergorl yes you can disable wandb by running `wandb disabled` and enable it by running `wandb online`
Or you can also uninstall wandb using `pip uninstall wandb`

Let me know if you face any troubles

**Comment by sergorl** [comment]
@AyushExel , please, give me code/command example, how I can do it before launch `python train.py ...`

**Comment by AyushExel** [comment]
@sergorl can you try this:.
```
wandb disabled
python train.py ...
```

**Comment by sergorl** [comment]
@AyushExel , is `wandb` application with extension `.exe`? where is the location of `wandb` in Windows 10?

**Comment by AyushExel** [comment]
@sergorl no it's python package that comes with a command line interface. Is the previous command not working for you ?

**Comment by sergorl** [comment]
@AyushExel , no, command `wandb disabled` doesn't work in Windows 10 terminal: Windows OS doens't find it.

**Comment by AyushExel** [comment]
@sergorl okaym I'll verify this but and get back

**Comment by AyushExel** [comment]
@sergorl It's working for me on windows. 
* training after running `wandb disabled` inside that directory creates no wandb run
![Screenshot (84)](https://user-images.githubusercontent.com/15766192/143441777-c780bdd7-7cb4-4404-9559-b4316030a985.png)

* To enable wandb again, run `wandb online` 
![Screenshot (85)](https://user-images.githubusercontent.com/15766192/143441866-7191b2cb-22f0-4e0f-ae64-2dc47dc13078.png)

**Comment by AyushExel** [comment]
@sergorl coming back to the original issue. Choosing option 3 works fine for me
![Screenshot (87)](https://user-images.githubusercontent.com/15766192/143442818-4ae18abc-6330-4b37-9b42-7e3add1e800d.png)
