### ISSUE TITLE
Something goes wrong during training

### ISSUE THREAD

**Issue by sergorl** [ultralytics/yolov5#5773]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Command `python train.py --img 960 --batch 4 --epochs 100 --data "D:\repositories\yolov5Test\train\shapes.yaml" --weights yolov5n.pt`

gives me:

```
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
train: weights=yolov5n.pt, cfg=, data=D:\repositories\yolov5Test\train\shapes.yaml, hyp=data\hyps\hyp.scratch.yaml, epochs=100, batch_size=4, imgsz=960, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=0, save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2021-11-22 torch 1.8.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2080 Super, 8192MiB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
wandb: Tracking run with wandb version 0.12.7
wandb: Syncing run jumping-glade-7
wandb:  View project at https://wandb.ai/sergorl/train
wandb:  View run at https://wandb.ai/sergorl/train/runs/2wrfwkzq
wandb: Run data is saved locally in C:\Users\s00557672\.cache\torch\hub\ultralytics_yolov5_master\wandb\run-20211124_174238-2wrfwkzq
wandb: Run `wandb offline` to turn off syncing.

Overriding model.yaml nc=80 with nc=9

                 from  n    params  module                                  arguments
  0                -1  1      1760  models.common.Conv                      [3, 16, 6, 2, 2]
  1                -1  1      4672  models.common.Conv                      [16, 32, 3, 2]
  2                -1  1      4800  models.common.C3                        [32, 32, 1]
  3                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  4                -1  2     29184  models.common.C3                        [64, 64, 2]
  5                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  6                -1  3    156928  models.common.C3                        [128, 128, 3]
  7                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  8                -1  1    296448  models.common.C3                        [256, 256, 1]
  9                -1  1    164608  models.common.SPPF                      [256, 256, 5]
 10                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 14                -1  1      8320  models.common.Conv                      [128, 64, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     22912  models.common.C3                        [128, 64, 1, False]
 18                -1  1     36992  models.common.Conv                      [64, 64, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1     74496  models.common.C3                        [128, 128, 1, False]
 21                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 24      [17, 20, 23]  1     18942  models.yolo.Detect                      [9, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [64, 128, 256]]
Model Summary: 270 layers, 1776094 parameters, 1776094 gradients, 4.2 GFLOPs

Transferred 343/349 items from yolov5n.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight, 60 weight (no decay), 60 bias
train: Scanning 'D:\dataset\flowchart\raw\dataset\labels.cache' images and labels... 7478 found, 1 missing, 3 empty, 0
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
val: Scanning 'D:\dataset\flowchart\raw\dataset\labels.cache' images and labels... 7478 found, 1 missing, 3 empty, 0 corrupted: 100%|███████████████████████████████████████████████████████████████████████████| 7479/7479 [00:00<?, ?it/s]
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
wandb: Currently logged in as: sergorl (use `wandb login --relogin` to force relogin)
Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_common.py", line 449, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\stats.py", line 132, in _thread_body
    stats = self.stats()
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\stats.py", line 185, in stats
    in_use_by_us = gpu_in_use_by_this_process(handle)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\stats.py", line 41, in gpu_in_use_by_this_process
    base_process = psutil.Process().parent() or psutil.Process()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 559, in parent
    ppid = self.ppid()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_common.py", line 452, in wrapper
    return fun(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 620, in ppid
    self._ppid = self._ppid or self._proc.ppid()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 803, in ppid
    return ppid_map()[self.pid]
OSError: [WinError 1455] The paging file is too small for this operation to complete
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\wandb_run.py", line 167, in check_status
    status_response = self._interface.communicate_stop_status()
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface.py", line 109, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface_queue.py", line 401, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface_queue.py", line 237, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\wandb_run.py", line 149, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface.py", line 120, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface_queue.py", line 411, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\interface\interface_queue.py", line 237, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
```

How can I fixt it and start training?

### Environment

- YOLO: YOLOv5  2021-11-22 torch 1.8.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2080 Super, 8192MiB)
- OS: Windows 10
- Python: 3.8.3

### Minimal Reproducible Example

 `python train.py --img 960 --batch 4 --epochs 100 --data "D:\repositories\yolov5Test\train\shapes.yaml" --weights yolov5n.pt`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AyushExel can you take a look at this? Thanks!

**Comment by AyushExel** [comment]
@sergorl is this a one time thing or is it happening every time you try to run the script?

**Comment by sergorl** [comment]
@AyushExel , I made some investigations through experiments and it seems it happens every time when batch size > 1, like `--batch 4`

**Comment by AyushExel** [comment]
@sergorl okay thanks for the info. I'll investigate and get back to you

**Comment by AyushExel** [comment]
@sergorl maybe try to run the latest of yolov5 and wandb. I wasn't able to reproduce this issue. Let me know if you still encounter this

**Comment by HannahHaensen** [comment]
@AyushExel I encounter the same issue with batchsize >1

**Comment by AyushExel** [comment]
@HannahHaensen hey are you on the latest version of yolov5 and wandb ?

**Comment by HannahHaensen** [comment]
@AyushExel yes, just updated everything due to this bug 4 hours ago, as i saw this thread

**Comment by AyushExel** [comment]
@HannahHaensen thanks. I think I found out the problem. It is actually a windows error but just after that error is raised, wandb also crashes. 
Try to do run the script again after disabling wandb. You should still see the error
```
wandb disabled
python train.py --batch-size 2
```
I got the following error. It is the same as this original issue
![Screenshot (91)](https://user-images.githubusercontent.com/15766192/143475554-617248ca-4755-4f1c-bf1a-65ec75bfbf1f.png)
```
OSError: [WinError 1455] The paging file is too small for this operation to complete
```
This is the main problem.  I see that this was[ reported in yolov3](https://github.com/ultralytics/yolov3/issues/1643) some time ago now. A user seemed to have solved the issue by manually setting `nw = 1`

@glenn-jocher tagging you in case you know a better workaround for this?

**Comment by HannahHaensen** [comment]
@AyushExel i am aware of the nw=1 setting to one for windows, i already did this, still same error. I also checked out the thread at yolov3

I agree on the WindowsError, but even with nw=1 and disabled wanddb this error still happens to me

**Comment by alaap001** [comment]
I am facing the same on ubuntu 20 machine while Evolving. Any solution to this?
