### ISSUE TITLE
wandb --resume train error  

### ISSUE THREAD

**Issue by Wilbertbh-Tan** [ultralytics/yolov5#5961]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Getting a train error with the data loader when resuming to the wandb checkpoint on colab. Odd thing is the code worked fine previously, but now running the resume gives me this error in train.py. When I re-run training from the start it works fine so that would mean that the directories and files are in the right place. A. My yolov5 is up to date, same for wandb. Any suggestions for getting around this?

Input: 

```
 run_path = "myrunpath"
 !python train.py --resume wandb-artifact://{myrunpath}  #--img 1280 --epochs 40 --data coral.yaml --save-period 5
```

Output
```
wandb: Currently logged in as: myname(use `wandb login --relogin` to force relogin)
train: weights=yolov5s.pt, cfg=, data=data/coco128.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=300, batch_size=16, imgsz=640, rect=False, resume=wandb-artifact://wilbert28/DeathStar/3noqzdmz, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=0, save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.0-139-g8f35436 torch 1.10.0+cu111 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
wandb: Tracking run with wandb version 0.12.7
wandb: Resuming run yolov5x_baseline_40epoch
wandb: Downloading large artifact run_3noqzdmz_model:latest, 659.30MB. 1 files... Done. 0:0:0

                 from  n    params  module                                  arguments                     
  0                -1  1      8800  models.common.Conv                      [3, 80, 6, 2, 2]              
  1                -1  1    115520  models.common.Conv                      [80, 160, 3, 2]               
  2                -1  4    309120  models.common.C3                        [160, 160, 4]                 
  3                -1  1    461440  models.common.Conv                      [160, 320, 3, 2]              
  4                -1  8   2259200  models.common.C3                        [320, 320, 8]                 
  5                -1  1   1844480  models.common.Conv                      [320, 640, 3, 2]              
  6                -1 12  13125120  models.common.C3                        [640, 640, 12]                
  7                -1  1   7375360  models.common.Conv                      [640, 1280, 3, 2]             
  8                -1  4  19676160  models.common.C3                        [1280, 1280, 4]               
  9                -1  1   4099840  models.common.SPPF                      [1280, 1280, 5]               
 10                -1  1    820480  models.common.Conv                      [1280, 640, 1, 1]             
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  4   5332480  models.common.C3                        [1280, 640, 4, False]         
 14                -1  1    205440  models.common.Conv                      [640, 320, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  4   1335040  models.common.C3                        [640, 320, 4, False]          
 18                -1  1    922240  models.common.Conv                      [320, 320, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  4   4922880  models.common.C3                        [640, 640, 4, False]          
 21                -1  1   3687680  models.common.Conv                      [640, 640, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  4  19676160  models.common.C3                        [1280, 1280, 4, False]        
 24      [17, 20, 23]  1     40374  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [320, 640, 1280]]
Model Summary: 567 layers, 86217814 parameters, 86217814 gradients, 204.2 GFLOPs

Transferred 745/745 items from artifacts/run_3noqzdmz_model:v1/last.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 123 weight, 126 weight (no decay), 126 bias
albumentations: version 1.0.3 required by YOLOv5, but version 0.1.12 is currently installed
Traceback (most recent call last):
  File "/content/yolov5/utils/datasets.py", line 407, in __init__
    raise Exception(f'{prefix}{p} does not exist')
Exception: train: train does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 626, in <module>
    main(opt)
  File "train.py", line 523, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 216, in train
    prefix=colorstr('train: '), shuffle=True)
  File "/content/yolov5/utils/datasets.py", line 109, in create_dataloader
    prefix=prefix)
  File "/content/yolov5/utils/datasets.py", line 412, in __init__
    raise Exception(f'{prefix}Error loading data from {path}: {e}\nSee {HELP_URL}')
Exception: train: Error loading data from train: train: train does not exist
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
```

**Comment by AyushExel** [comment]
@Wilbertbh-Tan can you share your run link that you're trying to resume?

**Comment by Wilbertbh-Tan** [comment]
Thank you.

the run can be found here: 
wilbert28/DeathStar/1yjmrmtz



Datafile 
```
train: wandb-artifact://DeathStar/train
val: wandb-artifact://DeathStar/val
nc: 1  
names: ['starfish'] 
```


```
# # Resume yolox_baseline
run_path = 'wilbert28/DeathStar/gxyw01qj'
!python train.py --img 1280 --epoch 40 --resume wandb-artifact://{run_path} --data wandb_star.yaml #--img 1280 --epochs 40 --data coral_wandb.yaml --save-period 5
```

**Comment by Wilbertbh-Tan** [comment]
@AyushExel 
I managed to fix the error by porting all the data to wandb via yaml. Previously I had my datafiles downloaded and unzipped to a virtual environment (colab), and although the dataset was the same each time and stored locally, when I tried to restore the epoch checkpoint using wandb it wasn't able to find the dataset.

**Comment by AyushExel** [comment]
@Wilbertbh-Tan that's a nice workaround. The runs that upload the data via `--upload_data` or start training from _wandb.yaml files can automatically be resumed on any device.
