### ISSUE TITLE
Evolve - Anchors behavior

### ISSUE THREAD

**Issue by Camilochiang** [ultralytics/yolov5#6079]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, Little question here :)
So after fitting several models (30-40?), I decide that was time to improve one of them, specially as the detection was not so good.
First I run:
``` 
python3 train.py --img 1024 --weights yolov5n.pt --epoch 1 --data apples.yaml
``` 
and observe the following hyperparameters and last layer configuration
``` 
lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0

 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [64, 128, 256]]
``` 
 Looks good. We can see the anchors of yolov5n in the last layer. Then when I run 
``` 
python3 train.py --img 1024 --weights yolov5n.pt --epoch 10 --data apples.yaml --cache --evolve
``` 
I had the error mention on #3482 , related to kmeas. To avoid this I follow the recommendation and add two things:
- the flag :  --noautoanchor
- the anchors to my yaml file who finish partially like this (to keep the same anchors later during training) 
```
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```
Running the following command:
```
python3 train.py --img 1024 --weights yolov5n.pt --epoch 10 --data Agroscope_apples.yaml --cache --evolve --noautoanchor
```
give me this for each iteration:
```
lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, anchors=3
24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.01029, lrf=0.11421, momentum=0.93013, weight_decay=0.0005, warmup_epochs=2.61299, warmup_momentum=0.89976, warmup_bias_lr=0.10843, box=0.05694, cls=0.5, cls_pw=0.92142, obj=0.8267, obj_pw=0.94387, iou_t=0.2, anchor_t=3.92884, fl_gamma=0.0, hsv_h=0.01325, hsv_s=0.7263, hsv_v=0.4, degrees=0.0, translate=0.09819, scale=0.49122, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, anchors=2.38802
 24      [17, 20, 23]  1      5412  models.yolo.Detect                      [1, [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], [64, 128, 256]]

 lr0=0.01149, lrf=0.1, momentum=0.9419, weight_decay=0.00044, warmup_epochs=3.63948, warmup_momentum=0.94268, warmup_bias_lr=0.11321, box=0.05, cls=0.50063, cls_pw=0.93907, obj=0.94729, obj_pw=1.14027, iou_t=0.2, anchor_t=4.24644, fl_gamma=0.0, hsv_h=0.0147, hsv_s=0.7, hsv_v=0.40228, degrees=0.0, translate=0.10495, scale=0.54109, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, anchors=2.83657
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

 lr0=0.00911, lrf=0.10484, momentum=0.94711, weight_decay=0.00055, warmup_epochs=3.02799, warmup_momentum=0.73544, warmup_bias_lr=0.10422, box=0.05, cls=0.40406, cls_pw=0.96561, obj=1.0, obj_pw=0.76282, iou_t=0.2, anchor_t=4.38711, fl_gamma=0.0, hsv_h=0.01631, hsv_s=0.77317, hsv_v=0.39914, degrees=0.0, translate=0.09751, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.97855, mixup=0.0, copy_paste=0.0, anchors=2.92104
  24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

 lr0=0.00975, lrf=0.1, momentum=0.9679, weight_decay=0.00049, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.11008, box=0.04345, cls=0.5, cls_pw=0.87619, obj=1.18109, obj_pw=0.95588, iou_t=0.2, anchor_t=5.52306, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.08955, scale=0.45408, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.95755, mixup=0.0, copy_paste=0.0, anchors=2.60779	
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.00675, lrf=0.10051, momentum=0.89989, weight_decay=0.00062, warmup_epochs=4.25126, warmup_momentum=0.91738, warmup_bias_lr=0.10422, box=0.04115, cls=0.40406, cls_pw=0.8174, obj=1.0, obj_pw=0.80256, iou_t=0.2, anchor_t=4.12261, fl_gamma=0.0, hsv_h=0.01631, hsv_s=0.77317, hsv_v=0.39914, degrees=0.0, translate=0.09751, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.97855, mixup=0.0, copy_paste=0.0, anchors=2.87081
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

 lr0=0.00918, lrf=0.09611, momentum=0.98, weight_decay=0.00048, warmup_epochs=2.26409, warmup_momentum=0.67465, warmup_bias_lr=0.11157, box=0.04433, cls=0.36539, cls_pw=1.05268, obj=0.98725, obj_pw=0.76282, iou_t=0.2, anchor_t=4.11224, fl_gamma=0.0, hsv_h=0.01778, hsv_s=0.75475, hsv_v=0.40064, degrees=0.0, translate=0.11381, scale=0.38803, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.99308, mixup=0.0, copy_paste=0.0, anchors=2.88296
24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.01104, lrf=0.11745, momentum=0.83933, weight_decay=0.00055, warmup_epochs=3.028, warmup_momentum=0.79645, warmup_bias_lr=0.09842, box=0.06017, cls=0.5087, cls_pw=0.96561, obj=0.84657, obj_pw=0.98506, iou_t=0.2, anchor_t=4.85172, fl_gamma=0.0, hsv_h=0.01422, hsv_s=0.61317, hsv_v=0.42146, degrees=0.0, translate=0.09295, scale=0.56667, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.97855, mixup=0.0, copy_paste=0.0, anchors=2.58528
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.01149, lrf=0.09977, momentum=0.9419, weight_decay=0.00044, warmup_epochs=3.66784, warmup_momentum=0.92804, warmup_bias_lr=0.11321, box=0.04996, cls=0.49936, cls_pw=0.93335, obj=0.93385, obj_pw=1.14523, iou_t=0.2, anchor_t=4.2245, fl_gamma=0.0, hsv_h=0.01478, hsv_s=0.70969, hsv_v=0.40487, degrees=0.0, translate=0.10495, scale=0.52887, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.99898, mixup=0.0, copy_paste=0.0, anchors=2.86228
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.01068, lrf=0.10366, momentum=0.96769, weight_decay=0.00056, warmup_epochs=3.6678, warmup_momentum=0.95, warmup_bias_lr=0.11321, box=0.04216, cls=0.61736, cls_pw=0.93335, obj=0.76826, obj_pw=1.1452, iou_t=0.2, anchor_t=3.07033, fl_gamma=0.0, hsv_h=0.01478, hsv_s=0.74055, hsv_v=0.40487, degrees=0.0, translate=0.10133, scale=0.48414, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.99898, mixup=0.0, copy_paste=0.0, anchors=2.57308
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.01149, lrf=0.09655, momentum=0.95652, weight_decay=0.00038, warmup_epochs=4.89032, warmup_momentum=0.8634, warmup_bias_lr=0.10822, box=0.0451, cls=0.49936, cls_pw=0.81087, obj=0.93385, obj_pw=1.122, iou_t=0.2, anchor_t=4.18764, fl_gamma=0.0, hsv_h=0.01378, hsv_s=0.58047, hsv_v=0.42186, degrees=0.0, translate=0.11362, scale=0.45198, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, anchors=3.09563
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.01043, lrf=0.11615, momentum=0.94258, weight_decay=0.00044, warmup_epochs=3.13844, warmup_momentum=0.92804, warmup_bias_lr=0.11097, box=0.04996, cls=0.49936, cls_pw=0.6372, obj=0.74345, obj_pw=1.38242, iou_t=0.2, anchor_t=4.25913, fl_gamma=0.0, hsv_h=0.01478, hsv_s=0.67397, hsv_v=0.47802, degrees=0.0, translate=0.10495, scale=0.52887, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.99898, mixup=0.0, copy_paste=0.0, anchors=2.40702
 24      [17, 20, 23]  1      5412  models.yolo.Detect                      [1, [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], [64, 128, 256]]

 lr0=0.01149, lrf=0.09977, momentum=0.9105, weight_decay=0.00044, warmup_epochs=3.6678, warmup_momentum=0.91396, warmup_bias_lr=0.10299, box=0.04698, cls=0.46709, cls_pw=0.93335, obj=0.93385, obj_pw=1.1924, iou_t=0.2, anchor_t=3.79098, fl_gamma=0.0, hsv_h=0.01478, hsv_s=0.70053, hsv_v=0.40487, degrees=0.0, translate=0.09503, scale=0.55581, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, anchors=3.37965
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]

lr0=0.01149, lrf=0.09977, momentum=0.94185, weight_decay=0.00044, warmup_epochs=3.67136, warmup_momentum=0.929, warmup_bias_lr=0.11319, box=0.04998, cls=0.49936, cls_pw=0.93287, obj=0.93385, obj_pw=1.14601, iou_t=0.2, anchor_t=4.2245, fl_gamma=0.0, hsv_h=0.01477, hsv_s=0.71014, hsv_v=0.40472, degrees=0.0, translate=0.10485, scale=0.52887, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.99994, mixup=0.0, copy_paste=0.0, anchors=2.86251
 24      [17, 20, 23]  1      8118  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 256]]
```

Then , I have a couple of questions:
- Why even though I gave the flag no autoanchor, we can see that is using other anchors than the once present in the yaml file?
- Will this evolve be optimal as it is not using the same initial anchors that will be given later in the real training?
-  Naive question: What do you refer in your code to anchors? I see that can take decimal values and I thought that this should be a int.

Thanks!

### Additional

And actually, now meanwhile I was writing this, there is no new output and the terminal is just not doing anything for the last 20 minutes (And I have way more than enough VRAM: using 4.6 of 16 G).

**Comment by glenn-jocher** [comment]
@Camilochiang --noautoanchor will prevent autoanchor from running. Evolution seeds initial anchors with poor values to trigger autoanchor unless `anchors` key is uncommented and `anchors: 0` is passed in your hyp file as comments show:

https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/data/hyps/hyp.scratch.yaml#L20

**Comment by Camilochiang** [comment]
Wow! Super quick. Thanks @glenn-jocher . 
I apologize, but I'm not understading the situation.

With `anchors` uncommented and `anchors:0`  evolve still start with the following anchors
```
 24      [17, 20, 23]  1      5412  models.yolo.Detect                      [1, [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], [64, 128, 256]]
```
I have been passing the anchors in the configuration yaml until now. Or should I put it in the hyp.yaml? I did that and I get an error
```
Traceback (most recent call last):
  File "train.py", line 629, in <module>
    main(opt)
  File "train.py", line 602, in main
    hyp[k] = max(hyp[k], v[1])  # lower limit
TypeError: '>' not supported between instances of 'float' and 'list'
```

**Comment by glenn-jocher** [comment]
@Camilochiang if you set `anchors: 0` in your hyp file, it will not evolve over the anchor count dimension, i.e. if you have 3 anchors it will always use 3 anchors. It will always initialize temporary anchors and apply AutoAnchor. Therefore when you pass --noautoanchor it uses the temporary anchors. This is not recommend.

**Comment by Camilochiang** [comment]
Hei @glenn-jocher Thanks for your recommendation! For sure I will not run them together.

Please correct me if I'm wrong but I believe that there is a small bug

In line train.py, line [532](https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/train.py#L532) you define `meta`, where by default `anchors` take values : 2, 2.0 ,10
`meta` overwrite the parameters of `hyp` during the cycle present in line [599,](https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/train.py#L599) therefore even if you set `anchor:0` and uncomment the line in your hyp file , this value will change to 2 in your first evolve cycle.

As you use `anchors` as boolean later in line 100 of [yolo.py,](https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/models/yolo.py#L100) this overwrite the model changing the anchors.

After doing a small change (for now I just add ` hyp['anchors'] = 0` after the cycle that start in line 599), I can get to run with evolve, fix number of anchors and the same anchors of the model given in my yaml file :D

So we went from this:

To this:
```
 python3 train.py --img 1024 --weights yolov5n.pt --epoch 10 --data apples.yaml --cache --cfg yolov5s.yaml --evolve
24      [17, 20, 23]  1      5412  models.yolo.Detect                      [1, [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], [64, 128, 256]] 
```
To this:
```
python3 train.py --img 1024 --weights yolov5n.pt --epoch 10 --data apples.yaml --cache --cfg yolov5s.yaml --evolve
24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
```

**Comment by glenn-jocher** [comment]
@Camilochiang oops, yes perhaps there is a bug there! Yes Meta defines the gain and bounds on each hyp. Anchors unfortunately are handled a bit uniquely in several places, as they are defined in the model.yaml (as either an integer and an array), and their count in hyp.yaml. 

If you have a good solution for simplifying the implementation or patching this bug please help other users out by submitting a PR. Thank you!
