### ISSUE TITLE
python3 -m onnxsim traingingmodel.onnx  convert_simple.onnx  

### ISSUE THREAD

**Issue by fsy8515-dev** [ultralytics/yolov5#62]
Before submitting a bug report, please ensure that you are using the latest versions of:
 - Python
 - PyTorch
 - This repository (run `git fetch && git status -uno` to check and `git pull` to update)
 
**Your issue must be reproducible on a public dataset (i.e COCO) using the latest version of the repository, and you must supply code to reproduce, or we can not help you.**

If this is a custom training question we suggest you include your `train*.jpg`, `test*.jpg` and `results.png` figures.

## To Reproduce
**REQUIRED**: Code to reproduce your issue below
```
python train.py ...
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by fsy8515-dev** [comment]
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Conv node. Name:'' Status Message: Input channels C is not equal to kernel channels * group. C: 257 kernel channels: 768 group: 1

**Comment by glenn-jocher** [comment]
@fsy8515-dev If this is a bug report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.

**Comment by fsy8515-dev** [comment]
fsy@arcsoft-03:~/yolov5-master/weights$ python3 -m onnxsim  ./best.onnx ./simple                                                                                                                                                             .onnx
Simplifying...
2020-06-15 13:25:58.438252932 [E:onnxruntime:, sequential_executor.cc:281 Execut                                                                                                                                                             e] Non-zero status code returned while running Conv node. Name:'' Status Message                                                                                                                                                             : Input channels C is not equal to kernel channels * group. C: 257 kernel channe                                                                                                                                                             ls: 768 group: 1
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fsy/.local/lib/python3.5/site-packages/onnxsim/__main__.py", line                                                                                                                                                              48, in <module>
    main()
  File "/home/fsy/.local/lib/python3.5/site-packages/onnxsim/__main__.py", line                                                                                                                                                              36, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_o                                                                                                                                                             ptimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes)
  File "/home/fsy/.local/lib/python3.5/site-packages/onnxsim/onnx_simplifier.py"                                                                                                                                                             , line 311, in simplify
    res = forward_for_node_outputs(model, const_nodes, input_shapes=input_shapes                                                                                                                                                             )
  File "/home/fsy/.local/lib/python3.5/site-packages/onnxsim/onnx_simplifier.py"                                                                                                                                                             , line 160, in forward_for_node_outputs
    res = forward(model, input_shapes=input_shapes)
  File "/home/fsy/.local/lib/python3.5/site-packages/onnxsim/onnx_simplifier.py"                                                                                                                                                             , line 150, in forward
    res = OrderedDict(zip(outputs, sess.run(outputs, inputs, run_options=run_opt                                                                                                                                                             ions)))
  File "/home/fsy/.local/lib/python3.5/site-packages/onnxruntime/capi/session.py                                                                                                                                                             ", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL                                                                                                                                                              : Non-zero status code returned while running Conv node. Name:'' Status Message:                                                                                                                                                              Input channels C is not equal to kernel channels * group. C: 257 kernel channel                                                                                                                                                             s: 768 group: 1

**Comment by glenn-jocher** [comment]
@fsy8515-dev you may want to raise this on the repo that is causing the error instead of here. This is not our code.

**Comment by zhangyilalala** [comment]
@fsy8515-dev  Hi~ I meet the same problem,have you solved this problem?

**Comment by glenn-jocher** [comment]
@zhangyilalala onnx issues should be raised on the relevant repo. This error originates outside of this repository.

**Comment by fsy8515-dev** [comment]
> @fsy8515-dev Hi~ I meet the same problem,have you solved this problem?
    已经解决了，我是把python（3.7）和pytorch（1.5）的版本更新为作者的版本，后来转化就可以了

**Comment by zhangyilalala** [comment]
@fsy8515-dev  好的，谢谢！ @glenn-jocher sorry~~~
