### ISSUE TITLE
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 

### ISSUE THREAD

**Issue by ouening** [ultralytics/yolov5#6205]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

```
detect: weights=yolov5s.pt, source=0, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5  v6.0-177-g5402753 torch 1.10.1+cu113 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)

Fusing layers...
Model Summary: 224 layers, 7266973 parameters, 0 gradients
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

0: 480x640 Done. (0.337s)
Traceback (most recent call last):
  File "D:\Github\yolov5\detect.py", line 257, in <module>
    main(opt)
  File "D:\Github\yolov5\detect.py", line 252, in main
    run(**vars(opt))
  File "D:\Applications\WPy64-3950\python-3.9.5.amd64\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "D:\Github\yolov5\detect.py", line 132, in run
    pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
  File "D:\Github\yolov5\utils\general.py", line 722, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "D:\Applications\WPy64-3950\python-3.9.5.amd64\lib\site-packages\torchvision\ops\boxes.py", line 35, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\cpu\nms_kernel.cpp:111 [kernel]
QuantizedCPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:18 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:35 [backend fallback]
AutogradCPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:39 [backend fallback]
AutogradCUDA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:47 [backend fallback]
AutogradXLA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:51 [backend fallback]
AutogradLazy: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:55 [backend fallback]
AutogradXPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:43 [backend fallback]
AutogradMLC: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:59 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:291 [backend fallback]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:305 [backend fallback]
Batched: registered at ..\aten\src\ATen\BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
```

### Environment

- OS: Windows11
- CUDA: Cuda compilation tools, release 11.3, V11.3.58, Build cuda_11.3.r11.3/compiler.29745058_0
- GPU: RTX 3060
- Python: 3.9
- Pytorch: 1.10.1
- torchvision: 0.11.2
- YOLOV5: v6.0-177-g5402753

### Minimal Reproducible Example

```
python detect.py --source 0
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ouening** [comment]
My mistake. After installing the correct version of `torchvision`, the problem solved.
`pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

**Comment by shahkarKhan24** [comment]
I am facing same issue

**Comment by glenn-jocher** [comment]
@shahkarKhan24 this issue occurs when `torchvision` is not compatible with the installed version of PyTorch or CUDA. Make sure that you have installed the correct version of `torchvision` that is compatible with your PyTorch and CUDA versions. 

You can use a command like the following to install the correct version of `torchvision` with CUDA support for PyTorch 1.10.1:

```
pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

If this does not solve your issue, please provide more information about your environment and the steps to reproduce the error.
