### ISSUE TITLE
Error when trying to run YOLOv5 detection 

### ISSUE THREAD

**Issue by Sqchia** [ultralytics/yolov5#6272]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I am currently doing a project where I connected drone live stream to YOLOv5. One of my drones while RTMP to YOLOv5, I received an error. 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "E:\yolov5-master\utils\datasets.py", line 341, in update
    time.sleep(1 / self.fps[i])  # wait time
ValueError: Invalid value NaN (not a number)
Traceback (most recent call last):
  File "E:\yolov5-master\detect.py", line 243, in <module>
    main(opt)
  File "E:\yolov5-master\detect.py", line 238, in main
    run(**vars(opt))
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\yolov5-master\detect.py", line 194, in run
    t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
  File "E:\yolov5-master\detect.py", line 194, in <genexpr>
    t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
ZeroDivisionError: float division by zero
```

Only this drone when RTMP to YOLOv5, this error shows up. Another drone works fine though. 
Anyone who knows how to solve this problem, please help me. Thanks in advance!

**Comment by glenn-jocher** [comment]
@Sqchia your code is out of date. Update your code.

**Comment by Sqchia** [comment]
> @Sqchia your code is out of date. Update your code.

Oh Okay, Thank you! :)
