### ISSUE TITLE
val.py does not run well on gpu

### ISSUE THREAD

**Issue by antran89** [ultralytics/yolov5#6378]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

docker@94401437f0ef:/data/ot-workspace/yolov5$ python val.py --data data/ourdata.yaml --img 640 --conf 0.001 --iou-thres 0.65 --weights best_privacy_yolov5_not-focus_deconv4.pt --device 0
val: data=data/ourdata.yaml, weights=['best_privacy_yolov5_not-focus_deconv4.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, task=val, device=0, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v6.0-206-g9419b3d torch 1.8.0 CUDA:0 (Tesla V100-PCIE-16GB, 16160MiB)

Fusing layers...
Model Summary: 223 layers, 7382079 parameters, 0 gradients
val: Scanning '/data/vdata/blurring/labels/valid.cache' images and labels... 7660 found, 0 missing, 298 empty, 0 corrupt: 100%|███████████████| 7660/7660 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/240 [00:00<?, ?it/s]                                           torch.FloatTensor
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/240 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "val.py", line 384, in <module>
    main(opt)
  File "val.py", line 357, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 194, in run
    out, train_out = model(im) if training else model(im, augment=augment, val=True)  # inference, loss outputs
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/ot-workspace/yolov5/models/common.py", line 397, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/ot-workspace/yolov5/models/yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/data/ot-workspace/yolov5/models/yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/ot-workspace/yolov5/models/common.py", line 50, in forward_fuse
    return self.act(self.conv(x))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

### Environment

ubuntu inside a docker

### Minimal Reproducible Example

```
python val.py --data data/ourdata.yaml --img 640 --conf 0.001 --iou-thres 0.65 --weights best_privacy_yolov5_not-focus_deconv4.pt --device 0
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by antran89** [comment]
I figured it out, because I changed something in the code!

**Comment by jersonal** [comment]
> I figured it out, because I changed something in the code!

I met the same problem, how did you solve it?

**Comment by iamdami** [comment]
There are various reasons but I figured it out by changing the batch size!

**Comment by glenn-jocher** [comment]
@iamdami great to hear that you were able to resolve the issue! Changing the batch size can indeed have a significant impact on the performance of the validation script. Besides batch size, there are other factors such as available GPU memory and model architecture that can also affect the script's performance. If you have any more questions or need further assistance, feel free to ask!
