### ISSUE TITLE
TypeError: Object does not appear to be a 8-bit string path or a Python file-like object

### ISSUE THREAD

**Issue by llzhaoshuo** [ultralytics/yolov5#643]
## ❔Question
when I use my own dataset run this :
python train.py --img 640 --batch 4 --epochs 50 --data ./data/coco128.yaml --cfg ./models/yolov5s.yaml --weights ''
I get the following error :

Traceback (most recent call last):
  File "train.py", line 477, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 217, in train
    plot_labels(labels, save_dir=log_dir)
  File "/media/lzs/de2ef254-eaa4-4486-b00b-ab367ed2a6d8/home/yolov5/utils/general.py", line 1161, in plot_labels
    plt.savefig(Path(save_dir) / 'labels.png', dpi=200)
  File "/home/lzs/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/lzs/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/lzs/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 172, in print_figure
    super(FigureCanvasQTAggBase, self).print_figure(*args, **kwargs)
  File "/home/lzs/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2259, in print_figure
    **kwargs)
  File "/home/lzs/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 526, in print_png
    self.figure.dpi, metadata=metadata)
TypeError: Object does not appear to be a 8-bit string path or a Python file-like object

**Comment by glenn-jocher** [comment]
@llzhaoshuo if you can train correctly on coco128, but not your dataset, then I believe you know the source of the problem...
