### ISSUE TITLE
Show the weight epoch when validation

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#6553]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

In the val.py, I try to add this to show the weight epoch.
Do you have other method to get weight epoch ?

```
        ckpt = torch.load(weights)  # load checkpoint
        print(f"The weight is {ckpt['epoch']} epoch")
```

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 308, in _check_seekable
    f.seek(f.tell())
AttributeError: 'list' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "val.py", line 370, in <module>
    main(opt)
  File "val.py", line 343, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 125, in run
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'list' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@alicera your error is unrelated to the code you showed. Your checkpoint is simply corrupted or has some issue:

```
  File "val.py", line 125, in run
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
```

**Comment by alicera** [comment]
Hi,
How can I show the weight epoch in the val.py ?
In the train.py it use the ckpt['epoch'] to get the epoch

**Comment by glenn-jocher** [comment]
The epoch key will only be populated during training, after training it is reset to -1 to allow the *.pt file to be used as pretrained weights for a new training (like the official models).

**Comment by alicera** [comment]
In fact, the process of training will save the best.pt . And I want to know its epoch. Next time, when I train the dataset, I can set the epoch that the weight can get the good mAP quickly.
Is it a good idea to do this ?

For example,
I set the 300 epoch to train and get the best mAP at 150 epoch.
Next time, I can set about 160 epoch to train.

**Comment by glenn-jocher** [comment]
@alicera yeah I hear what you are saying. The main issue is the 'epoch' key tracks checkpoint epochs before they pass through strip_optimizer to prepare it for deployment or to use as pretrained weights:

https://github.com/ultralytics/yolov5/blob/006eb40ab72147dceef2ce0d37b5e0c8f4e2f216/utils/general.py#L769-L783
