### ISSUE TITLE
log_dataset.py: wandb_utils.py doesn't create/use correct data folder (if doesn't exist)

### ISSUE THREAD

**Issue by or-toledano** [ultralytics/yolov5#6605]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Traceback (most recent call last):
  File "yolov5_6/utils/loggers/wandb/log_dataset.py", line 30, in <module>
    create_dataset_artifact(opt)
  File "yolov5_6/utils/loggers/wandb/log_dataset.py", line 12, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "yolov5_6/utils/loggers/wandb/wandb_utils.py", line 190, in __init__
    self.data_dict = self.check_and_upload_dataset(opt)
  File "yolov5_6/utils/loggers/wandb/wandb_utils.py", line 203, in check_and_upload_dataset
    config_path = self.log_dataset_artifact(opt.data,
  File "yolov5_6/utils/loggers/wandb/wandb_utils.py", line 363, in log_dataset_artifact
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/mydata.yaml'

### Environment

Python 3.8

### Minimal Reproducible Example

log_dataset.py

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AyushExel seems like a W&B /data dir is not being created causing this error.

**Comment by or-toledano** [comment]
@glenn-jocher Fixed by PR #6606
