### ISSUE TITLE
W&B error on resume

### ISSUE THREAD

**Issue by wartek69** [ultralytics/yolov5#6822]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Hey
I'm using W&B on Google Collab to train a model, since Collab times out quite often the resume option of is a great addon!
I started training my model with the following command:
`!python train.py --img 1280 --batch -1 --epochs 300 --data /content/drive-mnt/yaml_configs/second_baseline.yaml --weights yolov5s.pt --project /content/drive-mnt/training_logs --save-period 10 --cache --upload_dataset`

After the first time collab timed-out I continued with
`!python train.py --resume wandb-artifact://alex69/training_logs/18xq5ecx --save-period 10`
This worked great and I trained the model further.

After that Collab timed-out again and I used exactly the same command to continue the training, but this time an issue appeared.

<details><summary>Strack trace</summary>

```
wandb: Currently logged in as: alex69 (use `wandb login --relogin` to force relogin)
train: weights=yolov5s.pt, cfg=, data=data/coco128.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=300, batch_size=16, imgsz=640, rect=False, resume=wandb-artifact://alex69/training_logs/18xq5ecx, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=10, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.1-11-g63ddb6f torch 1.10.0+cu111 CUDA:0 (Tesla K80, 11441MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
Problem at: /content/yolov5/utils/loggers/wandb/wandb_utils.py 156 __init__
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 622, in init
    run._set_run_obj(run_result.run)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1132, in _set_run_obj
    self.config._update(c_dict, allow_val_change=True, ignore_locked=True)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 175, in _update
    parsed_dict, allow_val_change, ignore_keys=locked_keys
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 227, in _sanitize_dict
    self._raise_value_error_on_nested_artifact(config_dict)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 266, in _raise_value_error_on_nested_artifact
    "Instances of wandb.Artifact and wandb.apis.public.Artifact"
ValueError: Instances of wandb.Artifact and wandb.apis.public.Artifact can only be top level keys in wandb.config
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 622, in init
    run._set_run_obj(run_result.run)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1132, in _set_run_obj
    self.config._update(c_dict, allow_val_change=True, ignore_locked=True)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 175, in _update
    parsed_dict, allow_val_change, ignore_keys=locked_keys
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 227, in _sanitize_dict
    self._raise_value_error_on_nested_artifact(config_dict)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 266, in _raise_value_error_on_nested_artifact
    "Instances of wandb.Artifact and wandb.apis.public.Artifact"
ValueError: Instances of wandb.Artifact and wandb.apis.public.Artifact can only be top level keys in wandb.config

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 643, in <module>
    main(opt)
  File "train.py", line 539, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 95, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "/content/yolov5/utils/loggers/__init__.py", line 73, in __init__
    self.wandb = WandbLogger(self.opt, run_id)
  File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 156, in __init__
    allow_val_change=True)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 992, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process wandb_internal:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal.py", line 162, in wandb_internal
    thread.join()
  File "/usr/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```
</details>

I do see the correct artifacts being present on my W&B home portal as can be seen from the following screenshot.
![Screenshot from 2022-03-02 10-51-52](https://user-images.githubusercontent.com/26298408/156338104-a9face6d-58e8-4038-ba24-9f6e045fd8a0.png)

Any clue what might be causing this and how to resolve it?
If I'm not mistaken W&B bugs are handled by @AyushExel so just to be sure I ping you if you don't mind :).
Looking forward to your reply!
Kind regards
Alex

### Environment

- Google Collab using a Tesla K80

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@wartek69 thanks for reporting this! 
* What version of wandb are you using? Was this happening in the previous version as well?
 I'll try to repro this today and get back

**Comment by AyushExel** [comment]
@wartek69 Okay I was able to confirm this. I think if you downgrade version 0.12.10, you'll be able to use this feature.. I'll see what's causing this and fix this. Meanwhile just downgrade

**Comment by wartek69** [comment]
@AyushExel Thank you for your prompt reply, downgrading did fix the issue for now.
