### ISSUE TITLE
ROS detect.py shows error while running on cuda

### ISSUE THREAD

**Issue by Phyrokar** [ultralytics/yolov5#6919]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello, I tried to deploy yolov5 in a ROS environment. For that I used this code: 
```

1. #!/usr/bin/env python3
2. 
3. import os
4. 
5. os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
6. 
7. 
8. # Python imports
9. import numpy as np
10. import cv2
11. 
12. # ROS imports
13. import rospy
14. import scipy.io as sio
15. import std_msgs.msg
16. # Deep Learning imports
17. import torch
18. import yaml
19. from cv_bridge import CvBridge, CvBridgeError
20. from geometry_msgs.msg import Point32, Polygon
21. from numpy import random
22. from rospkg import RosPack
23. from sensor_msgs.msg import Image
24. from skimage.transform import resize
25. from std_msgs.msg import UInt8
26. from torch.autograd import Variable
27. from yolov5_pytorch_ros.msg import BoundingBox, BoundingBoxes
28. 
29. from models.experimental import attempt_load
30. from utils.datasets import LoadImages, LoadStreams
31. from utils.general import (apply_classifier, check_img_size,
32.                            check_requirements, increment_path,
33.                            non_max_suppression, scale_coords, set_logging,
34.                            strip_optimizer)
35. from utils.plots import plot_one_box
36. # util + model imports
37. from utils.torch_utils import load_classifier, select_device, time_synchronized
38. 
39. package = RosPack()
40. package_path = package.get_path('yolov5_pytorch_ros')
41. 
42. 
43. class Detector:
44.     def __init__(self):
45.         # Load weights parameter
46.         self.weights_path = rospy.get_param('~weights_path')
47.         rospy.loginfo("Found weights, loading %s", self.weights_path)
48. 
49.         # Raise error if it cannot find the model
50.         if not os.path.isfile(self.weights_path):
51.             raise IOError(('{:s} not found.').format(self.weights_path))
52. 
53.         # Load image parameter and confidence threshold
54.         self.image_topic = rospy.get_param(
55.             '~image_topic', '/camera/rgb/image_raw')
56. 
57.         log_str = "Subscribing to image topic: %s" % self.image_topic
58.         rospy.loginfo(log_str)
59. 
60.         self.conf_thres = rospy.get_param('~confidence', 0.5)
61. 
62.         # Load other parameters
63.         self.device_name = 'cpu'
64.         self.device = select_device(self.device_name)
65.         self.gpu_id = rospy.get_param('~gpu_id', 0)
66.         self.network_img_size = rospy.get_param('~img_size', 416)
67.         self.publish_image = rospy.get_param('~publish_image')
68.         self.iou_thres = 0.45
69.         self.augment = True
70. 
71.         self.classes = None
72.         self.agnostic_nms = False
73. 
74.         self.w = 0
75.         self.h = 0
76. 
77.         # Second-stage classifier
78.         self.classify = False
79. 
80.         # Initialize
81.         self.half = self.device.type != 'cpu'  # half precision only supported on CUDA
82. 
83.         # Load model
84.         self.model = attempt_load(
85.             self.weights_path, map_location=self.device)  # load FP32 model
86.         self.stride = int(self.model.stride.max())      # model stride
87.         self.network_img_size = check_img_size(
88.             self.network_img_size, s=self.stride)  # check img_size
89. 
90.         if self.half:
91.             self.model.half()  # to FP16
92. 
93.         if self.classify:
94.             self.modelc = load_classifier(name='resnet101', n=2)  # initialize
95.             self.modelc.load_state_dict(torch.load(
96.                 'weights/resnet101.pt', map_location=self.device)['model']).to(self.device).eval()
97. 
98.         # Get names and colors
99.         self.names = self.model.module.names if hasattr(
100.             self.model, 'module') else self.model.names
101.         self.colors = [[random.randint(0, 255)
102.                         for _ in range(3)] for _ in self.names]
103. 
104.         # Run inference
105.         if self.device.type != 'cpu':
106.             self.model(torch.zeros(1, 3, self.network_img_size, self.network_img_size).to(
107.                 self.device).type_as(next(self.model.parameters())))  # run once
108. 
109.         # Load CvBridge
110.         self.bridge = CvBridge()
111. 
112.         # Load publisher topic
113.         self.detected_objects_topic = rospy.get_param(
114.             '~detected_objects_topic')
115.         self.published_image_topic = rospy.get_param('~detections_image_topic')
116. 
117.         # Define subscribers
118.         self.image_sub = rospy.Subscriber(
119.             self.image_topic, Image, self.image_cb, queue_size=1, buff_size=2**24)
120. 
121.         # Define publishers
122.         self.pub_ = rospy.Publisher(
123.             self.detected_objects_topic, BoundingBoxes, queue_size=10)
124.         self.pub_viz_ = rospy.Publisher(
125.             self.published_image_topic, Image, queue_size=10)
126.         rospy.loginfo("Launched node for object detection")
127. 
128.         # Spin
129.         rospy.spin()
130. 
131.     def image_cb(self, data):
132.         # Convert the image to OpenCV
133.         try:
134.             self.cv_img = self.bridge.imgmsg_to_cv2(data, "rgb8")
135.         except CvBridgeError as e:
136.             print(e)
137.         # Initialize detection results
138. 
139.         detection_results = BoundingBoxes()
140.         detection_results.header = data.header
141.         detection_results.image_header = data.header
142.         input_img = self.preprocess(self.cv_img)
143.         input_img = Variable(input_img.type(torch.FloatTensor))
144. 
145.         # Get detections from network
146.         with torch.no_grad():
147.             detections = self.model(input_img)[0]
148.             detections = non_max_suppression(detections, self.conf_thres, self.iou_thres,
149.                                              classes=self.classes, agnostic=self.agnostic_nms)
150.         # Parse detections
151.         if detections[0] is not None:
152.             for detection in detections[0]:
153.                 # Get xmin, ymin, xmax, ymax, confidence and class
154.                 xmin, ymin, xmax, ymax, conf, det_class = detection
155.                 pad_x = max(self.h - self.w, 0) * \
156.                     (self.network_img_size/max(self.h, self.w))
157.                 pad_y = max(self.w - self.h, 0) * \
158.                     (self.network_img_size/max(self.h, self.w))
159.                 unpad_h = self.network_img_size-pad_y
160.                 unpad_w = self.network_img_size-pad_x
161.                 xmin_unpad = ((xmin-pad_x//2)/unpad_w)*self.w
162.                 xmax_unpad = ((xmax-xmin)/unpad_w)*self.w + xmin_unpad
163.                 ymin_unpad = ((ymin-pad_y//2)/unpad_h)*self.h
164.                 ymax_unpad = ((ymax-ymin)/unpad_h)*self.h + ymin_unpad
165. 
166.                 # Populate darknet message
167.                 detection_msg = BoundingBox()
168.                 detection_msg.xmin = int(xmin_unpad)
169.                 detection_msg.xmax = int(xmax_unpad)
170.                 detection_msg.ymin = int(ymin_unpad)
171.                 detection_msg.ymax = int(ymax_unpad)
172.                 detection_msg.probability = float(conf)
173.                 detection_msg.Class = self.names[int(det_class)]
174. 
175.                 # Append in overall detection message
176.                 detection_results.bounding_boxes.append(detection_msg)
177. 
178.         # Publish detection results
179.         self.pub_.publish(detection_results)
180. 
181.         # Visualize detection results
182.         if (self.publish_image):
183.             self.visualize_and_publish(detection_results, self.cv_img)
184.         return True
185. 
186.     def preprocess(self, img):
187.         # Extract image and shape
188.         img = np.copy(img)
189.         img = img.astype(float)
190.         height, width, channels = img.shape
191.         if (height != self.h) or (width != self.w):
192.             self.h = height
193.             self.w = width
194.             # Determine image to be used
195.             self.padded_image = np.zeros(
196.                 (max(self.h, self.w), max(self.h, self.w), channels)).astype(float)
197. 
198.         # Add padding
199.         if (self.w > self.h):
200.             self.padded_image[(self.w-self.h)//2: self.h +
201.                               (self.w-self.h)//2, :, :] = img
202.         else:
203.             self.padded_image[:, (self.h-self.w)//2: self.w +
204.                               (self.h-self.w)//2, :] = img
205.         # Resize and normalize
206.         input_img = resize(self.padded_image, (self.network_img_size, self.network_img_size, 3))/255.
207. 
208.         # Channels-first
209.         input_img = np.transpose(input_img, (2, 0, 1))
210. 
211.         # As pytorch tensor
212.         input_img = torch.from_numpy(input_img).float()
213.         input_img = input_img[None]
214. 
215.         return input_img
216. 
217.     def visualize_and_publish(self, output, imgIn):
218.         # Copy image and visualize
219.         imgOut = imgIn.copy()
220.         font = cv2.FONT_HERSHEY_SIMPLEX
221.         fontScale = 0.8
222.         thickness = 2
223.         for index in range(len(output.bounding_boxes)):
224.             label = output.bounding_boxes[index].Class
225.             x_p1 = output.bounding_boxes[index].xmin
226.             y_p1 = output.bounding_boxes[index].ymin
227.             x_p3 = output.bounding_boxes[index].xmax
228.             y_p3 = output.bounding_boxes[index].ymax
229.             confidence = output.bounding_boxes[index].probability
230. 
231.             # Set class color
232.             color = self.colors[self.names.index(label)]
233. 
234.             # Create rectangle
235.             cv2.rectangle(imgOut, (int(x_p1), int(y_p1)), (int(x_p3), int(
236.                 y_p3)), (color[0], color[1], color[2]), thickness)
237.             text = ('{:s}: {:.3f}').format(label, confidence)
238.             cv2.putText(imgOut, text, (int(x_p1), int(y_p1+20)), font,
239.                         fontScale, (255, 255, 255), thickness, cv2.LINE_AA)
240. 
241.         # Publish visualization image
242.         image_msg = self.bridge.cv2_to_imgmsg(imgOut, "rgb8")
243.         image_msg.header.frame_id = 'camera'
244.         image_msg.header.stamp = rospy.Time.now()
245.         self.pub_viz_.publish(image_msg)
246. 
247. 
248. if __name__ == '__main__':
249.     rospy.init_node('detector')
250. 
251.     # Define detector object
252.     dm = Detector()

```
from https://github.com/raghavauppuluri13/yolov5_pytorch_ros

Everything runs fine on my CPU. But I would like to run the program on my GPU. 
So I changed line 63 from 
`self.device_name = 'cpu'`
 to 
`self.device_name = '0'`

That's when I encounter the error 
```
[ERROR] [1646838893.844289]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7f96407525b0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 76, in callback
    self.signalMessage(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 240, in add
    self.signalMessage(*msgs)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/home/matthias/catkin_ws/src/yolov5_pytorch_ros/src/detect.py", line 147, in image_cb
    detections = self.model(input_img)[0]
  File "/home/matthias/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/matthias/catkin_ws/src/yolov5_pytorch_ros/src/models/yolo.py", line 119, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/matthias/catkin_ws/src/yolov5_pytorch_ros/src/models/yolo.py", line 135, in forward_once
    x = m(x)  # run
  File "/home/matthias/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/matthias/catkin_ws/src/yolov5_pytorch_ros/src/models/common.py", line 132, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/home/matthias/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/matthias/catkin_ws/src/yolov5_pytorch_ros/src/models/common.py", line 60, in fuseforward
    return self.act(self.conv(x))
  File "/home/matthias/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/matthias/anaconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/matthias/anaconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

```

Anyone have an idea how I can solve the problem? 

### Environment

Ubuntu 20.04
Python 3.9.7
CUDA Version: 11.6 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Phyrokar 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by nhat-m-le** [comment]
I've deployed YOLOv5 on ROS Noetic here you can take a look https://github.com/mats-robotics/yolov5_ros
