### ISSUE TITLE
when i detect best.onnx on webcam i got " FileNotFoundError: [Errno 2] No such file or directory: '0' "

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#6982]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

when i try to detect using web camer i got this error, the camera is opend and closed and i got this error
the detect is work well with images

```
Loading best.onnx for ONNX Runtime inference...
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

Traceback (most recent call last):
  File "detect.py", line 394, in <module>
    main(opt)
  File "detect.py", line 389, in main
    run(**vars(opt))
  File "C:\Users\H\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 338, in run
    old_filename, x, summary_time,old_center = first(p, x, old_filename, id_, summary_time, count_n,old_center, xcenter[0])
  File "detect.py", line 114, in first
    g, t, d = (get_date(filename))
  File "detect.py", line 95, in get_date
    image_exif = Image.open(filename)
  File "C:\Users\H\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2912, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '0'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VYRION-Ai** [comment]
i happen in old version off yolov5 , i have to download the last version of the repo
