### ISSUE TITLE
ZED + YOLOv5 Implementation 

### ISSUE THREAD

**Issue by kmat231** [ultralytics/yolov5#7138]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation, Detection, Integrations

### Bug

OpenGL_accelerate module loaded
Using accelerated ArrayDatatype
Intializing Network...
Initializing Camera...
Initialized Camera
fatal: cannot change to '/usr/local/zed/samples/object': No such file or directory
YOLOv5 🚀 2022-3-20 torch 1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 3910MiB)

**freeglut (detector.py):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow**
/home/kanary/.local/lib/python3.8/site-packages/torch/_utils.py:79: UserWarning: CUDA warning: driver shutting down (Triggered internally at  ../c10/cuda/impl/CUDAGuardImpl.h:45.)
  return new_type(self.size()).copy_(self, non_blocking)
/home/kanary/.local/lib/python3.8/site-packages/torch/_utils.py:79: UserWarning: CUDA warning: driver shutting down (Triggered internally at  ../c10/cuda/impl/CUDAGuardImpl.h:61.)
  return new_type(self.size()).copy_(self, non_blocking)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
	self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
	self._target(*self._args, **self._kwargs)
  File "detector.py", line 100, in torch_thread
	model = attempt_load(weights, map_location=device)  # load FP32
  File "/usr/local/zed/samples/object detection/custom detector/python/pytorch_yolov5/./yolov5/models/experimental.py", line 96, in attempt_load
	ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
	return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/serialization.py", line 1046, in _load
	result = unpickler.load()
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/serialization.py", line 1016, in persistent_load
	load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/serialization.py", line 1001, in load_tensor
	wrap_storage=restore_location(storage, location),
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/serialization.py", line 973, in restore_location
	return default_restore_location(storage, str(map_location))
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/serialization.py", line 176, in default_restore_location
	result = fn(storage, location)
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/serialization.py", line 158, in _cuda_deserialize
	return obj.cuda(device)
  File "/home/kanary/.local/lib/python3.8/site-packages/torch/_utils.py", line 79, in _cuda
	return new_type(self.size()).copy_(self, non_blocking)
**RuntimeError: CUDA error: driver shutting down**
**CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.**
[1]-  Killed              	python3 object_detection.py  (wd: /usr/local/zed/samples/tutorials/tutorial 6 - object detection/python)
(wd now: /usr/local/zed/samples/object detection/custom detector/python/pytorch_yolov5)
[2]+  Killed              	python3 object_detection.py  (wd: /usr/local/zed/samples/tutorials/tutorial 6 - object detection/python)
(wd now: /usr/local/zed/samples/object detection/custom detector/python/pytorch_yolov5)

### Environment

- YOLOv5 🚀 2022-3-20 torch 1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 3910MiB)
- Ubuntu 20.04.4
- ZED SDK 3.7
- PyOpenGL 3.1.6  
- PyOpenGL-accelerate → 3.1.5 

### Minimal Reproducible Example

python3 detector.py –weights yolov5m.pt 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
fatal: cannot change to '/usr/local/zed/samples/object': No such file or directory

**Comment by Yousef-Alhattab** [comment]
did you solve it? I got same

**Comment by glenn-jocher** [comment]
@urbansound8K thanks for reaching out! The issue "fatal: cannot change to '/usr/local/zed/samples/object': No such file or directory" seems to be related to the file path. You may need to adjust the file path in your script to ensure it points to the correct location.

As for the CUDA error, it seems to be related to the GPU driver shutting down. Make sure your GPU drivers are up to date and consider setting CUDA_LAUNCH_BLOCKING=1 for debugging.

Let me know if you need further assistance!
