### ISSUE TITLE
How to use engine created with tensorrtx?

### ISSUE THREAD

**Issue by pglah** [ultralytics/yolov5#7603]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I created an `.engine` file from your `yolov5s6.pt` model,  using https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5. When I would like to run your detection script like `python3 detect.py --weights /data/yolov5s6rtx.engine --device 0 --imgsz 832` I get the following error: 

```
[04/27/2022-06:59:16] [TRT] [I] [MemUsageChange] Init CUDA: CPU +203, GPU +0, now: CPU 295, GPU 3810 (MiB)
[04/27/2022-06:59:16] [TRT] [I] Loaded engine size: 33 MB
[04/27/2022-06:59:16] [TRT] [I] [MemUsageSnapshot] deserializeCudaEngine begin: CPU 328 MiB, GPU 3877 MiB
[04/27/2022-06:59:17] [TRT] [E] 3: getPluginCreator could not find plugin: YoloLayer_TRT version: 1
[04/27/2022-06:59:17] [TRT] [E] 1: [pluginV2Runner.cpp::load::292] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[04/27/2022-06:59:17] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::76] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "detect.py", line 257, in <module>
    main(opt)
  File "detect.py", line 252, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 92, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
  File "/yolov5/models/common.py", line 345, in __init__
    for index in range(model.num_bindings):
AttributeError: 'NoneType' object has no attribute 'num_bindings'
```

The deserialization fails. How could I use the `.engine` file created with tensorrtx together with your detect backend? 

I am asking since I experienced a better performance while using the `.engine` file from tensorrtx on my Jetson Nano, rather than converting the `.pt` file to `.onnx` --> `.engine` 

I use your repo based on release 6.1. My TensorRT version is 8.2. 

Thanks in advance

**Comment by glenn-jocher** [comment]
@pglah please raise an issue directly on https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5 with this question, as I'm exactly sure what the differences might be.

**Comment by HarrySm** [comment]
@pglah ,

Hello have you succeeded to get it work?
