### ISSUE TITLE
Exported saved_model error when using TensorFlow Serving

### ISSUE THREAD

**Issue by pilgrim88** [ultralytics/yolov5#7707]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export, Other

### Bug

Hello,

I wanted to export a saved_model and use it with TensorFlow Serving  but I have some problems with this.

1. I use it with --agnostic-nms: `!python3 export.py --imgsz 256 512 --weights yolov5m.pt --include saved_model --iou-thres 0.6 --conf-thres 0.6 --agnostic-nms`
2. After the export the pb file is smaller than it was before (575MB->80MB)
3. When i try to inference it via TensorFlow Serving it gives me this error: 

```
_InactiveRpcError: _InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "input tensor alias not found in signature: input_1. Inputs expected to be in the set {x}."
```

4. When it worked it looked like this:

```
{
"model_spec":{
 "name": "yolo",
 "signature_name": "",
 "version": "1"
}
,
"metadata": {"signature_def": {
 "signature_def": {
  "serving_default": {
   "inputs": {
    "input_1": {
     "dtype": "DT_FLOAT",
     "tensor_shape": {
      "dim": [
       {
        "size": "1",
        "name": ""
       },
       {
        "size": "256",
        "name": ""
       },
       {
        "size": "512",
        "name": ""
       },
       {
        "size": "3",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "serving_default_input_1:0"
    }
   },
   "outputs": {
    "agnostic_nms_1_2": {
     "dtype": "DT_FLOAT",
     "tensor_shape": {
      "dim": [
       {
        "size": "1",
        "name": ""
       },
       {
        "size": "-1",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "StatefulPartitionedCall:2"
    },
...
```

5. And now it looks like this:

```
{
"model_spec":{
 "name": "yolo",
 "signature_name": "",
 "version": "1"
}
,
"metadata": {"signature_def": {
 "signature_def": {
  "serving_default": {
   "inputs": {
    "x": {
     "dtype": "DT_FLOAT",
     "tensor_shape": {
      "dim": [
       {
        "size": "1",
        "name": ""
       },
       {
        "size": "256",
        "name": ""
       },
       {
        "size": "512",
        "name": ""
       },
       {
        "size": "3",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "serving_default_x:0"
    }
   },
   "outputs": {
    "output_0": {
     "dtype": "DT_FLOAT",
     "tensor_shape": {
      "dim": [
       {
        "size": "1",
        "name": ""
       },
       {
        "size": "-1",
        "name": ""
       },
       {
        "size": "4",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "PartitionedCall:0"
    },
    "output_1": {
     "dtype": "DT_FLOAT",
     "tensor_shape": {
      "dim": [
       {
        "size": "1",
        "name": ""
       },
       {
        "size": "-1",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "PartitionedCall:1"
    },
...
```

What could be the problem?

Thank you.

### Environment

- YOLOv5 🚀 2022-5-5 torch 1.11.0+cu113 CPU
- Ubuntu 20.04
- TensorFlow 2.8.0
- TensorFlow Serving 2.8.0-gpu
- Python 3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pilgrim88 for issues generated by external tools I would recommend raising these directly with the tools themselves, as they are outside the scope of our knowledge or support.

**Comment by pilgrim88** [comment]
@glenn-jocher I tried this `!python3 export.py --imgsz 512 512 --weights yolov5m.pt --include saved_model --iou-thres 0.6 --conf-thres 0.6 --agnostic-nms` again and than I ran the detect.py `!python3 detect.py --weights /yolov5/yolov5m_saved_model --img 512 --conf 0.25 --source /yolov5/data/images/zidane.jpg` but got this error:

```
Loading /yolov5/yolov5m_saved_model for TensorFlow SavedModel inference...
2022-05-06 10:55:45.656551: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-06 10:55:45.660286: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-05-06 10:55:45.660305: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-05-06 10:55:45.660480: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Importing a function (__inference_pruned_10055) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
Traceback (most recent call last):
  File "detect.py", line 252, in <module>
    main(opt)
  File "detect.py", line 247, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 108, in run
    model.warmup(imgsz=(1 if pt else bs, 3, *imgsz))  # warmup
  File "/yolov5/models/common.py", line 478, in warmup
    self.forward(im)  # warmup
  File "/yolov5/models/common.py", line 451, in forward
    y = (self.model(im, training=False) if self.keras else self.model(im)).numpy()
AttributeError: 'list' object has no attribute 'numpy'
```

Without --nms or --agnostic-nms it worked properly with detect.py.

Any idea why does not it work with --agnostic-nms?

Thank you.

**Comment by glenn-jocher** [comment]
@pilgrim88 YOLOv5 model NMS is handled automatically by PyTorch, we don't currently support any fully pipelined models. These may be intended for other destinations like Android apps etc.
