### ISSUE TITLE
Prediction on CPU

### ISSUE THREAD

**Issue by Muhammad4hmed** [ultralytics/yolov5#780]
Hi, I trained my model on google colab using GPU following the tutorial posted on Roboflow.

I downloaded the weights in my local computer with CPU, tried to predict images using:
`!python detect.py --weights last_yolov5s_results2.pt --img 416 --conf 0.4 --source converted`

but got following error:
`Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=416, iou_thres=0.5, output='inference/output', save_txt=False, source='converted', update=False, view_img=False, weights=['last_yolov5s_results2.pt'])
Using CPU

Fusing layers... Model Summary: 120 layers, 6.8612e+06 parameters, 6.31725e+06 gradients
image 1/1170 C:\Users\Muhammad Ahmed\Desktop\DS\Hackathon\yolov5\converted\frame0.jpg: 

Traceback (most recent call last):
  File "detect.py", line 171, in <module>
    detect()
  File "detect.py", line 72, in detect
    pred = model(img, augment=opt.augment)[0]
  File "C:\Users\Muhammad Ahmed\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Muhammad Ahmed\Desktop\DS\Hackathon\yolov5\models\yolo.py", line 109, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "C:\Users\Muhammad Ahmed\Desktop\DS\Hackathon\yolov5\models\yolo.py", line 129, in forward_once
    x = m(x)  # run
  File "C:\Users\Muhammad Ahmed\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Muhammad Ahmed\Desktop\DS\Hackathon\yolov5\models\yolo.py", line 36, in forward
    x[i] = self.m[i](x[i])  # conv
  File "C:\Users\Muhammad Ahmed\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'
`

**Comment by NanoCode012** [comment]
Try a reclone. Your file is probably old.

```
File "C:\Users\Muhammad Ahmed\Desktop\DS\Hackathon\yolov5\models\yolo.py", line 36, in forward
x[i] = self.mi # conv
```
https://github.com/ultralytics/yolov5/blob/da35727c683dd38547ceebf697c25648a92b625c/models/yolo.py#L35-L40
