### ISSUE TITLE
Error Load Trained Model using torch.hub.load 

### ISSUE THREAD

**Issue by firqaaa** [ultralytics/yolov5#7985]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have trained YOLOv5 using custom dataset and result a custom .pt model. I want to do inference using this trained model using this code :

```
def load_model(ckpt_path, conf=0.25, iou=0.50):
    model = torch.hub.load("D:/Notebook/Projects/Python/kaggle/yolov5-lib-ds",
                           "custom",
                           path=ckpt_path,
                           source='local',
                           force_reload=True)
    model.conf = conf
    model.iou = iou
    model.classes = None
    model.multi_label = False
    model.max_det = 1000
    return model
```

```
CKPT_PATH = "D:/Notebook/Projects/Python/kaggle/yolov5/GreatBarrierReef/yolov5s_size500_epochs3_batch4_simple/weights/best.pt"
IMG_SIZE = 9000
CONF = 0.25
IOU = 0.40
AUGMENT = True

```
```
model = load_model(CKPT_PATH, conf=CONF, iou=IOU)
image_paths = df[df.num_bbox>1].sample(100).image_path.tolist()
for idx, path in enumerate(image_paths):
    img = cv2.imread(path)[...,::-1]
    bboxes, config = predict(model, img, size=IMG_SIZE, augment=AUGMENT)
    display(show_img(img, bboxes, bbox_format='coco'))
    if idx>5:
        break
```
But an error occurs. It says like this : 

```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "D:\Anaconda\envs\mmlab\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\firqa\AppData\Local\Temp\ipykernel_31824\1239863707.py", line 1, in <cell line: 1>
    model = load_model(CKPT_PATH, conf=CONF, iou=IOU)
  File "C:\Users\firqa\AppData\Local\Temp\ipykernel_31824\1264064108.py", line 2, in load_model
    model = torch.hub.load("D:/Notebook/Projects/Python/kaggle/yolov5-lib-ds",
  File "D:\Anaconda\envs\mmlab\lib\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\torch\hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "D:/Notebook/Projects/Python/kaggle/yolov5-lib-ds\hubconf.py", line 69, in custom
    return _create(path, autoshape=autoshape, verbose=verbose, device=device)
  File "D:/Notebook/Projects/Python/kaggle/yolov5-lib-ds\hubconf.py", line 30, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "D:\Notebook/Projects/Python/kaggle/yolov5-lib-ds\models\common.py", line 30, in <module>
    from utils.datasets import exif_transpose, letterbox
ModuleNotFoundError: No module named 'utils.datasets'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda\envs\mmlab\lib\site-packages\IPython\core\interactiveshell.py", line 1992, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "D:\Anaconda\envs\mmlab\lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "D:\Anaconda\envs\mmlab\lib\site-packages\IPython\core\ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "D:\Anaconda\envs\mmlab\lib\site-packages\IPython\core\ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "D:\Anaconda\envs\mmlab\lib\site-packages\IPython\core\ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "D:\Anaconda\envs\mmlab\lib\site-packages\IPython\core\ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "D:\Anaconda\envs\mmlab\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\stack_data\core.py", line 698, in lines
    pieces = self.included_pieces
  File "D:\Anaconda\envs\mmlab\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\stack_data\core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\stack_data\core.py", line 628, in executing_piece
    return only(
  File "D:\Anaconda\envs\mmlab\lib\site-packages\executing\executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

What should I do? 
FYI : I trained using my local computer

### Environment

YOLOv5  v6.1-207-g5774a15 Python-3.9.12 torch-1.11.0 CUDA:0 (NVIDIA GeForce RTX 2060, 6144MiB)
OS : Windows 11
Python: 3.9.x

I am also trying this code in my local computer : 
```
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True, force_reload=True)
```
and the errors still same as before.

**Comment by glenn-jocher** [comment]
@firqaaa your local source is out of date

    model = torch.hub.load("D:/Notebook/Projects/Python/kaggle/yolov5-lib-ds",
