### ISSUE TITLE
Error while running val.py

### ISSUE THREAD

**Issue by Mashaakim** [ultralytics/yolov5#8029]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

I ran the following 
`python3 val.py --weights weights/with_1000_synth.pt --data weeds_crops/data.yaml --img 640 --name exp10 --task test --device 0` 
and got the error:
`Matplotlib created a temporary config/cache directory at /tmp/matplotlib-50o704nt because the default path (/home/maria/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
val: data=weeds_crops/data.yaml, weights=['weights/with_1000_synth.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=0, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp10, exist_ok=False, half=False, dnn=False
Python 3.7.0 required by YOLOv5, but Python 3.6.9 is currently installed
YOLOv5 🚀 v6.1-162-g2611477 torch 1.10.0a0+git36449ea CUDA:0 (NVIDIA Tegra X1, 3964MiB)

Fusing layers... 
Model summary: 213 layers, 7015519 parameters, 0 gradients
Downloading https://ultralytics.com/assets/Arial.ttf to /home/maria/.config/Ultralytics/Arial.ttf...
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1438, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 956, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "val.py", line 396, in <module>
    main(opt)
  File "val.py", line 369, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 153, in run
    data = check_dataset(data)  # check
  File "/home/maria/yolov5/utils/general.py", line 493, in check_dataset
    check_font('Arial.ttf' if is_ascii(data['names']) else 'Arial.Unicode.ttf', progress=True)  # download fonts
  File "/home/maria/yolov5/utils/general.py", line 435, in check_font
    torch.hub.download_url_to_file(url, str(file), progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 452, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
`

I ran this command on Jetson Nano. Thanks in advance for any help.

### Environment

Python 3.6.9
Jetson Nano

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Mashaakim looks like just an internet connection error. Check your connection and try again.
