### ISSUE TITLE
Evaluation metrics on the test dataset

### ISSUE THREAD

**Issue by DevHwary** [ultralytics/yolov5#8142]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I want to evaluate the model on the test dataset.
I saw an old issues, the answer was to use the command ` $ python val.py --task test ` #[5442](https://github.com/ultralytics/yolov5/issues/5442)
but I get this error :
```
val: data=data/coco128.yaml, weights=yolov5s.pt, batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v6.1-244-g47233e1 Python-3.7.13 torch-1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Traceback (most recent call last):
  File "/content/drive/MyDrive/projectFolder/projectName/yolov5/utils/dataloaders.py", line 426, in __init__
    p = Path(p)  # os-agnostic
  File "/usr/lib/python3.7/pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "val.py", line 394, in <module>
    main(opt)
  File "val.py", line 367, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 181, in run
    prefix=colorstr(f'{task}: '))[0]
  File "/content/drive/MyDrive/projectFolder/projectName/yolov5/utils/dataloaders.py", line 126, in create_dataloader
    prefix=prefix)
  File "/content/drive/MyDrive/projectFolder/projectName/yolov5/utils/dataloaders.py", line 442, in __init__
    raise Exception(f'{prefix}Error loading data from {path}: {e}\nSee {HELP_URL}')
Exception: test: Error loading data from None: expected str, bytes or os.PathLike object, not NoneType
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
```

Thanks in advance.

**Comment by glenn-jocher** [comment]
@DevHwary this is user error, you have no test data to evaluate.
