### ISSUE TITLE
Can not train with multiple GPU even using Issue 475

### ISSUE THREAD

**Issue by bsugerman** [ultralytics/yolov5#820]
Just grabbed a brand new clone and tried to do multi-gpu training a few different ways, including the ones suggested in [475](https://github.com/ultralytics/yolov5/issues/475). All I get are errors:

```
python  train.py --data coco128.yaml --weights '' --epochs 1 --device 0,1  

Traceback (most recent call last):
  File "train.py", line 650, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 407, in train
    pred = model(imgs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/spindisk/falcon/models/yolo.py", line 133, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/spindisk/falcon/models/yolo.py", line 153, in forward_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/spindisk/falcon/models/layers.py", line 230, in forward
    return self.step2(self.step1(x))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/spindisk/falcon/models/layers.py", line 96, in forward
    return self.conv(self.act(self.bn(x)))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

```
python -m torch.distributed.launch --nproc_per_node 2 train.py --data coco128.yaml --weights '' --epochs 1

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11016MB)

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 633, in <module>
    torch.cuda.set_device(opt.local_rank)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/cuda/Module.cpp:59
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 254, in main
    process.wait()
  File "/opt/conda/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
```

```
python -m torch.distributed.launch --nproc_per_node 2 train.py --data coco128.yaml --weights '' --epochs 1 --device 0,1

Using DDP

Using DDP
Scanning labels (127 found, 0 missing, 1 empty, 0 duplicate, for 128 images): 128it [00:00, 10289.22it/s]
Traceback (most recent call last):
  File "train.py", line 650, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 165, in train
    grayworld=opt.grayworld)
  File "/spindisk/falcon/utils/datasets.py", line 305, in create_dataloader
    collate_fn=LoadImagesAndLabels.collate_fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 201, in __init__
Traceback (most recent call last):
  File "train.py", line 650, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 165, in train
    grayworld=opt.grayworld)
  File "/spindisk/falcon/utils/datasets.py", line 305, in create_dataloader
    collate_fn=LoadImagesAndLabels.collate_fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 201, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=1', '--data', 'coco128.yaml', '--weights', '', '--epochs', '1', '--device', '0,1']' returned non-zero exit status 1.
```

Running on Linux Ubuntu with 2 GTX 2080 GPUs. I can run on one GPU without any problems.

**Comment by glenn-jocher** [comment]
@bsugerman multi-GPU training operates correctly in all modes. Tested 22 August 2020. 

<img width="1423" alt="Screen Shot 2020-08-22 at 2 22 44 PM" src="https://user-images.githubusercontent.com/26833433/90966080-35a3d700-e483-11ea-9e6f-e22cb88280b9.png">
<img width="1423" alt="Screen Shot 2020-08-22 at 2 24 22 PM" src="https://user-images.githubusercontent.com/26833433/90966081-363c6d80-e483-11ea-8c7d-ba673d515fa8.png">

**Comment by glenn-jocher** [comment]
@bsugerman it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by bsugerman** [comment]
Indeed, upgrading to python 3.8 worked. Probably worth noting this somewhere prominently on your main page for people using multiple GPUs. Your dockerfile defaults to python 3.6, and most of the torch dockerfiles out there default to 3.7. :-( In the end, I had to use a torch dockerfile, then use conda to create a new environment with 3.8. But, it worked!

**Comment by NanoCode012** [comment]
Hi @bsugerman , glad to see it worked out for you! I tried to make the guide as simple and informative as possible (like req Python 3.8), but it's easy to gloss over the information.

I normally use 3.7 for my training (both single and multi). However, I have recently (a day or two old) ran using the docker (3.6) for multi-gpu training, and there were no issues. Has yolov5 docker not work for you?

**Comment by Frank1126lin** [comment]
I got the same `non-zero exit status 1` problem just because I mix the dir name `labels` with `label.` 
I found this just when I try to use single GPU mode.
`FileNotFoundError: [Errno 2] No such file or directory: '../Battery/duanmian/labels/train.cache'`
The DDP error below:
`subprocess.CalledProcessError: Command '['/root/miniconda3/envs/yolo/bin/python3', '-u', 'train.py', '--local_rank=3', '--epochs', '2000', '--batch-size', '256', '--cfg', 'models/yolov5l-Battery-duanmian.yaml', '--data', 'data/battery_duanmian.yaml', '--weights', '', '--device', '0,1,2,3']' returned non-zero exit status 1.`

**Comment by glenn-jocher** [comment]
@Frank1126lin for dataset configuration advice see
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

For Multi-GPU see Multi-GPU Tutorial in
https://docs.ultralytics.com/yolov5

**Comment by wuzuowuyou** [comment]
i got some same errors:
```
python -m torch.distributed.launch --nproc_per_node 1 --nnodes 2 --node_rank 1 --master_addr "10.188.192.11" --master_port 12394 train.py --batch 16 --data coco128.yaml --epochs 300 --weights yolov5s.pt --device 0
train: Scanning /media/algo/data_1/project_others/yolo/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
=====>>>broadcast_list= [None]
Traceback (most recent call last):
  File "train.py", line 637, in <module>
    main(opt)
  File "train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 398, in train
    dist.broadcast_object_list(broadcast_list, 0)  # broadcast 'stop' to all ranks
  File "/media/algo/data_1/software/anconda_install/envs/pytorch1.7.0_general/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1382, in broadcast_object_list
    object_sizes_tensor = object_sizes_tensor.to(my_rank)
RuntimeError: CUDA error: invalid device ordinal
Traceback (most recent call last):
  File "/media/algo/data_1/software/anconda_install/envs/pytorch1.7.0_general/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/algo/data_1/software/anconda_install/envs/pytorch1.7.0_general/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/algo/data_1/software/anconda_install/envs/pytorch1.7.0_general/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/media/algo/data_1/software/anconda_install/envs/pytorch1.7.0_general/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/media/algo/data_1/software/anconda_install/envs/pytorch1.7.0_general/bin/python', '-u', 'train.py', '--local_rank=0', '--batch', '16', '--data', 'coco128.yaml', '--epochs', '300', '--weights', 'yolov5s.pt', '--device', '0']' returned non-zero exit status 1.
```

**Comment by glenn-jocher** [comment]
@wuzuowuyou if you encounter the error "CUDA error: invalid device ordinal" during multi-GPU training, please ensure that all your GPU devices are properly recognized and assigned by checking `CUDA_VISIBLE_DEVICES`. You may also consider using the `TORCH_CUDA_ARCH_LIST` environment variable to specify the architecture of your GPU to optimize performance. 

For more information on troubleshooting multi-GPU training, you can refer to our documentation at https://docs.ultralytics.com/yolov5.
