### ISSUE TITLE
An error occurred when validating model after trained complete 

### ISSUE THREAD

**Issue by zzy444626905** [ultralytics/yolov5#8401]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

   Epoch   gpu_mem       box       obj       cls    labels  img_size
   298/299        0G  0.008621  0.002274         0         9       640: 100%|██████████| 49/49 [01:17<00:00,  1.59s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 25/25 [00:19<00:00,  1.29it/s]
                 all        245        258      0.986      0.961      0.988      0.793

     Epoch   gpu_mem       box       obj       cls    labels  img_size
   299/299        0G  0.008668  0.002224         0        10       640: 100%|██████████| 49/49 [01:21<00:00,  1.66s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 25/25 [00:21<00:00,  1.18it/s]
                 all        245        258      0.987      0.961      0.988      0.794

300 epochs completed in 8.675 hours.
Optimizer stripped from runs/train/xfl-yolov5/weights/last.pt, 6.7MB
Optimizer stripped from runs/train/xfl-yolov5/weights/best.pt, 6.7MB

Validating runs/train/xfl-yolov5/weights/best.pt...
Fusing layers...
Model summary: 280 layers, 3087256 parameters, 0 gradients, 4.2 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 25/25 [00:20<00:00,  1.24it/s]
                 all        245        258      0.988      0.964       0.99      0.795
Results saved to runs/train/xfl-yolov5
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f11279289d0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

### Environment

YOLOv5 🚀 v6.1-269-gf76a78e Python-3.8.13 torch-1.11.0+cu102 CPU
os：ubuntu20.04
python3.8

### Minimal Reproducible Example

python train.py --img 640 --batch 5 --epochs 300 --data xfl.yaml --weights yolov5n6.pt --device cpu --name xfl-yolov5

### Additional

no

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zzy444626905 thanks for the bug report! This is a torch issue, the torch team is aware of it and this should be fixed in the next release. See https://github.com/ultralytics/yolov5/issues/6962#issuecomment-1087576234

**Comment by glenn-jocher** [comment]
@zzy444626905 BTW the console errors do not have any negative side effect, i.e. there is no problem, they simply clutter the console.
