### ISSUE TITLE
When i rename the common.py file which is inside models folder getting the following error-

### ISSUE THREAD

**Issue by ayush431** [ultralytics/yolov5#8472]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Traceback (most recent call last):
  File "C:\Users\USER\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\magure_inc_june_latest\magureinc_demos_be\ml_demos\object_detection_yolov5\__main__.py", line 24, in <module>
    main()
  File "E:\magure_inc_june_latest\magureinc_demos_be\ml_demos\object_detection_yolov5\__main__.py", line 13, in main
    _run(args=args)
  File "E:\magure_inc_june_latest\magureinc_demos_be\ml_demos\object_detection_yolov5\__main__.py", line 17, in _run
    objectDetectionYolov5Obj = ObjectDetectionYolov5()
  File "E:\magure_inc_june_latest\magureinc_demos_be\ml_demos\object_detection_yolov5\object_detection_yolov5.py", line 22, in __init__
    self.load_model()
  File "E:\magure_inc_june_latest\magureinc_demos_be\ml_demos\object_detection_yolov5\object_detection_yolov5.py", line 26, in load_model
    self.model = DetectMultiBackend(self.weights, device=self.device, dnn=self.dnn, data=self.data, fp16=self.half)
  File "E:\magure_inc_june_latest\magureinc_demos_be\ml_demos\common\models\yolov5_common.py", line 93, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device)
  File "E:\magure_inc_june_latest\magureinc_demos_be\ml_demos\common\models\yolov5_common.py", line 141, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "E:\magure_inc_june_latest\magureinc_demos_be\venv\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "E:\magure_inc_june_latest\magureinc_demos_be\venv\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "E:\magure_inc_june_latest\magureinc_demos_be\venv\lib\site-packages\torch\serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.common'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ayush431 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
