### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by JianxiangL** [ultralytics/yolov5#8627]
I just started to contact YOLO.
When I train my dataset, it prompts me with the following error. Is this a network problem? How can I solve it?  Thanks!!
```
(droidlet_locobot) swpu@swpu:~/yolov5_train/yolov5$ python train.py --img 640 --batch 16 --epochs 300 --data ./data/data.yaml --cfg ./models/yolov5l.yaml --weight ''
train: weights=, cfg=./models/yolov5l.yaml, data=./data/data.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=300, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2022-7-17 Python-3.7.12 torch-1.9.1 CUDA:0 (NVIDIA GeForce RTX 2060, 12027MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
Downloading https://ultralytics.com/assets/Arial.ttf to /home/swpu/.config/Ultralytics/Arial.ttf...
Traceback (most recent call last):
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/http/client.py", line 1451, in connect
    server_hostname=server_hostname)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 646, in <module>
    main(opt)
  File "train.py", line 541, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 107, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/swpu/yolov5_train/yolov5/utils/general.py", line 514, in check_dataset
    check_font('Arial.ttf' if is_ascii(data['names']) else 'Arial.Unicode.ttf', progress=True)  # download fonts
  File "/home/swpu/yolov5_train/yolov5/utils/general.py", line 455, in check_font
    torch.hub.download_url_to_file(url, str(file), progress=progress)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/site-packages/torch/hub.py", line 437, in download_url_to_file
    u = urlopen(req)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/swpu/anaconda3/envs/droidlet_locobot/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 0] 
```

Related configurations of my device：

```
(droidlet_locobot) swpu@swpu:~/yolov5_train/yolov5$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0] on linux
>>> import torch
>>> print(torch.__version__)
1.9.1
```

```
(droidlet_locobot) swpu@swpu:~/yolov5_train/yolov5$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0
```
```
|----datasets
       |-----train
              |----images
              |----labels
       |----val
               |----images
               |----labels
```
and i use LabelImg to get the label(.txt)

**Comment by glenn-jocher** [comment]
@JianxiangL seems to be a connection error to https://ultralytics.com/assets/Arial.ttf, just retry your command.

**Comment by JianxiangL** [comment]
Thank you, I have solved it！I download Arial.tff and change the network.

**Comment by glenn-jocher** [comment]
@JianxiangL glad to hear that you were able to resolve the issue! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLO training!
