### ISSUE TITLE
Why is my program reporting this error

### ISSUE THREAD

**Issue by nuonuofenfen** [ultralytics/yolov5#8734]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

D:\Anaconda\envs\cyb\python.exe D:/wc/gpu/yolov5-master/yolov5-master/train.py
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
train: weights=yolov5s.pt, cfg=, data=data\coco128.yaml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=300, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5  2022-7-27 Python-3.8.12 torch-1.10.2 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/
wandb: wandb version 0.12.21 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: ERROR Error while calling W&B API: user is not logged in (<Response [401]>)
Thread SenderThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "D:\Anaconda\envs\cyb\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "D:\Anaconda\envs\cyb\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1298, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\lib\retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\util.py", line 817, in no_retry_auth
    raise CommError("Invalid or missing api_key.  Run wandb login")
wandb.errors.CommError: Invalid or missing api_key.  Run wandb login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\internal_util.py", line 102, in _run
    self._process(record)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\internal.py", line 291, in _process
    self._sm.send(record)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\sender.py", line 240, in send
    send_handler(record)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\sender.py", line 708, in send_run
    self._init_run(run, config_value_dict)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\sender.py", line 732, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\apis\normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "D:\Anaconda\envs\cyb\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1298, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\lib\retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\util.py", line 817, in no_retry_auth
    raise CommError("Invalid or missing api_key.  Run wandb login")
wandb.errors.CommError: Invalid or missing api_key.  Run wandb login
wandb: ERROR Internal wandb error: file data was not synced
Traceback (most recent call last):
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\wandb_init.py", line 582, in init
    backend.cleanup()
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\backend\backend.py", line 228, in cleanup
    self.interface.join()
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 481, in join
    super(InterfaceQueue, self).join()
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\interface\interface.py", line 591, in join
    self._communicate_shutdown()
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 478, in _communicate_shutdown
    _ = self._communicate(record)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "D:\Anaconda\envs\cyb\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 237, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Problem at: D:\wc\gpu\yolov5-master\yolov5-master\utils\loggers\wandb\wandb_utils.py 159 __init__
wandb: ERROR Abnormal program exit

Process finished with exit code -1

### Additional

python=3.8
potorch
gpu

**Comment by glenn-jocher** [comment]
@nuonuofenfen it appears you may have environment problems related to wandb. You can disable or uninstall wandb to bypass these issues with `wandb disabled` or `pip uninstall wandb`.

Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by soumik12345** [comment]
Hi @nuonuofenfen, you can grab your Weights & Biases API key from https://wandb.ai/authorize and set it using `set WANDB_API_KEY=XXXX`.
