### ISSUE TITLE
ImportError: cannot import name 'notf' from 'tensorboard.compat'

### ISSUE THREAD

**Issue by Jacobfinn123** [ultralytics/yolov5#8802]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

**Full Traceback:**

```
Traceback (most recent call last):
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jacob\Desktop\desktop\PycharmProjects1\MISC\ML\yolov5\train.py", line 642, in <module>
    main(opt)
  File "C:\Users\Jacob\Desktop\desktop\PycharmProjects1\MISC\ML\yolov5\train.py", line 537, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\Jacob\Desktop\desktop\PycharmProjects1\MISC\ML\yolov5\train.py", line 91, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "C:\Users\Jacob\Desktop\desktop\PycharmProjects1\MISC\ML\yolov5\utils\loggers\__init__.py", line 75, in __init__
    self.tb = SummaryWriter(str(s))
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 246, in __init__
    self._get_file_writer()
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 276, in _get_file_writer
    self.file_writer = FileWriter(
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 75, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\__init__.py", line 473, in <module>
    keras._load()
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\__init__.py", line 25, in <module>
    from keras import models
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\functional.py", line 25, in <module>
    from keras.engine import base_layer
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\mixed_precision\loss_scale_optimizer.py", line 20, in <module>
    from keras.optimizer_experimental import optimizer as optimizer_experimental
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\optimizer_experimental\optimizer.py", line 649, in <module>
    tf.__internal__.saved_model.load.register_revived_type(
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\revived_types.py", line 133, in register_revived_type
    raise AssertionError(f"Duplicate registrations for type '{identifier}'")
AssertionError: Duplicate registrations for type 'experimentalOptimizer'
```

When I run `pip check` after running `pip install -r requirements.txt`:
```
tf-nightly 2.10.0.dev20220417 has requirement tf-estimator-nightly~=2.10.0.dev, but you have tf-estimator-nightly 2.8.0.dev2021122109.
```

Although, when you try to install this version of tf-estimator-nightly I get:

```
tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, but you have tf-estimator-nightly 2.10.0.dev2022072018 which is incompatible.
```

Not sure if these are related to the main issue or not.

**Comment by glenn-jocher** [comment]
@TheSweeet this issue appears to be related to compatibility problems with TensorFlow and its dependencies. I recommend checking the installation of TensorFlow and its subcomponents such as tf-estimator-nightly to ensure they are compatible with each other. It may also be beneficial to consider using a stable release version rather than a nightly one. Let me know if you need further assistance in resolving this matter. 👍
