### ISSUE TITLE
After clearml upload is completed, torch reports an error

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#8885]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug
@glenn-jocher 
After clearml upload is completed, torch reports an error:

```shell
Results saved to runs/train/exp
2022-08-06 08:48:13,994 - clearml.Task - INFO - Waiting to finish uploads
2022-08-06 08:48:18,292 - clearml.Task - INFO - Completed model upload to https://files.clear.ml/YOLOv5/training.a2d0300ee14f4a84a294dfbbc85a266b/models/best.pt
2022-08-06 08:48:29,341 - clearml.Task - INFO - Finished uploading
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f0bfa39d310>
Traceback (most recent call last):
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f0bfa39d310>
Traceback (most recent call last):
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f0bfa39d310>
```

It is displayed normally on clearml:
![ksnip_20220806-085417](https://user-images.githubusercontent.com/41098760/183227203-c9990d8c-b946-462b-b094-c5cbb99d7ccb.png)

### Environment

- YOLOv5 🚀 v6.1-369-g030586a Python-3.8.0 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1070 Ti, 8116MiB)
- ubuntu 20.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@thepycoder Hey can you take a look whenever you're back? Thanks!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer thanks for the bug report! I think this is related to https://github.com/ultralytics/yolov5/issues/6962 and https://github.com/pytorch/pytorch/issues/74016, and should be resolved in torch>1.12.0

I see you have torch 1.11.0 installed. Can you upgrade your torch and see if this resolves your issue?

**Comment by Zengyf-CVer** [comment]
@glenn-jocher @AyushExel 
I tested on torch==1.12.0 and everything works fine.
Here is my configuration: YOLOv5 🚀 v6.1-370-g20f1b7e Python-3.9.12 torch-1.12.0+cu116 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
![ksnip_20220806-174057](https://user-images.githubusercontent.com/41098760/183243688-91c62d34-dd3e-4d80-a58b-4574e26267f1.png)

**Comment by glenn-jocher** [comment]
@Zengyf-CVer awesome, thanks for testing!!
