### ISSUE TITLE
 _multiarray_umath error

### ISSUE THREAD

**Issue by c0pyy** [ultralytics/yolov5#8945]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

PS C:\Users\micha\Desktop\yolov5> Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.& C:/Users/mich+ ...  _multiarray_umath: The specified module could not be found.& C:/User ... 
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for      
future use; wrap an ampersand in double quotation marks ("&") to pass it as     
part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx  
   ception
    + FullyQualifiedErrorId : AmpersandNotAllowed
 
PS C:\Users\micha\Desktop\yolov5> & C:/Users/micha/anaconda3/python.exe c:/Users/micha/Desktop/test.py
Traceback (most recent call last):
  File "c:\Users\micha\Desktop\test.py", line 4, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\hub.py", line 537, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\hub.py", line 133, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):    
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 214, in urlopen   
    return opener.open(url, data, timeout)
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
PS C:\Users\micha\Desktop\yolov5> & C:/Users/micha/anaconda3/python.exe c:/Users/micha/Desktop/test.py
Traceback (most recent call last):
  File "c:\Users\micha\Desktop\test.py", line 4, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\hub.py", line 537, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\hub.py", line 133, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\micha\anaconda3\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

### Additional

Not really sure what the problem is, any help would be appreciated. Thanks.

**Comment by glenn-jocher** [comment]
@c0pyy 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
