### ISSUE TITLE
PyTorch Hub Load custom training model "Cache may be out of date" error even after setting "force_reload=True"

### ISSUE THREAD

**Issue by Berttwm** [ultralytics/yolov5#9145]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

My console output:
```
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\xjera/.cache\torch\hub\master.zip
YOLOv5  2022-8-25 Python-3.9.12 torch-1.12.0+cpu CPU

Traceback (most recent call last):
  File "C:\Users\xjera/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 47, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "C:\Users\xjera/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 331, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "C:\Users\xjera/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 80, in attempt_load
    ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
AttributeError: 'Tensor' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xjera/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 55, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "C:\Users\xjera/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 80, in attempt_load
    ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
AttributeError: 'Tensor' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\dev\test\test.py", line 48, in <module>
    yc.run_generated_model()
  File "D:\dev\test\test.py", line 25, in run_generated_model
    model = torch.hub.load('ultralytics/yolov5', 'custom', path=generated_model_path, force_reload=True)
  File "C:\Users\xjera\anaconda3\envs\yolov-5\lib\site-packages\torch\hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\xjera\anaconda3\envs\yolov-5\lib\site-packages\torch\hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\xjera/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 78, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\xjera/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 73, in _create
    raise Exception(s) from e
Exception: 'Tensor' object has no attribute 'get'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.
```

### Environment

-Yolov5: v6.1-315-gf5425d5 Python-3.9.12 torch-1.12.0+cpu CPU
-OS : Windows 10
-Python: 3.9.12

### Minimal Reproducible Example

```
        generated_model_path ="/path/to/model.pt"
        model = torch.hub.load('ultralytics/yolov5', 'custom', path=generated_model_path, force_reload=True) 
```

### Additional

After generating a yolov5s `.pt` model using the `train.py` script that comes with the repository, I try to `torch.hub.load` the output `.pt` file with the `force_reload=True` tag included. 

The resulting error suggests that my "Cache may be out of date, try 'force_reload=True'" which I have already included.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Berttwm** [comment]
The `.pt` file I used had an error. Marking this as closed

**Comment by glenn-jocher** [comment]
@Berttwm thanks for updating us! Don't hesitate to return if you encounter any more issues or have additional questions. The YOLOv5 community and the Ultralytics team are here to help.
