### ISSUE TITLE
Can you add for yolov5 Classification  export to tfjs?

### ISSUE THREAD

**Issue by unnellu** [ultralytics/yolov5#9169]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi.
Can you add for yolov5 Classification  export to tfjs?
Or how i can get it?
Thanks =)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@unnellu export.py supports export of all models including classification models. See export.py Usage examples.

**Comment by unnellu** [comment]
> @unnellu export.py supports export of all models including classification models. See export.py Usage examples.

!python export.py --weights runs/train-cls/exp/weights/best.pt --include tfjs 
`export: data=data/coco128.yaml, weights=['runs/train-cls/exp/weights/best.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['tfjs']
YOLOv5 🚀 v6.2-66-ge57275a Python-3.7.13 torch-1.12.1+cu113 CPU

Fusing layers... 
Model summary: 117 layers, 4169250 parameters, 0 gradients, 10.4 GFLOPs

PyTorch: starting from runs/train-cls/exp/weights/best.pt with output shape (1, 2) (8.1 MB)

TensorFlow SavedModel: starting export with tensorflow 2.8.2...
TensorFlow SavedModel: export failure ❌ 2.0s: 'ClassificationModel' object has no attribute 'yaml'

TensorFlow GraphDef: starting export with tensorflow 2.8.2...
TensorFlow GraphDef: export failure ❌ 0.0s: 'NoneType' object has no attribute 'inputs'

TensorFlow.js: starting export with tensorflowjs 3.20.0...
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 827, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 831, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 818, in convert
    weight_shard_size_bytes, metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 588, in _dispatch_converter
    metadata=metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 522, in convert_tf_frozen_model
    graph = load_graph(frozen_model_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 68, in load_graph
    graph_def.ParseFromString(f.read())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 114, in read
    self._preread_check()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 77, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: runs/train-cls/exp/weights/best.pb; No such file or directory
TensorFlow.js: export failure ❌ 3.2s: [Errno 2] No such file or directory: 'runs/train-cls/exp/weights/best_web_model/model.json'`

**Comment by glenn-jocher** [comment]
@unnellu ah yes. ClassificationModel export is only supported for non-TF formats currently.

**Comment by glenn-jocher** [comment]
@AyushExel here's another example of TF export support. Would be better if we could automate via torch > onnx > tf, the channel order issue would need resolving though which was a major hurdle last time i checked.
