### ISSUE TITLE
Coustum Model can't load with TorchHub

### ISSUE THREAD

**Issue by Petopp** [ultralytics/yolov5#9179]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

Hello,

I have already tried everything and just can not get any further. No matter what I do, I can not load my model in TorchHub. With detect and the export as onnx it works, but is not what I want. Know that a few also have the problem, only a solution I have not yet seen.

Hope someone can help. 

Peter

```
import torch
model = torch.hub.load('.', 'custom', path='/home/petop/OneDrive/Projekte/Python/Yolo5/Einfahrt/best.pt', source='local')

img = '/home/petop/Bilder/20211204-1334_MIT.jpg'
results = model(img)
results.show()
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "/home/petop/OneDrive/Projekte/Python/Yolo5/yolo_P.py", line 4, in <module>
    model = torch.hub.load('.', 'custom', path='/home/petop/OneDrive/Projekte/Python/Yolo5/Einfahrt/best.pt', source='local')
  File "/home/petop/.local/lib/python3.10/site-packages/torch/hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/petop/.local/lib/python3.10/site-packages/torch/hub.py", line 430, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "/home/petop/.local/lib/python3.10/site-packages/torch/hub.py", line 76, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/petop/OneDrive/Projekte/Python/Yolo5/./hubconf.py'
```

### Environment

OS: Ubunut 20.04/22.04
Python 3.8/3.10
yolo5 newest version

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Petopp** [comment]
You can find my model and image here: https://drive.google.com/drive/folders/1HQpfS7KhPjOLctBx6hgAxNRCUoKji_76?usp=sharing

**Comment by Petopp** [comment]
Okay, the problem was the missing link to the yolo5 directory. Was already completely blind

**Comment by glenn-jocher** [comment]
@Petopp glad to hear you found the solution! If you have more questions or need further assistance, feel free to ask. Also, your feedback helps improve the YOLOv5 community, as well as our team at Ultralytics.
