### ISSUE TITLE
export onnx error

### ISSUE THREAD

**Issue by zhangyilalala** [ultralytics/yolov5#93]
I meet this error when I run onnx_export.py,could anyone help me how to fix this?

Fusing layers...
Traceback (most recent call last):
  File "models/onnx_export.py", line 31, in <module>
    model.fuse()
  File "/home/zhangyi/yolov5-master/models/yolo.py", line 140, in fuse
    m.conv = torch_utils.fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/home/zhangyi/yolov5-master/utils/torch_utils.py", line 86, in fuse_conv_and_bn
    w_bn = torch.diag(bn.weight.div(torch.sqrt(bn.eps + bn.running_var)))
RuntimeError: "add_cpu/sub_cpu" not implemented for 'Half'

**Comment by glenn-jocher** [comment]
@zhangyilalala bug should be fixed in latest commit. Please git pull and try again.
