### ISSUE TITLE
Error in forwad() while loading model from pytorch hub with custom number of classes

### ISSUE THREAD

**Issue by ashBabu** [ultralytics/yolov5#9321]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 
I am on Ubuntu 18 and using Pytorch version 1.12.1. The following code throws an error
```python
import torch
from PIL import Image
import numpy as np

print(torch.__version__)  ## 1.12.1
img = Image.open('/home/ash/Ash/repo/yolov5/data/images/zidane.jpg')

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=10)
t = np.zeros((640, 1280, 3))
output = model([t])
# output = model([img])
```
The error is
```Traceback (most recent call last):
  File "/opt/pycharm-2022.1.4/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-2022.1.4/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ash/Ash/repo/object_detection/python/test.py", line 10, in <module>
    output = model([t])
  File "/home/ash/anaconda3/envs/torch_latest/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ash/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py", line 189, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/ash/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py", line 102, in _forward_once
    x = m(x)  # run
  File "/home/ash/anaconda3/envs/torch_latest/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ash/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 47, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/ash/anaconda3/envs/torch_latest/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ash/anaconda3/envs/torch_latest/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ash/anaconda3/envs/torch_latest/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (list, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!list!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!list!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)
```

To give a little bit of context, I would like to load a model with [10 classes](https://docs.ultralytics.com/tutorials/pytorch-hub/#number-of-classes) with pretrained weights except for the output layer. Then [freeze all layers](https://github.com/ultralytics/yolov5/issues/1314) except the output layer and carry out fine-tuning. I was hoping to do the fine tuning using the Pytorch example as described in [here](https://github.com/pytorch/tutorials/blob/master/beginner_source/transfer_learning_tutorial.py#L277) (Dont know yet if this is a good idea or not)

Thanks

**Comment by glenn-jocher** [comment]
@ashBabu user error. Models with arbitrary classes are not wrapped with AutoShape and must be passed torch tensors in BCHW

**Comment by ashBabu** [comment]
Thanks @glenn-jocher  for the quick reply. After making the modifications as suggested, it works now. I am posting the code for any future reference
```python
import torch
from PIL import Image
import torchvision.transforms as T

print(torch.__version__)
img = Image.open('images/zidane.jpg')
trans = T.Compose([T.Resize([640, 640]),
                   T.ToTensor()
                   ])
img_trans = trans(img)
img_trans = img_trans.unsqueeze(0).cuda()
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=10)
output = model(img_trans)
```

**Comment by glenn-jocher** [comment]
You're welcome @ashBabu! I'm glad to hear it's working for you now. Thank you for sharing the code for future reference. If you have any more questions or need further assistance, feel free to ask! Good luck with your fine-tuning!
