### ISSUE TITLE
wandb invaild name error in classification training

### ISSUE THREAD

**Issue by EscaticZheng** [ultralytics/yolov5#9407]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

After my first run the **classification training**, the twice run raise error:
wandb: ERROR Invalid project name "runs\train-cls": cannot contain characters "/,\,#,?,%,:", found "\\"
I removed the whole run folder and ran again, but still the same error

**The details are as the follows**:
wandb: ERROR Invalid project name "runs\train-cls": cannot contain characters "/,\,#,?,%,:", found "\\"
Traceback (most recent call last):
  File "D:\yolov5-master-cls\yolov5-master\classify\train.py", line 331, in <module>
    main(opt)
  File "D:\yolov5-master-cls\yolov5-master\classify\train.py", line 317, in main
    train(opt, device)
  File "D:\yolov5-master-cls\yolov5-master\classify\train.py", line 71, in train
    logger = GenericLogger(opt=opt, console_logger=LOGGER) if RANK in {-1, 0} else None
  File "D:\yolov5-master-cls\yolov5-master\utils\loggers\__init__.py", line 334, in __init__
    self.wandb = wandb.init(project=web_project_name(str(opt.project)),
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_init.py", line 1040, in init
    wi.setup(kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_init.py", line 273, in setup
    settings._apply_init(kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 1500, in _apply_init
    self.update(init_settings, source=Source.INIT)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 1203, in update
    self.__dict__[key].update(value, source)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 334, in update
    self._value = self._validate(self._preprocess(value))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 295, in _validate
    if not v(value):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 733, in _validate_project
    raise UsageError(
wandb.errors.UsageError: Invalid project name "runs\train-cls": cannot contain characters "/,\,#,?,%,:", found "\"

### Environment

Software: conda 4.10.3
OS : Windows 11
Python : 3.9.7

### Minimal Reproducible Example

python classify/train.py --model yolov5s-cls.pt --data mnist --epochs 5 --img 224 --batch 128

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@EscaticZheng your code is probably out of date. I'm unable to reproduce any issues with W&B logging of Classification training:
<img width="915" alt="Screenshot 2022-09-15 at 20 42 39" src="https://user-images.githubusercontent.com/26833433/190484350-49eb6460-9716-4785-9edc-4a01629c11ee.png">

**Comment by EscaticZheng** [comment]
> @EscaticZheng your code is probably out of date. I'm unable to reproduce any issues with W&B logging of Classification training: <img alt="Screenshot 2022-09-15 at 20 42 39" width="915" src="https://user-images.githubusercontent.com/26833433/190484350-49eb6460-9716-4785-9edc-4a01629c11ee.png">

I cloned it 3 days ago, and I think it's a windows directory error, in windows, the directory is "\" not "/", so wandb throw that error, about reproducing, just use "python classify/train.py --model yolov5s-cls.pt --data mnist --epochs 5 --img 224 --batch 128" in windows.

After day I try changed the default directory to the yolov5 root, then never throw error again.

**Comment by EscaticZheng** [comment]
> @EscaticZheng does the error resolve if you use a '' in the --name instead of a '/'?
> 
> It's strange because the project name is a Path object so it should autocorrect for windows path separators:
> 
> https://github.com/ultralytics/yolov5/blob/c7a2d6bcf4f7e88db53f3d09a8484391dac7bc89/classify/train.py#L280-L281

@glenn-jocher I use “train-cls” instead of “run/train-cls” then no error throw…May be it’s a win11 bug?

**Comment by glenn-jocher** [comment]
@EscaticZheng what if you use `runs\train-cls`?

**Comment by EscaticZheng** [comment]
> @EscaticZheng what if you use `runs\train-cls`?

error too. "Invalid project name "runs\train-cls": cannot contain characters "/,\,#,?,%,:", found "\""

**Comment by EscaticZheng** [comment]
![@RCN254}0VQ }OR`N895F3E](https://user-images.githubusercontent.com/107376080/190628741-391636d5-ac82-493e-b2f9-f47a1f9f1f6f.png)

**Comment by aminey555** [comment]
I met the same mistake too, after I move the file to root ,  the error had gone.
