### ISSUE TITLE
Error while trying to log dataset as artifact in W&B

### ISSUE THREAD

**Issue by ShpihanVlad** [ultralytics/yolov5#9591]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

So I'm using ```python utils/loggers/wandb/log_dataset.py --data data/coco128.yaml``` command to log dataset to W&B, but the following error ocurs.
```

Traceback (most recent call last):
  File "utils/loggers/wandb/log_dataset.py", line 27, in <module>
    create_dataset_artifact(opt)
  File "utils/loggers/wandb/log_dataset.py", line 11, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "/content/yolov5/yolov5/utils/loggers/wandb/wandb_utils.py", line 196, in __init__
    self.data_dict = self.check_and_upload_dataset(opt)
  File "/content/yolov5/yolov5/utils/loggers/wandb/wandb_utils.py", line 210, in check_and_upload_dataset
    'YOLOv5' if opt.project == 'runs/train' else Path(opt.project).stem)
  File "/content/yolov5/yolov5/utils/loggers/wandb/wandb_utils.py", line 355, in log_dataset_artifact
    name='train') if data.get('train') else None
  File "/content/yolov5/yolov5/utils/loggers/wandb/wandb_utils.py", line 439, in create_dataset_table
    table.add_data(si, wandb.Image(paths, classes=class_set, boxes=boxes), list(img_classes.values()),
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 2081, in __init__
    self._set_initialization_meta(grouping, caption, classes, boxes, masks)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 2109, in _set_initialization_meta
    boxes_final[key] = BoundingBoxes2D(box_item, key)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 1817, in __init__
    super(BoundingBoxes2D, self).__init__(val)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 1361, in __init__
    self.validate(val)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/data_types.py", line 1863, in validate
    "Class labels must be a dictionary of numbers to string"
TypeError: Class labels must be a dictionary of numbers to string
```

### Environment

Google Colab env based on tutorial, only first cell and the one for logger were runned. wandb == 0.12.10 is used

### Minimal Reproducible Example

```
python utils/loggers/wandb/log_dataset.py --data data/coco128.yaml
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Mattwmaster58** [comment]
running into this as well

**Comment by glenn-jocher** [comment]
@Mattwmaster58 hi there! Thanks for reaching out. Just wanted to let you know that we're aware of this issue 🐛. Our team is currently looking into it, and we'll do our best to get it resolved as soon as possible. Your patience is much appreciated. Let me know if you have any further questions or concerns!
