### ISSUE TITLE
deepcopy protocol错误，请问有什么建议吗

### ISSUE THREAD

**Issue by Wisdom2wisdom** [ultralytics/yolov5#9623]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

**_Traceback (most recent call last):
  File "E:/executable_code/YOLO/yoloair2022/train.py", line 704, in <module>
    main(opt)
  File "E:/executable_code/YOLO/yoloair2022/train.py", line 600, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:/executable_code/YOLO/yoloair2022/train.py", line 192, in train
    ema = ModelEMA(model) if RANK in [-1, 0] else None_**
  File "E:\executable_code\YOLO\yoloair2022\utils\torch_utils.py", line 307, in __init__
    self.ema = deepcopy(de_parallel(model)).eval()  # FP32 EMA
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\tensor.py", line 55, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Wisdom2wisdom hi there! It looks like you're encountering an issue with the `deepcopy` protocol. This error typically occurs when trying to perform deep copying of PyTorch objects that are not directly supported. 

Without the context of your specific use case, it's a bit challenging to provide a targeted solution, but you might want to consider alternative approaches such as manually creating a deep copy of the model or using PyTorch's built-in methods for copying model states. 

Feel free to check out the Ultralytics Docs for YOLOv5 for more insights on handling model state copying and reach out if you need further assistance! 

Your willingness to submit a PR is greatly appreciated - it's contributions from users like you that help make YOLOv5 even better! Thank you!
