### ISSUE TITLE
Cannot load images from the dataset

### ISSUE THREAD

**Issue by JesusSilvaUtrera** [ultralytics/yolov5#9845]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, I'm trying to build code for yolov5 models training and inference, but not using the data.yaml file (instead I create a parameter in train method called 'dataset_path' and then I provide inside the code the training and validation paths.

The problem is that when it's time to load the images from the dataset (I'm using coco128 dataset as an example to verify if the code works), it doesn´t seem to be recognizing the images, and an error related to the cache is displayed:
Traceback (most recent call last):
```
  File "<string>", line 1, in <module>
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/test_detector_yolo_v5.py", line 16, in <module>
    results = model.train('YOLOv5/data/coco128')
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/detector_yolo_v5.py", line 174, in train
    train_loader, dataset = create_dataloader(train_path,
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/dataloaders.py", line 114, in create_dataloader
    dataset = LoadImagesAndLabels(
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/dataloaders.py", line 455, in __init__
    cache, exists = self.cache_labels(cache_path, prefix), False  # run cache ops
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/dataloaders.py", line 541, in cache_labels
    with Pool(NUM_THREADS) as pool:
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_poTraceback (most recent call last):
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/dataloaders.py", line 453, in __init__
ol()
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42,     assert cache['hash'] == get_hash(self.label_files + self.im_files)  # identical hash
AssertionError
```
Although, if I try to call the original train.py from the terminal it works well, and I don't know why because the only thing that changed is that the content of the data.yaml file is now passed to the code. Here is my train.py and my test.py:
```
class DetectionYolov5(pt_model):
    def __init__(
        self,
        options,
        num_classes,
        classes_names,
        initial_weight_path,
        model_weights,
    ):
        self.options = options
        self.num_classes = num_classes
        self.classes_names = classes_names
        self.initial_weight_path = initial_weight_path
        self.model_weights = model_weights

    def train(self, dataset_path, opt_file = 'YOLOv5/data/opt/optPrueba.yaml', callbacks = Callbacks()):
        #Todo lo del dataset va en la parte de config
        #Habria que adaptar los dirctorios para integracion, y guardar solo el archivo mejor de pesos con su nombre de modelo
        #Juntar todo en un txt a la hora de la integracion si es posible (mas eficiente), no un txt para cada imagen
        epochs = self.options.get("epochs", 10)
        batch_size = self.options.get("batch_size", 8)
        imgsz = self.options.get("input_shape", 416)
        lr = self.options.get("learning_rate", 0.01)

        # Hyperparameters
        if isinstance(opt_file, str):
            with open(opt_file, errors='ignore') as f:
                opt = yaml.safe_load(f)  # load opt dict
        opt = namedtuple("options", opt.keys())(*opt.values())
        save_dir = opt.save_dir

        if isinstance(opt.hyp, str):
            with open(opt.hyp, errors='ignore') as f:
                hyp = yaml.safe_load(f)  # load hyps dict
        LOGGER.info(colorstr('hyperparameters: ') + ', '.join(f'{k}={v}' for k, v in hyp.items()))
        cfg = opt.cfg

        # Directories
        if not os.path.isdir(save_dir):
            os.mkdir(save_dir)
        w = save_dir + '/weights'  # weights dir
        if not os.path.isdir(w):
            os.mkdir(w)
        last, best = w + '/last.pt', w + '/best.pt'

        # Loggers
        data_dict = None
        if RANK in {-1, 0}:
            loggers = Loggers(save_dir, self.initial_weight_path, opt, hyp, LOGGER)  # loggers instance
            if loggers.wandb:
                data_dict = loggers.wandb.data_dict

        # Config
        init_seeds(1 + RANK)
        train_path, val_path = dataset_path + '/images/train2017', dataset_path + '/images/train2017'
        nc = self.num_classes  # number of classes
        names = self.classes_names  # class names
        assert len(names) == nc, f'{len(names)} names found for nc={nc} dataset in {dataset_path}'  # check
        #is_coco = isinstance(val_path, str) and val_path.endswith('coco/val2017.txt')  # COCO dataset

        # Model
        check_suffix(self.initial_weight_path, '.pt')  # check weights
        pretrained = self.initial_weight_path.endswith('.pt')
        if pretrained:
            with torch_distributed_zero_first(LOCAL_RANK):
                self.initial_weight_path = attempt_download(self.initial_weight_path)  # download if not found locally
            ckpt = torch.load(self.initial_weight_path, map_location='cpu')  # load checkpoint to CPU to avoid CUDA memory leak
            model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp['anchors'])  # create
            exclude = ['anchor'] if (cfg or hyp['anchors']) and not opt.resume else []  # exclude keys
            csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
            csd = intersect_dicts(csd, model.state_dict(), exclude=exclude)  # intersect
            model.load_state_dict(csd, strict=False)  # load
            LOGGER.info(f'Transferred {len(csd)}/{len(model.state_dict())} items from {self.initial_weight_path}')  # report
        else:
            model = Model(cfg, ch=3, nc=nc, anchors=hyp['anchors'])  # create
        amp = check_amp(model)  # check AMP

        # Freeze
        freeze = [f'model.{x}.' for x in (opt.freeze if len(opt.freeze) > 1 else range(opt.freeze[0]))]  # layers to freeze
        for k, v in model.named_parameters():
            v.requires_grad = True  # train all layers
            if any(x in k for x in freeze):
                LOGGER.info(f'freezing {k}')
                v.requires_grad = False
        
        # Image size
        gs = max(int(model.stride.max()), 32)  # grid size (max stride)
        imgsz = check_img_size(imgsz, gs, floor=gs * 2)  # verify imgsz is gs-multiple

        # Optimizer
        nbs = 64  # nominal batch size
        accumulate = max(round(nbs / batch_size), 1)  # accumulate loss before optimizing
        hyp['weight_decay'] *= batch_size * accumulate / nbs  # scale weight_decay
        LOGGER.info(f"Scaled weight_decay = {hyp['weight_decay']}")

        g = [], [], []  # optimizer parameter groups
        bn = tuple(v for k, v in nn.__dict__.items() if 'Norm' in k)  # normalization layers, i.e. BatchNorm2d()
        for v in model.modules():
            if hasattr(v, 'bias') and isinstance(v.bias, nn.Parameter):  # bias
                g[2].append(v.bias)
            if isinstance(v, bn):  # weight (no decay)
                g[1].append(v.weight)
            elif hasattr(v, 'weight') and isinstance(v.weight, nn.Parameter):  # weight (with decay)
                g[0].append(v.weight)

        if self.options.get('optimizer') == 'Adam':
            optimizer = Adam(g[2], lr=lr, betas=(hyp['momentum'], 0.999))  # adjust beta1 to momentum
        elif self.options.get('optimizer') == 'AdamW':
            optimizer = AdamW(g[2], lr=lr, betas=(hyp['momentum'], 0.999))  # adjust beta1 to momentum
        else:
            optimizer = SGD(g[2], lr=lr, momentum=hyp['momentum'], nesterov=True)

        optimizer.add_param_group({'params': g[0], 'weight_decay': hyp['weight_decay']})  # add g0 with weight_decay
        optimizer.add_param_group({'params': g[1]})  # add g1 (BatchNorm2d weights)
        LOGGER.info(f"{colorstr('optimizer:')} {type(optimizer).__name__} with parameter groups "
                    f"{len(g[1])} weight (no decay), {len(g[0])} weight, {len(g[2])} bias")
        del g

        # Scheduler
        if opt.cos_lr:
            lf = one_cycle(1, lr, epochs)  # cosine 1->hyp['lrf']
        else:
            lf = lambda x: (1 - x / epochs) * (1.0 - lr) + lr  # linear
        scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lf)

        # EMA
        ema = ModelEMA(model) if RANK in {-1, 0} else None

        # Trainloader
        train_loader, dataset = create_dataloader(train_path,
                                                imgsz,
                                                batch_size // WORLD_SIZE,
                                                gs,
                                                opt.single_cls,
                                                hyp=hyp,
                                                augment=True,
                                                cache=None if opt.cache == 'val' else opt.cache,
                                                rect=opt.rect,
                                                rank=LOCAL_RANK,
                                                workers=opt.workers,
                                                image_weights=opt.image_weights,
                                                quad=opt.quad,
                                                prefix=colorstr('train: '),
                                                shuffle=True)
        mlc = int(np.concatenate(dataset.labels, 0)[:, 0].max())  # max label class
        nb = len(train_loader)  # number of batches
        assert mlc < nc, f'Label class {mlc} exceeds nc={nc} in {dataset_path}. Possible class labels are 0-{nc - 1}'

        # Process 0
        if RANK in {-1, 0}:
            val_loader = create_dataloader(val_path,
                                        imgsz,
                                        batch_size // WORLD_SIZE * 2,
                                        gs,
                                        opt.single_cls,
                                        hyp=hyp,
                                        cache=None if opt.noval else opt.cache,
                                        rect=True,
                                        rank=-1,
                                        workers=opt.workers * 2,
                                        pad=0.5,
                                        prefix=colorstr('val: '))[0]

            if not opt.resume:
                labels = np.concatenate(dataset.labels, 0)
                # c = torch.tensor(labels[:, 0])  # classes
                # cf = torch.bincount(c.long(), minlength=nc) + 1.  # frequency
                # model._initialize_biases(cf.to(device))
                if opt.plots:
                    plot_labels(labels, names, save_dir)

                # Anchors
                if not opt.noautoanchor:
                    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
                model.half().float()  # pre-reduce anchor precision

            callbacks.run('on_pretrain_routine_end')

        # Model attributes
        nl = de_parallel(model).model[-1].nl  # number of detection layers (to scale hyps)
        hyp['box'] *= 3 / nl  # scale to layers
        hyp['cls'] *= nc / 80 * 3 / nl  # scale to classes and layers
        hyp['obj'] *= (imgsz / 640) ** 2 * 3 / nl  # scale to image size and layers
        hyp['label_smoothing'] = opt.label_smoothing
        model.nc = nc  # attach number of classes to model
        model.hyp = hyp  # attach hyperparameters to model
        model.class_weights = labels_to_class_weights(dataset.labels, nc) * nc  # attach class weights
        model.names = names

        # Start training
        start_epoch, best_fitness = 0, 0.0
        t0 = time.time()
        nw = max(round(hyp['warmup_epochs'] * nb), 100)  # number of warmup iterations, max(3 epochs, 100 iterations)
        # nw = min(nw, (epochs - start_epoch) / 2 * nb)  # limit warmup to < 1/2 of training
        last_opt_step = -1
        maps = np.zeros(nc)  # mAP per class
        results = (0, 0, 0, 0, 0, 0, 0)  # P, R, mAP@.5, mAP@.5-.95, val_loss(box, obj, cls)
        scheduler.last_epoch = start_epoch - 1  # do not move
        scaler = torch.cuda.amp.GradScaler(enabled=amp)
        stopper, stop = EarlyStopping(opt.patience), False
        compute_loss = ComputeLoss(model)  # init loss class
        callbacks.run('on_train_start')
        LOGGER.info(f'Image sizes {imgsz} train, {imgsz} val\n'
                    f'Using {train_loader.num_workers * WORLD_SIZE} dataloader workers\n'
                    f"Logging results to {colorstr('bold', save_dir)}\n"
                    f'Starting training for {epochs} epochs...')
        for epoch in range(start_epoch, epochs):  # epoch ------------------------------------------------------------------
            callbacks.run('on_train_epoch_start')
            model.train()

            # Update image weights (optional, single-GPU only)
            if opt.image_weights:
                cw = model.class_weights.cpu().numpy() * (1 - maps) ** 2 / nc  # class weights
                iw = labels_to_image_weights(dataset.labels, nc=nc, class_weights=cw)  # image weights
                dataset.indices = random.choices(range(dataset.n), weights=iw, k=dataset.n)  # rand weighted idx

            # Update mosaic border (optional)
            # b = int(random.uniform(0.25 * imgsz, 0.75 * imgsz + gs) // gs * gs)
            # dataset.mosaic_border = [b - imgsz, -b]  # height, width borders

            mloss = torch.zeros(3, device=opt.device)  # mean losses
            if RANK != -1:
                train_loader.sampler.set_epoch(epoch)
            pbar = enumerate(train_loader)
            LOGGER.info(('\n' + '%10s' * 7) % ('Epoch', 'gpu_mem', 'box', 'obj', 'cls', 'labels', 'img_size'))
            if RANK in {-1, 0}:
                pbar = tqdm(pbar, total=nb, bar_format='{l_bar}{bar:10}{r_bar}{bar:-10b}')  # progress bar
            optimizer.zero_grad()
            for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
                callbacks.run('on_train_batch_start')
                ni = i + nb * epoch  # number integrated batches (since train start)
                imgs = imgs.to(opt.device, non_blocking=True).float() / 255  # uint8 to float32, 0-255 to 0.0-1.0

                # Warmup
                if ni <= nw:
                    xi = [0, nw]  # x interp
                    # compute_loss.gr = np.interp(ni, xi, [0.0, 1.0])  # iou loss ratio (obj_loss = 1.0 or iou)
                    accumulate = max(1, np.interp(ni, xi, [1, nbs / batch_size]).round())
                    for j, x in enumerate(optimizer.param_groups):
                        # bias lr falls from 0.1 to lr0, all other lrs rise from 0.0 to lr0
                        x['lr'] = np.interp(ni, xi, [hyp['warmup_bias_lr'] if j == 0 else 0.0, x['initial_lr'] * lf(epoch)])
                        if 'momentum' in x:
                            x['momentum'] = np.interp(ni, xi, [hyp['warmup_momentum'], hyp['momentum']])

                # Multi-scale
                if opt.multi_scale:
                    sz = random.randrange(imgsz * 0.5, imgsz * 1.5 + gs) // gs * gs  # size
                    sf = sz / max(imgs.shape[2:])  # scale factor
                    if sf != 1:
                        ns = [math.ceil(x * sf / gs) * gs for x in imgs.shape[2:]]  # new shape (stretched to gs-multiple)
                        imgs = nn.functional.interpolate(imgs, size=ns, mode='bilinear', align_corners=False)

                # Forward
                with torch.cuda.amp.autocast(amp):
                    pred = model(imgs)  # forward
                    loss, loss_items = compute_loss(pred, targets.to(opt.device))  # loss scaled by batch_size
                    if RANK != -1:
                        loss *= WORLD_SIZE  # gradient averaged between devices in DDP mode
                    if opt.quad:
                        loss *= 4.

                # Backward
                scaler.scale(loss).backward()

                # Optimize
                if ni - last_opt_step >= accumulate:
                    scaler.step(optimizer)  # optimizer.step
                    scaler.update()
                    optimizer.zero_grad()
                    last_opt_step = ni

                # Log
                if RANK in {-1, 0}:
                    mloss = (mloss * i + loss_items) / (i + 1)  # update mean losses
                    mem = f'{torch.cuda.memory_reserved() / 1E9 if torch.cuda.is_available() else 0:.3g}G'  # (GB)
                    pbar.set_description(('%10s' * 2 + '%10.4g' * 5) %
                                        (f'{epoch}/{epochs - 1}', mem, *mloss, targets.shape[0], imgs.shape[-1]))
                    callbacks.run('on_train_batch_end', ni, model, imgs, targets, paths, opt.plots)
                    if callbacks.stop_training:
                        return
                # end batch ------------------------------------------------------------------------------------------------

            # Scheduler
            lr = [x['lr'] for x in optimizer.param_groups]  # for loggers
            scheduler.step()

            if RANK in {-1, 0}:
                # mAP
                callbacks.run('on_train_epoch_end', epoch=epoch)
                ema.update_attr(model, include=['yaml', 'nc', 'hyp', 'names', 'stride', 'class_weights'])
                final_epoch = (epoch + 1 == epochs) or stopper.possible_stop
                if not opt.noval or final_epoch:  # Calculate mAP
                    results, maps, _ = val.run(data_dict,
                                            batch_size=batch_size // WORLD_SIZE * 2,
                                            imgsz=imgsz,
                                            model=ema.ema,
                                            single_cls=opt.single_cls,
                                            dataloader=val_loader,
                                            save_dir=save_dir,
                                            plots=False,
                                            callbacks=callbacks,
                                            compute_loss=compute_loss)

                # Update best mAP
                fi = fitness(np.array(results).reshape(1, -1))  # weighted combination of [P, R, mAP@.5, mAP@.5-.95]
                stop = stopper(epoch=epoch, fitness=fi)  # early stop check
                if fi > best_fitness:
                    best_fitness = fi
                log_vals = list(mloss) + list(results) + lr
                callbacks.run('on_fit_epoch_end', log_vals, epoch, best_fitness, fi)

                # Save model
                if (not opt.nosave) or (final_epoch and not opt.evolve):  # if save
                    ckpt = {
                        'epoch': epoch,
                        'best_fitness': best_fitness,
                        'model': deepcopy(de_parallel(model)).half(),
                        'ema': deepcopy(ema.ema).half(),
                        'updates': ema.updates,
                        'optimizer': optimizer.state_dict(),
                        'wandb_id': loggers.wandb.wandb_run.id if loggers.wandb else None,
                        'date': datetime.now().isoformat()}

                    # Save last, best and delete
                    torch.save(ckpt, last)
                    if best_fitness == fi:
                        torch.save(ckpt, best)
                    if opt.save_period > 0 and epoch % opt.save_period == 0:
                        torch.save(ckpt, w / f'epoch{epoch}.pt')
                    del ckpt
                    callbacks.run('on_model_save', last, epoch, final_epoch, best_fitness, fi)

            # EarlyStopping
            if RANK != -1:  # if DDP training
                broadcast_list = [stop if RANK == 0 else None]
                dist.broadcast_object_list(broadcast_list, 0)  # broadcast 'stop' to all ranks
                if RANK != 0:
                    stop = broadcast_list[0]
            if stop:
                break  # must break all DDP ranks

                # end epoch ----------------------------------------------------------------------------------------------------
            # end training -----------------------------------------------------------------------------------------------------

        if RANK in {-1, 0}:
            LOGGER.info(f'\n{epoch - start_epoch + 1} epochs completed in {(time.time() - t0) / 3600:.3f} hours.')
            for f in last, best:
                if f.exists():
                    strip_optimizer(f)  # strip optimizers
                    if f is best:
                        LOGGER.info(f'\nValidating {f}...')
                        results, _, _ = val.run(
                            data_dict,
                            batch_size=batch_size // WORLD_SIZE * 2,
                            imgsz=imgsz,
                            model=attempt_load(f, opt.device).half(),
                            iou_thres=0.60,  # best pycocotools results at 0.65
                            single_cls=opt.single_cls,
                            dataloader=val_loader,
                            save_dir=save_dir,
                            save_json=True,
                            verbose=True,
                            plots=opt.plots,
                            callbacks=callbacks,
                            compute_loss=compute_loss)  # val best model with plots

            callbacks.run('on_train_end', last, best, opt.plots, epoch, results)

        torch.cuda.empty_cache()
        return results

# Create DetectionYolov5 object
model = DetectionYolov5({"batch_size": 8, "epochs": 10, "input_shape": 416, "optimizer": "SGD", "learning_rate": 0.01},
        80, ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
        'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
        'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
        'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
        'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
        'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
        'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
        'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
        'hair drier', 'toothbrush'], 'YOLOv5/yolov5s.pt', None)

# Train it
results = model.train('YOLOv5/data/coco128')
```
Please someone who could help with this issue

### Environment

-YOLO: yolov5 official repository by Ultralytics
-IDE: Visual Studio Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about YOLOv5 🚀 **dataset formatting**. To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths) and 2) a class `names` dictionary:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush

```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<p align="center"><img width="750" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg"></p>

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>

Good luck 🍀 and let us know if you have any other questions!

**Comment by MartinPedersenpp** [comment]
Can you provide your dataset folder structure?

**Comment by JesusSilvaUtrera** [comment]
My dataset is the coco128 dataset, downloaded directly from the official Kaggle website, and seeing that the training works with the original code from the repository with the same dataset, the problem shouldn't be there. The error that displays is this: 
```
File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/dataloaders.py", line 455, in __init__
    assert cache['hash'] == get_hash(self.label_files + self.im_files)  # identical hash
AssertionError
```
self.label_files and self.im_files are reading the annotations and images files correctly (I debugged and showed them on terminal), so I don't know why that assert is not working

**Comment by JesusSilvaUtrera** [comment]
If I comment that line, given that it is an assert and it isn't mandatory, it still doesn't load the images and labels
`train: Scanning 'YOLOv5/data/coco128/labels/train2017' images and labels...:   0%|          | 0/128 [00:09<?, ?it/s]     `
So I assume that this is the main problem, loading the images from the folder

**Comment by JesusSilvaUtrera** [comment]
I don't know that if the problem may be that I have the dataset inside my yolov5 folder, and it is mandatory that it is placed outside on a different folder called 'datasets'

**Comment by JesusSilvaUtrera** [comment]
@MartinPedersenpp @glenn-jocher if any of you knows what can be happening, I would thank you very much

**Comment by MartinPedersenpp** [comment]
@JesusSilvaUtrera 
I am not sure what is going on, I was just asking because of this line:
`train_path, val_path = dataset_path + '/images/train2017', dataset_path + '/images/train2017'`

If your images weren't in the correct folder then it would be an issue with the script not being able to locate your images, but you say that you can indeed load them from within your script, so I was wrong.

**Comment by JesusSilvaUtrera** [comment]
@MartinPedersenpp @glenn-jocher yeah I can load my dataset now, but when it creates the train_loader it displays this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/test_detector_yolo_v5.py", line 16, in <module>
    results = model.train('/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/data/coco128')
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/detector_yolo_v5.py", line 174, in train
    train_loader, dataset = create_dataloader(train_path,
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/dataloaders.py", line 134, in create_dataloader
    return loader(dataset,
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/dataloaders.py", line 152, in __init__
    self.iterator = super().__iter__()
  File "/Users/jsilva/.pyenv/versions/yolov5_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "/Users/jsilva/.pyenv/versions/yolov5_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/jsilva/.pyenv/versions/yolov5_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1077, in __init__
    w.start()
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/jsilva/.pyenv/versions/3.10.0/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
I'm going to search for this error but if any of you has experienced something similar before it would be helpful.

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera I updated the COCO128 dataset on Kaggle to the latest version just now in case there were any issues:
https://www.kaggle.com/datasets/ultralytics/coco128

The easiest way to use COCO128 though is just to let YOLOv5 autodownload it for you. Delete COCO128 and then just run:
```
python train.py --data coco128.yaml
```

That's it.

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera glad to hear it's working! I'll keep an eye out for your new issue and be happy to help.
