### ISSUE TITLE
Non-agnostic NMS not supported by TFJS export

### ISSUE THREAD

**Issue by jmj23** [ultralytics/yolov5#9848]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug
The non-agnostic implementation of NMS is not supported by TFJS
```
TensorFlow.js: starting export with tensorflowjs 4.0.0...
2022-10-18 17:59:59.463278: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/cv2/../../lib64:
2022-10-18 17:59:59.479647: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-18 17:59:59.894639: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/cv2/../../lib64:
2022-10-18 17:59:59.894681: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/cv2/../../lib64:
2022-10-18 17:59:59.894689: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/env_pytorch/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 827, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 831, in main
    convert(argv[0].split(' '))
  File "/opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 818, in convert
    weight_shard_size_bytes, metadata_map)
  File "/opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 588, in _dispatch_converter
    metadata=metadata_map)
  File "/opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 630, in convert_tf_frozen_model
    metadata=metadata)
  File "/opt/miniconda3/envs/env_pytorch/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 170, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
CombinedNonMaxSuppression
```

### Environment

- OS: ubuntu 20.04
- Python: 3.7.13
- torch 1.10.2+cu113
- tensorflow 2.10.0
- tensorflowjs 4.0.0

### Minimal Reproducible Example

Set `agnostic_nms` to false in `export.py` under `export_saved_model` 

```
export_saved_model(model.cpu(),
                                           im,
                                           file,
                                           dynamic,
                                           tf_nms=nms or agnostic_nms or tfjs,
                                           agnostic_nms=agnostic_nms,# or tfjs,
                                           topk_per_class=topk_per_class,
                                           topk_all=topk_all,
                                           iou_thres=iou_thres,
                                           conf_thres=conf_thres,
                                           keras=keras)
```
then run
`python export.py  --weights path/to/weights/best.pt --include tfjs`

### Additional

I would like to have a model exported for TF JS with NMS but class-specific since there are desired overlapping predictions of different classes.
I am working to solve the issue and would make a PR if I am able to, but wanted to see if the community had any input or if this was already a solved issue. Much thanks in advance.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jmj23 thanks for reaching out! Indeed, the non-agnostic NMS isn't currently supported by TFJS export. This is a known limitation, and at the moment, it's not straightforward to enable class-specific NMS while exporting to TFJS.

Your detailed report and willingness to contribute are much appreciated! To address this limitation, we're actively considering and implementing solutions as part of ongoing YOLOv5 development. In the meantime, you might consider implementing a post-export workaround in your TFJS application for the desired overlapping predictions of different classes.

Your support and understanding as we work to resolve this are truly valued. If you have any further questions or insights, feel free to share them! Thanks again for your engagement and desire to help the community.
