### ISSUE TITLE
callbacks.run('on_pretrain_routine_end') not working

### ISSUE THREAD

**Issue by JesusSilvaUtrera** [ultralytics/yolov5#9853]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, I'm trying to train with the coco128 dataset but without using the data.yaml. Instead of that, I pass a parameter called 'dataset_path' to my new 'train' function. It loads the images and labels correctly, and makes the autoanchor. But when it finishes the autoanchor, in the callbacks.run('on_pretrain_routine_end') line it displays this error:
```
Traceback (most recent call last):
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/test_detector_yolo_v5.py", line 17, in <module>
    results = model.train('/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/data/coco128')
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/detector_yolo_v5.py", line 229, in train
    callbacks.run('on_pretrain_routine_end')
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/callbacks.py", line 71, in run
    logger['callback'](*args, **kwargs)
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/loggers/__init__.py", line 97, in on_pretrain_routine_end
    paths = self.save_dir.glob('*labels*.jpg')  # training labels
AttributeError: 'str' object has no attribute 'glob'
```
I don't know what I'm doing wrong

### Environment

- IDE: VS Code
- Yolov5: yolov5 official repository
- dataset: coco128

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JesusSilvaUtrera** [comment]
I have solved this error changing inside utils/loggers/__init__.py a line of code:
`self.save_dir = Path(save_dir)`
to avoid that type(self.save_dir) == str but now I have the error:
```
Traceback (most recent call last):
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/test_detector_yolo_v5.py", line 17, in <module>
    results = model.train('/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/data/coco128')
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/detector_yolo_v5.py", line 330, in train
    callbacks.run('on_train_batch_end', ni, model, imgs, targets, paths, plots)
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/callbacks.py", line 71, in run
    logger['callback'](*args, **kwargs)
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/loggers/__init__.py", line 117, in on_train_batch_end
    self.wandb.log({'Mosaics': [wandb.Image(str(f), caption=f.name) for f in files if f.exists()]})
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/YOLOv5/utils/loggers/__init__.py", line 117, in <listcomp>
    self.wandb.log({'Mosaics': [wandb.Image(str(f), caption=f.name) for f in files if f.exists()]})
AttributeError: module 'YOLOv5.utils.loggers.wandb' has no attribute 'Image'
```
I will continue investigating and debugging to see what's happening

**Comment by JesusSilvaUtrera** [comment]
Setting self.wandb to None in YOLOv5/utils/loggers/__init__.py (line 83) solved this issue, but another one showed up in the scheduler.step() line when it finishes training an epoch:
```
Traceback (most recent call last):
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/test_detector_yolo_v5.py", line 17, in <module>
    results = model.train('/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/data/coco128')
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/detector_yolo_v5.py", line 338, in train
    scheduler.step()
  File "/Users/jsilva/.pyenv/versions/yolov5_env/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 154, in step
    values = self.get_lr()
  File "/Users/jsilva/.pyenv/versions/yolov5_env/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 252, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "/Users/jsilva/.pyenv/versions/yolov5_env/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 252, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
  File "/Users/jsilva/Documents/Proyectos/rd-mini-projects/yolo_v5/detector_yolo_v5.py", line 174, in <lambda>
    lf = lambda x: (1 - x / epochs) * (1.0 - lr) + lr  # linear
TypeError: unsupported operand type(s) for -: 'float' and 'list'
```
Debugging I have found that lr becomes a list of float when it finishes an epoch (in my case `lr: [0.08650000000000001, 0.0015, 0.0015], tipo: <class 'list'>`) and obviously you can't use the operand (-) to a list. I don't understand this error, or how it could be solved (maybe leaving lr as a float and not a list of float would do it?)

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
