### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by yjcreation** [ultralytics/yolov5#9960]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

During training, it appears the following problem:

Results saved to runs\train\exp3
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 213, in run
    self._on_run()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 171, in _on_run
    self.wait_pydb_threads_to_finish()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 186, in wait_pydb_threads_to_finish
    % ', '.join([t.getName() for t in pydb_daemon_threads if t is not self]))
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 186, in <listcomp>
    % ', '.join([t.getName() for t in pydb_daemon_threads if t is not self]))
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 213, in run
    self._on_run()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 171, in _on_run
    self.wait_pydb_threads_to_finish()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 186, in wait_pydb_threads_to_finish
    % ', '.join([t.getName() for t in pydb_daemon_threads if t is not self]))
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 186, in <listcomp>
    % ', '.join([t.getName() for t in pydb_daemon_threads if t is not self]))
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 213, in run
    self._on_run()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 171, in _on_run
    self.wait_pydb_threads_to_finish()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 186, in wait_pydb_threads_to_finish
    % ', '.join([t.getName() for t in pydb_daemon_threads if t is not self]))
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 186, in <listcomp>
    % ', '.join([t.getName() for t in pydb_daemon_threads if t is not self]))
RuntimeError: dictionary changed size during iteration

Process finished with exit code 0

**Comment by yjcreation** [comment]
> Search before asking
This is screenshots.
![1](https://user-images.githubusercontent.com/22938656/198811951-b71b2160-e065-4808-8907-c73552545627.png)
After the program finishes executing the “return results", the above error will be reported.
![image](https://user-images.githubusercontent.com/22938656/198812255-5ae0202b-41e5-4887-86f7-4d2a2a15bd23.png)

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
